{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "9.1.2-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-9.1.2-b0.jar",
          "url": "core-ng-api-9.1.2-b0.jar",
          "size": 10994,
          "sha512": "f1a935134472127c1b0ea1f15a7cb8c3034736db0432ec0f9de37fccda1f4a1f18d48a81d0ca86ff2f5afa51ffa605259aa1508aee9e2d20f66421033ceada49",
          "sha256": "012ae3a83b11d2797dc555f3283ec74d4a76e12e5f8e6f6757e4f5e10d15ae67",
          "sha1": "08f49b749e28c45f54812e76571568ea5953080f",
          "md5": "2202dfef0ed776b79a9115c657f8a3f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.1.2-b0.jar",
          "url": "core-ng-api-9.1.2-b0.jar",
          "size": 10994,
          "sha512": "f1a935134472127c1b0ea1f15a7cb8c3034736db0432ec0f9de37fccda1f4a1f18d48a81d0ca86ff2f5afa51ffa605259aa1508aee9e2d20f66421033ceada49",
          "sha256": "012ae3a83b11d2797dc555f3283ec74d4a76e12e5f8e6f6757e4f5e10d15ae67",
          "sha1": "08f49b749e28c45f54812e76571568ea5953080f",
          "md5": "2202dfef0ed776b79a9115c657f8a3f7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.1.2-b0-sources.jar",
          "url": "core-ng-api-9.1.2-b0-sources.jar",
          "size": 8644,
          "sha512": "4910e802c6ab4c6a9eb3e023487da08cf6f982f6ba9ae80eba07bb31188cd5b4c01bdb010137c06c26ecd1cf3958462a31be20b352189b1bb3588379126e9966",
          "sha256": "eade022385edfd7dda74fc7a5c581381e6d598a2c93b07076019d23e52f5bc93",
          "sha1": "2a5581cf6d45ff5459b53ebab9b169a82be0d642",
          "md5": "c9b31d37b04f0a4f44fc640c3c67bdef"
        }
      ]
    }
  ]
}
