{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "9.4.0-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.4.0-b1.jar",
          "url": "core-ng-search-test-9.4.0-b1.jar",
          "size": 10074,
          "sha512": "d11681020a0869c6a553a60aded3c4ae2d13a2c272b62cabeca97eec368bec342b4700141bd88be8b02a2271547e9a656db790b7e77d52879e5f77a3e0dc48f0",
          "sha256": "ae3378d32d18c8620e86fcc88139ca3fdbc7d9aad003bf67462067d21d1149b2",
          "sha1": "45679e7c9673143de846e8713ab776d8f8c91465",
          "md5": "c08a7bda2d5c6a746f630c29b2c3b7b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.4.0-b1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "9.4.0-b1"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "8.18.1"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "reindex",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-9.4.0-b1.jar",
          "url": "core-ng-search-test-9.4.0-b1.jar",
          "size": 10074,
          "sha512": "d11681020a0869c6a553a60aded3c4ae2d13a2c272b62cabeca97eec368bec342b4700141bd88be8b02a2271547e9a656db790b7e77d52879e5f77a3e0dc48f0",
          "sha256": "ae3378d32d18c8620e86fcc88139ca3fdbc7d9aad003bf67462067d21d1149b2",
          "sha1": "45679e7c9673143de846e8713ab776d8f8c91465",
          "md5": "c08a7bda2d5c6a746f630c29b2c3b7b3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.4.0-b1-sources.jar",
          "url": "core-ng-search-test-9.4.0-b1-sources.jar",
          "size": 6289,
          "sha512": "c38f6eda806c9cacf26b60cad0373ff193083ac78f28873be4ad3110f53cb9fca41adac0cb832fec6982219093567d1eaf708044ee32c3095b5c09708740b72e",
          "sha256": "c6e989883340f017005ab73ea6ef6011b52c3b29470d8850cbe8547c96699f84",
          "sha1": "ef015ee8174e7e25caedbe5ae55a8ea772372077",
          "md5": "bb43e25cea5165acf044475458f96dc6"
        }
      ]
    }
  ]
}
