{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "9.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.0.6.jar",
          "url": "core-ng-mongo-test-9.0.6.jar",
          "size": 2386,
          "sha512": "ef895fffd3e5bb3976652921c77257eab8e9288847224d58c81fd96b0e55d7afa66b11121864fe63a5a79479cb75cf2a28c9d2183ca260611f2dda28fc45ab11",
          "sha256": "6364c2dd1140d06c93b4a4b9f3f19c1373e754ebc44117d148c1effb03001ee5",
          "sha1": "84ebf13529b8eefb2ba447cf4a6405f30f94e296",
          "md5": "2d33029804e16fe942c1476ae500b9b8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.0.6"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "9.0.6"
          }
        },
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.44.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-9.0.6.jar",
          "url": "core-ng-mongo-test-9.0.6.jar",
          "size": 2386,
          "sha512": "ef895fffd3e5bb3976652921c77257eab8e9288847224d58c81fd96b0e55d7afa66b11121864fe63a5a79479cb75cf2a28c9d2183ca260611f2dda28fc45ab11",
          "sha256": "6364c2dd1140d06c93b4a4b9f3f19c1373e754ebc44117d148c1effb03001ee5",
          "sha1": "84ebf13529b8eefb2ba447cf4a6405f30f94e296",
          "md5": "2d33029804e16fe942c1476ae500b9b8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.0.6-sources.jar",
          "url": "core-ng-mongo-test-9.0.6-sources.jar",
          "size": 1720,
          "sha512": "5d68029298f07a934fb5ba4a5bcdf0015830087bec5d88ae6c291530b2d7ee2d521873949f23c37aad59346b9890caeb6cb4559cf6510e003096e28a47350789",
          "sha256": "cf9b928088caa8b048e3c1f3e5cbdfa280f0e71514d5c300171160da82a7df30",
          "sha1": "42bd3c9be982e14f35a263283667e0f31044da94",
          "md5": "0e1c4d8ed866c7c4dc309ba7690c4767"
        }
      ]
    }
  ]
}
