{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "7.6.5-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "ccyvjnb7orff5dpf6eczxv6e7a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.6.5-b1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "7.6.5-b1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-7.6.5-b1.jar",
          "url": "core-ng-mongo-test-7.6.5-b1.jar",
          "size": 2384,
          "sha512": "1e3b24eb28c38eed8e680702fdf47d10241d0271b717a947b382a80f6483e3dd0a14e73bd72d2dc370f039fba0372887cf826dfd58327d437c4689376fe1b877",
          "sha256": "d3431c9e7baa47818de31fee1f6bdc344b9a611d34c7b931faa9e566d86ec0e8",
          "sha1": "8d33fce0baea09f796e1a6ede5769b2ce16b4daa",
          "md5": "b4d90ef93f11d76e05d789396d827d46"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.36.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.6.5-b1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "7.6.5-b1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-7.6.5-b1.jar",
          "url": "core-ng-mongo-test-7.6.5-b1.jar",
          "size": 2384,
          "sha512": "1e3b24eb28c38eed8e680702fdf47d10241d0271b717a947b382a80f6483e3dd0a14e73bd72d2dc370f039fba0372887cf826dfd58327d437c4689376fe1b877",
          "sha256": "d3431c9e7baa47818de31fee1f6bdc344b9a611d34c7b931faa9e566d86ec0e8",
          "sha1": "8d33fce0baea09f796e1a6ede5769b2ce16b4daa",
          "md5": "b4d90ef93f11d76e05d789396d827d46"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-7.6.5-b1-sources.jar",
          "url": "core-ng-mongo-test-7.6.5-b1-sources.jar",
          "size": 1722,
          "sha512": "ec47f6b3a29103aba638456b7a956bdd9e2ea9cbd8afa0a0dad9cd76cb8a91b56f6eed91b6b515d8786d967d79455accf8a676e53756443428eec590cdffc68a",
          "sha256": "544ad1b77ff46c7c12efd4b216458352bb3584c809e99cfc32e85a54de1f7916",
          "sha1": "2b7cc6d251915a7e51f613a6d44c2889baf43ff5",
          "md5": "90dba4cce496171b7964c04f11eb0e7c"
        }
      ]
    }
  ]
}
