{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "9.1.7-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-9.1.7-b1.jar",
          "url": "core-ng-api-9.1.7-b1.jar",
          "size": 11022,
          "sha512": "4332abef2b59267d90e9f19c8413309e587fd91772a0dd75dbe9bdf20b3506f21314c975998e886457d7079885666501a2dee314a4456763ae4c8bc05ddb37df",
          "sha256": "6cba61a8004f8921c827f0f75f82dd41a4d0418f93333e2d24abdc54c489e640",
          "sha1": "ff5f71535a845b8e891f83b6eac897c37c3c4a76",
          "md5": "c5ac5076a8c98ea32ee3d59290f89159"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.1.7-b1.jar",
          "url": "core-ng-api-9.1.7-b1.jar",
          "size": 11022,
          "sha512": "4332abef2b59267d90e9f19c8413309e587fd91772a0dd75dbe9bdf20b3506f21314c975998e886457d7079885666501a2dee314a4456763ae4c8bc05ddb37df",
          "sha256": "6cba61a8004f8921c827f0f75f82dd41a4d0418f93333e2d24abdc54c489e640",
          "sha1": "ff5f71535a845b8e891f83b6eac897c37c3c4a76",
          "md5": "c5ac5076a8c98ea32ee3d59290f89159"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.1.7-b1-sources.jar",
          "url": "core-ng-api-9.1.7-b1-sources.jar",
          "size": 8665,
          "sha512": "6a07aa1ed8db25f4976fc3ed409bb022ef60e1387855be945b1584c22cb082a9f794ee7031736ae3572eaef60732841434e3d01cdfd6e554eb178bed243799d0",
          "sha256": "fbcefbc87a9ec37174e9eefb0ca0af70fff6d1a54aacdbabccc895ab62cbf94e",
          "sha1": "7796df489a4be73063e9608aecfa2d2538ec768e",
          "md5": "59680c7a325610ca6c2140c9e7f0aaee"
        }
      ]
    }
  ]
}
