{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "7.6.16-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.6.16-b0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.6.16-b0.jar",
          "url": "core-ng-7.6.16-b0.jar",
          "size": 697511,
          "sha512": "517ee9f255f522aff4ec90421abdefacd90d10d63721abdf173bd1c5949fbc4741bde836b2e70589a4bdaa9bcbf03eb8680e22b32c6a6ee56f93298851f982f3",
          "sha256": "4733ec52f25482e6038ce0ce9ca3f80a6c52674d2845d3537e4f9192033c806f",
          "sha1": "380552449d1307cfc1ef79995a4003bf50469cdd",
          "md5": "23e160c3ee187117211d4ad145315a06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.27.0-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.2.7.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.8.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.8.4"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.6.16-b0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.6.16-b0.jar",
          "url": "core-ng-7.6.16-b0.jar",
          "size": 697511,
          "sha512": "517ee9f255f522aff4ec90421abdefacd90d10d63721abdf173bd1c5949fbc4741bde836b2e70589a4bdaa9bcbf03eb8680e22b32c6a6ee56f93298851f982f3",
          "sha256": "4733ec52f25482e6038ce0ce9ca3f80a6c52674d2845d3537e4f9192033c806f",
          "sha1": "380552449d1307cfc1ef79995a4003bf50469cdd",
          "md5": "23e160c3ee187117211d4ad145315a06"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-7.6.16-b0-sources.jar",
          "url": "core-ng-7.6.16-b0-sources.jar",
          "size": 356102,
          "sha512": "2869d5ff3d2d16719189bc689f58f180e77ce0c09851eaf8c3cd6fb82bcfcbe5fa6fe84be1de924ba732f24503595774edac5fab76f98ec85de560a307deb792",
          "sha256": "bf43ab8887f8576e830dca5aaacad46a85e7d194dd857f8517394c7995ab7239",
          "sha1": "8a98a5f172b40a3b80600d0442bde5a01c391855",
          "md5": "17110f53b2b301e0e1a740faf50b2d78"
        }
      ]
    }
  ]
}
