{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "7.6.5-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "xfkirao6brgntg7bbsmeiie7me"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.5-b1"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.6.5-b1.jar",
          "url": "core-ng-mongo-7.6.5-b1.jar",
          "size": 54023,
          "sha512": "649a4af2b47cfe6b3b27e7e9b7c9ce3b80955a784dab0497d5dd34b4681fe4f965093e7c3411e0272525858675a9d8947975620450c317877248d833a0be2e61",
          "sha256": "ffd8f761024675a30295400c9d7350add160f56134b3257bf1d9bb0a9af2a9bd",
          "sha1": "1c5133a22a50018cd48fc8321cd61090f8ad00f9",
          "md5": "55e6b7c9a36dfd66c150002108f01150"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.5-b1"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.6.5-b1.jar",
          "url": "core-ng-mongo-7.6.5-b1.jar",
          "size": 54023,
          "sha512": "649a4af2b47cfe6b3b27e7e9b7c9ce3b80955a784dab0497d5dd34b4681fe4f965093e7c3411e0272525858675a9d8947975620450c317877248d833a0be2e61",
          "sha256": "ffd8f761024675a30295400c9d7350add160f56134b3257bf1d9bb0a9af2a9bd",
          "sha1": "1c5133a22a50018cd48fc8321cd61090f8ad00f9",
          "md5": "55e6b7c9a36dfd66c150002108f01150"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-7.6.5-b1-sources.jar",
          "url": "core-ng-mongo-7.6.5-b1-sources.jar",
          "size": 25363,
          "sha512": "2f356570f5d0455abb52edc873c453cba91e2a468218a9844d29936a883cadc4694c0a70dd13fe3d117b4aacadc3dec526eefff0d66095e23a61042e8bdfaf85",
          "sha256": "aeeac14ba5e8b879f7878ca7abbce43587673c2a1f87d1a379f7832c0cb00063",
          "sha1": "a7d7052863af4df1275d30eaadc830ccda2ead0f",
          "md5": "3262ea0d560ffa0313ed4b24442a3d07"
        }
      ]
    }
  ]
}
