{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "7.6.5-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "ccyvjnb7orff5dpf6eczxv6e7a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.5-b1"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.6.5-b1.jar",
          "url": "core-ng-mongo-7.6.5-b1.jar",
          "size": 54023,
          "sha512": "00c2253baf5690d29d512d6591a376e7187115db35157bb051de70613b233ff22e4578674dad414c39514a0f01b906cbee3b2fbce1cf78862d635ed771649970",
          "sha256": "83cd5cbb8c86af9a9f731a45d35646ca3bdef181aefe2be332f79713e3239d3f",
          "sha1": "dbdd0cac1188b252f45077798b11d00e5807e1c1",
          "md5": "22f7dd7f2971917525649a12684416d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.5-b1"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.6.5-b1.jar",
          "url": "core-ng-mongo-7.6.5-b1.jar",
          "size": 54023,
          "sha512": "00c2253baf5690d29d512d6591a376e7187115db35157bb051de70613b233ff22e4578674dad414c39514a0f01b906cbee3b2fbce1cf78862d635ed771649970",
          "sha256": "83cd5cbb8c86af9a9f731a45d35646ca3bdef181aefe2be332f79713e3239d3f",
          "sha1": "dbdd0cac1188b252f45077798b11d00e5807e1c1",
          "md5": "22f7dd7f2971917525649a12684416d1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-7.6.5-b1-sources.jar",
          "url": "core-ng-mongo-7.6.5-b1-sources.jar",
          "size": 25363,
          "sha512": "f4b8ff604d68ade66c41470e1ea8ad67a0107443f14efd1c7afac627f2485c6c97e29d6bd77ad7cc68e5ee84b835533f757395d88a989b02f5cf7d3c8b04db8e",
          "sha256": "47b7c2896f7a43ec8a5f9827eb9850f86069375b25ecee800c71c7202f339ab4",
          "sha1": "ab81187ddd6d498176a301205ea30e022d85b11c",
          "md5": "50e65f407be35cb619dba025f77d697b"
        }
      ]
    }
  ]
}
