{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.5.1-b5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.5.1-b5"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.5.1-b5.jar",
          "url": "core-ng-9.5.1-b5.jar",
          "size": 789768,
          "sha512": "24dfe884d44c7effefa65609f11ebd82508afbb73f7f8a90fc9027c1e455a90035f3c043f841f5dd516370e7c4058d4fe48f767eccb3b5de6a6d997d828f63f7",
          "sha256": "06fc7dc60a8a74b7899a37d78a22f4033b862fe48dace586182d756bcdc3c20f",
          "sha1": "461328d5835470b32f07472761e359093d3e32ee",
          "md5": "7c9274fb2112fcbf46ac1a7d28bea632"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "tools.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "tools.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.24.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "4.2.0"
          },
          "excludes": [
            {
              "group": "org.xerial.snappy",
              "module": "*"
            },
            {
              "group": "at.yawk.lz4",
              "module": "*"
            }
          ]
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.5.1-b5"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.5.1-b5.jar",
          "url": "core-ng-9.5.1-b5.jar",
          "size": 789768,
          "sha512": "24dfe884d44c7effefa65609f11ebd82508afbb73f7f8a90fc9027c1e455a90035f3c043f841f5dd516370e7c4058d4fe48f767eccb3b5de6a6d997d828f63f7",
          "sha256": "06fc7dc60a8a74b7899a37d78a22f4033b862fe48dace586182d756bcdc3c20f",
          "sha1": "461328d5835470b32f07472761e359093d3e32ee",
          "md5": "7c9274fb2112fcbf46ac1a7d28bea632"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.5.1-b5-sources.jar",
          "url": "core-ng-9.5.1-b5-sources.jar",
          "size": 405944,
          "sha512": "5fcf8dca322eb3f4b973192bf124e55a27ea8cd47626168dd4972f3c6710145000c088be638f595c2c9452df1e8401d33113ab25ed6db0c6f093c33709102f53",
          "sha256": "680bc2f7c6e7fe5e76e27c2c82edbcbf9b689990a0c550be72247b27633c9cb5",
          "sha1": "f2179b6c515105e16034c9e199984935b0ee67ec",
          "md5": "2103437dc4d826d8650fc1b15edbd8fc"
        }
      ]
    }
  ]
}
