{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "9.4.0-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.4.0-b0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.4.0-b0.jar",
          "url": "core-ng-mongo-9.4.0-b0.jar",
          "size": 60081,
          "sha512": "f2e4d2ea138eab284c1910971d252d109c335c4c203515a9df0779c067b5ee1402edae70d8ff91817305dfb21b6783da9a9aa220ec408321b68a7bf41797710d",
          "sha256": "2fb2ffda3731202be2bacffbf4c340c143cb5be1ceb24010dbbe1e879ca48045",
          "sha1": "581561841e9a8da9103eed09bba1f87ff0640025",
          "md5": "ccefc717335448f0ded406b9823b45d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.4.0-b0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.4.0-b0.jar",
          "url": "core-ng-mongo-9.4.0-b0.jar",
          "size": 60081,
          "sha512": "f2e4d2ea138eab284c1910971d252d109c335c4c203515a9df0779c067b5ee1402edae70d8ff91817305dfb21b6783da9a9aa220ec408321b68a7bf41797710d",
          "sha256": "2fb2ffda3731202be2bacffbf4c340c143cb5be1ceb24010dbbe1e879ca48045",
          "sha1": "581561841e9a8da9103eed09bba1f87ff0640025",
          "md5": "ccefc717335448f0ded406b9823b45d5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-9.4.0-b0-sources.jar",
          "url": "core-ng-mongo-9.4.0-b0-sources.jar",
          "size": 28820,
          "sha512": "a990b41bf2b4bf68f02e181985b0ca6c25e4ce7d366601e083f03458efe4634f1ad981f6f164f618b4047b1727a6da026fab13eb49c86a4b347f513d1ba0f8f1",
          "sha256": "c0e4d9a7c53dd3bd7b07b5158afa3cebee4fbef51cdd765576b18687ff72d8ab",
          "sha1": "856b25ad7115d037a1ac709aeec6eb01dab1ae17",
          "md5": "e216d545f2f2a5476ccd00549ffdfa4d"
        }
      ]
    }
  ]
}
