{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework.mysql",
    "module": "mysql-connector-j",
    "version": "8.4.0-r2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mysql-connector-j-8.4.0-r2.jar",
          "url": "mysql-connector-j-8.4.0-r2.jar",
          "size": 517931,
          "sha512": "b39ada30b8a65ef6f2ba15665a1bab23cb9dc18cb3699323a62825e4a778a15440412f8c3b4ebba3cfc6777766ca8184e5dc042de43dd5f91ecc85a1ba9af770",
          "sha256": "080e12073f9c59e287467fc49967518617b754ce5acd3726b4a3166638b0d648",
          "sha1": "111ddf9fe9d4cb8e83f4badb5fadc3e1bfcf406f",
          "md5": "6189b30795c5f9139b495f3561588f6e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mysql-connector-j-8.4.0-r2.jar",
          "url": "mysql-connector-j-8.4.0-r2.jar",
          "size": 517931,
          "sha512": "b39ada30b8a65ef6f2ba15665a1bab23cb9dc18cb3699323a62825e4a778a15440412f8c3b4ebba3cfc6777766ca8184e5dc042de43dd5f91ecc85a1ba9af770",
          "sha256": "080e12073f9c59e287467fc49967518617b754ce5acd3726b4a3166638b0d648",
          "sha1": "111ddf9fe9d4cb8e83f4badb5fadc3e1bfcf406f",
          "md5": "6189b30795c5f9139b495f3561588f6e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mysql-connector-j-8.4.0-r2-sources.jar",
          "url": "mysql-connector-j-8.4.0-r2-sources.jar",
          "size": 520717,
          "sha512": "e308263b27d4735a28375b825ef2f1189cbd157cbde37d934bcb4f7b90a214790bf046736d7fa1c9fbff2e8ddb0b1f089f81ac2818747325cffb18310790bfd4",
          "sha256": "8af8d1bdd532e5964c17ffe5e17eef1cdbc27f7ed268d021f846c09fe36cad05",
          "sha1": "9d57e5ce18f1d57e40f820a2202ed22c0a49c027",
          "md5": "4e237be8e235611221652df9e54420ac"
        }
      ]
    }
  ]
}
