{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "9.2.2-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.2.2-b0"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.18.1"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.2.2-b0.jar",
          "url": "core-ng-search-9.2.2-b0.jar",
          "size": 54207,
          "sha512": "1acd0c645d13f781545b61f5047f0084271ef6c0b4e3d3e324da9d6edcdfb99c93bafc2388dd64d410e96a4a0570c4b2b1c56fb24b0702a1baa1fe1ed40c63f8",
          "sha256": "803b346e27318dacefa5777c542edbb7ae9d9c731174428cb974ba6488b9488d",
          "sha1": "e09e69bb6a2b5e3e89b4828824d005908c94c53b",
          "md5": "59b7026ab8a7ecbea41fb09bd8c8825a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.4"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.2.2-b0"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.18.1"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.2.2-b0.jar",
          "url": "core-ng-search-9.2.2-b0.jar",
          "size": 54207,
          "sha512": "1acd0c645d13f781545b61f5047f0084271ef6c0b4e3d3e324da9d6edcdfb99c93bafc2388dd64d410e96a4a0570c4b2b1c56fb24b0702a1baa1fe1ed40c63f8",
          "sha256": "803b346e27318dacefa5777c542edbb7ae9d9c731174428cb974ba6488b9488d",
          "sha1": "e09e69bb6a2b5e3e89b4828824d005908c94c53b",
          "md5": "59b7026ab8a7ecbea41fb09bd8c8825a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-9.2.2-b0-sources.jar",
          "url": "core-ng-search-9.2.2-b0-sources.jar",
          "size": 22334,
          "sha512": "0c50473ea18311dc4652aa7a3cc2f6b817aa4c13d2618939e3caf7c237c48ba6551c87c29fa1f62df00b59cadc9758a43153ec750712ccc28f3125f21fb7a9ad",
          "sha256": "b1c38dffd8e9cfe0183dd606d5de594495424d17fdb3e907f99dac8865b4c1d5",
          "sha1": "4bc45586b0acf67e4721a1cb40042627106ff1e7",
          "md5": "235123257706f22abd58e289df2543a9"
        }
      ]
    }
  ]
}
