{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "7.7.1-b2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-7.7.1-b2.jar",
          "url": "core-ng-api-7.7.1-b2.jar",
          "size": 10959,
          "sha512": "f57d9f58b6f1e9ed9e5b38742bf7680d2b5ea85d5b7d990487c8e8759577f1ef128c184397bcac8f7873ee5b7bd5ccbce16b2d509b25ee743b3f56325186ca2f",
          "sha256": "2e0dc3e4a626aeff16f8ecc5b6e86a8206f9c3ca134554beeeaf53285195ae2e",
          "sha1": "fafbcfc99a1760984720f9909e6d35b93b492829",
          "md5": "0e74147c7ad0e0b8a0b7c38eb29b23a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.7.1-b2.jar",
          "url": "core-ng-api-7.7.1-b2.jar",
          "size": 10959,
          "sha512": "f57d9f58b6f1e9ed9e5b38742bf7680d2b5ea85d5b7d990487c8e8759577f1ef128c184397bcac8f7873ee5b7bd5ccbce16b2d509b25ee743b3f56325186ca2f",
          "sha256": "2e0dc3e4a626aeff16f8ecc5b6e86a8206f9c3ca134554beeeaf53285195ae2e",
          "sha1": "fafbcfc99a1760984720f9909e6d35b93b492829",
          "md5": "0e74147c7ad0e0b8a0b7c38eb29b23a0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.7.1-b2-sources.jar",
          "url": "core-ng-api-7.7.1-b2-sources.jar",
          "size": 8644,
          "sha512": "950a80d9a9d07f57d6cb1ac75a9e31b88e75c0e4782fa398ce1981540f8fde03b8c9e51cc6aa0341993121de4d0a13345970ca41029e2f023c4893000fb86a45",
          "sha256": "e5ceebe63953873d460d8f75250b58e7b86e930a00ebbc2dcf51378917da6805",
          "sha1": "6e263b357f07a7cedffa8131971a522cbbfcaf53",
          "md5": "598fc1a395ca9cf9a84a14f2581e154e"
        }
      ]
    }
  ]
}
