{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "9.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.10.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.0.8.jar",
          "url": "core-ng-test-9.0.8.jar",
          "size": 45691,
          "sha512": "0597eee6cea4286e61b36e864ef7cc38c00f67295263f2536b96e39069b6f37738e47f411e9bb259df7d689e92bf80e4a0dbecce3b15bac0f061a08f31c0acfe",
          "sha256": "9561d4f7eb7f1896941471cc7ce0d4b4e941b83e341820c78142f404173fe38f",
          "sha1": "c45be659c919d9d3a6f67834957f1aa4e3e7704f",
          "md5": "0082fca5165f4c36d4bf437a01c1757f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.8"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.10.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.0.8.jar",
          "url": "core-ng-test-9.0.8.jar",
          "size": 45691,
          "sha512": "0597eee6cea4286e61b36e864ef7cc38c00f67295263f2536b96e39069b6f37738e47f411e9bb259df7d689e92bf80e4a0dbecce3b15bac0f061a08f31c0acfe",
          "sha256": "9561d4f7eb7f1896941471cc7ce0d4b4e941b83e341820c78142f404173fe38f",
          "sha1": "c45be659c919d9d3a6f67834957f1aa4e3e7704f",
          "md5": "0082fca5165f4c36d4bf437a01c1757f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-9.0.8-sources.jar",
          "url": "core-ng-test-9.0.8-sources.jar",
          "size": 22167,
          "sha512": "1f4f364bb9e8bd265f38b9541df7129034e29746fc9ae1e43ebcfba646ca5043a8584e104744d1979f061ef319d7008a48ba6be97cc3d51e7fb872dc4496e5d0",
          "sha256": "774a33082e1090376aa37b2cf520295de8a44e07a8a29f88deda2136620c76a5",
          "sha1": "d34afdbe102b56053d4a8f76d6279450ec54fb4c",
          "md5": "4e7d4e884a81433b9a90bcef57f69f3e"
        }
      ]
    }
  ]
}
