{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.0.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.0.4.jar",
          "url": "core-ng-9.0.4.jar",
          "size": 734823,
          "sha512": "8c3b39886b848dd12298489ce3b4f703215315309ddaffb21bde8e56c42d648003ebf478fa94d6ba13bf3c62d575cb22372e904cc555139c9ed9427e91182ab8",
          "sha256": "ad451a69d7ee814e38534c7fab944065e5ef6510dfa15388906e69dafadd5882",
          "sha1": "e71e26a82f10b80c8074fc6dc0ea716fdc39a66f",
          "md5": "b96b26ac76031f27243d8c34e4d032c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.15.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.15.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.10.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "3.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.10.5"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.0.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.0.4.jar",
          "url": "core-ng-9.0.4.jar",
          "size": 734823,
          "sha512": "8c3b39886b848dd12298489ce3b4f703215315309ddaffb21bde8e56c42d648003ebf478fa94d6ba13bf3c62d575cb22372e904cc555139c9ed9427e91182ab8",
          "sha256": "ad451a69d7ee814e38534c7fab944065e5ef6510dfa15388906e69dafadd5882",
          "sha1": "e71e26a82f10b80c8074fc6dc0ea716fdc39a66f",
          "md5": "b96b26ac76031f27243d8c34e4d032c1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.0.4-sources.jar",
          "url": "core-ng-9.0.4-sources.jar",
          "size": 377825,
          "sha512": "da673e7d716d51f4733a39277974e48bb7e1b8491a356a8fac6ea7102b889d348ce644ad68e828a12141ec6ddc9c2882adfb43084a341cb8ccb8610e7451da44",
          "sha256": "1d9aba10759994964a5920a5a029168565fc6b7a30fd5b11e1c10078406376ce",
          "sha1": "a433584a7928c9ac3a9868ef9c7281b90f923c6c",
          "md5": "21fc86a4dbbcaef9ff45583062bbafc0"
        }
      ]
    }
  ]
}
