{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "7.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6",
      "buildId": "jdhsmwlbjvg6foywe56zxxdxk4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.5.6"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.6.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.5.7"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.5.6.jar",
          "url": "core-ng-test-7.5.6.jar",
          "size": 36182,
          "sha512": "98830833e3746ed2110f59287fa995da020e96003c05ac202c200352d499dd71a47acbf93cc839768e84c5611c9ce6c15316c45aa76813fd1793178990791deb",
          "sha256": "494602168aeb415d26217228b945b44a321f162aea247e2c408a607a1a9f51a5",
          "sha1": "6b0e8865efe6e8ace5a0fda011debd093dd19162",
          "md5": "0525228762775b35d2d980c617b3c247"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.6.2"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.4.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.5.6"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.6.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.5.7"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.5.6.jar",
          "url": "core-ng-test-7.5.6.jar",
          "size": 36182,
          "sha512": "98830833e3746ed2110f59287fa995da020e96003c05ac202c200352d499dd71a47acbf93cc839768e84c5611c9ce6c15316c45aa76813fd1793178990791deb",
          "sha256": "494602168aeb415d26217228b945b44a321f162aea247e2c408a607a1a9f51a5",
          "sha1": "6b0e8865efe6e8ace5a0fda011debd093dd19162",
          "md5": "0525228762775b35d2d980c617b3c247"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-7.5.6-sources.jar",
          "url": "core-ng-test-7.5.6-sources.jar",
          "size": 18191,
          "sha512": "bda29e3505158537f04d778044cff2c009f25579b87a263ec6bc6290031c62a0d5f31c6f0d9a9e59057ebca7f419953c6de99a6c101a97291007dc865b33ee57",
          "sha256": "e1af95d6dbc29374bd4190a4b845e2b35c4e13ad408f9527b66b3b3137f85f55",
          "sha1": "4362719abbf6a486db12681e97cf4339c9aa1674",
          "md5": "b4801e5828cd253f0bab452420957fc8"
        }
      ]
    }
  ]
}
