{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "9.1.2-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.2-b0"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.1.2-b0.jar",
          "url": "core-ng-search-9.1.2-b0.jar",
          "size": 53958,
          "sha512": "43a1e3398504bea12a5bf2356408f6b6ad928b2276c8b4b2e8f63d9f2fc98a3cdbbf62fde96d07a936982f5b9e5c23bd8c54f7be3e840e967eeb7a27767567b7",
          "sha256": "077cea6ed91acd3d589eaaa95f04c7d4f1cbbf6941f828bdb829aff54dfccaee",
          "sha1": "5bce13e14dd3e4d1d91f24fbdad5cfb3112a0b8a",
          "md5": "b27d2dfa087fdc149d18e2ecaf2c1ce5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.2-b0"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.1.2-b0.jar",
          "url": "core-ng-search-9.1.2-b0.jar",
          "size": 53958,
          "sha512": "43a1e3398504bea12a5bf2356408f6b6ad928b2276c8b4b2e8f63d9f2fc98a3cdbbf62fde96d07a936982f5b9e5c23bd8c54f7be3e840e967eeb7a27767567b7",
          "sha256": "077cea6ed91acd3d589eaaa95f04c7d4f1cbbf6941f828bdb829aff54dfccaee",
          "sha1": "5bce13e14dd3e4d1d91f24fbdad5cfb3112a0b8a",
          "md5": "b27d2dfa087fdc149d18e2ecaf2c1ce5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-9.1.2-b0-sources.jar",
          "url": "core-ng-search-9.1.2-b0-sources.jar",
          "size": 22291,
          "sha512": "5a2ed48bd0487d4080bbad9c56cb5be2d2b0ab90ad2f50743713bcf00b201ccc1990ec99d112871854b42d66b599b934c185c066f0bc7f8814cbb8a00dc12dbd",
          "sha256": "8d1f0b0d073a2b234bf4e5ae0bd577af39b5cacb82f48c0a3af9fc58f274d3f9",
          "sha1": "760c53862ed44bc2736a4f42170a7c76c3002b4d",
          "md5": "9d46daae6e8e2004eb80ba4875cfbb12"
        }
      ]
    }
  ]
}
