{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "7.7.1-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.7.1-b1"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "7.13.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "elasticsearch",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch-x-content",
          "version": {
            "requires": "7.13.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "elasticsearch-x-content",
              "type": "jar",
              "extension": "jar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.7.1-b1.jar",
          "url": "core-ng-search-7.7.1-b1.jar",
          "size": 38916,
          "sha512": "7951821cd11f44c3c55db0d22f615af84ebd55c2fb21df3a98c83406572a30e32990b89e3df288840a11be385a8a069a635889a24a706b588c6ad17542138d4c",
          "sha256": "c8665b4e1bf098f43d8c2f47a63229d125dc889a63d7a5aee2ab8a3e0bff0997",
          "sha1": "576e5fbad489a85d86237bf40663b211e328c1e1",
          "md5": "42629d4641a2585776a39c2469ad5e3e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.elasticsearch.client",
          "module": "elasticsearch-rest-high-level-client",
          "version": {
            "requires": "7.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.7.1-b1"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "7.13.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "elasticsearch",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch-x-content",
          "version": {
            "requires": "7.13.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "elasticsearch-x-content",
              "type": "jar",
              "extension": "jar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.7.1-b1.jar",
          "url": "core-ng-search-7.7.1-b1.jar",
          "size": 38916,
          "sha512": "7951821cd11f44c3c55db0d22f615af84ebd55c2fb21df3a98c83406572a30e32990b89e3df288840a11be385a8a069a635889a24a706b588c6ad17542138d4c",
          "sha256": "c8665b4e1bf098f43d8c2f47a63229d125dc889a63d7a5aee2ab8a3e0bff0997",
          "sha1": "576e5fbad489a85d86237bf40663b211e328c1e1",
          "md5": "42629d4641a2585776a39c2469ad5e3e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-7.7.1-b1-sources.jar",
          "url": "core-ng-search-7.7.1-b1-sources.jar",
          "size": 17511,
          "sha512": "094735bdd0e9470d780d3cb6ef16137b12686362b90d8ada9e56678ed6f91d2a1c5150a04d1fbd5183395bf7399183e6c5de3a7d790c11a816b4d3b54baf1d87",
          "sha256": "57a5eccccd0ee2fe43d2108874001a7fe52dae1a8d84833d167819172b8ee0e2",
          "sha1": "8bae876c885d7fa631ff6ab992db03b7b3af3633",
          "md5": "4d7a8ec8373afbd21d672e0367f30bdd"
        }
      ]
    }
  ]
}
