{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "7.6.8-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "fbkkyz4bmredpnyliz2efiny7u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.6.8-b0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.6.8-b0.jar",
          "url": "core-ng-7.6.8-b0.jar",
          "size": 676404,
          "sha512": "5aa37c2d67e8f3b4237cc023b3466310ae63df47288b85caa1f12526c6aeef743e84644d0829761ed16476f6bd7bfb089c7bb8908a5f117401bae96bed214dcb",
          "sha256": "0e0b9411abfce7ff0f1a265e5325b3ec4ee854dc04ec73ce8ca35e2173e9cae0",
          "sha1": "d5f52ca4c04478bd7e66d811ab026f1692a8b5df",
          "md5": "2710482775ca3e57bba7ac8f8b1cc4ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.27.0-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.2.3.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.7.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.8.2"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.6.8-b0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.6.8-b0.jar",
          "url": "core-ng-7.6.8-b0.jar",
          "size": 676404,
          "sha512": "5aa37c2d67e8f3b4237cc023b3466310ae63df47288b85caa1f12526c6aeef743e84644d0829761ed16476f6bd7bfb089c7bb8908a5f117401bae96bed214dcb",
          "sha256": "0e0b9411abfce7ff0f1a265e5325b3ec4ee854dc04ec73ce8ca35e2173e9cae0",
          "sha1": "d5f52ca4c04478bd7e66d811ab026f1692a8b5df",
          "md5": "2710482775ca3e57bba7ac8f8b1cc4ca"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-7.6.8-b0-sources.jar",
          "url": "core-ng-7.6.8-b0-sources.jar",
          "size": 345870,
          "sha512": "e70fd1b87f8eccad188d11156a9852c26bb0a4ae7868d8eef243196ac0f4daf5e08152b9e2307897d760d45e15ecd946c37e8e0371be6bbd8627da0463e0a94e",
          "sha256": "5255093d912b60a7647bffa6178dcb7da8b178363e9087caa04459264af34b3a",
          "sha1": "a47558f0a658e4ed82d65a77ccf040aeb26ad960",
          "md5": "b23e0050052fd1792b22586045e79a15"
        }
      ]
    }
  ]
}
