{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "7.6.5-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "ccyvjnb7orff5dpf6eczxv6e7a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.5-b1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.6.5-b1.jar",
          "url": "core-ng-test-7.6.5-b1.jar",
          "size": 39069,
          "sha512": "e4f38b7f2027b1e53f743468a75b45ec80ce134f16d897f3abcb8bb16715f6588981d65863cff9a7f519c8f4a4ee058152fb7c13d45f48db63e292ac977f2d4d",
          "sha256": "9bb29ad9e143af4e26c069eb5ccd6307439be08ecdedf80ac6666614f3fd4990",
          "sha1": "e6266350a2082f6ea7b01a81daa4c45974eee616",
          "md5": "94eeb4a00ae02b48ed80a1a14a76f3a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.4.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.5-b1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.6.5-b1.jar",
          "url": "core-ng-test-7.6.5-b1.jar",
          "size": 39069,
          "sha512": "e4f38b7f2027b1e53f743468a75b45ec80ce134f16d897f3abcb8bb16715f6588981d65863cff9a7f519c8f4a4ee058152fb7c13d45f48db63e292ac977f2d4d",
          "sha256": "9bb29ad9e143af4e26c069eb5ccd6307439be08ecdedf80ac6666614f3fd4990",
          "sha1": "e6266350a2082f6ea7b01a81daa4c45974eee616",
          "md5": "94eeb4a00ae02b48ed80a1a14a76f3a0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-7.6.5-b1-sources.jar",
          "url": "core-ng-test-7.6.5-b1-sources.jar",
          "size": 19185,
          "sha512": "18b0be724fd5055cc557d405c5381f3ca0610c3b2c5f4de0066aab6dc6d27ce669d51d26318468e92eb9211b015d6e28aff83f82fd35209cf727b3a54517b5df",
          "sha256": "dc2f4fc81638712d4375bbf197b583e64e77398039f722c326e036a9e1bf695f",
          "sha1": "f87fdc82f122c7db1146f1579e4bc80220ba6536",
          "md5": "fec073751d87f3223251be6f8564806a"
        }
      ]
    }
  ]
}
