{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "7.6.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "5ouw753gz5cgbnubxggdyz4bvu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.12"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.6.12.jar",
          "url": "core-ng-mongo-7.6.12.jar",
          "size": 54022,
          "sha512": "aa39d6b1eb31eb588d9aa32f286d6e210561a461196fccdf3e4e7cd4b5c0e30f65f7b28e4b90671b3a0a0e6b77908cdd1115cdea73868cf747660f2ef85f3606",
          "sha256": "33f6e6fd92bfc1cd65dd9c89636b3f6bfddae6a8857fbe030af9a95301e51ec3",
          "sha1": "a55137ce5ab4e4b7c19eb2a19dcfb503e1db4f3b",
          "md5": "174df956930e2ae85b4641c54378d8ef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.12"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.6.12.jar",
          "url": "core-ng-mongo-7.6.12.jar",
          "size": 54022,
          "sha512": "aa39d6b1eb31eb588d9aa32f286d6e210561a461196fccdf3e4e7cd4b5c0e30f65f7b28e4b90671b3a0a0e6b77908cdd1115cdea73868cf747660f2ef85f3606",
          "sha256": "33f6e6fd92bfc1cd65dd9c89636b3f6bfddae6a8857fbe030af9a95301e51ec3",
          "sha1": "a55137ce5ab4e4b7c19eb2a19dcfb503e1db4f3b",
          "md5": "174df956930e2ae85b4641c54378d8ef"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-7.6.12-sources.jar",
          "url": "core-ng-mongo-7.6.12-sources.jar",
          "size": 25362,
          "sha512": "5b2afa254a7887d52bf04ee8935fd3a58884544897adbeba32df3c805ed15ed21bcce7d48fd4dc3ced326ce7404baed1d2ab4df9989bb7cc3d0fe7d3b27e4edb",
          "sha256": "76ec30dcbe09b7be7f860c76fb8d7d008d9697b61d4d5e1c7c307b874681d1dd",
          "sha1": "ddb74602593dbce112c0078fa5fd8e1c528e1fdf",
          "md5": "a064622aea8e8b1c96a502d2a85d212c"
        }
      ]
    }
  ]
}
