{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.1.0-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.0-b0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.1.0-b0.jar",
          "url": "core-ng-9.1.0-b0.jar",
          "size": 765691,
          "sha512": "6c75105aedfa8f9207b71c54021b50abbfe741545b6161a68a21337793efb40598f5a5553612fed7ab170aede868374e86d5403b6ef601458eb76fbf4c7511c0",
          "sha256": "19674d7359a7fd71fda2d15500afae31669def4bbe0a415fe718566b36b65ae6",
          "sha1": "180e3384c2732ef43381a712cfeef170c5036cf8",
          "md5": "36307829b35ad3c96664b4f3352af5e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "okhttp",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.10.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "3.7.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.10.5"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.0-b0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.1.0-b0.jar",
          "url": "core-ng-9.1.0-b0.jar",
          "size": 765691,
          "sha512": "6c75105aedfa8f9207b71c54021b50abbfe741545b6161a68a21337793efb40598f5a5553612fed7ab170aede868374e86d5403b6ef601458eb76fbf4c7511c0",
          "sha256": "19674d7359a7fd71fda2d15500afae31669def4bbe0a415fe718566b36b65ae6",
          "sha1": "180e3384c2732ef43381a712cfeef170c5036cf8",
          "md5": "36307829b35ad3c96664b4f3352af5e3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.1.0-b0-sources.jar",
          "url": "core-ng-9.1.0-b0-sources.jar",
          "size": 391562,
          "sha512": "be6abbaec1f88a7c1637878760d35e4808a46f4324af6c2a9649287b370531cf75d6943a3dd4434867968ccfe96dd4f175c32e2dcdc133488aeec8a3eb70fb6f",
          "sha256": "f55d73abfa6a7be3abc4e20a8ab7bf37ffe3f6fdc20285578d6eb6f0c58155ed",
          "sha1": "4fe771f02133efbb1fcec9b978bd78b9198dd374",
          "md5": "378e9fa10a854b274229a4058753f75a"
        }
      ]
    }
  ]
}
