{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "9.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.6.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.24.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.0.3.jar",
          "url": "core-ng-test-9.0.3.jar",
          "size": 45689,
          "sha512": "386fae7d683ae75e078fe8111d6bc2a79ee0cab1491c7d15550a4afbe500b094dd880206dfe0a2cbf43358b93ea4db5874063a11ab29918cf7f849af5341655f",
          "sha256": "adfa0b627334c250ba267f99dbcca8d641f88dd20eefad38e17689308ade883e",
          "sha1": "53d5fb8e00c159b0f31e17db031167c563699c18",
          "md5": "da0874e2158c2c39054ec93e2a980119"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.10.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.6.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.24.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.0.3.jar",
          "url": "core-ng-test-9.0.3.jar",
          "size": 45689,
          "sha512": "386fae7d683ae75e078fe8111d6bc2a79ee0cab1491c7d15550a4afbe500b094dd880206dfe0a2cbf43358b93ea4db5874063a11ab29918cf7f849af5341655f",
          "sha256": "adfa0b627334c250ba267f99dbcca8d641f88dd20eefad38e17689308ade883e",
          "sha1": "53d5fb8e00c159b0f31e17db031167c563699c18",
          "md5": "da0874e2158c2c39054ec93e2a980119"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-9.0.3-sources.jar",
          "url": "core-ng-test-9.0.3-sources.jar",
          "size": 22165,
          "sha512": "cb4ea7a1b28be311b0d760703c99f5378b48d1f2059cd24e83dab87778611da621b94d8f24a27d2e0af43d11ec0f91f9b2e7ea528ea0a0dd7a1f6ad2f92a9513",
          "sha256": "5c257b8f0b1cfde097d18fad5157d1a18e6ccf4e0f7699da861ab902ddfb43b3",
          "sha1": "b1fbf26050253aaee9c7fb729aec0761ffe7ca5a",
          "md5": "31d8eede1136973e90226f2272f6f1b3"
        }
      ]
    }
  ]
}
