{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "9.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.4.0.jar",
          "url": "core-ng-mongo-test-9.4.0.jar",
          "size": 2940,
          "sha512": "523107886492fb80e40e8a321401bf68bab7141281522c5f56e2efec26799f58250999c0becc05afb91436635df220b330f2ea0b764d46b39ae7cc1d68342b3f",
          "sha256": "f6aab550a0bc6e696fa8698a760aa5237f9b3fe1b06b04b0cea6b5d9afad4839",
          "sha1": "96f58036e2679bf6cfef0b24c6131d4fb2e3df60",
          "md5": "b2838a799f78ed840935b991f2573399"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.4.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "9.4.0"
          }
        },
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.47.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-9.4.0.jar",
          "url": "core-ng-mongo-test-9.4.0.jar",
          "size": 2940,
          "sha512": "523107886492fb80e40e8a321401bf68bab7141281522c5f56e2efec26799f58250999c0becc05afb91436635df220b330f2ea0b764d46b39ae7cc1d68342b3f",
          "sha256": "f6aab550a0bc6e696fa8698a760aa5237f9b3fe1b06b04b0cea6b5d9afad4839",
          "sha1": "96f58036e2679bf6cfef0b24c6131d4fb2e3df60",
          "md5": "b2838a799f78ed840935b991f2573399"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.4.0-sources.jar",
          "url": "core-ng-mongo-test-9.4.0-sources.jar",
          "size": 2079,
          "sha512": "64e9d84ad414a4624ae2eff297e86a7bf917847813412488898f8a778636e760745bc63c7112ecd76362eb646ae0e0dde393ac217ac6101e8ff81306e290b564",
          "sha256": "916600c831fcd9344c332d834134515a1a01dea5372d5c5dd4c844685d435b0f",
          "sha1": "0c97987e40fbcae6c6216ab69c9e3dd6a2130fb3",
          "md5": "4dd04f8c86e691d69db2ceb3c74e2e31"
        }
      ]
    }
  ]
}
