{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "7.7.1-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.7.1-b0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.7.1-b0.jar",
          "url": "core-ng-7.7.1-b0.jar",
          "size": 685493,
          "sha512": "869286628dd35e832b0b70eb0b8ccbf2c06d7808bb45ae18a1cea0eb6461eebc28b4301d06bcd23c98194e4e909de80b688f2c47608f59e1585b77f198a3020e",
          "sha256": "a90e22735f211f286147da59a47a2c9a9f8402ad3c043b84be7f10ef538ab792",
          "sha1": "085775ec1bbdc0e32d5a920a701ad4e5a30b666e",
          "md5": "0e955de8de21d1b58d43c14e1e98572f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.28.0-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.2.7.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.8.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.8.4"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.7.1-b0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.7.1-b0.jar",
          "url": "core-ng-7.7.1-b0.jar",
          "size": 685493,
          "sha512": "869286628dd35e832b0b70eb0b8ccbf2c06d7808bb45ae18a1cea0eb6461eebc28b4301d06bcd23c98194e4e909de80b688f2c47608f59e1585b77f198a3020e",
          "sha256": "a90e22735f211f286147da59a47a2c9a9f8402ad3c043b84be7f10ef538ab792",
          "sha1": "085775ec1bbdc0e32d5a920a701ad4e5a30b666e",
          "md5": "0e955de8de21d1b58d43c14e1e98572f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-7.7.1-b0-sources.jar",
          "url": "core-ng-7.7.1-b0-sources.jar",
          "size": 352440,
          "sha512": "afd1fcc60766c16c40658c4ac4201935b78cb71b16bc3afa5cf64254188d082d9ea1e9c056a258ff619c02c8d16b446a0b8329b5772983a19dd4e030e7726beb",
          "sha256": "8fbd65038ef3d5a99c8716d8ca5ebbbe6a1077326afc5cb80f0c1771299309cd",
          "sha1": "5c7e83f465f76368a9cac4863801e85ac9185b55",
          "md5": "4b1ddcb6736d6ccfe397ebeba4d38750"
        }
      ]
    }
  ]
}
