{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "7.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "tiw26whr7vh43djrdosu3oi4rq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.4.6"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.4.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.4.6.jar",
          "url": "core-ng-search-test-7.4.6.jar",
          "size": 9074,
          "sha512": "5f73494934a2d51847f8af1199f9e6addc55ae239a04182dffab6e0231d51645b07b324685b39cb0e3fa2937f32488de335b8735e3ad5a4ad359d67f2c8d3d5d",
          "sha256": "ae960401ce604afe0b87201ae3b5bfc2a11f5742d3a77ded5f99ab50dafb2d7e",
          "sha1": "f7bdbf5f8c499cd9f32dfbfb95b9e28b3f379a86",
          "md5": "fa7414637323aaec2547f2b898536f85"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4-client",
          "version": {
            "requires": "7.7.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "reindex-client",
          "version": {
            "requires": "7.7.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "7.7.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "7.7.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "7.7.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.4.6"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.4.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.4.6.jar",
          "url": "core-ng-search-test-7.4.6.jar",
          "size": 9074,
          "sha512": "5f73494934a2d51847f8af1199f9e6addc55ae239a04182dffab6e0231d51645b07b324685b39cb0e3fa2937f32488de335b8735e3ad5a4ad359d67f2c8d3d5d",
          "sha256": "ae960401ce604afe0b87201ae3b5bfc2a11f5742d3a77ded5f99ab50dafb2d7e",
          "sha1": "f7bdbf5f8c499cd9f32dfbfb95b9e28b3f379a86",
          "md5": "fa7414637323aaec2547f2b898536f85"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.4.6-sources.jar",
          "url": "core-ng-search-test-7.4.6-sources.jar",
          "size": 5455,
          "sha512": "62366e6110f48b4921e1aacf1f75b68ec6d598b12f2c6e0e9bc3038d8800a202a15d0882bdf9ec704633d0382ee1d54f70a5198f5314574048cc2f02cb107338",
          "sha256": "a32ae8eb8639d382b8787a073c3565a52cbec507d17d4a613a84e7ae34473993",
          "sha1": "c89e452d855d033a862dd2c088731ba3e3755f46",
          "md5": "341495a435887c9af957d3c95fc9a093"
        }
      ]
    }
  ]
}
