{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "7.6.16-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.16-b1"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "7.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "elasticsearch",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch-x-content",
          "version": {
            "requires": "7.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "elasticsearch-x-content",
              "type": "jar",
              "extension": "jar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.6.16-b1.jar",
          "url": "core-ng-search-7.6.16-b1.jar",
          "size": 38549,
          "sha512": "b05c69d8d197a795cbbcf9c99267930fe83dff7deb9e36544da69ba0bd9250ae25c46bd0403de5e2bd0196c45d8d90ea2515e654fec5ed3dc57815cc0b3c59fe",
          "sha256": "9a235812f8363b6e69f7cd1f1c51d9a85a082cc0ae0d2667196ec331db5bf8e7",
          "sha1": "5e83c069072654d55887457186c8113ce380d46f",
          "md5": "c38895201496da8c94e90b3efc6335a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.elasticsearch.client",
          "module": "elasticsearch-rest-high-level-client",
          "version": {
            "requires": "7.12.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.16-b1"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "7.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "elasticsearch",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch-x-content",
          "version": {
            "requires": "7.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "elasticsearch-x-content",
              "type": "jar",
              "extension": "jar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.6.16-b1.jar",
          "url": "core-ng-search-7.6.16-b1.jar",
          "size": 38549,
          "sha512": "b05c69d8d197a795cbbcf9c99267930fe83dff7deb9e36544da69ba0bd9250ae25c46bd0403de5e2bd0196c45d8d90ea2515e654fec5ed3dc57815cc0b3c59fe",
          "sha256": "9a235812f8363b6e69f7cd1f1c51d9a85a082cc0ae0d2667196ec331db5bf8e7",
          "sha1": "5e83c069072654d55887457186c8113ce380d46f",
          "md5": "c38895201496da8c94e90b3efc6335a1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-7.6.16-b1-sources.jar",
          "url": "core-ng-search-7.6.16-b1-sources.jar",
          "size": 17342,
          "sha512": "fc23b40500f469d625741a35d48c7e70168b477d3463be6bca09979688aea6613bef19d50fa2b034753ed479b122a2d00094abe7377cec01db5eabccd161ad17",
          "sha256": "ee00a728003849b9d162ccc9579c309095ca76ada2b8fb360d8993f58e3e4a50",
          "sha1": "dc860622fbbb5cd43bea5f517c05672ad5608f4b",
          "md5": "4b9ffb3a3982f522e5a9ba4a85bf6c46"
        }
      ]
    }
  ]
}
