{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "9.4.0-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.4.0-b1"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.4.0-b1.jar",
          "url": "core-ng-mongo-9.4.0-b1.jar",
          "size": 60080,
          "sha512": "5c5a49f312627f6705efc88dad4f803a803de7f9a0084b962fffd45b0eda7effa6d4b32a8793f0969a234f2fa81cbc060cf013974b41e7edb1458896deebe65b",
          "sha256": "1a2186cdecca9d65c5855e01d5788bf41b25f8743d44366abb2e9ba5584312f6",
          "sha1": "a82ee7bbe8ac977fde5dba2b0667ef7b67886653",
          "md5": "cb71f66276b2b54b3f866da3572d6c7e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.4.0-b1"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.4.0-b1.jar",
          "url": "core-ng-mongo-9.4.0-b1.jar",
          "size": 60080,
          "sha512": "5c5a49f312627f6705efc88dad4f803a803de7f9a0084b962fffd45b0eda7effa6d4b32a8793f0969a234f2fa81cbc060cf013974b41e7edb1458896deebe65b",
          "sha256": "1a2186cdecca9d65c5855e01d5788bf41b25f8743d44366abb2e9ba5584312f6",
          "sha1": "a82ee7bbe8ac977fde5dba2b0667ef7b67886653",
          "md5": "cb71f66276b2b54b3f866da3572d6c7e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-9.4.0-b1-sources.jar",
          "url": "core-ng-mongo-9.4.0-b1-sources.jar",
          "size": 28819,
          "sha512": "ebdb1c81ec1fd87af18fe6d45b3e92a568c890899b024a801dd42e374bfdb7f4468e7dac198ee79585408af2cf3a820dac80c2d7503e365f74ddc60d0f4693d1",
          "sha256": "539267de82031fea1f897fae2ea1c0e9103246c7237c0d267b82879be5cec214",
          "sha1": "7b97b67ca962defd3d905d1eac257a9999d8579d",
          "md5": "e2bf5dd256b4c3c239a02eeb6c4e35ca"
        }
      ]
    }
  ]
}
