{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "7.7.4-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-7.7.4-b0.jar",
          "url": "core-ng-api-7.7.4-b0.jar",
          "size": 10958,
          "sha512": "b958a73b47e3a055ee46d0e560e7205225377f75f74fd30f1b3f404ed122ae0a239bc78f2a3780642a5e9abbabff063c9de49ba74172ed075f5fb0a45e9b3c72",
          "sha256": "70bf55c0485c6aa5d47bd615f324c189bd27ccd35af6c0295b53efab204ff9ac",
          "sha1": "a0ea85eb79e40df4e59e8c5b18a044041ab3c2c6",
          "md5": "512da80de84daa019a85837d4a01025d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.7.4-b0.jar",
          "url": "core-ng-api-7.7.4-b0.jar",
          "size": 10958,
          "sha512": "b958a73b47e3a055ee46d0e560e7205225377f75f74fd30f1b3f404ed122ae0a239bc78f2a3780642a5e9abbabff063c9de49ba74172ed075f5fb0a45e9b3c72",
          "sha256": "70bf55c0485c6aa5d47bd615f324c189bd27ccd35af6c0295b53efab204ff9ac",
          "sha1": "a0ea85eb79e40df4e59e8c5b18a044041ab3c2c6",
          "md5": "512da80de84daa019a85837d4a01025d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.7.4-b0-sources.jar",
          "url": "core-ng-api-7.7.4-b0-sources.jar",
          "size": 8643,
          "sha512": "fafc44ee794cfdacaa0ae271bc29a38b012352841f96695ed7f357c9141ab9e1a8192efbddf8d9b8ab6061253d19b66257e4f86444eef89d9e707a348111d70f",
          "sha256": "1e1e3e5649280dae99aa8e4877ee719eab142ce50b661d850780f9b06adeef2d",
          "sha1": "0991aff983fe5228f0e9a60c870421630afefae5",
          "md5": "08551a3cee5a769247d0a454ded3c42c"
        }
      ]
    }
  ]
}
