{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "9.3.1-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.3.1-b0.jar",
          "url": "core-ng-search-test-9.3.1-b0.jar",
          "size": 10069,
          "sha512": "a0f6365d8aed03116b382d3d99108cf89a462448327dd4f5a5222be8cdc242554680e9554007ca390db4dbcd2a35a9331fef50603f0b3fd43a849f9b9ef4c743",
          "sha256": "173d5173b89768c0c678da16af19eb92fa5b6085c843317cc8adc140a4671918",
          "sha1": "ba449959462b25bb4b52404ec07204be5347bd25",
          "md5": "7d0839398643011e13e643a4acd07a59"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.3.1-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "9.3.1-b0"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "8.18.1"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "reindex",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-9.3.1-b0.jar",
          "url": "core-ng-search-test-9.3.1-b0.jar",
          "size": 10069,
          "sha512": "a0f6365d8aed03116b382d3d99108cf89a462448327dd4f5a5222be8cdc242554680e9554007ca390db4dbcd2a35a9331fef50603f0b3fd43a849f9b9ef4c743",
          "sha256": "173d5173b89768c0c678da16af19eb92fa5b6085c843317cc8adc140a4671918",
          "sha1": "ba449959462b25bb4b52404ec07204be5347bd25",
          "md5": "7d0839398643011e13e643a4acd07a59"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.3.1-b0-sources.jar",
          "url": "core-ng-search-test-9.3.1-b0-sources.jar",
          "size": 6284,
          "sha512": "23d66b6ed23842d020647253c99346be81753c4e4ee23959f6457ff7be38df6bfc01cd1af752c886dc3df5d7d2bde6bc9d78c80dbb3f169c9b48fb4126479d61",
          "sha256": "ea2ef2c71b52b68288a75b255354a16bbc3ead5156bb84ef2f925fb3e85425a5",
          "sha1": "f179f30e89d6fe77be0d71029eeac4dc1fe21e3e",
          "md5": "0212a4328a08ca3d7eab9df382aed3f2"
        }
      ]
    }
  ]
}
