{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "9.5.1-b4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.5.1-b4"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "9.3.2"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            },
            {
              "group": "io.opentelemetry.semconv",
              "module": "*"
            },
            {
              "group": "com.fasterxml.jackson.core",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.5.1-b4.jar",
          "url": "core-ng-search-9.5.1-b4.jar",
          "size": 59457,
          "sha512": "07cd282f00a2a7c7eb555c08403402d1ea3e4501d85809d7be18482c7898cd9fb87c4d638443a8548669305a9ba653b9a1bcf99f5e5ec43a39d981fa1f9f1c7e",
          "sha256": "bd2fc7876f206090bfd203292f341546a8f75f5c6c06144d3713085150fc9c0f",
          "sha1": "279d21e386ac46fcafecc387aa1a4a0676f82e3d",
          "md5": "b5c63a4fdeee9a478491f5c3e880332c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-rest5-client",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "tools.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.5.1-b4"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "9.3.2"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            },
            {
              "group": "io.opentelemetry.semconv",
              "module": "*"
            },
            {
              "group": "com.fasterxml.jackson.core",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.5.1-b4.jar",
          "url": "core-ng-search-9.5.1-b4.jar",
          "size": 59457,
          "sha512": "07cd282f00a2a7c7eb555c08403402d1ea3e4501d85809d7be18482c7898cd9fb87c4d638443a8548669305a9ba653b9a1bcf99f5e5ec43a39d981fa1f9f1c7e",
          "sha256": "bd2fc7876f206090bfd203292f341546a8f75f5c6c06144d3713085150fc9c0f",
          "sha1": "279d21e386ac46fcafecc387aa1a4a0676f82e3d",
          "md5": "b5c63a4fdeee9a478491f5c3e880332c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-9.5.1-b4-sources.jar",
          "url": "core-ng-search-9.5.1-b4-sources.jar",
          "size": 24936,
          "sha512": "65901e6f65943a660e8c7d191ca28b112754ced2fe52110010c317aea7451ee3fa0ac328041e894fa190014ae3fa2a9f33eeb78a7a1e65722b9f1b3e8bb563bf",
          "sha256": "7a8802b240f9a03ecc763c08900addea9a6eb0d1c87adcc22cb2222893a89dba",
          "sha1": "81a779221c80c56367f603b1c596cc9f57a5d8b3",
          "md5": "c1aedb31e784198d5b83e48630ac8bf5"
        }
      ]
    }
  ]
}
