{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "9.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.4.0"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.18.1"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.4.0.jar",
          "url": "core-ng-search-9.4.0.jar",
          "size": 56008,
          "sha512": "1875c8f4a008c831194eebe86b1f0e681297022a06a6e20b372078972a16019aa95f848d811c547c3f76f746339c3674799ab6334255933ac00eefd650a397c3",
          "sha256": "cf685a6ade911679d7a1bc59b20c70d219c34e9b9b11a45153d132e87090a878",
          "sha1": "534634637035ead48bf486eec7749391953ea83d",
          "md5": "3ef5ad93c4d40cef67708b1750a10eeb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.4.0"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.18.1"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.4.0.jar",
          "url": "core-ng-search-9.4.0.jar",
          "size": 56008,
          "sha512": "1875c8f4a008c831194eebe86b1f0e681297022a06a6e20b372078972a16019aa95f848d811c547c3f76f746339c3674799ab6334255933ac00eefd650a397c3",
          "sha256": "cf685a6ade911679d7a1bc59b20c70d219c34e9b9b11a45153d132e87090a878",
          "sha1": "534634637035ead48bf486eec7749391953ea83d",
          "md5": "3ef5ad93c4d40cef67708b1750a10eeb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-9.4.0-sources.jar",
          "url": "core-ng-search-9.4.0-sources.jar",
          "size": 23526,
          "sha512": "22369f2af99de53dfd57ad021b831ba2edd191f812aad14437384a37b2ce6a00b5fcfe9caf504e9d689a8f21fc5b5a23ff427533f9e95d632581e1f292c9075c",
          "sha256": "ae64ad145d7f290d063ef47ea36460c8f3b9686b99f7dc58447d3562f31b2a04",
          "sha1": "1ef61aa30923f7d03c0fa6181afa3bafa56f3660",
          "md5": "156e3c1fc05db76559b96fdc14d9e70a"
        }
      ]
    }
  ]
}
