{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "9.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.9"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.13.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.0.9.jar",
          "url": "core-ng-search-9.0.9.jar",
          "size": 52823,
          "sha512": "1c284c5cd35a67db4f687b6be2423fb85fd05952edc81f9db34dc89a31125fb86804b08d7dafe80bf1eb8db2faac4d877b8dca348d8e094ff9bea5633fb34671",
          "sha256": "70ab43dbba7b6f8a28f06bcfcd291b00a9cb864680ff3f322115911406ef14a9",
          "sha1": "d5ee3398f7b6800f69916b917eb450c6361e86ab",
          "md5": "6cdcb08ab6afcbee8726fce9cfbac7ef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.9"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.13.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.0.9.jar",
          "url": "core-ng-search-9.0.9.jar",
          "size": 52823,
          "sha512": "1c284c5cd35a67db4f687b6be2423fb85fd05952edc81f9db34dc89a31125fb86804b08d7dafe80bf1eb8db2faac4d877b8dca348d8e094ff9bea5633fb34671",
          "sha256": "70ab43dbba7b6f8a28f06bcfcd291b00a9cb864680ff3f322115911406ef14a9",
          "sha1": "d5ee3398f7b6800f69916b917eb450c6361e86ab",
          "md5": "6cdcb08ab6afcbee8726fce9cfbac7ef"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-9.0.9-sources.jar",
          "url": "core-ng-search-9.0.9-sources.jar",
          "size": 21978,
          "sha512": "7c632f1898125788df554424f2778c42f37bc32bca8459f3add126dc3efd9570bb8bf6765a559d3eecc5bc9fa66570d623b54e64a080658bca0bf111acb83e22",
          "sha256": "711a6eb15eb08c159af09a79a363c46f3aaf660be023777848ba6288b2aa1611",
          "sha1": "45d497a255dea3ad8e844f8bb20c16d2af854331",
          "md5": "a5b0e238b1dd049b95abe84bf2dd01d9"
        }
      ]
    }
  ]
}
