{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "9.4.0-b4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.4.0-b4"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.18.1"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.4.0-b4.jar",
          "url": "core-ng-search-9.4.0-b4.jar",
          "size": 56012,
          "sha512": "916b55cfcd11f402d13a9b3ad7be13a859a4179c7fc6c983c4d5f3315c9886b6666472f744bd20dde61316185ab1c8066eed73fb6cef0747b44e561e05e9fc08",
          "sha256": "dfc9dea9f95cf09cbfc74ef4570a5d82499b4fcc2bd07b4bf8a7f52ed3e75ea9",
          "sha1": "90d3a2d45618254dea4ce877a19e1e91cdcbc01c",
          "md5": "8b1c776b85a90abc9337e619628ff528"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.4.0-b4"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.18.1"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.4.0-b4.jar",
          "url": "core-ng-search-9.4.0-b4.jar",
          "size": 56012,
          "sha512": "916b55cfcd11f402d13a9b3ad7be13a859a4179c7fc6c983c4d5f3315c9886b6666472f744bd20dde61316185ab1c8066eed73fb6cef0747b44e561e05e9fc08",
          "sha256": "dfc9dea9f95cf09cbfc74ef4570a5d82499b4fcc2bd07b4bf8a7f52ed3e75ea9",
          "sha1": "90d3a2d45618254dea4ce877a19e1e91cdcbc01c",
          "md5": "8b1c776b85a90abc9337e619628ff528"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-9.4.0-b4-sources.jar",
          "url": "core-ng-search-9.4.0-b4-sources.jar",
          "size": 23530,
          "sha512": "db9d7c6c44f9992306c1a4719066f257af3ee0066e641eea4fafe823a673894a9ae1fe985a8aaad9adf717d3624cb8eb6c947b07e40964a029e5b8f14198b057",
          "sha256": "37dabd286ce99d0be3cb16b17d1903f86d5cde43a7fa20821bfc98b65ebdd858",
          "sha1": "be94ff0db2e6b2d1c1633b875229b90be96d0df7",
          "md5": "04eec61c1db1568b71e714fef9015c49"
        }
      ]
    }
  ]
}
