{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "7.6.16-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.6.16-b1.jar",
          "url": "core-ng-search-test-7.6.16-b1.jar",
          "size": 9069,
          "sha512": "a3777712c4743d5967c0254a11251d85fcf31229e569809ed0b9779b0a49207f71554ab36a8f21202ce9f77523c1cd4d264935caffc763ecc3ef122335aee036",
          "sha256": "d9ecea5bb18ad38cd9f1743a33eca757f0e9979abe1092d128fe95c0143993e8",
          "sha1": "6d3799ddf4c03035267bd2e032cec1c9c5d9f599",
          "md5": "cd42940dc0798b01cdf048e7edf52205"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.6.16-b1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.6.16-b1"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "7.12.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4-client",
          "version": {
            "requires": "7.12.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "reindex-client",
          "version": {
            "requires": "7.12.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "mapper-extras-client",
          "version": {
            "requires": "7.12.0"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "7.12.0"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "7.12.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.6.16-b1.jar",
          "url": "core-ng-search-test-7.6.16-b1.jar",
          "size": 9069,
          "sha512": "a3777712c4743d5967c0254a11251d85fcf31229e569809ed0b9779b0a49207f71554ab36a8f21202ce9f77523c1cd4d264935caffc763ecc3ef122335aee036",
          "sha256": "d9ecea5bb18ad38cd9f1743a33eca757f0e9979abe1092d128fe95c0143993e8",
          "sha1": "6d3799ddf4c03035267bd2e032cec1c9c5d9f599",
          "md5": "cd42940dc0798b01cdf048e7edf52205"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.6.16-b1-sources.jar",
          "url": "core-ng-search-test-7.6.16-b1-sources.jar",
          "size": 5480,
          "sha512": "467ad1f634a1b09008b241eabf76645472fce9f8e46a539fd90803d03a10eedfa8b05cc6e443afeceb879d10b3de5ebeac1410e397263709c088e95159fc09fa",
          "sha256": "c07a7c86eaa0fc72b99c51c661165363e1a91e619828e2d76a31e56ac62b1398",
          "sha1": "43ffd23e62052e4f472ed135424d681d33232af3",
          "md5": "2167fcb925448aa991e9bb49fa9a5f7c"
        }
      ]
    }
  ]
}
