{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "7.4.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "3mlsin3fvvb55bqty7rjpsuugu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.4.1.1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.6.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.4.1.1.jar",
          "url": "core-ng-test-7.4.1.1.jar",
          "size": 35990,
          "sha512": "83a0aa3a7970ba7ae1ccf30e59a7225f71b00c55cf54600a152910a38c709cd5e144ea37766a60b70f1bdcb65593ebfc037eda7dc222b5a255e76f57f12dc356",
          "sha256": "70dc221475f35421500cf0ea9287ca7a64dda65c9b435b42ed791ea8110145fc",
          "sha1": "9ddf7c515573d4fa0da23d68c7bedc94789d3583",
          "md5": "8b7ad0c2a444ae741e85dff707e9377f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.6.2"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.4.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.4.1.1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.6.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.4.1.1.jar",
          "url": "core-ng-test-7.4.1.1.jar",
          "size": 35990,
          "sha512": "83a0aa3a7970ba7ae1ccf30e59a7225f71b00c55cf54600a152910a38c709cd5e144ea37766a60b70f1bdcb65593ebfc037eda7dc222b5a255e76f57f12dc356",
          "sha256": "70dc221475f35421500cf0ea9287ca7a64dda65c9b435b42ed791ea8110145fc",
          "sha1": "9ddf7c515573d4fa0da23d68c7bedc94789d3583",
          "md5": "8b7ad0c2a444ae741e85dff707e9377f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-7.4.1.1-sources.jar",
          "url": "core-ng-test-7.4.1.1-sources.jar",
          "size": 18199,
          "sha512": "960111841af7fac727eb580bee4d3279fbfa2d1188ede2f72a5ed024463df5e63aea8a92508093b9f569c08208e13ce4346594ad90f59126b4e4a4552ea5a514",
          "sha256": "5a405200ddb76123fe5e881a4a251135bf8e6e66b334cfe262adcc566faa6e49",
          "sha1": "d118ce7e18fe9bc18e00a0e9597c440868e4c786",
          "md5": "af0480c44639f9f27214d69e937af91d"
        }
      ]
    }
  ]
}
