{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.2.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.2.0.jar",
          "url": "core-ng-9.2.0.jar",
          "size": 743218,
          "sha512": "6dc773a45ee2053368c11cbee78ad39bc7c051b8ee386f49548a547c7d6ebe0e4b87e687382fa2ae18974834440b4118de44d3d8c607ab3f6c1c051112da0dc6",
          "sha256": "fe21be5ed747ea05b0e3e89294696c3771014e76778db54d019034fe3ee956d1",
          "sha1": "0fa8a0f7ff638de558cccd335808e61023a8ccea",
          "md5": "0e87f85ff53aa9b07cde94eef6940f1a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.18.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.18.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "4.0.0"
          },
          "excludes": [
            {
              "group": "org.xerial.snappy",
              "module": "*"
            }
          ]
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.2.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.2.0.jar",
          "url": "core-ng-9.2.0.jar",
          "size": 743218,
          "sha512": "6dc773a45ee2053368c11cbee78ad39bc7c051b8ee386f49548a547c7d6ebe0e4b87e687382fa2ae18974834440b4118de44d3d8c607ab3f6c1c051112da0dc6",
          "sha256": "fe21be5ed747ea05b0e3e89294696c3771014e76778db54d019034fe3ee956d1",
          "sha1": "0fa8a0f7ff638de558cccd335808e61023a8ccea",
          "md5": "0e87f85ff53aa9b07cde94eef6940f1a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.2.0-sources.jar",
          "url": "core-ng-9.2.0-sources.jar",
          "size": 381666,
          "sha512": "5ef9622862566f9929f056ff806f168e1156f5d9c2b669e479449fe307abcb360f3d0a41c6460337d8af8976eca4bee734ce056706cd48f371460042ef2759df",
          "sha256": "45d562a62dcbb926b353c8154019dce6daf4a73c47d18ae2ba6fc86fb0e75dbe",
          "sha1": "7ad58c34662c2bb439dab79123cda4516df7c3e1",
          "md5": "c07331e482f15282f5c28ec5d143fc0a"
        }
      ]
    }
  ]
}
