{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "8.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.4.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.24.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-8.1.6.jar",
          "url": "core-ng-test-8.1.6.jar",
          "size": 45962,
          "sha512": "04d7fccb0f74cf8f0378853b32831e3bc00c2a3ffe3a91babd1c4d912da9ee4a6699abd3c8ed299c9f7c5c0d62728758835bb19a4f3072baa39f6af4fdf4c23a",
          "sha256": "3864ca707e5034d7ac06d8dfeb01307367cc67270879cc26017f6fbcf8470ca8",
          "sha1": "a8a5ff3ad448bd21434ac953135709b8883c27f3",
          "md5": "afc00ea571fbdf9a58e5a69ab20e2e75"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "8.1.6"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.10.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.4.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.24.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-8.1.6.jar",
          "url": "core-ng-test-8.1.6.jar",
          "size": 45962,
          "sha512": "04d7fccb0f74cf8f0378853b32831e3bc00c2a3ffe3a91babd1c4d912da9ee4a6699abd3c8ed299c9f7c5c0d62728758835bb19a4f3072baa39f6af4fdf4c23a",
          "sha256": "3864ca707e5034d7ac06d8dfeb01307367cc67270879cc26017f6fbcf8470ca8",
          "sha1": "a8a5ff3ad448bd21434ac953135709b8883c27f3",
          "md5": "afc00ea571fbdf9a58e5a69ab20e2e75"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-8.1.6-sources.jar",
          "url": "core-ng-test-8.1.6-sources.jar",
          "size": 22429,
          "sha512": "eea6fb878f319053f99ff2eae652b9d2929b0e67c1889e4edb60c7fd736b16473f673ebd4bca541d074c0113214ccc29759f7aaa1bd401068842289ebbe245a8",
          "sha256": "3b969d3f047319f39c7732f821f2f938c9c8c03b2c1a2eb4df0c2315d32a5c16",
          "sha1": "61a7d03d4b39223140e020b8a8e7ea0fdcc48e77",
          "md5": "6d9fbba0cf7036369c2c5d83280ea495"
        }
      ]
    }
  ]
}
