{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "7.6.8-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "fbkkyz4bmredpnyliz2efiny7u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.6.8-b0.jar",
          "url": "core-ng-search-test-7.6.8-b0.jar",
          "size": 9069,
          "sha512": "6e4ae5cd0c181501ec1f4dbac3cfcc54c44574416e9592f6147d3d5d7992bd4e16a12a08a709cca847d9bae36d3195910218702edb0fc3a7c7c3eca3ad8a0d75",
          "sha256": "6762a8925befd904707f90ffba1675ed8efa9255296d205b004849874a860c9a",
          "sha1": "653dad3e612d62c284012b224b4804f668424a9f",
          "md5": "596752d22dffce768285139ece7ca59c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.6.8-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.6.8-b0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4-client",
          "version": {
            "requires": "7.10.1"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "reindex-client",
          "version": {
            "requires": "7.10.1"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "7.10.1"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "7.10.1"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "7.10.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.6.8-b0.jar",
          "url": "core-ng-search-test-7.6.8-b0.jar",
          "size": 9069,
          "sha512": "6e4ae5cd0c181501ec1f4dbac3cfcc54c44574416e9592f6147d3d5d7992bd4e16a12a08a709cca847d9bae36d3195910218702edb0fc3a7c7c3eca3ad8a0d75",
          "sha256": "6762a8925befd904707f90ffba1675ed8efa9255296d205b004849874a860c9a",
          "sha1": "653dad3e612d62c284012b224b4804f668424a9f",
          "md5": "596752d22dffce768285139ece7ca59c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.6.8-b0-sources.jar",
          "url": "core-ng-search-test-7.6.8-b0-sources.jar",
          "size": 5480,
          "sha512": "893e487aee64a534ef6ded8b5d0561a74bfe6457329deb602a1a5639de7e34496ee17c79540f88f6c95207807ce3093a13dab3b54a8110612084196d0b03a2e1",
          "sha256": "118bb4acb1edcd579a261230fa66e26d7c810cada5dd96a3cfeeb5f24f2b6234",
          "sha1": "c4d590781ba50843820707d170c3400a876e983b",
          "md5": "2112f26492f7e13383deee3063f576c4"
        }
      ]
    }
  ]
}
