{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "9.4.0-b2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.4.0-b2"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.18.1"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.4.0-b2.jar",
          "url": "core-ng-search-9.4.0-b2.jar",
          "size": 56012,
          "sha512": "da6012c13f99f4871b3eda54262b9380289f78faa5609f615618126b559d70b3fbd0f8c38662d9facfde8733a522b6cf1b816cf12c77b609c2295bc3061deb4a",
          "sha256": "87fea127abe110b098c74cd8ec7b1763cdd7e3151cf22435a1d592212a35754c",
          "sha1": "e7a934b911238f71a5f23e84e58baf254e7f57c3",
          "md5": "5a2f6eadabff403e8e10a2f5f6ff103a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.4.0-b2"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.18.1"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.4.0-b2.jar",
          "url": "core-ng-search-9.4.0-b2.jar",
          "size": 56012,
          "sha512": "da6012c13f99f4871b3eda54262b9380289f78faa5609f615618126b559d70b3fbd0f8c38662d9facfde8733a522b6cf1b816cf12c77b609c2295bc3061deb4a",
          "sha256": "87fea127abe110b098c74cd8ec7b1763cdd7e3151cf22435a1d592212a35754c",
          "sha1": "e7a934b911238f71a5f23e84e58baf254e7f57c3",
          "md5": "5a2f6eadabff403e8e10a2f5f6ff103a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-9.4.0-b2-sources.jar",
          "url": "core-ng-search-9.4.0-b2-sources.jar",
          "size": 23530,
          "sha512": "293794a75fe8c8f3f47ae05b9b88a4fb8d1d21d7d40e00bd8524e1d5447d8ee80a9e1715e4f15e50d33493a2bcc58871929a3ea3065f0eff997d2a3a25905bf9",
          "sha256": "ad19a42cc8b7a63075ed1ba514324cac42e5ee8c8929b9e9719b7fc5c60da319",
          "sha1": "789136b554d169bae08e5e56bc6611a2fb2d2f80",
          "md5": "f4c9831f7838586e62708a7afb52dfb3"
        }
      ]
    }
  ]
}
