{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "7.7.4-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.7.4-b1"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.7.4-b1.jar",
          "url": "core-ng-mongo-7.7.4-b1.jar",
          "size": 53969,
          "sha512": "88abcabfc6a756f02cb71852b627d63d3b511b918e3c17eaa345dfe859bc1199b4ce7a440ef7bf100b9c23fd780c6d65f5157624687e99764900805439ec6ad1",
          "sha256": "c26421a1e1ba89f36f6a63ab04ad6ee0904686a9be247848fff40f431717624e",
          "sha1": "a2c36d32777c906a3b816086c233a52da08bfa0a",
          "md5": "e082d12c8bd504c437760149bf54afde"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.7.4-b1"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.7.4-b1.jar",
          "url": "core-ng-mongo-7.7.4-b1.jar",
          "size": 53969,
          "sha512": "88abcabfc6a756f02cb71852b627d63d3b511b918e3c17eaa345dfe859bc1199b4ce7a440ef7bf100b9c23fd780c6d65f5157624687e99764900805439ec6ad1",
          "sha256": "c26421a1e1ba89f36f6a63ab04ad6ee0904686a9be247848fff40f431717624e",
          "sha1": "a2c36d32777c906a3b816086c233a52da08bfa0a",
          "md5": "e082d12c8bd504c437760149bf54afde"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-7.7.4-b1-sources.jar",
          "url": "core-ng-mongo-7.7.4-b1-sources.jar",
          "size": 25322,
          "sha512": "b1dd206d4176450ce5426d62c6a74edb7df133a9ac9ba99d0736d62139e2f7789f877fd19c4d7017ef1ce9611f14e50cb03244d7a1cf0cc219896a5824a65302",
          "sha256": "80406a41dfe8fc83465a5c156cd95b54281653a5b6e0bede1c97d6301ea20873",
          "sha1": "0a4d5762fbf4ab04dd7fea80b1768ddce44de0d0",
          "md5": "ef82eda280f9b64ee7e783346da98278"
        }
      ]
    }
  ]
}
