{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "7.3.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "n256ilhourhwnpb4f4kxqe2zpy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.3.12"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "7.3.12"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-7.3.12.jar",
          "url": "core-ng-mongo-test-7.3.12.jar",
          "size": 2339,
          "sha512": "7ba4802b89203a0b67994173464102e97de08cb5a0f86f006c7a2e18fce04d33c464be827396ccaa3fd03e09b7423a3ce927ad4cd45c65bb46a7a532147b3c94",
          "sha256": "f6b248528f35fbe67b833a90d5b771eb22d436aef7f5bbae83e8602b284d46d5",
          "sha1": "c6f277287d066211db995bfa9b66bf97dcac8470",
          "md5": "51a2e553596e2b56a910e0aab954de46"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.24.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.3.12"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "7.3.12"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-7.3.12.jar",
          "url": "core-ng-mongo-test-7.3.12.jar",
          "size": 2339,
          "sha512": "7ba4802b89203a0b67994173464102e97de08cb5a0f86f006c7a2e18fce04d33c464be827396ccaa3fd03e09b7423a3ce927ad4cd45c65bb46a7a532147b3c94",
          "sha256": "f6b248528f35fbe67b833a90d5b771eb22d436aef7f5bbae83e8602b284d46d5",
          "sha1": "c6f277287d066211db995bfa9b66bf97dcac8470",
          "md5": "51a2e553596e2b56a910e0aab954de46"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-7.3.12-sources.jar",
          "url": "core-ng-mongo-test-7.3.12-sources.jar",
          "size": 1575,
          "sha512": "dcd8973536e6e1121866d08b1b1bb06c68051162085a3af59e7d10b5b9889527143dc88b2497e0b2c701dbe634ffe4862b58bab6a75bade81197789d78210a26",
          "sha256": "9dda36abc0ba98513e20bf19c888bee641217144b98716d8c4b3211151e6b9be",
          "sha1": "1c7775cbdeb6c0c9391f22796ea71070072a1ab7",
          "md5": "92ce3c45e9005d3481c758b7e024d958"
        }
      ]
    }
  ]
}
