{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "7.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "tiw26whr7vh43djrdosu3oi4rq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.4.6"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.4.6.jar",
          "url": "core-ng-mongo-7.4.6.jar",
          "size": 54208,
          "sha512": "64427a1ea19323c9aeb264ad198ae1dc4a6abf520508988174e89502eb5dc8e8d70092fcefd598abaf9ba7ad7ae519abde3128d7fa91d06db46e02590a56fbda",
          "sha256": "dcaf51dbf291347f04c1fd902fd57e86089028805baeabb5b8489c5f5343bd56",
          "sha1": "b376b2768c4d985be1f11bf05064fa99c12834d3",
          "md5": "9485f60a7ef0b121d0f74cad065c5242"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.4.6"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.4.6.jar",
          "url": "core-ng-mongo-7.4.6.jar",
          "size": 54208,
          "sha512": "64427a1ea19323c9aeb264ad198ae1dc4a6abf520508988174e89502eb5dc8e8d70092fcefd598abaf9ba7ad7ae519abde3128d7fa91d06db46e02590a56fbda",
          "sha256": "dcaf51dbf291347f04c1fd902fd57e86089028805baeabb5b8489c5f5343bd56",
          "sha1": "b376b2768c4d985be1f11bf05064fa99c12834d3",
          "md5": "9485f60a7ef0b121d0f74cad065c5242"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-7.4.6-sources.jar",
          "url": "core-ng-mongo-7.4.6-sources.jar",
          "size": 25673,
          "sha512": "bd3b84d5d69f86f94149d73c039b2a53f2d59dc20300d86632f40e986a2c37f79c02527e8296c17569a68a67da14e574fa002f9c075ba17783a1368d34510da7",
          "sha256": "5438ddc6e71c53e7d2596e43b7b63ca9a2fb478f999767002c4ef9fedb0e56f7",
          "sha1": "a6c91be50ac7a75298c29aebe351ea10fa5b217c",
          "md5": "a5d38482a60ec54c1dfce501a5a600d9"
        }
      ]
    }
  ]
}
