{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.0.5"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.0.5.jar",
          "url": "core-ng-9.0.5.jar",
          "size": 738439,
          "sha512": "f10c786f03a93db4a704eb8d78eea73d2e81bdf32d1aa879fc21f4929632775f13500f9aebdc309ff937a2b83702d2d6d9f9f9ff44fa6399e62b9af6519ae4b6",
          "sha256": "cbf497af0c323eef72427a844fe71c623120cef1d34d338790dda295b0b2fc27",
          "sha1": "e3737ceb0d6ba920bdef81982ec4bd29704209b4",
          "md5": "6ea55b59340e18d65dd7023b1623878e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.16.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.16.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.10.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "3.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.10.5"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.0.5"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.0.5.jar",
          "url": "core-ng-9.0.5.jar",
          "size": 738439,
          "sha512": "f10c786f03a93db4a704eb8d78eea73d2e81bdf32d1aa879fc21f4929632775f13500f9aebdc309ff937a2b83702d2d6d9f9f9ff44fa6399e62b9af6519ae4b6",
          "sha256": "cbf497af0c323eef72427a844fe71c623120cef1d34d338790dda295b0b2fc27",
          "sha1": "e3737ceb0d6ba920bdef81982ec4bd29704209b4",
          "md5": "6ea55b59340e18d65dd7023b1623878e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.0.5-sources.jar",
          "url": "core-ng-9.0.5-sources.jar",
          "size": 379808,
          "sha512": "e25cb1b25d64a1e3426d9fa59b9c97220cfe1ad122d65651f8bf955f569f72370d2e87fe0f48bb6e606a3f6e9a5377d4b350a7624bb6b07716bc6a8007c426f3",
          "sha256": "70f1e12eed6fdc1418e6e1f5117e113d4c60ec92aa485eb03ddb57dcfdbba965",
          "sha1": "b7d10510e92f2b51f827f0430b84399bb257ca19",
          "md5": "3d91c1b2ec9d578897958996a7f92d60"
        }
      ]
    }
  ]
}
