{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "7.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "k2jakp6nkfdonngpza6tht5nna"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.3.6"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.3.6.jar",
          "url": "core-ng-7.3.6.jar",
          "size": 611909,
          "sha512": "d1943f08504b38e44818e3d1646bde71781e0c787bc7762ff4320275ff9d3ad9717ebcc0902cb7544ca181e1c505a3e6ff9cddc930d7089e7c1ca874daab9ffd",
          "sha256": "e1a4e7895c43259064dd04413ab0e7c5b83492fb74c3288cbf5bc43167ad63f1",
          "sha1": "410a30942257aaacf7b666bbf3f2d6da4fe1ca22",
          "md5": "14e13eed995c2f844feb4f41164a1e8e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.26.0-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.10.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.10.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.3.1"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.0.29.Final"
          }
        },
        {
          "group": "org.jboss.xnio",
          "module": "xnio-nio",
          "version": {
            "requires": "3.7.7.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.7.3"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.3.6"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.3.6.jar",
          "url": "core-ng-7.3.6.jar",
          "size": 611909,
          "sha512": "d1943f08504b38e44818e3d1646bde71781e0c787bc7762ff4320275ff9d3ad9717ebcc0902cb7544ca181e1c505a3e6ff9cddc930d7089e7c1ca874daab9ffd",
          "sha256": "e1a4e7895c43259064dd04413ab0e7c5b83492fb74c3288cbf5bc43167ad63f1",
          "sha1": "410a30942257aaacf7b666bbf3f2d6da4fe1ca22",
          "md5": "14e13eed995c2f844feb4f41164a1e8e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-7.3.6-sources.jar",
          "url": "core-ng-7.3.6-sources.jar",
          "size": 311208,
          "sha512": "5c6795458d83968bd6d5580aa46dfc1c0fd05f2b4b36f1f00907a35083dca24635e86ecfb61b84c540ede29e7cd68a0bbde16aa9403ec49db0a7bd37955e92da",
          "sha256": "62aea6a0d3715213230927c26e0476353b758b7443498053b31e824a0f00fc03",
          "sha1": "00a862ba0563c388bfdd51b19eb7d157125f4659",
          "md5": "ca988d28a281859164023c2ee52e66af"
        }
      ]
    }
  ]
}
