{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework.mysql",
    "module": "mysql-connector-j",
    "version": "8.4.0-r3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mysql-connector-j-8.4.0-r3.jar",
          "url": "mysql-connector-j-8.4.0-r3.jar",
          "size": 517268,
          "sha512": "feea2b4e8b0dede1ebfe88224b373329b61502f686506b99aaaa1e60fc0c7186be07de918264ce8c9704e2c82902d1311545f57f7772afdaadd5edf14b6cdc28",
          "sha256": "bbe111e07b66192b6ad510a138a0d0199b1e9db6450e0255e5aec325242e59bc",
          "sha1": "674aa17f28b531d29415d8112eb404b543e685ed",
          "md5": "678fc84b0dc43788a1df09e7a633fa82"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mysql-connector-j-8.4.0-r3.jar",
          "url": "mysql-connector-j-8.4.0-r3.jar",
          "size": 517268,
          "sha512": "feea2b4e8b0dede1ebfe88224b373329b61502f686506b99aaaa1e60fc0c7186be07de918264ce8c9704e2c82902d1311545f57f7772afdaadd5edf14b6cdc28",
          "sha256": "bbe111e07b66192b6ad510a138a0d0199b1e9db6450e0255e5aec325242e59bc",
          "sha1": "674aa17f28b531d29415d8112eb404b543e685ed",
          "md5": "678fc84b0dc43788a1df09e7a633fa82"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mysql-connector-j-8.4.0-r3-sources.jar",
          "url": "mysql-connector-j-8.4.0-r3-sources.jar",
          "size": 520375,
          "sha512": "31b90182125704e9dd14d0a841adf0b526387995d7a633aca8a85adf438d8a2fc08cc49087c39f20821ec2ee5ebbbc5620cfd487b6ca23d0af77718a71a0545a",
          "sha256": "261a6c8c371dd4f59e3998043512dae27668dddff80051ad8300b3731d26d80c",
          "sha1": "17f93f73df4236082f77011486642329a67edf2a",
          "md5": "11429c6f45909a70dd3e45e34e481c4a"
        }
      ]
    }
  ]
}
