{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "7.7.1-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-7.7.1-b0.jar",
          "url": "core-ng-api-7.7.1-b0.jar",
          "size": 10958,
          "sha512": "80da4b65869a5dada081fb15bd18cf4f3d31e7b5afbcf7b9d3a03e4b06651b6c968df1724cd400351734696288649befd42da8cfaf882a514f9b9e143dbcb13d",
          "sha256": "1fdffd2dd373a11462c89d8176436c1571d20b15b316a2e7252cff1e32f09625",
          "sha1": "aafec6fc3f8a793f64776c57bb91ddc7f1e9f16f",
          "md5": "bd27bfe6996b52235f03566f43da8734"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.7.1-b0.jar",
          "url": "core-ng-api-7.7.1-b0.jar",
          "size": 10958,
          "sha512": "80da4b65869a5dada081fb15bd18cf4f3d31e7b5afbcf7b9d3a03e4b06651b6c968df1724cd400351734696288649befd42da8cfaf882a514f9b9e143dbcb13d",
          "sha256": "1fdffd2dd373a11462c89d8176436c1571d20b15b316a2e7252cff1e32f09625",
          "sha1": "aafec6fc3f8a793f64776c57bb91ddc7f1e9f16f",
          "md5": "bd27bfe6996b52235f03566f43da8734"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.7.1-b0-sources.jar",
          "url": "core-ng-api-7.7.1-b0-sources.jar",
          "size": 8643,
          "sha512": "cd54aba7405fafae8b9eca0e6e4c9b4f06ab5b434039055f594740a42afc392a5bd0f464b224e0ab2112146db1c654e3b0c6b5b963cdc02be11e9bf8eeec457a",
          "sha256": "d999459011ac5128f939db38fb6eb2e3e4abc5b30726d1b946bc294eacc1219a",
          "sha1": "9711c15d180c3866653cbcf98f8dc020ccfad00a",
          "md5": "b44d8556db51b4e9677155f5ae9874eb"
        }
      ]
    }
  ]
}
