{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "7.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "khklefg2nva3beahmqh2vw57ea"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.3.7"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "7.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-7.3.7.jar",
          "url": "core-ng-mongo-test-7.3.7.jar",
          "size": 2341,
          "sha512": "bf8049bbe707983b902c626e1b708db21bdbd8502e389704f6912fd6f570aac5364c8aefc85b2fba7e0a71a8ae3f089c0fc13e99f088de3f58b3862f612c60e7",
          "sha256": "04e11f917ec51fc327eee18e61bcc0e4a0183d0a9ba9b4d15338a00a52ae0ca4",
          "sha1": "830fe81a3a34091f8a8a50519f9dbeba1aeab095",
          "md5": "ef7143b422dda11760c59c08a6a9de05"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.24.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.3.7"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "7.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-7.3.7.jar",
          "url": "core-ng-mongo-test-7.3.7.jar",
          "size": 2341,
          "sha512": "bf8049bbe707983b902c626e1b708db21bdbd8502e389704f6912fd6f570aac5364c8aefc85b2fba7e0a71a8ae3f089c0fc13e99f088de3f58b3862f612c60e7",
          "sha256": "04e11f917ec51fc327eee18e61bcc0e4a0183d0a9ba9b4d15338a00a52ae0ca4",
          "sha1": "830fe81a3a34091f8a8a50519f9dbeba1aeab095",
          "md5": "ef7143b422dda11760c59c08a6a9de05"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-7.3.7-sources.jar",
          "url": "core-ng-mongo-test-7.3.7-sources.jar",
          "size": 1576,
          "sha512": "a120f5ef78125bc16dce59c4b504e0a6572e25870add9c5511709bb7f16b4217c1e39bc201fc758486ae62b65e5f056577ba66f1ee46b25ed35e284f51a4da28",
          "sha256": "1683b910289f699d5ad748bf9fda1c088d960b22102457a1fed00c55ad373e8d",
          "sha1": "16e0f5fb10a33ad1a5998718e2c4750c01ce5643",
          "md5": "3089174e523eb65b109b4fe1c8f3e565"
        }
      ]
    }
  ]
}
