{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "7.6.8-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "fbkkyz4bmredpnyliz2efiny7u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.8-b0"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "7.10.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "elasticsearch",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch-x-content",
          "version": {
            "requires": "7.10.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "elasticsearch-x-content",
              "type": "jar",
              "extension": "jar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.6.8-b0.jar",
          "url": "core-ng-search-7.6.8-b0.jar",
          "size": 38504,
          "sha512": "db3bb7b7a12a4db9aad586a7f08156b2090454d568462e372ad767157a704ab3b8b6b75cad7ed719dc1209439e9d2b0366f755bdf4f1dbeafa4b3bac21e9ba08",
          "sha256": "894e07d86e04d486663c71e83335ecb4a20c2b709665b924fc4d42a18d1284c1",
          "sha1": "72880dd1d3ac7b87ac8826f78ba1d594058fc6b0",
          "md5": "c2dbc3a41459d14b1420f5e4cffa1b0a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.elasticsearch.client",
          "module": "elasticsearch-rest-high-level-client",
          "version": {
            "requires": "7.10.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.8-b0"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "7.10.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "elasticsearch",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch-x-content",
          "version": {
            "requires": "7.10.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "elasticsearch-x-content",
              "type": "jar",
              "extension": "jar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.6.8-b0.jar",
          "url": "core-ng-search-7.6.8-b0.jar",
          "size": 38504,
          "sha512": "db3bb7b7a12a4db9aad586a7f08156b2090454d568462e372ad767157a704ab3b8b6b75cad7ed719dc1209439e9d2b0366f755bdf4f1dbeafa4b3bac21e9ba08",
          "sha256": "894e07d86e04d486663c71e83335ecb4a20c2b709665b924fc4d42a18d1284c1",
          "sha1": "72880dd1d3ac7b87ac8826f78ba1d594058fc6b0",
          "md5": "c2dbc3a41459d14b1420f5e4cffa1b0a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-7.6.8-b0-sources.jar",
          "url": "core-ng-search-7.6.8-b0-sources.jar",
          "size": 17330,
          "sha512": "c6997f5ce2705eeafcabe4c5ef7022284c60fa0997178e00487b3440fe0b18c397d70d07732ab2978cc298eef33963ea718d48f83db725525fa578264a560026",
          "sha256": "2a5b130940ec52416ea5de575067b4dd7b7013958414bed7872943ddf0bb603b",
          "sha1": "40d27def1c024e9a8b0bba6235e1eedd06573f85",
          "md5": "a4fe25468b27180ce8c72702e1d4e5cb"
        }
      ]
    }
  ]
}
