{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "7.6.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "cj4ceplftrgnjo6zmp4mmewmni"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.6.13"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.6.13.jar",
          "url": "core-ng-7.6.13.jar",
          "size": 685356,
          "sha512": "2420733c8e2151bb6b9188932ccf37d8dd269c486fb61bd271b0405bce085ce9919a998e6604fd16ca3d483d25c2c92669745fcb32a9953094fd928c2eda6f69",
          "sha256": "f1142d7d189ee7340f7b4d6ff61513a8fb27a395e4df1986b2275c2914ddfc56",
          "sha1": "49a3373b1c1592eb7554095a36ccc1d5d1a5c76e",
          "md5": "6893861864a85a2087a3be4c118565da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.27.0-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.2.4.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.7.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.8.2"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.6.13"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.6.13.jar",
          "url": "core-ng-7.6.13.jar",
          "size": 685356,
          "sha512": "2420733c8e2151bb6b9188932ccf37d8dd269c486fb61bd271b0405bce085ce9919a998e6604fd16ca3d483d25c2c92669745fcb32a9953094fd928c2eda6f69",
          "sha256": "f1142d7d189ee7340f7b4d6ff61513a8fb27a395e4df1986b2275c2914ddfc56",
          "sha1": "49a3373b1c1592eb7554095a36ccc1d5d1a5c76e",
          "md5": "6893861864a85a2087a3be4c118565da"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-7.6.13-sources.jar",
          "url": "core-ng-7.6.13-sources.jar",
          "size": 352588,
          "sha512": "af464775d0c162ca1ab760b84c7bcbaabbf5c7b845d4c18e0680bff06bf3aafd3f856e4af229b4ed6013f4e67da76b63a0230a9d01fd3b60b174bdd47957d5a7",
          "sha256": "9c1209a88e15c9e6211c257099b9d8f63d9423c8459843ae79dc33b8ad877515",
          "sha1": "33f008c943e4137fbeb730a161d2fe7fbeda7a85",
          "md5": "214f0286a12a6271e47fd0e9297dc7af"
        }
      ]
    }
  ]
}
