{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "7.6.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "5ouw753gz5cgbnubxggdyz4bvu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-7.6.12.jar",
          "url": "core-ng-mongo-test-7.6.12.jar",
          "size": 2383,
          "sha512": "da1f4331c1b369772f16245cb6b27c84e9c0598dce6c21d2b6fafd81ebe6964d6ed5367216fd0dec4a8c40d17a3ef47908c6d98f32f2de3040a2a94cafd1b6ae",
          "sha256": "e136ee56a8feaf0f6512f11c7826e6884a6ce270733891ac04036a89746333e9",
          "sha1": "b2f04c0f8467cf47ebc23d698837823e208b072c",
          "md5": "eea51314e1827cb7d433d9f13689e5d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.6.12"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "7.6.12"
          }
        },
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.37.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-7.6.12.jar",
          "url": "core-ng-mongo-test-7.6.12.jar",
          "size": 2383,
          "sha512": "da1f4331c1b369772f16245cb6b27c84e9c0598dce6c21d2b6fafd81ebe6964d6ed5367216fd0dec4a8c40d17a3ef47908c6d98f32f2de3040a2a94cafd1b6ae",
          "sha256": "e136ee56a8feaf0f6512f11c7826e6884a6ce270733891ac04036a89746333e9",
          "sha1": "b2f04c0f8467cf47ebc23d698837823e208b072c",
          "md5": "eea51314e1827cb7d433d9f13689e5d8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-7.6.12-sources.jar",
          "url": "core-ng-mongo-test-7.6.12-sources.jar",
          "size": 1721,
          "sha512": "8126f9801284d6a9aa0c6e235537576ca362b331bbfb151faf6af0db74761ba178fedeec5eb279347ea6176ef2ff414f6b6e6ec8fb14003ba58b726e777f849c",
          "sha256": "17de399e45c67e655c9d6802997526961d2ce0b808e54bfe915ddc3338c9ba51",
          "sha1": "d65013da448a57cd98e0093b9e7702ace181b3e9",
          "md5": "ffba908771f134a06222ece7d8a5e086"
        }
      ]
    }
  ]
}
