{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "8.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "8.1.6"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-8.1.6.jar",
          "url": "core-ng-search-8.1.6.jar",
          "size": 52829,
          "sha512": "2b4d5f1a296204164e1705727ea5a7f637d239bd781acfab7d1dba53e00ce1dc54fdf21f4ecb9a724235aee6e4da1604d258063769fe3f364458d11da3c41414",
          "sha256": "ba69de59a9e5acdd027869f60bee84720c898c432d74a945c24fda2101f5ae2c",
          "sha1": "330ae3b9d48be23b8f1968b5c3d051208014d65d",
          "md5": "497be7785bdca204c0fcffba7b3b9160"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "8.1.6"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-8.1.6.jar",
          "url": "core-ng-search-8.1.6.jar",
          "size": 52829,
          "sha512": "2b4d5f1a296204164e1705727ea5a7f637d239bd781acfab7d1dba53e00ce1dc54fdf21f4ecb9a724235aee6e4da1604d258063769fe3f364458d11da3c41414",
          "sha256": "ba69de59a9e5acdd027869f60bee84720c898c432d74a945c24fda2101f5ae2c",
          "sha1": "330ae3b9d48be23b8f1968b5c3d051208014d65d",
          "md5": "497be7785bdca204c0fcffba7b3b9160"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-8.1.6-sources.jar",
          "url": "core-ng-search-8.1.6-sources.jar",
          "size": 21979,
          "sha512": "3860bdb54211ffc89a9e57926fb8b77248ace0973f39dfa28a8d8bb9de05c920f609b556d99a0781d6039e150c756ee657533c22fde7b5e4461f87f3ef257eb4",
          "sha256": "6a4681774bf7a8beb3e9c226a6e70b7f101aa6f3e0ed99d40477531111187978",
          "sha1": "43e5a1451418955a26428e89da7ef8b8a3d5561c",
          "md5": "edce5263935255359a7d31877624129f"
        }
      ]
    }
  ]
}
