{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "9.3.0-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.3.0-b0.jar",
          "url": "core-ng-mongo-test-9.3.0-b0.jar",
          "size": 2939,
          "sha512": "2b3f37fb5efc16d4db713c53b0ac48197fe16db517b9de687ee623194af0a999196565215af7365f2947fa19cfbf7fb16b6621ee59c8f8dc5b09a038bf5daac0",
          "sha256": "42070d05b414bfc58d86d3ea0ef9f43dca10c4bb79b5f2c027b0038bddae0f2c",
          "sha1": "c900418c2ca17ed846b7517289f3d1c8b2a4533a",
          "md5": "c7d936990fcad8875fe649a976c621e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.3.0-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "9.3.0-b0"
          }
        },
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.47.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-9.3.0-b0.jar",
          "url": "core-ng-mongo-test-9.3.0-b0.jar",
          "size": 2939,
          "sha512": "2b3f37fb5efc16d4db713c53b0ac48197fe16db517b9de687ee623194af0a999196565215af7365f2947fa19cfbf7fb16b6621ee59c8f8dc5b09a038bf5daac0",
          "sha256": "42070d05b414bfc58d86d3ea0ef9f43dca10c4bb79b5f2c027b0038bddae0f2c",
          "sha1": "c900418c2ca17ed846b7517289f3d1c8b2a4533a",
          "md5": "c7d936990fcad8875fe649a976c621e5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.3.0-b0-sources.jar",
          "url": "core-ng-mongo-test-9.3.0-b0-sources.jar",
          "size": 2078,
          "sha512": "e25b8abae504b24e894293c3d14607b5baa5a39e642dab6f50504ef9f5b980689a603c8cf318031ca8f2b606656131cac80761a42dc257f4daeb9e8d8cbfe121",
          "sha256": "51bd0665768eae8c99f5743d2fcdb30c4d94c89870fcf85dc23db40a3424ce6d",
          "sha1": "1a7f42002c81574aa435142241c0fab3b870f31a",
          "md5": "db2a9ce781cd17b6b34bac1dac7682dd"
        }
      ]
    }
  ]
}
