{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "9.5.1-b3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.5.1-b3"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "9.3.2"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            },
            {
              "group": "io.opentelemetry.semconv",
              "module": "*"
            },
            {
              "group": "com.fasterxml.jackson.core",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.5.1-b3.jar",
          "url": "core-ng-search-9.5.1-b3.jar",
          "size": 59683,
          "sha512": "f83459f582804d563da23fa27600fdb189430f426876e9289cbb856a4d8f561dbbeed236d56e98b26f38c0cc07512b814e312966d88b3db498997f718de17faf",
          "sha256": "bcd69e6b11cce9053cf925e268e6e9415fb3d6256689c3b847015b83cd496dfc",
          "sha1": "625a78d6c12d9598c00a070a6aa26b57f6d0c6a6",
          "md5": "85827aac1b5ed187e3be8f6d391d7566"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-rest5-client",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "tools.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.5.1-b3"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "9.3.2"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            },
            {
              "group": "io.opentelemetry.semconv",
              "module": "*"
            },
            {
              "group": "com.fasterxml.jackson.core",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.5.1-b3.jar",
          "url": "core-ng-search-9.5.1-b3.jar",
          "size": 59683,
          "sha512": "f83459f582804d563da23fa27600fdb189430f426876e9289cbb856a4d8f561dbbeed236d56e98b26f38c0cc07512b814e312966d88b3db498997f718de17faf",
          "sha256": "bcd69e6b11cce9053cf925e268e6e9415fb3d6256689c3b847015b83cd496dfc",
          "sha1": "625a78d6c12d9598c00a070a6aa26b57f6d0c6a6",
          "md5": "85827aac1b5ed187e3be8f6d391d7566"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-9.5.1-b3-sources.jar",
          "url": "core-ng-search-9.5.1-b3-sources.jar",
          "size": 25135,
          "sha512": "2fa85efc955e18498cd24b9acef256297674d7fdc5d2e5405c6642832b00122a29f7e3a3375396e03369734a8c1b30573a492b8735472c25ffed9ce21016d16c",
          "sha256": "fe16888f4fbcbeb39909a3d44c1c3ef7a52521995d3d2d0be02ec515bda48168",
          "sha1": "0592bbd209da012da02ea2f1c71d67a401ba1768",
          "md5": "d1c860904a491ee0aac4964ecd8182e8"
        }
      ]
    }
  ]
}
