{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.4.0-b3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.4.0-b3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.4.0-b3.jar",
          "url": "core-ng-9.4.0-b3.jar",
          "size": 788992,
          "sha512": "3adcd494be3f80876ae1dd15de95c04c9516ef7f374df29c680f7305b98ebde32339823d97ce0ed847e98834951fd6d2d85ad01409055dcd919f71bbca3095c9",
          "sha256": "1209a0a86c56ea4276ae2c2a91f5dd87a3034d0f3b347e1bfa9f34a6c7f7d8d7",
          "sha1": "b5932dd455b1ea4caaa8b889822e53a711f30da8",
          "md5": "5b2d5f57e4bf7c8718795754448eeec8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.22.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "4.1.1"
          },
          "excludes": [
            {
              "group": "org.xerial.snappy",
              "module": "*"
            },
            {
              "group": "org.lz4",
              "module": "*"
            }
          ]
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.4.0-b3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.4.0-b3.jar",
          "url": "core-ng-9.4.0-b3.jar",
          "size": 788992,
          "sha512": "3adcd494be3f80876ae1dd15de95c04c9516ef7f374df29c680f7305b98ebde32339823d97ce0ed847e98834951fd6d2d85ad01409055dcd919f71bbca3095c9",
          "sha256": "1209a0a86c56ea4276ae2c2a91f5dd87a3034d0f3b347e1bfa9f34a6c7f7d8d7",
          "sha1": "b5932dd455b1ea4caaa8b889822e53a711f30da8",
          "md5": "5b2d5f57e4bf7c8718795754448eeec8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.4.0-b3-sources.jar",
          "url": "core-ng-9.4.0-b3-sources.jar",
          "size": 405439,
          "sha512": "ddca2fe210c97946bdfb1dd5a4489b50dda6f2a768163bc64b41a54da3a4d98f287da49c947036362429f9ca30a65e9516fb84cf3a8b516324b43d40f9a90577",
          "sha256": "6a9a68dde165a1068aa915508d28ba1189cdcbab0ce6de2d36ce8820a5d7abef",
          "sha1": "7bdee6e30d13b3edb052ddc3e6c5e7f3738cdd20",
          "md5": "1cd03b634a3114667ec942aae74a3bbc"
        }
      ]
    }
  ]
}
