{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "9.1.6-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.1.6-b1.jar",
          "url": "core-ng-search-test-9.1.6-b1.jar",
          "size": 13291,
          "sha512": "40255227427f2e955cd481c4f403abe9581c7ffb742662fe52a90cdf159df1124bac7fcc25c910047d8b15a400e740a043efc4cb34c72261d265546e4d433cdf",
          "sha256": "0906c6e42d278e0139acac2f2f5b334992f0e9cc82f5a3bb2cfdd04be21e0443",
          "sha1": "e5bb640e8cf19ba4450474065596fdcd3c982b33",
          "md5": "1957bcde3a9939c7f6a8829babee67a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.1.6-b1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "9.1.6-b1"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "8.15.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4",
          "version": {
            "requires": "8.15.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "8.15.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "8.15.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "8.15.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "reindex",
          "version": {
            "requires": "8.15.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "reindex",
              "type": "jar",
              "extension": "jar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-9.1.6-b1.jar",
          "url": "core-ng-search-test-9.1.6-b1.jar",
          "size": 13291,
          "sha512": "40255227427f2e955cd481c4f403abe9581c7ffb742662fe52a90cdf159df1124bac7fcc25c910047d8b15a400e740a043efc4cb34c72261d265546e4d433cdf",
          "sha256": "0906c6e42d278e0139acac2f2f5b334992f0e9cc82f5a3bb2cfdd04be21e0443",
          "sha1": "e5bb640e8cf19ba4450474065596fdcd3c982b33",
          "md5": "1957bcde3a9939c7f6a8829babee67a5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.1.6-b1-sources.jar",
          "url": "core-ng-search-test-9.1.6-b1-sources.jar",
          "size": 7351,
          "sha512": "100aac39637ad644f71dcff47c656c96c7bfd5343c2a736d1c12500a4d751a658a3664340421ab091505c3365a3b8293567fce4c3e408aa1ecb476d04ef117d0",
          "sha256": "48e4cf069b136ecd6b270deafe621ca7fcaa2ff53b32421d9d96899ec013fbc5",
          "sha1": "07240fb5ac033a9e1c707bb06fe095fb13ebb0f7",
          "md5": "564e3adeb6c3abd6767e0581a87031ad"
        }
      ]
    }
  ]
}
