{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "7.7.4-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.7.4-b1.jar",
          "url": "core-ng-search-test-7.7.4-b1.jar",
          "size": 9068,
          "sha512": "1eb4fef8fa038a43f8b7cca3245db33c00428ebcdd72d4dc4a2a40404d0b1db077c4b4c64b7ca1ccb60da86ac997d33c63b23452cc0411755e2362fba2c1cc3c",
          "sha256": "fd475f06668106a742e7bde1f0388d61050342e41b35c6c77bf47d9b096fa895",
          "sha1": "c1cf7d3e9b30071963ea6cc771cde25b0d754e86",
          "md5": "ace850f4132f3a59733c4e901100a930"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.7.4-b1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.7.4-b1"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "7.13.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4-client",
          "version": {
            "requires": "7.13.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "reindex-client",
          "version": {
            "requires": "7.13.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "mapper-extras-client",
          "version": {
            "requires": "7.13.0"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "7.13.0"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "7.13.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.7.4-b1.jar",
          "url": "core-ng-search-test-7.7.4-b1.jar",
          "size": 9068,
          "sha512": "1eb4fef8fa038a43f8b7cca3245db33c00428ebcdd72d4dc4a2a40404d0b1db077c4b4c64b7ca1ccb60da86ac997d33c63b23452cc0411755e2362fba2c1cc3c",
          "sha256": "fd475f06668106a742e7bde1f0388d61050342e41b35c6c77bf47d9b096fa895",
          "sha1": "c1cf7d3e9b30071963ea6cc771cde25b0d754e86",
          "md5": "ace850f4132f3a59733c4e901100a930"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.7.4-b1-sources.jar",
          "url": "core-ng-search-test-7.7.4-b1-sources.jar",
          "size": 5479,
          "sha512": "1fa2deb9c172ac0db8f2718465502a9d57b000297eac6221eba8cfe019c3b4121288b517f5d93fd73805b273b1316abf2896b054170109c41667b974cf01f698",
          "sha256": "35b01212d85d72ada24df0009e89fed0c0baa299e816525cf396b72e5fb190d7",
          "sha1": "8914e4c0635ad0b78c6330b2f2cf503c0bc555e9",
          "md5": "2e7ac4a2701e26c91397e170799cad17"
        }
      ]
    }
  ]
}
