{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "9.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-9.2.0.jar",
          "url": "core-ng-api-9.2.0.jar",
          "size": 11018,
          "sha512": "49e8cec0f43f51e32247208b79a4f2146d18fbf92b152a70b8b84a929be40cd37bd9efd48db4f4cb92cbdcc35d6585639fdfec984ef87eb8a9aee8ae0b240ed7",
          "sha256": "66ce714213fcb7308f16e19924009b0d6127104e91a42e520f6bdd3c4e25e921",
          "sha1": "dbf9800669c7b084e4023b4d92568cea44fd06c3",
          "md5": "4f02655619ff9ba1f48fcbfda75c255e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.2.0.jar",
          "url": "core-ng-api-9.2.0.jar",
          "size": 11018,
          "sha512": "49e8cec0f43f51e32247208b79a4f2146d18fbf92b152a70b8b84a929be40cd37bd9efd48db4f4cb92cbdcc35d6585639fdfec984ef87eb8a9aee8ae0b240ed7",
          "sha256": "66ce714213fcb7308f16e19924009b0d6127104e91a42e520f6bdd3c4e25e921",
          "sha1": "dbf9800669c7b084e4023b4d92568cea44fd06c3",
          "md5": "4f02655619ff9ba1f48fcbfda75c255e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.2.0-sources.jar",
          "url": "core-ng-api-9.2.0-sources.jar",
          "size": 8662,
          "sha512": "6f436b7fda9e7a045a1629049980a48e97f49a86c2cd76f25141922507765a4b0080bd4cb5d57898629e6ce29744f4fb9469c21bb5cd3046fc0f4de9ef74ce46",
          "sha256": "519713bfaac5fe1f773a7d286ccfe1668a4bc2f4bf1a890391af2bf1f91869ee",
          "sha1": "527a4e8663cf691c2350525a077011a1a1e05b62",
          "md5": "5dae03171a68ff18117d668011015963"
        }
      ]
    }
  ]
}
