{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.3.0-b2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.3.0-b2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.3.0-b2.jar",
          "url": "core-ng-9.3.0-b2.jar",
          "size": 772449,
          "sha512": "9fdf46bbfdfe4cfa987be6d9e5fd721bbe63031ca64dcf689f8c87f28c0569ef26de81781372156870ea098dea6e6fc1d733f87fa1fb5a56258dd61eecd2f9c6",
          "sha256": "bc72845391603d99ed5040fad8e21558430f8ae974817d3c3603c100d908e50e",
          "sha1": "6d228e4f128c7f28e87ee48fdff4750049b49cc9",
          "md5": "f0e5cbb9d0aabc576f97e8b41a7a70d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.19.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "org.xerial.snappy",
              "module": "*"
            },
            {
              "group": "org.lz4",
              "module": "*"
            }
          ]
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.3.0-b2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.3.0-b2.jar",
          "url": "core-ng-9.3.0-b2.jar",
          "size": 772449,
          "sha512": "9fdf46bbfdfe4cfa987be6d9e5fd721bbe63031ca64dcf689f8c87f28c0569ef26de81781372156870ea098dea6e6fc1d733f87fa1fb5a56258dd61eecd2f9c6",
          "sha256": "bc72845391603d99ed5040fad8e21558430f8ae974817d3c3603c100d908e50e",
          "sha1": "6d228e4f128c7f28e87ee48fdff4750049b49cc9",
          "md5": "f0e5cbb9d0aabc576f97e8b41a7a70d4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.3.0-b2-sources.jar",
          "url": "core-ng-9.3.0-b2-sources.jar",
          "size": 398410,
          "sha512": "d1362f5dcc28e05ac0248d05d51e12b5d4544b665a2698390b6eb6e4b34f23abbf4aea750a2008a0491c192cfdb949c945d4dd09c0995511e3c34f0df73e4ebf",
          "sha256": "e725bb00c194681ec5473edfff2608327fd0694ddbc7de288aaf707440057feb",
          "sha1": "d2c14d7eaf6ec866d1abb6b0e797b5a459b05445",
          "md5": "56d723ea0f2d54285f4747770b7b55ed"
        }
      ]
    }
  ]
}
