{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "7.4.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "3mlsin3fvvb55bqty7rjpsuugu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.4.1.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "7.4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-7.4.1.1.jar",
          "url": "core-ng-mongo-test-7.4.1.1.jar",
          "size": 2342,
          "sha512": "1047305e2657f41fe3aaa8b2841ff1ffaaa58b5404373a288f8c2876082fa3360aba92339e7a1d30731eb6358d16d02607ac5e17ca0c731e90d77f8f0addc4d0",
          "sha256": "d7fbde96a4af774acc061c8a1357ab25cdee2121bad33c5d76bd34a32fc5cc8f",
          "sha1": "d25e2a43a1c36fd219411cc9e5c1613242914120",
          "md5": "73b9a0ca38033c0f5ec569ce1673e1b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.27.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.4.1.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "7.4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-7.4.1.1.jar",
          "url": "core-ng-mongo-test-7.4.1.1.jar",
          "size": 2342,
          "sha512": "1047305e2657f41fe3aaa8b2841ff1ffaaa58b5404373a288f8c2876082fa3360aba92339e7a1d30731eb6358d16d02607ac5e17ca0c731e90d77f8f0addc4d0",
          "sha256": "d7fbde96a4af774acc061c8a1357ab25cdee2121bad33c5d76bd34a32fc5cc8f",
          "sha1": "d25e2a43a1c36fd219411cc9e5c1613242914120",
          "md5": "73b9a0ca38033c0f5ec569ce1673e1b2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-7.4.1.1-sources.jar",
          "url": "core-ng-mongo-test-7.4.1.1-sources.jar",
          "size": 1576,
          "sha512": "54669156b319434d6b0cb23e1c278bc3ae7cff52f7a9b12ca93132b1497e233654e3cc5a9a460ae6eb2517c9fe93406deefef749acf1de5dfbc9bce46d10de0c",
          "sha256": "3326be01ac028b14c27ba6c8b4001705aaaf0ac5783d011e005ff0c0400ece29",
          "sha1": "0312f7a6a9b612bc6290f6bc12a6d204e2fa4224",
          "md5": "8df7b6b356e56b82f9661ced51fddc1b"
        }
      ]
    }
  ]
}
