{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "7.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "f7eqsbbfnjd2hgtrjqhlqd7ezy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.3.8"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.3.8"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.3.8.jar",
          "url": "core-ng-search-test-7.3.8.jar",
          "size": 8921,
          "sha512": "76aa2fb73107ef30fe47cf2d4c6d8905990d179304431b6c29e6a28e59d66a15fb555cbc5b509201a8e2b5b1c375d3f2d11f4eb1e582d18bb3746ca65bb5b5b1",
          "sha256": "c61ed789badd2f0a99126d6391476550307fb6ddfcbe084d4e8a59c273b47161",
          "sha1": "a9dc15ff4ae7e09a18c9c6107cc48b6997761e16",
          "md5": "1c298c61cb74ad0c9c4f97eca791c003"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4-client",
          "version": {
            "requires": "7.6.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "reindex-client",
          "version": {
            "requires": "7.6.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "7.6.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "7.6.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "7.6.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.3.8"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.3.8"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.3.8.jar",
          "url": "core-ng-search-test-7.3.8.jar",
          "size": 8921,
          "sha512": "76aa2fb73107ef30fe47cf2d4c6d8905990d179304431b6c29e6a28e59d66a15fb555cbc5b509201a8e2b5b1c375d3f2d11f4eb1e582d18bb3746ca65bb5b5b1",
          "sha256": "c61ed789badd2f0a99126d6391476550307fb6ddfcbe084d4e8a59c273b47161",
          "sha1": "a9dc15ff4ae7e09a18c9c6107cc48b6997761e16",
          "md5": "1c298c61cb74ad0c9c4f97eca791c003"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.3.8-sources.jar",
          "url": "core-ng-search-test-7.3.8-sources.jar",
          "size": 5095,
          "sha512": "8a42b6c578f42823ce719bac4fb396bab33bb5384087e8b0f1adaa438895c153b234c365a26cab2d4e31a91c5fe48be08bb4ab2eae156f82176d6f4d96b0e6d5",
          "sha256": "0c244b4e651d472325194cb1bf29bf742cc2616ed3ba9f5ce5880474cf0ab0d9",
          "sha1": "459d6706841cf022893a21158e4cfa0fcaa321ac",
          "md5": "ab4805f17e711ff39f0793233a947529"
        }
      ]
    }
  ]
}
