{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.4.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.4.0.jar",
          "url": "core-ng-9.4.0.jar",
          "size": 787156,
          "sha512": "6f1f69530be5aed4f30e9ce380a0df11a742ebf5f1c325b6995812ac380a52c66dd16be21fe4c05f1ed13bc72fd528a282e54b6194f2ebb5efaf37df5931bd1c",
          "sha256": "7c3eb2fd3cc5b1ba442d904d02ecbd98f0d4402047869a596e511bedf2bdefc0",
          "sha1": "0d18c28fb46f41f0d6463e3368a3aa421d92638f",
          "md5": "ae8fc261b95ceabe20f76e7f6a2ab5e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.22.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "4.1.1"
          },
          "excludes": [
            {
              "group": "org.xerial.snappy",
              "module": "*"
            },
            {
              "group": "org.lz4",
              "module": "*"
            }
          ]
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.4.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.4.0.jar",
          "url": "core-ng-9.4.0.jar",
          "size": 787156,
          "sha512": "6f1f69530be5aed4f30e9ce380a0df11a742ebf5f1c325b6995812ac380a52c66dd16be21fe4c05f1ed13bc72fd528a282e54b6194f2ebb5efaf37df5931bd1c",
          "sha256": "7c3eb2fd3cc5b1ba442d904d02ecbd98f0d4402047869a596e511bedf2bdefc0",
          "sha1": "0d18c28fb46f41f0d6463e3368a3aa421d92638f",
          "md5": "ae8fc261b95ceabe20f76e7f6a2ab5e5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.4.0-sources.jar",
          "url": "core-ng-9.4.0-sources.jar",
          "size": 405083,
          "sha512": "2020d5a17510b814a77fc3e1d3ae44d9a9336dfdf842d042771fde2c56e52f31351c2b49a01b64eedd541d0abcc6826c6d59c5f55985549e76eb3734519021f3",
          "sha256": "96ab49898eb8025803ccf25eeb2f02dbf5bbc935237d8a0dadca497388033fe7",
          "sha1": "80d2c9ca3dfc5172ab17ff3824cc26f6acdef05a",
          "md5": "22ea254b349b1961e2221596030fd05c"
        }
      ]
    }
  ]
}
