{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "7.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.7.0.jar",
          "url": "core-ng-test-7.7.0.jar",
          "size": 41885,
          "sha512": "106a441a1d2d0c2a57db79792951051971b06bf32b34becf733dc8994df8d1616a31df2a40e6cd12339c1d28fd131262f99fed9cccbaade4ca365b5745993ed5",
          "sha256": "e011fafcdb3e70aa0feb69b8be64d2dc469913a34a3697816a50650e1070e6f8",
          "sha1": "880e537fa1dd075e1fbde9e5ed1415d28fd168bd",
          "md5": "a6d23d07fa04e651101aa236f4ccd6e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.7.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.7.2"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.8.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.7.0.jar",
          "url": "core-ng-test-7.7.0.jar",
          "size": 41885,
          "sha512": "106a441a1d2d0c2a57db79792951051971b06bf32b34becf733dc8994df8d1616a31df2a40e6cd12339c1d28fd131262f99fed9cccbaade4ca365b5745993ed5",
          "sha256": "e011fafcdb3e70aa0feb69b8be64d2dc469913a34a3697816a50650e1070e6f8",
          "sha1": "880e537fa1dd075e1fbde9e5ed1415d28fd168bd",
          "md5": "a6d23d07fa04e651101aa236f4ccd6e4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-7.7.0-sources.jar",
          "url": "core-ng-test-7.7.0-sources.jar",
          "size": 20149,
          "sha512": "b303e828b1b4e4df8bacc81e56d9d7dfb17aefb889a2f3f4c1573617835906c30eb6128d2d36328a3a6381f1dd810e7641f4c8039bdc2899d6b76dd7183be2d8",
          "sha256": "f179ecda14233101fbc2b384a644d479bc865d0f52509e9d2063121bbf91ab4a",
          "sha1": "0b5321952cfbcbfabc24a263db29186791f5c16b",
          "md5": "9e1c51c3bb141a7b7e0ba6d3bab5bb3a"
        }
      ]
    }
  ]
}
