{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "7.6.16-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-7.6.16-b0.jar",
          "url": "core-ng-api-7.6.16-b0.jar",
          "size": 10959,
          "sha512": "130464de1f9b59b1d87d734aabdd5c14b2411eaaf1a35d5581603b981a5f2b27536fade6d3252ddf0cdefcae6c75454d7080fd05d33453e15dc81273284b9533",
          "sha256": "5263ae410dcbe23e9e7df8e82ffc7fd75f2d03e29997f98015234e5b42da5d31",
          "sha1": "e807672ce0f4594d8b44523e6db795e763faabd0",
          "md5": "dc4bd5fd1317bde5371aaafc666ed62c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.6.16-b0.jar",
          "url": "core-ng-api-7.6.16-b0.jar",
          "size": 10959,
          "sha512": "130464de1f9b59b1d87d734aabdd5c14b2411eaaf1a35d5581603b981a5f2b27536fade6d3252ddf0cdefcae6c75454d7080fd05d33453e15dc81273284b9533",
          "sha256": "5263ae410dcbe23e9e7df8e82ffc7fd75f2d03e29997f98015234e5b42da5d31",
          "sha1": "e807672ce0f4594d8b44523e6db795e763faabd0",
          "md5": "dc4bd5fd1317bde5371aaafc666ed62c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.6.16-b0-sources.jar",
          "url": "core-ng-api-7.6.16-b0-sources.jar",
          "size": 8644,
          "sha512": "10f73351efecbfcedd0fe2bfe8856255f8d8129fedb305b0943cc2cec16c9e900751c25fa203df4f8f694e427d7ef7f6323cff255ed755ebafe8d77fcf8235eb",
          "sha256": "bf51f854d3924ae2ad384e1ccd4f516d99e568a8311d89b3f9ac6ae2ebe7d360",
          "sha1": "80701b314564307451949dfe131611b61321c619",
          "md5": "31c33cf78958cd59fb9ca6736f7cb6ae"
        }
      ]
    }
  ]
}
