{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "7.6.16-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-7.6.16-b0.jar",
          "url": "core-ng-api-7.6.16-b0.jar",
          "size": 10959,
          "sha512": "8ada0c33b56fb5d41730d7f1539ac99abecbfddda874506fb8e6f02687e1dbff29d7d8081ce105ae7c940702f262878bea83ed43d1f87238e2bacedf2e20bb42",
          "sha256": "d2ec2b327d2aeabccf8c3d2814a3fb2e0fe98530012000269e3249f4187536eb",
          "sha1": "2e08ce800d48e8610ce39a093664a9c9ff5d53eb",
          "md5": "1dc74d824fe932751e1c82cce5ab5c5e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.6.16-b0.jar",
          "url": "core-ng-api-7.6.16-b0.jar",
          "size": 10959,
          "sha512": "8ada0c33b56fb5d41730d7f1539ac99abecbfddda874506fb8e6f02687e1dbff29d7d8081ce105ae7c940702f262878bea83ed43d1f87238e2bacedf2e20bb42",
          "sha256": "d2ec2b327d2aeabccf8c3d2814a3fb2e0fe98530012000269e3249f4187536eb",
          "sha1": "2e08ce800d48e8610ce39a093664a9c9ff5d53eb",
          "md5": "1dc74d824fe932751e1c82cce5ab5c5e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.6.16-b0-sources.jar",
          "url": "core-ng-api-7.6.16-b0-sources.jar",
          "size": 8644,
          "sha512": "a049056a12cb037ced9cbd4f05552f3e77bf4afe427712b9aa3271b643215445b994a76a8326fe2ca8f45f721b021dc6842cfe328baf6c31b21667bbac0f66ee",
          "sha256": "d1206f79a14079df34b768021e9cf7f8a5e784e127228dcfe707f19f004fe48b",
          "sha1": "476d0b7eea22a49a18852e6487323bafa0b92e19",
          "md5": "51ccf204f2d527d6a57df18f147c03c6"
        }
      ]
    }
  ]
}
