{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "9.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.0.1.jar",
          "url": "core-ng-mongo-test-9.0.1.jar",
          "size": 2384,
          "sha512": "03c7090e6192f3a4efc2ba6c7e609e1c658363d0cdd1c661c2acc18fa81ddf7cee2ad64f8aa791cdb32d1ab89d5699f3c8d6da5e4e70d882e0425b317f67e1ab",
          "sha256": "a79eba2c8932f3b11e8ee46340a7c0d50b606d1e0fd26d4e43eeae6aed5395b1",
          "sha1": "f358584a2cfba36bd2cf590822b1fddd7f9125f2",
          "md5": "40daac25e85816c4793c845208e734b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.0.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "9.0.1"
          }
        },
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.44.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-9.0.1.jar",
          "url": "core-ng-mongo-test-9.0.1.jar",
          "size": 2384,
          "sha512": "03c7090e6192f3a4efc2ba6c7e609e1c658363d0cdd1c661c2acc18fa81ddf7cee2ad64f8aa791cdb32d1ab89d5699f3c8d6da5e4e70d882e0425b317f67e1ab",
          "sha256": "a79eba2c8932f3b11e8ee46340a7c0d50b606d1e0fd26d4e43eeae6aed5395b1",
          "sha1": "f358584a2cfba36bd2cf590822b1fddd7f9125f2",
          "md5": "40daac25e85816c4793c845208e734b5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.0.1-sources.jar",
          "url": "core-ng-mongo-test-9.0.1-sources.jar",
          "size": 1718,
          "sha512": "07bfef311be1e260269d157d292ffad08569716348c73f774f1c1c602a70c7c3dc2ed9a6a2da390c4dac12a9a41327fc5b89f0a352453d94ac0946c78fc574f4",
          "sha256": "681d007b998a5b64bd67b0573ada90fa2c8c60957430a312e406be5153f5ee54",
          "sha1": "e23961401483d82afc3950b5e9494cbf589c44b4",
          "md5": "e359e3e4ae5262f36382fc9820a3fad5"
        }
      ]
    }
  ]
}
