{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "9.5.1-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.5.1-b1"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "9.3.2"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            },
            {
              "group": "io.opentelemetry.semconv",
              "module": "*"
            },
            {
              "group": "com.fasterxml.jackson.core",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.5.1-b1.jar",
          "url": "core-ng-search-9.5.1-b1.jar",
          "size": 58086,
          "sha512": "3979666b0c98b27523d644e352407a1152848fda5214d38449228099a684a642c7274a683cd9ab8de9e284bc69ac7c29f944d4daf273e7427bbd960adf20a4f2",
          "sha256": "5e89b45565e4ac31018b86cbe7f7a3dc40bcf8b01bda0aa1e6b5d50ea2a47e4c",
          "sha1": "91fadc5c068a3ec1965e3729a96bda4ca2fe81de",
          "md5": "c5433e3dacbfbf9a1b793bbf56fc082b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-rest5-client",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "tools.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.5.1-b1"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "9.3.2"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            },
            {
              "group": "io.opentelemetry.semconv",
              "module": "*"
            },
            {
              "group": "com.fasterxml.jackson.core",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.5.1-b1.jar",
          "url": "core-ng-search-9.5.1-b1.jar",
          "size": 58086,
          "sha512": "3979666b0c98b27523d644e352407a1152848fda5214d38449228099a684a642c7274a683cd9ab8de9e284bc69ac7c29f944d4daf273e7427bbd960adf20a4f2",
          "sha256": "5e89b45565e4ac31018b86cbe7f7a3dc40bcf8b01bda0aa1e6b5d50ea2a47e4c",
          "sha1": "91fadc5c068a3ec1965e3729a96bda4ca2fe81de",
          "md5": "c5433e3dacbfbf9a1b793bbf56fc082b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-9.5.1-b1-sources.jar",
          "url": "core-ng-search-9.5.1-b1-sources.jar",
          "size": 24230,
          "sha512": "2e7d5658cd25439197fda02e54ed739c9662002acb243854ca58e085f2da777e43d96e5c44d58185d8344a6068b411739b979224f67f45c1da089bdbdfbab0df",
          "sha256": "1c388bc39ca51b732f2d4fb46d286d0bf6b28b7caeff014b0d272ccf9d43678d",
          "sha1": "7db11f46198b102fc3802fa11d9877d52db12bb4",
          "md5": "8df933394f58293298edc00cf617749a"
        }
      ]
    }
  ]
}
