{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "7.6.4-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "d4bpwwgkvbhk5k3pu7mvcd3od4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.6.4-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.6.4-b0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.6.4-b0.jar",
          "url": "core-ng-search-test-7.6.4-b0.jar",
          "size": 9069,
          "sha512": "d975dc28bd535da77e2ab5e25173dc2f5e473e014c1a8026d3501698ed6089a5ce58e3a734861a1b05fe3fbdd1f0118ddc4c98326674ec41e06858c823f13bb4",
          "sha256": "dc9929bd89d3b53a7975d4d116e95375913df24abbf6196f76d4333c16278def",
          "sha1": "0275543dbf1fb50ac6bb0dc1247a61155110425e",
          "md5": "c2f3223cba4fc0ec6c3f830454818260"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4-client",
          "version": {
            "requires": "7.10.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "reindex-client",
          "version": {
            "requires": "7.10.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "7.10.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "7.10.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "7.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.6.4-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.6.4-b0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.6.4-b0.jar",
          "url": "core-ng-search-test-7.6.4-b0.jar",
          "size": 9069,
          "sha512": "d975dc28bd535da77e2ab5e25173dc2f5e473e014c1a8026d3501698ed6089a5ce58e3a734861a1b05fe3fbdd1f0118ddc4c98326674ec41e06858c823f13bb4",
          "sha256": "dc9929bd89d3b53a7975d4d116e95375913df24abbf6196f76d4333c16278def",
          "sha1": "0275543dbf1fb50ac6bb0dc1247a61155110425e",
          "md5": "c2f3223cba4fc0ec6c3f830454818260"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.6.4-b0-sources.jar",
          "url": "core-ng-search-test-7.6.4-b0-sources.jar",
          "size": 5480,
          "sha512": "acd791fb1db64154ffea299c29b317d34cd495b504f0f55634b03f79576aa291994082329bb50b8305284f16bce80ec31443b636ccc0ebe97c0e4646e087c7e3",
          "sha256": "f93b1b23421b5bc4fb6a53c9b2c4b6a22bd7e218f819070bbdc3cd8906acf129",
          "sha1": "9db1e963e6d11cf26c42dd567ee5dffbfa986f1f",
          "md5": "03ce38db8512abb629e733b6235806ea"
        }
      ]
    }
  ]
}
