{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "7.7.4-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-7.7.4-b0.jar",
          "url": "core-ng-mongo-test-7.7.4-b0.jar",
          "size": 2383,
          "sha512": "59b1accd0deb144db54bcb7d5f7f2fd716e908a62cf3f45f43053006413ad3fd6342370c7539c2ed453711a9fb20ae85968745cfad649178cec8cb58d210af42",
          "sha256": "cb83c705c89fa0d1077383cd3f6e7f9298041020f33d077ad1f7b0c22f5ac3e1",
          "sha1": "ecf310b2ca5a557981662f98d01d714ee50ffc5e",
          "md5": "b950171ac6d85785d45d521900ddf217"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.7.4-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "7.7.4-b0"
          }
        },
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.38.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-7.7.4-b0.jar",
          "url": "core-ng-mongo-test-7.7.4-b0.jar",
          "size": 2383,
          "sha512": "59b1accd0deb144db54bcb7d5f7f2fd716e908a62cf3f45f43053006413ad3fd6342370c7539c2ed453711a9fb20ae85968745cfad649178cec8cb58d210af42",
          "sha256": "cb83c705c89fa0d1077383cd3f6e7f9298041020f33d077ad1f7b0c22f5ac3e1",
          "sha1": "ecf310b2ca5a557981662f98d01d714ee50ffc5e",
          "md5": "b950171ac6d85785d45d521900ddf217"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-7.7.4-b0-sources.jar",
          "url": "core-ng-mongo-test-7.7.4-b0-sources.jar",
          "size": 1721,
          "sha512": "a7d5bcb4e62502dabf14d396a30b88158033891e365e8b3f4adfaf0207729fe42e51b8c516da972e31e75046fad0e1526379994a4e89153c1c7453589743541d",
          "sha256": "fb4515963db90f49a5ddd52282b7fc8817d8ec3f2a01feef667ac376455ee172",
          "sha1": "4e7667f1aa2795ab91a7be4aaf8b3ca0e09ea326",
          "md5": "f46c79f6011ab91f0097dbd207033a1d"
        }
      ]
    }
  ]
}
