{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "9.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-9.0.0.jar",
          "url": "core-ng-api-9.0.0.jar",
          "size": 10982,
          "sha512": "c7c9ca71e0e01b845843c1a1c1b62ed9a33c2d9672929ee6dddaa2095ed734610ae184b9386476c5bacf557715149b179f39ee66544008d015ea70a6148ba963",
          "sha256": "50d60a2427034d78334d1e1b474254695d7a8bf487f2f0b3eedfb800dff3336f",
          "sha1": "a6944070716d816f8d13e39f25328e1406937aa1",
          "md5": "87e5942d9b6798fc84b270b8bbe69e1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.0.0.jar",
          "url": "core-ng-api-9.0.0.jar",
          "size": 10982,
          "sha512": "c7c9ca71e0e01b845843c1a1c1b62ed9a33c2d9672929ee6dddaa2095ed734610ae184b9386476c5bacf557715149b179f39ee66544008d015ea70a6148ba963",
          "sha256": "50d60a2427034d78334d1e1b474254695d7a8bf487f2f0b3eedfb800dff3336f",
          "sha1": "a6944070716d816f8d13e39f25328e1406937aa1",
          "md5": "87e5942d9b6798fc84b270b8bbe69e1e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.0.0-sources.jar",
          "url": "core-ng-api-9.0.0-sources.jar",
          "size": 8640,
          "sha512": "7e922e97a46acd7593bd0a3d58d0aba9aa79e382c0a1bc12c946fd6ec6aba302bb9f47f3f785484cca71ed1307575629595f67b490a41fb30e5accd869b652b2",
          "sha256": "cfef02ec52b334c1a7115b8155157b895fd00c4d71b7714e44dc70d263b8016c",
          "sha1": "1be40b90d1d30c31f41fdf17b860d4a7c5ea673a",
          "md5": "dab707120ff570ffbc9b3b5fb0b037bd"
        }
      ]
    }
  ]
}
