{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "9.1.0-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.1.0-b1.jar",
          "url": "core-ng-search-test-9.1.0-b1.jar",
          "size": 13228,
          "sha512": "c7a21000d283563b5007a1ecf26b718a3ebca230cac9514fb59cf6c04c5331172cd738f72d192014f43480257d8590d19c1fdcd2afdfe979e25be0284420f4c0",
          "sha256": "5a18eae33cfdce87164f801af420ef82f0e7bea911640a011ad63a8cf91e26c5",
          "sha1": "ccfc6662550830d28ec38b60f7956a7a16d5ff67",
          "md5": "60dd1dd15be4525f57c5aaf61997467e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.1.0-b1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "9.1.0-b1"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "8.14.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4",
          "version": {
            "requires": "8.14.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "8.14.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "8.14.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "8.14.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "reindex",
          "version": {
            "requires": "8.14.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "reindex",
              "type": "jar",
              "extension": "jar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-9.1.0-b1.jar",
          "url": "core-ng-search-test-9.1.0-b1.jar",
          "size": 13228,
          "sha512": "c7a21000d283563b5007a1ecf26b718a3ebca230cac9514fb59cf6c04c5331172cd738f72d192014f43480257d8590d19c1fdcd2afdfe979e25be0284420f4c0",
          "sha256": "5a18eae33cfdce87164f801af420ef82f0e7bea911640a011ad63a8cf91e26c5",
          "sha1": "ccfc6662550830d28ec38b60f7956a7a16d5ff67",
          "md5": "60dd1dd15be4525f57c5aaf61997467e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.1.0-b1-sources.jar",
          "url": "core-ng-search-test-9.1.0-b1-sources.jar",
          "size": 7234,
          "sha512": "ed0180a18897b56a4f264dc5b04b3da141cbcc28ae22af70265e7c26056b3c7f63f76e050d4bfc890db7159b0a9be3cbaf121a5c88879f77d5071d0cdca37ebb",
          "sha256": "8b0fb3c4afa2592d4d5bf96dc763b124bccda150915902d571d653c54707631a",
          "sha1": "dc50f494bfede146b0bca8b222e0f4264f074455",
          "md5": "256c41cbded66a65c34296ca51a8eea4"
        }
      ]
    }
  ]
}
