{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "9.1.0-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.0-b1"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.1.0-b1.jar",
          "url": "core-ng-search-9.1.0-b1.jar",
          "size": 52825,
          "sha512": "ac41924a2e87acade6903235226f74aee048ed9c7c4194a8c9f898b98fe653e2919207cedb02b3c9b325610df896d812b334423225aa697ffa9037eaf5bbd0bd",
          "sha256": "10cc1681b9c0d81eac21c9bc6fa5eed96579d796af81c61a46527824ab1a309e",
          "sha1": "bcd0bf00f457f6ca3199e462e18ee13271ac7148",
          "md5": "2aca958503194056056bbf8d6d62d6e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.0-b1"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.1.0-b1.jar",
          "url": "core-ng-search-9.1.0-b1.jar",
          "size": 52825,
          "sha512": "ac41924a2e87acade6903235226f74aee048ed9c7c4194a8c9f898b98fe653e2919207cedb02b3c9b325610df896d812b334423225aa697ffa9037eaf5bbd0bd",
          "sha256": "10cc1681b9c0d81eac21c9bc6fa5eed96579d796af81c61a46527824ab1a309e",
          "sha1": "bcd0bf00f457f6ca3199e462e18ee13271ac7148",
          "md5": "2aca958503194056056bbf8d6d62d6e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-9.1.0-b1-sources.jar",
          "url": "core-ng-search-9.1.0-b1-sources.jar",
          "size": 21980,
          "sha512": "0e92b28a234d17ab0b94cdd56b378b27817796fcf6bbe70859ee3ac42867146044a3865ef9001d8b2a7dd905249ca7616f026307e3a16f5fd8007dc6829d0b47",
          "sha256": "1548bf4a592ef51018d44b338a4a8863800671ef7f5dfb364e1c7884dd1a0e82",
          "sha1": "8cee3811f619801fc9bc6fc96cc34a527022a274",
          "md5": "3e6e0131171a5dd8c719c7cfc533e3a9"
        }
      ]
    }
  ]
}
