{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "9.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.2.0.jar",
          "url": "core-ng-mongo-test-9.2.0.jar",
          "size": 2485,
          "sha512": "f972610c20542ed9f689e639c4791f7803f95582ac4230bbf605108c8b3057691e55604d5856919bb1261f0440eb57432ed96b36582257509f3c663adb4887a6",
          "sha256": "ed3970c77c0fbd53b30d57be2e978b8dd559c1f8505d7f57d0dfe003bac48ae5",
          "sha1": "3adbdc478b4b04717e65d3762c23e8150fb98b5a",
          "md5": "92c022fe836eab7fb5162b8d5743a642"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.2.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "9.2.0"
          }
        },
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.46.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-9.2.0.jar",
          "url": "core-ng-mongo-test-9.2.0.jar",
          "size": 2485,
          "sha512": "f972610c20542ed9f689e639c4791f7803f95582ac4230bbf605108c8b3057691e55604d5856919bb1261f0440eb57432ed96b36582257509f3c663adb4887a6",
          "sha256": "ed3970c77c0fbd53b30d57be2e978b8dd559c1f8505d7f57d0dfe003bac48ae5",
          "sha1": "3adbdc478b4b04717e65d3762c23e8150fb98b5a",
          "md5": "92c022fe836eab7fb5162b8d5743a642"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.2.0-sources.jar",
          "url": "core-ng-mongo-test-9.2.0-sources.jar",
          "size": 1778,
          "sha512": "5c73be807a6ed186a7fc9900478d77aa64f7e4a82745d4249495dcd300ec972e746f7a346b8b398b11fbdac5f165baa4268fbc41ac3987c23ded92372c4bb68a",
          "sha256": "6f7703b5247028dfa43ea5932eed60faf204caa2ccc72a2d1f0f93bc0c3110bd",
          "sha1": "c0e304f6c279915e4efcfa58365ce9432afcc306",
          "md5": "48b74ce5c67055f915d9beda406b6015"
        }
      ]
    }
  ]
}
