{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "7.6.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.6.15.jar",
          "url": "core-ng-search-test-7.6.15.jar",
          "size": 9063,
          "sha512": "328c4442d43df6d85ef768a0ee26ae77e8be1e97f3bc4fde7d8b78ec5cdabbea339f08fedfc572b8029927a8bfbd1fb266234428ba630274a237452bd54e18b8",
          "sha256": "15a6b023c5465afac8b4aeba1970c345c7c4972f4ae9e2d1c924fe0117dbeeb0",
          "sha1": "09a61e200a1c09fc7ca06afd87ccc8ea3d6d6945",
          "md5": "14e99a0926e78db19e36391ad041307c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.6.15"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.6.15"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "7.12.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4-client",
          "version": {
            "requires": "7.12.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "reindex-client",
          "version": {
            "requires": "7.12.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "mapper-extras-client",
          "version": {
            "requires": "7.12.0"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "7.12.0"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "7.12.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.6.15.jar",
          "url": "core-ng-search-test-7.6.15.jar",
          "size": 9063,
          "sha512": "328c4442d43df6d85ef768a0ee26ae77e8be1e97f3bc4fde7d8b78ec5cdabbea339f08fedfc572b8029927a8bfbd1fb266234428ba630274a237452bd54e18b8",
          "sha256": "15a6b023c5465afac8b4aeba1970c345c7c4972f4ae9e2d1c924fe0117dbeeb0",
          "sha1": "09a61e200a1c09fc7ca06afd87ccc8ea3d6d6945",
          "md5": "14e99a0926e78db19e36391ad041307c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.6.15-sources.jar",
          "url": "core-ng-search-test-7.6.15-sources.jar",
          "size": 5474,
          "sha512": "0b2480527025fd7d4abc2dc8e59fce25774f05fd20aa893df059a6f03a0f4cc3dbea387b986214c7bd1a0f50188c47d2ea9bf6194d9373f15cb1a55bfefb7086",
          "sha256": "1cd56918208baceb0471a4eb2474d0f87fce3d7c3e8e5d2ecf422ad7c4dd8c81",
          "sha1": "e287d2222735b9d8f85f7e6bb16959ec88b1de76",
          "md5": "de5212f8c4213b035797fe0b6c56942b"
        }
      ]
    }
  ]
}
