{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "9.1.6-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.1.6-b0.jar",
          "url": "core-ng-mongo-test-9.1.6-b0.jar",
          "size": 2489,
          "sha512": "c359a4e702ba10bcb1ef76076ef03916d6114504feba0867eabcc7e124927dc277d04a4a60e801fb72f75f592852406d6798c914ed0a2000171363de568c35ca",
          "sha256": "9df9dcc045045cd6f6736f12fb8e0d4d62bbec83a692486e8fb3f7efd4b28116",
          "sha1": "5f2a2b420f56b45ba97a21fe6d5350f62987dcbd",
          "md5": "e81637c05918ebe93044f4622eeadcdf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.1.6-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "9.1.6-b0"
          }
        },
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.46.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-9.1.6-b0.jar",
          "url": "core-ng-mongo-test-9.1.6-b0.jar",
          "size": 2489,
          "sha512": "c359a4e702ba10bcb1ef76076ef03916d6114504feba0867eabcc7e124927dc277d04a4a60e801fb72f75f592852406d6798c914ed0a2000171363de568c35ca",
          "sha256": "9df9dcc045045cd6f6736f12fb8e0d4d62bbec83a692486e8fb3f7efd4b28116",
          "sha1": "5f2a2b420f56b45ba97a21fe6d5350f62987dcbd",
          "md5": "e81637c05918ebe93044f4622eeadcdf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.1.6-b0-sources.jar",
          "url": "core-ng-mongo-test-9.1.6-b0-sources.jar",
          "size": 1781,
          "sha512": "10ae9a22bc17e43f45fc0a4ae3853a2e223f2b4d2d6831755634e1610f04f9164e076fba0d40659575d365a105e28c279e7f23df108ea06f4d61ff6cc4c134df",
          "sha256": "c2d1e3cc1ce14b142e513100db51ac6fc02efe4aacfffff5cca86ee077438433",
          "sha1": "31b7dcb0701068b2885c76504363e4fc8cae08fd",
          "md5": "c67803219090f81b48f7fa9797b0f6df"
        }
      ]
    }
  ]
}
