{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "9.2.3-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.2.3-b0.jar",
          "url": "core-ng-search-test-9.2.3-b0.jar",
          "size": 9215,
          "sha512": "72298dd2bdaaad3eff4628b3d4b739b2a5c4c0cf16944a60d2815397f9df9abe7ecd57b604b239748db1a43a27531611e39be74e530212aab7a467ae96737fbc",
          "sha256": "874d77db80c3ef3d62a5753193e990df3a0e570980712b2d0b4074218195eb89",
          "sha1": "302e1d48ec26331da4979b738a9c5199318f3b4a",
          "md5": "a896e166fcbd1a1fff737ac587eb7b45"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.2.3-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "9.2.3-b0"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "8.18.1"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "reindex",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-9.2.3-b0.jar",
          "url": "core-ng-search-test-9.2.3-b0.jar",
          "size": 9215,
          "sha512": "72298dd2bdaaad3eff4628b3d4b739b2a5c4c0cf16944a60d2815397f9df9abe7ecd57b604b239748db1a43a27531611e39be74e530212aab7a467ae96737fbc",
          "sha256": "874d77db80c3ef3d62a5753193e990df3a0e570980712b2d0b4074218195eb89",
          "sha1": "302e1d48ec26331da4979b738a9c5199318f3b4a",
          "md5": "a896e166fcbd1a1fff737ac587eb7b45"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.2.3-b0-sources.jar",
          "url": "core-ng-search-test-9.2.3-b0-sources.jar",
          "size": 5712,
          "sha512": "80b1b42958d68df895fdc3e1c092fc0d4dedcc83d781d1bdf3dfd5cb6d61e53a115edaf7fcd9a17e805b510df022d19d9df92f51da5932a05fa03aa1709cbda6",
          "sha256": "7c0c1c96cdfee439f2b71f67d83b003fce3ce6d942c8685982afe3f28098b555",
          "sha1": "1160f2348acbb59304223c305ab373f4ac053f03",
          "md5": "6f57f75860682e5634b1112f576eb1ea"
        }
      ]
    }
  ]
}
