{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "7.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "tiw26whr7vh43djrdosu3oi4rq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.4.6"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.4.6.jar",
          "url": "core-ng-7.4.6.jar",
          "size": 619227,
          "sha512": "b7ee46f022318d3dfc1779241da482ab0322588005e7e0db325ef3ea264f66ffd07e2fbac047a4edf10c44d693b106d24b0787f362c0985fb5096fbc7cda9e2f",
          "sha256": "2979102978f5f61271c57a506824afff4855d82cbfa7dbc8ebcc2021329e5775",
          "sha1": "352afdc03df486c8a937138ecd8a0dba9cbc67ab",
          "md5": "3b1bb6060d923d06e59ed929087c51ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.27.0-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.10.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.10.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.1.1.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.4.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.7.3"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.4.6"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.4.6.jar",
          "url": "core-ng-7.4.6.jar",
          "size": 619227,
          "sha512": "b7ee46f022318d3dfc1779241da482ab0322588005e7e0db325ef3ea264f66ffd07e2fbac047a4edf10c44d693b106d24b0787f362c0985fb5096fbc7cda9e2f",
          "sha256": "2979102978f5f61271c57a506824afff4855d82cbfa7dbc8ebcc2021329e5775",
          "sha1": "352afdc03df486c8a937138ecd8a0dba9cbc67ab",
          "md5": "3b1bb6060d923d06e59ed929087c51ba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-7.4.6-sources.jar",
          "url": "core-ng-7.4.6-sources.jar",
          "size": 317312,
          "sha512": "21b051f89f582840606b7a90b3d2a49b0c3f02da63914f7364493eab02c1959dc60982163ed99549a23119352d5d5aad64b72db962f1ef9f81641d48b8c86490",
          "sha256": "a9fab47216076f87e56c9e99b948bd77d12695745c95081a0d731b1850c0e07f",
          "sha1": "c1d3dc131db5a837a8d5b7a3d823b8990c5b4a4e",
          "md5": "93d5ea7f4b79cb8381b1b11a7d05110e"
        }
      ]
    }
  ]
}
