{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.5.0-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.5.0-b0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.5.0-b0.jar",
          "url": "core-ng-9.5.0-b0.jar",
          "size": 789227,
          "sha512": "2c00d0cdd9ee95bbc5ea656579ca9f6cdbd1c50f7d1948cc7a18a508c7ede88d75ce13f9248d43ae6a4c688f280562a4d2bc3cf0a3ad624f035dfde333139189",
          "sha256": "96ba4f5ede783ac08306a2289c149b0e6ea2967f89701a25898d3e86ec1c333a",
          "sha1": "adcb463dc92231c90dc3e902f0b8efcc1ef1972d",
          "md5": "b5a01d2c03bed3aba359b819ba4f835a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "tools.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "tools.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.23.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "4.2.0"
          },
          "excludes": [
            {
              "group": "org.xerial.snappy",
              "module": "*"
            },
            {
              "group": "at.yawk.lz4",
              "module": "*"
            }
          ]
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.5.0-b0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.5.0-b0.jar",
          "url": "core-ng-9.5.0-b0.jar",
          "size": 789227,
          "sha512": "2c00d0cdd9ee95bbc5ea656579ca9f6cdbd1c50f7d1948cc7a18a508c7ede88d75ce13f9248d43ae6a4c688f280562a4d2bc3cf0a3ad624f035dfde333139189",
          "sha256": "96ba4f5ede783ac08306a2289c149b0e6ea2967f89701a25898d3e86ec1c333a",
          "sha1": "adcb463dc92231c90dc3e902f0b8efcc1ef1972d",
          "md5": "b5a01d2c03bed3aba359b819ba4f835a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.5.0-b0-sources.jar",
          "url": "core-ng-9.5.0-b0-sources.jar",
          "size": 405476,
          "sha512": "39b6d8482a4e2aaf4b08c5e1aaff34ae49cc68fe808eb20134324ec3c42353504edb94fff2429b1335479ac607700eba672c8bca4fd982eff88eadce2e9d717d",
          "sha256": "1cfdd3de45b264123e85db853d0cf164c9febd7b581d1787b003204cf74def66",
          "sha1": "d77da4ffb6c03dadd419cd50beea67ac2df4f34c",
          "md5": "dd2b32f281709cb43094b3b088ebd417"
        }
      ]
    }
  ]
}
