{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "9.1.2-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.11.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.12.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.26.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.1.2-b0.jar",
          "url": "core-ng-test-9.1.2-b0.jar",
          "size": 45686,
          "sha512": "8efccd24b881d9a447d3d5256bf454de83018ec296d93925eb058b1b3f3ec1fd11a89ec7aa02af156fb4183527412555b6603149c5342f6798478ccf1f5a43dd",
          "sha256": "6e204ff00d94315841a27e041c85f2e5044e63985e0d0f5087d9aa83bacadfe9",
          "sha1": "fb66d7ef0c5e33ebf6df8303ecb8b3f109e211d9",
          "md5": "20ffacd748d9dd3d32b41b309d86b1dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.2-b0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.11.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.11.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.12.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.26.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.1.2-b0.jar",
          "url": "core-ng-test-9.1.2-b0.jar",
          "size": 45686,
          "sha512": "8efccd24b881d9a447d3d5256bf454de83018ec296d93925eb058b1b3f3ec1fd11a89ec7aa02af156fb4183527412555b6603149c5342f6798478ccf1f5a43dd",
          "sha256": "6e204ff00d94315841a27e041c85f2e5044e63985e0d0f5087d9aa83bacadfe9",
          "sha1": "fb66d7ef0c5e33ebf6df8303ecb8b3f109e211d9",
          "md5": "20ffacd748d9dd3d32b41b309d86b1dd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-9.1.2-b0-sources.jar",
          "url": "core-ng-test-9.1.2-b0-sources.jar",
          "size": 22204,
          "sha512": "7787a2e2f633a783991b58e0aaa6bcceb55541d865f4cbf3de00de3dfa9531532d2f53004ced489aa9be05da383a103beb6b81fa275bcadfdbc4f9cabf59ead1",
          "sha256": "21f6d89f17b3bcc7ff9f5d71666b29ddf1045e0c712d3e07e7545b6a3aef64f2",
          "sha1": "0a05cad930c0f30cd1163a15aed43727c0428fbb",
          "md5": "f09b8edf5e0347ea03601a1c24a9e621"
        }
      ]
    }
  ]
}
