{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "9.5.1-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.5.1-b0.jar",
          "url": "core-ng-search-test-9.5.1-b0.jar",
          "size": 11067,
          "sha512": "a60fd519a9e767883e4b109177defee94e8d22e01663b5696e81964779089855e38ac8bd2e491bd4d0eab7ba366a4970caa37aa5b80eab72b1f2ba4bbe8ce477",
          "sha256": "2afb96b8ca4aefb89d6f11a6c0d7c9cae3eae9385ed60500a513597b6197dddf",
          "sha1": "107e4d886f7eaada351d942720d18919ad92853c",
          "md5": "32a55fd8f9a1980799f492733037ead0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.5.1-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "9.5.1-b0"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "9.3.2"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "reindex",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-9.5.1-b0.jar",
          "url": "core-ng-search-test-9.5.1-b0.jar",
          "size": 11067,
          "sha512": "a60fd519a9e767883e4b109177defee94e8d22e01663b5696e81964779089855e38ac8bd2e491bd4d0eab7ba366a4970caa37aa5b80eab72b1f2ba4bbe8ce477",
          "sha256": "2afb96b8ca4aefb89d6f11a6c0d7c9cae3eae9385ed60500a513597b6197dddf",
          "sha1": "107e4d886f7eaada351d942720d18919ad92853c",
          "md5": "32a55fd8f9a1980799f492733037ead0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.5.1-b0-sources.jar",
          "url": "core-ng-search-test-9.5.1-b0-sources.jar",
          "size": 7107,
          "sha512": "45c42d431eb778c8f008d8f0ef1649452f324d4175be8556cdd1b8d03b1fbf8a41866f48bbd885998e84865cd79f8c68d8b84560f08bc1fc88351f8af9176369",
          "sha256": "d18f6d6733b968c1d510ea2029eaed32ee390e21467cecaa07c8f725fe9e87ae",
          "sha1": "5dcf9c5948f9ef4195b03aa264e11dc36dee8362",
          "md5": "382e2bbd09644e19ab8255ae665d4e00"
        }
      ]
    }
  ]
}
