{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "9.4.0-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.20.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.4.0-b0.jar",
          "url": "core-ng-test-9.4.0-b0.jar",
          "size": 50955,
          "sha512": "a639cc7580bd9d201d0241dc06006681f557f1ecdbdfdaa593758dbf38045c8ba998da0226b09126faaab0a21b565d497cc91bce503ccd6f16da71479fcde7be",
          "sha256": "735a0d27110592c1febb4d44000e097585a5dd5d526d1f7db095ba25bff8024f",
          "sha1": "7a4649e99f97a9187c876170278723007410ccbb",
          "md5": "e8fd004a97b76d5ffee9486c6ad85fff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.4.0-b0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.20.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.4.0-b0.jar",
          "url": "core-ng-test-9.4.0-b0.jar",
          "size": 50955,
          "sha512": "a639cc7580bd9d201d0241dc06006681f557f1ecdbdfdaa593758dbf38045c8ba998da0226b09126faaab0a21b565d497cc91bce503ccd6f16da71479fcde7be",
          "sha256": "735a0d27110592c1febb4d44000e097585a5dd5d526d1f7db095ba25bff8024f",
          "sha1": "7a4649e99f97a9187c876170278723007410ccbb",
          "md5": "e8fd004a97b76d5ffee9486c6ad85fff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-9.4.0-b0-sources.jar",
          "url": "core-ng-test-9.4.0-b0-sources.jar",
          "size": 25058,
          "sha512": "7e70029a68a6adcb4cfe043fb65fde67f68b56f514a92e1a24ef01c59f97fe108ba3231640ab2a345ba804f18135ab2e21bfd81330f02ffdc594bdfe69ae5c78",
          "sha256": "41ab94e0fb928cdfc485ad71a8b8808a39052e3ed507292b8ca8592fe3687a21",
          "sha1": "9f8bec0f5a0e0d3b90d183d767b805cdb33b4904",
          "md5": "ee4ebfcb01296002e6b1e4bb296498ca"
        }
      ]
    }
  ]
}
