{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "7.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "rulgpyki7zfhhnfoob5n3kcsmu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-7.3.0.jar",
          "url": "core-ng-mongo-test-7.3.0.jar",
          "size": 2339,
          "sha512": "1d0c980952ad438f80676b6ef272c94f472cd8123c5f065e28c9c61e8cbb6a2d687ce957f4d8e144b443359b484557008cfd23b7a39a9439ed18af538e8979c9",
          "sha256": "623725d672e329a125bd4f44d485992c8ba926c60b0169930f4fa24cade39320",
          "sha1": "b62925fd51c34c2746a454cb25772ada41e04c8",
          "md5": "f77c77dd11d0361c88746b2c819dd2e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.23.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-7.3.0.jar",
          "url": "core-ng-mongo-test-7.3.0.jar",
          "size": 2339,
          "sha512": "1d0c980952ad438f80676b6ef272c94f472cd8123c5f065e28c9c61e8cbb6a2d687ce957f4d8e144b443359b484557008cfd23b7a39a9439ed18af538e8979c9",
          "sha256": "623725d672e329a125bd4f44d485992c8ba926c60b0169930f4fa24cade39320",
          "sha1": "b62925fd51c34c2746a454cb25772ada41e04c8",
          "md5": "f77c77dd11d0361c88746b2c819dd2e0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-7.3.0-sources.jar",
          "url": "core-ng-mongo-test-7.3.0-sources.jar",
          "size": 1576,
          "sha512": "4dba64c614558c332ccd1539dcd7ea5915c6ada13214522e7bb6be02b98024c706cae70655ed00b769507bf2f8cab6e04dd2a3f6deb2ba4eba3a667160566b89",
          "sha256": "a1eae2012df6f54ec34e61b01569a2c288a8bb8ca8e17a56f5af97ce150570c4",
          "sha1": "949d0fdc73a0f83bdb164769f7df594af0d78dab",
          "md5": "1293e684dbddb5ca8d37e66f7280570f"
        }
      ]
    }
  ]
}
