{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "7.3.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "ptxujkuuoja2fk5lukuqxvnmqq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.3.12.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.3.12.1.jar",
          "url": "core-ng-7.3.12.1.jar",
          "size": 615219,
          "sha512": "8e07285d8999f96c6b13d236a5ad2c6f5f4ceb7456a666864b9e56d1ad79d9f518435f705bb300130ec49d40820c7003580f99448edfc61a1ef61918404154ad",
          "sha256": "04b32b27c963fbbcfcdcd128451098efa259238f3bb7c242bcdfad336e7e52f4",
          "sha1": "46a5116f7c14f2c2c8dfcdbd7fe977dc21119c26",
          "md5": "3271542d182d5ad4fe0fa2ca910bb6a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.27.0-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.10.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.10.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.4.1"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.0.30.Final"
          }
        },
        {
          "group": "org.jboss.xnio",
          "module": "xnio-nio",
          "version": {
            "requires": "3.7.7.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.4.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.7.3"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.3.12.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.3.12.1.jar",
          "url": "core-ng-7.3.12.1.jar",
          "size": 615219,
          "sha512": "8e07285d8999f96c6b13d236a5ad2c6f5f4ceb7456a666864b9e56d1ad79d9f518435f705bb300130ec49d40820c7003580f99448edfc61a1ef61918404154ad",
          "sha256": "04b32b27c963fbbcfcdcd128451098efa259238f3bb7c242bcdfad336e7e52f4",
          "sha1": "46a5116f7c14f2c2c8dfcdbd7fe977dc21119c26",
          "md5": "3271542d182d5ad4fe0fa2ca910bb6a5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-7.3.12.1-sources.jar",
          "url": "core-ng-7.3.12.1-sources.jar",
          "size": 313419,
          "sha512": "e40122449767a6484b435c25142570fef3ec1ea7935b5ec10c5d7171e1d61e386aba47e60f77f993013b10caa8196364ca35253507da910cd42acbccfdfd69a6",
          "sha256": "b7ebcfc3cdaa4beea2e09dd19ffaf1e4f96e168aac1221e46844393588738359",
          "sha1": "2d59a4dd2bdb98c503af097e2dda4cdc4fcf07de",
          "md5": "3cb64c7b560d15acb0931b98b86ddb02"
        }
      ]
    }
  ]
}
