{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "9.0.8-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.8-b0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.0.8-b0.jar",
          "url": "core-ng-mongo-9.0.8-b0.jar",
          "size": 57156,
          "sha512": "d96733ca0a36dc8a507f0458b473d452dfb7c1a7d4af0949f05489bf84e7c9dd054baf18f4507801ff8cfe7724cd23dca245d0176ec36b974e2310f4222eac05",
          "sha256": "745e764e12d2154c3462bb2a21150ff95fc14b3047f64fe1060d1aa7036bb0ba",
          "sha1": "4d67a595b0a83cc9cfa9060665901eb5e435d908",
          "md5": "f7b771373e0c300f0e0c37452b274a7e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.8-b0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.0.8-b0.jar",
          "url": "core-ng-mongo-9.0.8-b0.jar",
          "size": 57156,
          "sha512": "d96733ca0a36dc8a507f0458b473d452dfb7c1a7d4af0949f05489bf84e7c9dd054baf18f4507801ff8cfe7724cd23dca245d0176ec36b974e2310f4222eac05",
          "sha256": "745e764e12d2154c3462bb2a21150ff95fc14b3047f64fe1060d1aa7036bb0ba",
          "sha1": "4d67a595b0a83cc9cfa9060665901eb5e435d908",
          "md5": "f7b771373e0c300f0e0c37452b274a7e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-9.0.8-b0-sources.jar",
          "url": "core-ng-mongo-9.0.8-b0-sources.jar",
          "size": 27012,
          "sha512": "b83aad2fc965c4e67323f978105b886b231cd188529865c7adc7c712bc0fa047d3f085a590a39be54bbf404b3d5094f41da14f84215af98daa19f48e79288e11",
          "sha256": "a8176aa94abf749ca9db473ee9a7bf696c5c57809bf1cf58027678f0d7b0c0b4",
          "sha1": "ebba9907c753e5492a9f43c3db5f2295c70c87d4",
          "md5": "16a5173202d120b247106ce71245badb"
        }
      ]
    }
  ]
}
