{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "7.6.8-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "fbkkyz4bmredpnyliz2efiny7u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.6.28"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.6.8-b0.jar",
          "url": "core-ng-test-7.6.8-b0.jar",
          "size": 39070,
          "sha512": "24422ed0cd684c547fa96c82c5e792ff147f719cc1ef4b74f1f08acdc2d0ff409cdd828720fb4f4f11b5ac7ee865e3cf10e7098f565d8e53c24a41e77fd5c81d",
          "sha256": "d0837f77b635eaec2715b2d87e17b44148b6374cf8473ab5b03cde499c26653d",
          "sha1": "d2c51a47fed5c7a01f56fd83ce6c6117a6955329",
          "md5": "569929119d9ff6aff6b3497fd523030b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.8-b0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.7.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.6.28"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.6.8-b0.jar",
          "url": "core-ng-test-7.6.8-b0.jar",
          "size": 39070,
          "sha512": "24422ed0cd684c547fa96c82c5e792ff147f719cc1ef4b74f1f08acdc2d0ff409cdd828720fb4f4f11b5ac7ee865e3cf10e7098f565d8e53c24a41e77fd5c81d",
          "sha256": "d0837f77b635eaec2715b2d87e17b44148b6374cf8473ab5b03cde499c26653d",
          "sha1": "d2c51a47fed5c7a01f56fd83ce6c6117a6955329",
          "md5": "569929119d9ff6aff6b3497fd523030b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-7.6.8-b0-sources.jar",
          "url": "core-ng-test-7.6.8-b0-sources.jar",
          "size": 19186,
          "sha512": "b67499c6a06cb8cf48645f062db2eae5d80bf4648252494cb74dd39c3e9574a28b869d63e3eee3e0fac8faffbb16fa25c23f1e98eba494248c61279d443eb5ae",
          "sha256": "dd44c3a944d6cb089e3e4acc9982f9bbc9f18dd474cf59be48c217007c76293b",
          "sha1": "28cad6e06cd66256714aa80b553d4eb5bd995f91",
          "md5": "328893f872d0986fe228bfc48d0d3975"
        }
      ]
    }
  ]
}
