{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "7.6.2-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "5jfivrnadrg73pcyjgmirgtp24"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.2-b0"
          }
        },
        {
          "group": "org.elasticsearch.client",
          "module": "elasticsearch-rest-high-level-client",
          "version": {
            "requires": "7.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.6.2-b0.jar",
          "url": "core-ng-search-7.6.2-b0.jar",
          "size": 38501,
          "sha512": "30d6f995a00ffde4b717179e730358aff0252f4c435b4bedae7a72a213d674e7ca47cc3dc218c64391c7b56f57ddfbb13c198fc8f9c56b14c56aba6fbd029440",
          "sha256": "ec929a5cdb5f01ffc40489515b53fde30274228fb67d5aeec0c5585a68434266",
          "sha1": "a40c858fcd424c15a2e1cb64135130d4a7a56dc4",
          "md5": "6ae4e42b0c8dbc493fae9f4229504a92"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.2-b0"
          }
        },
        {
          "group": "org.elasticsearch.client",
          "module": "elasticsearch-rest-high-level-client",
          "version": {
            "requires": "7.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.6.2-b0.jar",
          "url": "core-ng-search-7.6.2-b0.jar",
          "size": 38501,
          "sha512": "30d6f995a00ffde4b717179e730358aff0252f4c435b4bedae7a72a213d674e7ca47cc3dc218c64391c7b56f57ddfbb13c198fc8f9c56b14c56aba6fbd029440",
          "sha256": "ec929a5cdb5f01ffc40489515b53fde30274228fb67d5aeec0c5585a68434266",
          "sha1": "a40c858fcd424c15a2e1cb64135130d4a7a56dc4",
          "md5": "6ae4e42b0c8dbc493fae9f4229504a92"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-7.6.2-b0-sources.jar",
          "url": "core-ng-search-7.6.2-b0-sources.jar",
          "size": 17320,
          "sha512": "5b5e19c8c417d7ae47116895d6ee11d3a694d7892b6393c8ca92ea8dd3584447cf3f9a322ebc9ec17c5dd57e9d297f35186ef99d61f92d7ff385dacba1f457c4",
          "sha256": "daa2d5f6b2eaefbd8d0a278c6be00ec83bde0e00660f8f746651d50722685141",
          "sha1": "e15322e50fe08ff54794307d930467eacd44ff69",
          "md5": "16044e7cacc4fbd032766be185fb7a17"
        }
      ]
    }
  ]
}
