{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "9.1.1-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.1-b1"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.1.1-b1.jar",
          "url": "core-ng-mongo-9.1.1-b1.jar",
          "size": 57161,
          "sha512": "abf262dbf739507028cf97cb636408b1816f81c8fc5f0012e6569db01e0327a12bff535c6e6b64771cccf514db4680c9df8c0dea3b6a90452bb83ae3bd4d0736",
          "sha256": "8f85bc727cacc20ca40e7dfd9ab834fb178f4014b9e9d6889dc086428f389f94",
          "sha1": "bf5113ffc09e5cee20788996ffe6c258c1868741",
          "md5": "59ee20af7cb23b035bbe58e05cffb70e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.1-b1"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.1.1-b1.jar",
          "url": "core-ng-mongo-9.1.1-b1.jar",
          "size": 57161,
          "sha512": "abf262dbf739507028cf97cb636408b1816f81c8fc5f0012e6569db01e0327a12bff535c6e6b64771cccf514db4680c9df8c0dea3b6a90452bb83ae3bd4d0736",
          "sha256": "8f85bc727cacc20ca40e7dfd9ab834fb178f4014b9e9d6889dc086428f389f94",
          "sha1": "bf5113ffc09e5cee20788996ffe6c258c1868741",
          "md5": "59ee20af7cb23b035bbe58e05cffb70e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-9.1.1-b1-sources.jar",
          "url": "core-ng-mongo-9.1.1-b1-sources.jar",
          "size": 27013,
          "sha512": "1ab19f9b9d98c10489acd645d03c1d364901d37071aac08b168ae5a180cc2f290b02f92a150d1d25e68e877d2558617f121bed62a3222f242a36567ef4ee4f3c",
          "sha256": "e1a6bc914a8b7489e3a9de7e7aa63dceca852c94c8a231cb5926150ab5ddcf13",
          "sha1": "eba0c820c81356eb5cfd1f2eb4b8c786916f7116",
          "md5": "a8ecca4fd7e8306d6953582a9303978b"
        }
      ]
    }
  ]
}
