{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "9.1.1-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.1-b1"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.1.1-b1.jar",
          "url": "core-ng-mongo-9.1.1-b1.jar",
          "size": 57161,
          "sha512": "c78669758a8f6ab86baae8dd6f02931434bd88c36c0580f339546974949d5fb05ce2c7c5e5a6255da83a8ae33270c736284c5e6c62670777b8d3566e58c2b255",
          "sha256": "800ae9d892524f055932ee7707b7042080d1dde9fe0576388c10e64163c72bbe",
          "sha1": "32c9af9e997f4df968b3def418a59bc2213f1138",
          "md5": "c977966c8e0361725935de87dd8de61b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.1-b1"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.1.1-b1.jar",
          "url": "core-ng-mongo-9.1.1-b1.jar",
          "size": 57161,
          "sha512": "c78669758a8f6ab86baae8dd6f02931434bd88c36c0580f339546974949d5fb05ce2c7c5e5a6255da83a8ae33270c736284c5e6c62670777b8d3566e58c2b255",
          "sha256": "800ae9d892524f055932ee7707b7042080d1dde9fe0576388c10e64163c72bbe",
          "sha1": "32c9af9e997f4df968b3def418a59bc2213f1138",
          "md5": "c977966c8e0361725935de87dd8de61b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-9.1.1-b1-sources.jar",
          "url": "core-ng-mongo-9.1.1-b1-sources.jar",
          "size": 27013,
          "sha512": "620dde5f95267d6388608d381f6a83a080f8222ee95a6cac75cd1926ec6d46e73dbdb8c172f68eae4a27abb26c7c75978453c638b12d9b34fff8d73ae3ce11a7",
          "sha256": "1913a7d3e824555bb0895dc9810cb60dabc43fc2a1a330944460298192d6f903",
          "sha1": "991ced4bb2bc18981f02fd9b5e86539c9ca4b0b7",
          "md5": "6fcbacf332aba21e2ebdb37348454d04"
        }
      ]
    }
  ]
}
