{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "9.4.0-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.4.0-b0.jar",
          "url": "core-ng-mongo-test-9.4.0-b0.jar",
          "size": 2944,
          "sha512": "60a06452885c33cc45440d34c8eb811c813204d94f3eb359b35c984d20e68633375d2aa2fbdf233a24e729cee7d4a46fa71aea221ea63fb0c42b324e45c95bbb",
          "sha256": "65b5d7eca4e211f6cd30fb016287c1016e8693f146625118d56fbba9c92d83df",
          "sha1": "5ab927039a85d83957311fb23dbab8d6a1f5874c",
          "md5": "9c410dff0319eb6e8edbd3cbe6b4d95c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.4.0-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "9.4.0-b0"
          }
        },
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.47.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-9.4.0-b0.jar",
          "url": "core-ng-mongo-test-9.4.0-b0.jar",
          "size": 2944,
          "sha512": "60a06452885c33cc45440d34c8eb811c813204d94f3eb359b35c984d20e68633375d2aa2fbdf233a24e729cee7d4a46fa71aea221ea63fb0c42b324e45c95bbb",
          "sha256": "65b5d7eca4e211f6cd30fb016287c1016e8693f146625118d56fbba9c92d83df",
          "sha1": "5ab927039a85d83957311fb23dbab8d6a1f5874c",
          "md5": "9c410dff0319eb6e8edbd3cbe6b4d95c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.4.0-b0-sources.jar",
          "url": "core-ng-mongo-test-9.4.0-b0-sources.jar",
          "size": 2083,
          "sha512": "4f1db9f8f9241fd57843be62136828cfe582a8defacccd684175e5377b7d99b735eda4fad83f60164f36d933e89ff8787f58cfc92b3808016a3ceed58bf47e53",
          "sha256": "dd3272697eaff73ec29d8c4f55d7b018120255149fe8f83d18ff8bed7e78015a",
          "sha1": "0e08369d1fe96f7b9f91b55bde54ffdd85019e89",
          "md5": "d75ec9777b06b0af281157e439c64241"
        }
      ]
    }
  ]
}
