{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "7.6.16-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.16-b0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.6.16-b0.jar",
          "url": "core-ng-mongo-7.6.16-b0.jar",
          "size": 53971,
          "sha512": "a2291827151615e1bea4e489308ce355281bd043aea67cd38abe6155bdedf54cde158643fc5846f9118f6b4ef81a4035e8adc188fe14cf578ef5fc85298fca7b",
          "sha256": "7808fb21dfe859e69b63dde1c3d75d2a10d111b8c1cc3a7c407beb741db5cd3d",
          "sha1": "5ee54dea50704969bfe0bc55d0b2c96f177c0df6",
          "md5": "a97ad4bb4be3c172560be25d98351eb8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.16-b0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.6.16-b0.jar",
          "url": "core-ng-mongo-7.6.16-b0.jar",
          "size": 53971,
          "sha512": "a2291827151615e1bea4e489308ce355281bd043aea67cd38abe6155bdedf54cde158643fc5846f9118f6b4ef81a4035e8adc188fe14cf578ef5fc85298fca7b",
          "sha256": "7808fb21dfe859e69b63dde1c3d75d2a10d111b8c1cc3a7c407beb741db5cd3d",
          "sha1": "5ee54dea50704969bfe0bc55d0b2c96f177c0df6",
          "md5": "a97ad4bb4be3c172560be25d98351eb8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-7.6.16-b0-sources.jar",
          "url": "core-ng-mongo-7.6.16-b0-sources.jar",
          "size": 25324,
          "sha512": "2fab0cda84d9bb0c0ef81d5a3c95518d0d6a3a4c87a0d7b9768db4ae4ce94f59526d88523c273cef5a857629ff873b59f2c2c3bb8d9ccd7fe18c903cb29762fc",
          "sha256": "5f35fdc179d7fd1237de72ad48d9b0b9d1ada1f25491615abc74425c36e85abd",
          "sha1": "6fe103b491c719cf9c22cab59ed0a7293691166a",
          "md5": "e3a7378c12e1b8171d86baec3287e45e"
        }
      ]
    }
  ]
}
