{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "7.7.4-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.11.1"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.7.4-b0.jar",
          "url": "core-ng-test-7.7.4-b0.jar",
          "size": 41889,
          "sha512": "db93b89287d3bc4fe211d5dbe4ec3a4f06bb6d8f8fc5717900641012ef627b0c2786b8c9fca3a068edadbc247cf38823a8537517c7333328ddc5c3f3407afd5f",
          "sha256": "4f4328bad44d554832aef03246ff24d95ebcae2169c8cd66bc78338a126709d0",
          "sha1": "d807981ba6afabd557675f0ef5047def6cc98146",
          "md5": "c3bdb7205b0ff5dc14b101dc317d1c36"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.7.4-b0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.7.2"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.8.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.11.1"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.7.4-b0.jar",
          "url": "core-ng-test-7.7.4-b0.jar",
          "size": 41889,
          "sha512": "db93b89287d3bc4fe211d5dbe4ec3a4f06bb6d8f8fc5717900641012ef627b0c2786b8c9fca3a068edadbc247cf38823a8537517c7333328ddc5c3f3407afd5f",
          "sha256": "4f4328bad44d554832aef03246ff24d95ebcae2169c8cd66bc78338a126709d0",
          "sha1": "d807981ba6afabd557675f0ef5047def6cc98146",
          "md5": "c3bdb7205b0ff5dc14b101dc317d1c36"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-7.7.4-b0-sources.jar",
          "url": "core-ng-test-7.7.4-b0-sources.jar",
          "size": 20153,
          "sha512": "1c5ee1de653b904b200923e4650e697f432a17925746103abfa492d9b1319baf0b5d87ceffbd0918e0637c8901f00be4269cb7b95b8fe0b32e693a875a0bea84",
          "sha256": "c735c9e32f4cd3a2e9788cd180279f79e5a52907c50ed646fcb295a246e0e258",
          "sha1": "f81d3ec5f7c61e1304046495c87b3dbf6c852c71",
          "md5": "93e98c73d0466d0a22e9a69a82f6dae0"
        }
      ]
    }
  ]
}
