{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "9.3.1-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.3.1-b0"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.18.1"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.3.1-b0.jar",
          "url": "core-ng-search-9.3.1-b0.jar",
          "size": 56009,
          "sha512": "d7e759b680fb9a94969d0b476196c76e5b51ada7626ee52f95126ecbf1be7dd540bf60623d8c822154ece470a433259728c569084edb81543db3e926edc56010",
          "sha256": "22c362abf2fd7a2837356627fb76f347467044297a37b63a8da44ad97342093d",
          "sha1": "17bd6330dc455709284368baa2f84269bbbd1228",
          "md5": "5bacbcaa702d96d3122dda364fe92e94"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.3.1-b0"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.18.1"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.3.1-b0.jar",
          "url": "core-ng-search-9.3.1-b0.jar",
          "size": 56009,
          "sha512": "d7e759b680fb9a94969d0b476196c76e5b51ada7626ee52f95126ecbf1be7dd540bf60623d8c822154ece470a433259728c569084edb81543db3e926edc56010",
          "sha256": "22c362abf2fd7a2837356627fb76f347467044297a37b63a8da44ad97342093d",
          "sha1": "17bd6330dc455709284368baa2f84269bbbd1228",
          "md5": "5bacbcaa702d96d3122dda364fe92e94"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-9.3.1-b0-sources.jar",
          "url": "core-ng-search-9.3.1-b0-sources.jar",
          "size": 23526,
          "sha512": "f446da480ebca57793fadf056bcaa760875153a022159bff96422842bbb7f4d39225ab362b5ba7c36d51c6eb31507bd0d0d06bf86f5af4288abbb8fa3b1ebed0",
          "sha256": "0f8c969f5f2eacebc95eaf8ea12c670fb79701f276cb30e4211aa5651e448f90",
          "sha1": "9b5933486f53370b272c89a1facd813197dc2786",
          "md5": "187640bdf618e6d13ad4771c1c72c03a"
        }
      ]
    }
  ]
}
