{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "9.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-params",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.23.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.7"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.6.2.jar",
          "url": "core-ng-test-9.6.2.jar",
          "size": 51138,
          "sha512": "52345267f12b6494f5d73ea66c319b84fe2b780a454bdb2627fa9c1141a5a2138531a64a767cce646a866c44b07990c88e55c71c4cb2062f354e515bbc733cba",
          "sha256": "ffa3b6a39a938b27b60ca1c4331db88e2a694b5e95ba7adb047381bcf52b18d3",
          "sha1": "58015fb13a273172e3b91802daedec758b8dca44",
          "md5": "4a029db4ce27cde9c5b4c13cf5ec116c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.6.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-params",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.23.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.7"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.6.2.jar",
          "url": "core-ng-test-9.6.2.jar",
          "size": 51138,
          "sha512": "52345267f12b6494f5d73ea66c319b84fe2b780a454bdb2627fa9c1141a5a2138531a64a767cce646a866c44b07990c88e55c71c4cb2062f354e515bbc733cba",
          "sha256": "ffa3b6a39a938b27b60ca1c4331db88e2a694b5e95ba7adb047381bcf52b18d3",
          "sha1": "58015fb13a273172e3b91802daedec758b8dca44",
          "md5": "4a029db4ce27cde9c5b4c13cf5ec116c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-9.6.2-sources.jar",
          "url": "core-ng-test-9.6.2-sources.jar",
          "size": 25105,
          "sha512": "7062f84170da6c6b5f94c5b22eb404f66efc7121e2f120a2e73da11aed6feaf9ab2ae5548ca5a69db7de9cfa3fad8adbcfb3c6399f7f281a8fc07ca200547a81",
          "sha256": "101826c04015b45ab30167fe63438a583c9db0389257a5418d7c7a1e35ba1a74",
          "sha1": "85956d692f42ad7a89aed557fbd032b5bf5c7e86",
          "md5": "503c31bc8a093b987125cc3b19390f17"
        }
      ]
    }
  ]
}
