{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "9.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.0.8.jar",
          "url": "core-ng-search-test-9.0.8.jar",
          "size": 13098,
          "sha512": "2dba883ee27f8f16cc2039be00b5901efa7aa5c1616afc215de5aa32bfca47850bef515cc78cd88d943e4387da86ac1427005df35cd4ec061f1dc57fd31bec8f",
          "sha256": "c1665b1a9d1e61e5055b8017e2060e5151eeaddc377c02403247d7f33c41390c",
          "sha1": "1dc75279a06c881af1f16877b885949c37c0b869",
          "md5": "4c76b2d8740f1d927556d1296b9e86dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.0.8"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "9.0.8"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "8.12.2"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4",
          "version": {
            "requires": "8.12.2"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "8.12.2"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "8.12.2"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "8.12.2"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "reindex",
          "version": {
            "requires": "8.12.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "reindex",
              "type": "jar",
              "extension": "jar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-9.0.8.jar",
          "url": "core-ng-search-test-9.0.8.jar",
          "size": 13098,
          "sha512": "2dba883ee27f8f16cc2039be00b5901efa7aa5c1616afc215de5aa32bfca47850bef515cc78cd88d943e4387da86ac1427005df35cd4ec061f1dc57fd31bec8f",
          "sha256": "c1665b1a9d1e61e5055b8017e2060e5151eeaddc377c02403247d7f33c41390c",
          "sha1": "1dc75279a06c881af1f16877b885949c37c0b869",
          "md5": "4c76b2d8740f1d927556d1296b9e86dc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.0.8-sources.jar",
          "url": "core-ng-search-test-9.0.8-sources.jar",
          "size": 7161,
          "sha512": "617199d0353ac0e6d9480736e271a6d333ebaec30e642cf6323411cc35f1c5e698c2d36a01a4ded0473701f6fba7f08b84290ac7434376c5da93308192f66950",
          "sha256": "f7ddc7b48f77bc4cf00470a254386326c67e644c9b45d20bfd43f7c001161a8a",
          "sha1": "05939b16662de0ba7e95cb7ddf92b832761a48e7",
          "md5": "4ca7a8e91b69200e1a6474fca953fdcd"
        }
      ]
    }
  ]
}
