{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "9.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-9.0.8.jar",
          "url": "core-ng-api-9.0.8.jar",
          "size": 10989,
          "sha512": "531865b24ac598877d1bac34a70fffa56465b0ccbe96219617f14900230762fe5c9a0708f81cce706ecca7c657aa6af73ab36277d5950500ac9cbcb1da1aaacb",
          "sha256": "1f699e0255e84b0f1eb525529d16bdfa7b01910921b2928a4081ff155d05e990",
          "sha1": "7294980bb9496ec9c9ba531f4d4b8eb063af5a84",
          "md5": "92dab34cc1eb96951dd874b3855689ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.0.8.jar",
          "url": "core-ng-api-9.0.8.jar",
          "size": 10989,
          "sha512": "531865b24ac598877d1bac34a70fffa56465b0ccbe96219617f14900230762fe5c9a0708f81cce706ecca7c657aa6af73ab36277d5950500ac9cbcb1da1aaacb",
          "sha256": "1f699e0255e84b0f1eb525529d16bdfa7b01910921b2928a4081ff155d05e990",
          "sha1": "7294980bb9496ec9c9ba531f4d4b8eb063af5a84",
          "md5": "92dab34cc1eb96951dd874b3855689ac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.0.8-sources.jar",
          "url": "core-ng-api-9.0.8-sources.jar",
          "size": 8643,
          "sha512": "89947bbfbeec6a9430ba73ffc7a531806f7ee30b0055416332dbe62b63a7937c191d209fafaf0dea626ca553b440db7126d4d72a42221ef7c6174bb883cdc794",
          "sha256": "a631641e0d9f5ad5a5c493978e75746710f40c14c035415dda52d1f96508f24d",
          "sha1": "85aa8f9df5c6f1598aa362653e01da7980576541",
          "md5": "23864fa53ab84b9f247adf30be02a1fa"
        }
      ]
    }
  ]
}
