{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "9.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.10"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.0.10.jar",
          "url": "core-ng-mongo-9.0.10.jar",
          "size": 57159,
          "sha512": "3640b91c370a4e24b246cd5dc74b91abc0da089b48df2f91d9f6598107308a3ad4eeb2a4eb7a2da3a3f523a5ae977c4e7f725fbb13a74072d120d6ece4c9ae69",
          "sha256": "71b0526be7a7dced3e202d50445e23cb923cd8bca6a7dd7f4c9f7fe4236a5367",
          "sha1": "3bc663f560ef408809427c51d0c3b5dccaa023ae",
          "md5": "2b29c21947f06d84ef2fdaf772c56bb4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.10"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.0.10.jar",
          "url": "core-ng-mongo-9.0.10.jar",
          "size": 57159,
          "sha512": "3640b91c370a4e24b246cd5dc74b91abc0da089b48df2f91d9f6598107308a3ad4eeb2a4eb7a2da3a3f523a5ae977c4e7f725fbb13a74072d120d6ece4c9ae69",
          "sha256": "71b0526be7a7dced3e202d50445e23cb923cd8bca6a7dd7f4c9f7fe4236a5367",
          "sha1": "3bc663f560ef408809427c51d0c3b5dccaa023ae",
          "md5": "2b29c21947f06d84ef2fdaf772c56bb4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-9.0.10-sources.jar",
          "url": "core-ng-mongo-9.0.10-sources.jar",
          "size": 27011,
          "sha512": "afa98b2376611cd76f9bd53fe834bf53c4c8bb789bb63c08b5fdbc842e858faee0663eb85920d18015770cafe40b16555b22108d43cc7f64d171ef6ccedba7cc",
          "sha256": "2cfecd8da81b2b966ec662f8993945b69f0b12f8c6b06ef20e8113558f6b02c2",
          "sha1": "5c9eb3bfbad32336351bcf70b18aff2f012a4798",
          "md5": "93e5648ec00808a3c4d8b9b9e111d638"
        }
      ]
    }
  ]
}
