{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "9.1.0-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.0-b0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.1.0-b0.jar",
          "url": "core-ng-mongo-9.1.0-b0.jar",
          "size": 57159,
          "sha512": "25ec4b721cd9dba3eb03a5237f7c5ccb62d14c9bff3f630437c911c6262b9f6ae8dbcbc2cba52d6bab08723fc6a4088d3ae9c6111f3dac579adcec57e214d8b5",
          "sha256": "60007dd1461b0900547f9a196d2de16178b59fb3cd8af84f2d594b620508b581",
          "sha1": "389b0348947a100ea712bc058d91827bf05050eb",
          "md5": "c668d9463c85288277c99e517f482b0e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.0-b0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.1.0-b0.jar",
          "url": "core-ng-mongo-9.1.0-b0.jar",
          "size": 57159,
          "sha512": "25ec4b721cd9dba3eb03a5237f7c5ccb62d14c9bff3f630437c911c6262b9f6ae8dbcbc2cba52d6bab08723fc6a4088d3ae9c6111f3dac579adcec57e214d8b5",
          "sha256": "60007dd1461b0900547f9a196d2de16178b59fb3cd8af84f2d594b620508b581",
          "sha1": "389b0348947a100ea712bc058d91827bf05050eb",
          "md5": "c668d9463c85288277c99e517f482b0e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-9.1.0-b0-sources.jar",
          "url": "core-ng-mongo-9.1.0-b0-sources.jar",
          "size": 27011,
          "sha512": "6f6f18b9315a14642ff2328640c062f881c1f1acb95535339720f7bba395a5c6fd72e43b4d6976f63d9b0e3c49950b657c48875c40f4d903a46022cc6e87c0a7",
          "sha256": "81a72ac759c34284e2bd23ea5c3a2c54cee656d597e4a20cdf61c2956fda008d",
          "sha1": "0fe3cc6d68e157bd06580be10a428580f2fbdce0",
          "md5": "3b4cabbc93f54f529f89be384dc53c7c"
        }
      ]
    }
  ]
}
