{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "7.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "tiw26whr7vh43djrdosu3oi4rq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.4.6"
          }
        },
        {
          "group": "org.elasticsearch.client",
          "module": "elasticsearch-rest-high-level-client",
          "version": {
            "requires": "7.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.4.6.jar",
          "url": "core-ng-search-7.4.6.jar",
          "size": 37720,
          "sha512": "b39f56757688f6091936dcf4f02444a036db97fa140ad4015ba76910202e0383d95465d66b56444639a222f9d45cb437e20a1ff3665c74329013f3c8dea00c31",
          "sha256": "c8db3a575d65976112ef1d7731c80a3813a667de4688ded25a584cf03334859d",
          "sha1": "43cda30298d95da23f489c99a548840657f75722",
          "md5": "f09565c794e7bc8ba124a3e9b9ba82b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.4.6"
          }
        },
        {
          "group": "org.elasticsearch.client",
          "module": "elasticsearch-rest-high-level-client",
          "version": {
            "requires": "7.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.4.6.jar",
          "url": "core-ng-search-7.4.6.jar",
          "size": 37720,
          "sha512": "b39f56757688f6091936dcf4f02444a036db97fa140ad4015ba76910202e0383d95465d66b56444639a222f9d45cb437e20a1ff3665c74329013f3c8dea00c31",
          "sha256": "c8db3a575d65976112ef1d7731c80a3813a667de4688ded25a584cf03334859d",
          "sha1": "43cda30298d95da23f489c99a548840657f75722",
          "md5": "f09565c794e7bc8ba124a3e9b9ba82b6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-7.4.6-sources.jar",
          "url": "core-ng-search-7.4.6-sources.jar",
          "size": 16833,
          "sha512": "c3f145fd516361e6e02b957e798b58163683443e03866b07f09c224b9674bb6ba069f338bcd3529f338ed03868ab06ae6ee734a7065e3dfacefc6fd72b77e314",
          "sha256": "dcc6a48b5ccd67dfcaea7cc58b9b1aff2df7cfd58db5e978251ac7420b52e2ca",
          "sha1": "46143775bfa456866752c9728b567228cb8193f1",
          "md5": "6acf888d58a1dd1295caba7b7506f526"
        }
      ]
    }
  ]
}
