{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "9.5.0-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.5.0-b0"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "9.3.2"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            },
            {
              "group": "io.opentelemetry.semconv",
              "module": "*"
            },
            {
              "group": "com.fasterxml.jackson.core",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.5.0-b0.jar",
          "url": "core-ng-search-9.5.0-b0.jar",
          "size": 57972,
          "sha512": "9652b2a6d593bc70c3e1fe379d18f759958f89827ded02e92c9570320f810426de384f0c37930d58ab63fd80565e02e7a3048e436bc01b26a4e0b9f2c57b782d",
          "sha256": "4de89c059925e4744102b503574a64bb2d10f4ab3b702724e699db5f81930227",
          "sha1": "d371a4a37abf3cf36fc04e94e57402596a28bfa3",
          "md5": "b5acdc966ad5c25f3e0c4a4b385b4c2d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-rest5-client",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "tools.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.5.0-b0"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "9.3.2"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            },
            {
              "group": "io.opentelemetry.semconv",
              "module": "*"
            },
            {
              "group": "com.fasterxml.jackson.core",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.5.0-b0.jar",
          "url": "core-ng-search-9.5.0-b0.jar",
          "size": 57972,
          "sha512": "9652b2a6d593bc70c3e1fe379d18f759958f89827ded02e92c9570320f810426de384f0c37930d58ab63fd80565e02e7a3048e436bc01b26a4e0b9f2c57b782d",
          "sha256": "4de89c059925e4744102b503574a64bb2d10f4ab3b702724e699db5f81930227",
          "sha1": "d371a4a37abf3cf36fc04e94e57402596a28bfa3",
          "md5": "b5acdc966ad5c25f3e0c4a4b385b4c2d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-9.5.0-b0-sources.jar",
          "url": "core-ng-search-9.5.0-b0-sources.jar",
          "size": 23900,
          "sha512": "7aa8dad3aaff3258eb9b7079c462c27c07367abfacc6c71c889236ca898dc1e8966a140938b5382c9ffcc7c39a0f3e2c3cb70ef816f70f6a5779ebc23d9e73cf",
          "sha256": "bb87878229b816811d65b5785cca5ed212bd6a7f7f21eb2a987ebd2d0b0872ea",
          "sha1": "1bc8d59613d641d960ba1a8ab49ac305ed640811",
          "md5": "caed4bf056d3bd5de8af74098ff30f65"
        }
      ]
    }
  ]
}
