{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "7.6.16-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.6.16-b0.jar",
          "url": "core-ng-search-test-7.6.16-b0.jar",
          "size": 9067,
          "sha512": "dd1e3d350195de2ea095a1c5fcb30998beb63b520c61e8a92767ceae42a590e43e91dd6dc6a5601bed24ca1d26538361e7e489d3267530e345003a2a01e7486f",
          "sha256": "cf168d7a61271e12a6b851a4337d05a84adbf256b10b4ce8cc5b135d2cdd8d27",
          "sha1": "d664bed6f16cb47215389740c98a8e4431415f49",
          "md5": "926939f38d157990ff1c5116869cdefd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.6.16-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.6.16-b0"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "7.12.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4-client",
          "version": {
            "requires": "7.12.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "reindex-client",
          "version": {
            "requires": "7.12.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "mapper-extras-client",
          "version": {
            "requires": "7.12.0"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "7.12.0"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "7.12.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.6.16-b0.jar",
          "url": "core-ng-search-test-7.6.16-b0.jar",
          "size": 9067,
          "sha512": "dd1e3d350195de2ea095a1c5fcb30998beb63b520c61e8a92767ceae42a590e43e91dd6dc6a5601bed24ca1d26538361e7e489d3267530e345003a2a01e7486f",
          "sha256": "cf168d7a61271e12a6b851a4337d05a84adbf256b10b4ce8cc5b135d2cdd8d27",
          "sha1": "d664bed6f16cb47215389740c98a8e4431415f49",
          "md5": "926939f38d157990ff1c5116869cdefd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.6.16-b0-sources.jar",
          "url": "core-ng-search-test-7.6.16-b0-sources.jar",
          "size": 5478,
          "sha512": "a3a6c8fff2a47e58159b8309d7b3ce3c83f4469917f3154a92ad9f079eefcac3634a0b81d122e275943e44f5f21e8e2476489c90e08fa3a2b0c00275ca28536a",
          "sha256": "32b4f119fa861aafb3ad2a49c0247881912663fd9667a4e68764159e9b8d33bf",
          "sha1": "5d2d757af37b3d374f19e26ababf8caef5af18a3",
          "md5": "a58289f6890bbf30379a00a5311d87bf"
        }
      ]
    }
  ]
}
