{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "9.3.1-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.20.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.3.1-b0.jar",
          "url": "core-ng-test-9.3.1-b0.jar",
          "size": 50951,
          "sha512": "6468044c4a54ec66fdc506c8ff9fbfa2d37b017c66d94f511173604c7c6f81143a81061eeaac0f39699173aa858a2db02405b8c2416df256f5e63365cef57d5d",
          "sha256": "b308c6618bd995eb8a43e3121696a034cdc21425e1b400983c0e2280fc86db87",
          "sha1": "d25525d799cdd8e974b43b81bc0f6fcacbf4717c",
          "md5": "8dca29e71fa2dc8735bd5be23e0f3bc8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.3.1-b0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.20.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.3.1-b0.jar",
          "url": "core-ng-test-9.3.1-b0.jar",
          "size": 50951,
          "sha512": "6468044c4a54ec66fdc506c8ff9fbfa2d37b017c66d94f511173604c7c6f81143a81061eeaac0f39699173aa858a2db02405b8c2416df256f5e63365cef57d5d",
          "sha256": "b308c6618bd995eb8a43e3121696a034cdc21425e1b400983c0e2280fc86db87",
          "sha1": "d25525d799cdd8e974b43b81bc0f6fcacbf4717c",
          "md5": "8dca29e71fa2dc8735bd5be23e0f3bc8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-9.3.1-b0-sources.jar",
          "url": "core-ng-test-9.3.1-b0-sources.jar",
          "size": 25054,
          "sha512": "7d7fe66b97d1ee46b04fde33b91675b5170a688eefd6d752dd835eff8a539517e0223e0e8d2c24888635dce5b7087dd0acdcf80a6e56c47a3cdb336721dd3520",
          "sha256": "43461b90bb5df7811dccd4ca162502747c3f720289411ecd4b29810c6cd581d4",
          "sha1": "afe24a8b31632a2dec1cb9b0f7397043e9177373",
          "md5": "3191ead876e8996cbd77d8a3008c92a6"
        }
      ]
    }
  ]
}
