{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "9.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-params",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.23.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.7"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.6.1.jar",
          "url": "core-ng-test-9.6.1.jar",
          "size": 51136,
          "sha512": "439d8a1be9b267fc648f4e5509fb30ca123c9072b272effdab83d354965c2994185e1afae978763a1f2c256559f818dcefe47aa734d13836e120b1896587c1a3",
          "sha256": "3914ee0f0778d85338a89c32d9db323dbafd1ec1ed499717c8372ce60973b482",
          "sha1": "a21cbcbcd6f140a515bcf9b5ddcda37ea7e07674",
          "md5": "b7f6063902b3d9bc00803f8fb6d95039"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.6.1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-params",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.23.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.7"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.6.1.jar",
          "url": "core-ng-test-9.6.1.jar",
          "size": 51136,
          "sha512": "439d8a1be9b267fc648f4e5509fb30ca123c9072b272effdab83d354965c2994185e1afae978763a1f2c256559f818dcefe47aa734d13836e120b1896587c1a3",
          "sha256": "3914ee0f0778d85338a89c32d9db323dbafd1ec1ed499717c8372ce60973b482",
          "sha1": "a21cbcbcd6f140a515bcf9b5ddcda37ea7e07674",
          "md5": "b7f6063902b3d9bc00803f8fb6d95039"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-9.6.1-sources.jar",
          "url": "core-ng-test-9.6.1-sources.jar",
          "size": 25103,
          "sha512": "727ccbd7fe7fd2b508ec4f546d9051419b9e8ece3956b0451cb2ec3a384b3c23aaa96fa5ea2e5c453cdd746cc080560ae77b5e6d648c3629b286994e64a37487",
          "sha256": "1084595c025142307a29b1a54526fdbec20cc56b97e089c7ac6f840a7983b35c",
          "sha1": "ac6ddcf06b7174a08564d5f16f3fc3f593743b50",
          "md5": "14551ad3a9280bf3ef11371efd21fbc7"
        }
      ]
    }
  ]
}
