{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "7.5.13-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6",
      "buildId": "2uzdmxjnafdqllzk2zdacqveqe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.5.13-b0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.6.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.5.7"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.5.13-b0.jar",
          "url": "core-ng-test-7.5.13-b0.jar",
          "size": 36187,
          "sha512": "4a697beadc485ef3a124b0ff77f2e125524561b07b79d7f392c7c7ce4ac8eb1480c11c81765148c106c9a6c6484b7c48cff7de2b85e54e4e36df30e83cdb3364",
          "sha256": "d734b5e361fbfc1214369948023f8a45a1c337430ce3b20f297ca1a88fe3fde0",
          "sha1": "6ea1db2c100276c63d0babf2f78dc600eb7f8930",
          "md5": "64baeb4aab96bf6b364504083ac63ff8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.6.2"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.4.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.5.13-b0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.6.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.5.7"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.5.13-b0.jar",
          "url": "core-ng-test-7.5.13-b0.jar",
          "size": 36187,
          "sha512": "4a697beadc485ef3a124b0ff77f2e125524561b07b79d7f392c7c7ce4ac8eb1480c11c81765148c106c9a6c6484b7c48cff7de2b85e54e4e36df30e83cdb3364",
          "sha256": "d734b5e361fbfc1214369948023f8a45a1c337430ce3b20f297ca1a88fe3fde0",
          "sha1": "6ea1db2c100276c63d0babf2f78dc600eb7f8930",
          "md5": "64baeb4aab96bf6b364504083ac63ff8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-7.5.13-b0-sources.jar",
          "url": "core-ng-test-7.5.13-b0-sources.jar",
          "size": 18196,
          "sha512": "9532011a1bc68a8d6fc4225a78f8b0124275b0610fca729d0de2a6a4d931b73792969117440d730f57a0e92ec4d4acf01356745f9ee4ddecfff2bbd6c820b520",
          "sha256": "887432349268bac1123fedce0290f056fa6b689ad25217154c67ebb1de7686fb",
          "sha1": "8c3ac1aba979d966c26417218ae79f015e39c860",
          "md5": "563199b56d2751a99b624ad6c5673887"
        }
      ]
    }
  ]
}
