{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "9.1.1-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.1.1-b1.jar",
          "url": "core-ng-mongo-test-9.1.1-b1.jar",
          "size": 2487,
          "sha512": "14009ec75216bee5b4e1a63bda609dc59a6933d29d3189471fefe53ceb1d28432b3c04e38ae128222200eda44630f5b61e0441d2ace87756a6883ee836b63aba",
          "sha256": "4c1af84f879d3062c15ad2449237384869f8e22331fca4b64c643e43aff49352",
          "sha1": "e2c754ac157fe798c7490958fc51134dfeb4e09b",
          "md5": "d8d33b05155ef72fef058dd43c49134c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.1.1-b1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "9.1.1-b1"
          }
        },
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.45.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-9.1.1-b1.jar",
          "url": "core-ng-mongo-test-9.1.1-b1.jar",
          "size": 2487,
          "sha512": "14009ec75216bee5b4e1a63bda609dc59a6933d29d3189471fefe53ceb1d28432b3c04e38ae128222200eda44630f5b61e0441d2ace87756a6883ee836b63aba",
          "sha256": "4c1af84f879d3062c15ad2449237384869f8e22331fca4b64c643e43aff49352",
          "sha1": "e2c754ac157fe798c7490958fc51134dfeb4e09b",
          "md5": "d8d33b05155ef72fef058dd43c49134c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.1.1-b1-sources.jar",
          "url": "core-ng-mongo-test-9.1.1-b1-sources.jar",
          "size": 1779,
          "sha512": "4ac5b53d1c783d0c7deb8ba674879b6f9ad7b1bf42c5ec9acb1981f4a2d6a6912ca7ca80114389ec29330d24c58556ab457ac06886a8a19e6fa35285246aaffb",
          "sha256": "9022fa5997857028697fe9e93503c901ad4034a997fe3fea4cfde906211a09bd",
          "sha1": "47053008feee7b57855e0ebd474b533162914c1b",
          "md5": "d2a924f1ed83cfb757c7d2511741e84e"
        }
      ]
    }
  ]
}
