{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "7.6.5-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "6ecqkefeljhonffelsxv5ejxx4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.6.5-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.6.5-b0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.6.5-b0.jar",
          "url": "core-ng-search-test-7.6.5-b0.jar",
          "size": 9069,
          "sha512": "582f7db4656b48e8530909252549cb06b628e77e26850c59d2392d7a5df04ab0deadeda9a1d17b8c9ff563ee00d166aa882ae7566b03e9878d2e8b41c5a8beda",
          "sha256": "1ea03f4c60999cf0219757dba023446751509e49246ea3fc58fac5fc1b60ed62",
          "sha1": "acafa0d7cd7e994ed42fa8612dff0adbf31a7467",
          "md5": "6fecce048fa35b7ad18ee753f94bb601"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4-client",
          "version": {
            "requires": "7.10.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "reindex-client",
          "version": {
            "requires": "7.10.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "7.10.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "7.10.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "7.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.6.5-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.6.5-b0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.6.5-b0.jar",
          "url": "core-ng-search-test-7.6.5-b0.jar",
          "size": 9069,
          "sha512": "582f7db4656b48e8530909252549cb06b628e77e26850c59d2392d7a5df04ab0deadeda9a1d17b8c9ff563ee00d166aa882ae7566b03e9878d2e8b41c5a8beda",
          "sha256": "1ea03f4c60999cf0219757dba023446751509e49246ea3fc58fac5fc1b60ed62",
          "sha1": "acafa0d7cd7e994ed42fa8612dff0adbf31a7467",
          "md5": "6fecce048fa35b7ad18ee753f94bb601"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.6.5-b0-sources.jar",
          "url": "core-ng-search-test-7.6.5-b0-sources.jar",
          "size": 5480,
          "sha512": "c5919c686d05ec6a5fc30f9dc8d066a636cab63d299ac0d3113a29ba168c81c491f3c0489ef1354e1b3ac4c42bdfc8518f7aa440f8089cf936f2713a8618130c",
          "sha256": "123f80bb9c83bd4ef1a2c3e08e84b8c179ab08addf269e83734bc419d7f3d6a3",
          "sha1": "fa76458e1cd2fb21fe3a7713ba5dbbaddcedf56c",
          "md5": "dc849112a5a6cf2cc19eaeba3d4f055d"
        }
      ]
    }
  ]
}
