{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "9.3.0-b2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-api-9.3.0-b2.jar",
          "url": "core-ng-api-9.3.0-b2.jar",
          "size": 11009,
          "sha512": "46e28b41b23536a73b2118e33a2e55be3b9a3f430234b1f8b142aef68468976307e2b0946bb1c33d39952024e34108986d15dc5b717e2cbc4c270a0f4a7f76ae",
          "sha256": "a080395e1325cfae42205d45d34c0f06358643b06b3fe102e36de42e6903a9b3",
          "sha1": "cb8542425c2aecea282590348b968bf8ba4a1334",
          "md5": "439b4c504e639a3f1fec1fd8be5c06d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-api-9.3.0-b2.jar",
          "url": "core-ng-api-9.3.0-b2.jar",
          "size": 11009,
          "sha512": "46e28b41b23536a73b2118e33a2e55be3b9a3f430234b1f8b142aef68468976307e2b0946bb1c33d39952024e34108986d15dc5b717e2cbc4c270a0f4a7f76ae",
          "sha256": "a080395e1325cfae42205d45d34c0f06358643b06b3fe102e36de42e6903a9b3",
          "sha1": "cb8542425c2aecea282590348b968bf8ba4a1334",
          "md5": "439b4c504e639a3f1fec1fd8be5c06d6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.3.0-b2-sources.jar",
          "url": "core-ng-api-9.3.0-b2-sources.jar",
          "size": 8661,
          "sha512": "1a7cd1a57f008b894b7a36fe1a1353d2c339557b579a89b5d24e26e176ace32d26df946b26cd69808014e3c5dc551dcc5ccb2cc904f7031adcffa514c9afa096",
          "sha256": "7a2233dc9aba598ab35f8c8192eca2bc8296080b102fd3c80cbdea0dc0c6ec06",
          "sha1": "fee0cb50cfed8fb3d57728b61e37e366c9fa16da",
          "md5": "2ee75f7fa123234225ac62fb509a814c"
        }
      ]
    }
  ]
}
