{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "7.6.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "y4jpvy47ejel5oivsnxw6bxvra"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-7.6.12.jar",
          "url": "core-ng-api-7.6.12.jar",
          "size": 10963,
          "sha512": "ffc25a16cab3e7eff1ebd2a977a5737a847f31acb9d6c0580105cff9c38a879827837a1b430e998e660a41d6bd4674fe552aafdbb9a2c3afaf9879fb2a6d8417",
          "sha256": "c63d9118a567770a17fa111f6441dde893bc9aa600d119e089024509156ff5e2",
          "sha1": "7b903a882043e7e3882f6a7dc5add6dfceaf7ab2",
          "md5": "af8993d7a671428eec4caff7194c0b2f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.6.12.jar",
          "url": "core-ng-api-7.6.12.jar",
          "size": 10963,
          "sha512": "ffc25a16cab3e7eff1ebd2a977a5737a847f31acb9d6c0580105cff9c38a879827837a1b430e998e660a41d6bd4674fe552aafdbb9a2c3afaf9879fb2a6d8417",
          "sha256": "c63d9118a567770a17fa111f6441dde893bc9aa600d119e089024509156ff5e2",
          "sha1": "7b903a882043e7e3882f6a7dc5add6dfceaf7ab2",
          "md5": "af8993d7a671428eec4caff7194c0b2f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.6.12-sources.jar",
          "url": "core-ng-api-7.6.12-sources.jar",
          "size": 8644,
          "sha512": "a979b793b2a3c92d27605f0d11b94bc265401919355f83abd469edc2389c4c392b2fff0495537ee7c3c1cf447596a0282bb94195cc28b4ddc68b113f01fbb6b2",
          "sha256": "86c8c6915048db6bd2f4413f0d23c9a0ee3f5956665e3a7db2227c4e6a744f08",
          "sha1": "0392d65c95ee6e5db5088d83667388fcc99b654d",
          "md5": "4d5af58efae206ee34b261b420178501"
        }
      ]
    }
  ]
}
