{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "7.6.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "5ouw753gz5cgbnubxggdyz4bvu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-7.6.12.jar",
          "url": "core-ng-api-7.6.12.jar",
          "size": 10963,
          "sha512": "b567bcff5f5c3875b40e837ac55e0f3edb2742d96a03150c20acf58adabdf33ad1ea6082e82e63b81f91c7e72098a7c9ae68be3f7ff1028cb108869377548d68",
          "sha256": "a50ec1b3fdd249d0c153a841a0ed295974bf51db54c933388aea470b550ac1cb",
          "sha1": "b1fe8f652fef42321fdafca83a4b9a475f029882",
          "md5": "c21ef35a79eb8b31f69464a4ee5b875f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.6.12.jar",
          "url": "core-ng-api-7.6.12.jar",
          "size": 10963,
          "sha512": "b567bcff5f5c3875b40e837ac55e0f3edb2742d96a03150c20acf58adabdf33ad1ea6082e82e63b81f91c7e72098a7c9ae68be3f7ff1028cb108869377548d68",
          "sha256": "a50ec1b3fdd249d0c153a841a0ed295974bf51db54c933388aea470b550ac1cb",
          "sha1": "b1fe8f652fef42321fdafca83a4b9a475f029882",
          "md5": "c21ef35a79eb8b31f69464a4ee5b875f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.6.12-sources.jar",
          "url": "core-ng-api-7.6.12-sources.jar",
          "size": 8644,
          "sha512": "d639838b17da77ddff837cbde2ffe4904212202a53b93a9c8ec9f3bdfd1f21c38ae470267cfa6ed13a0e56ecd7e367aba38db3793fa179186a7351cda01043fb",
          "sha256": "5d4679bca082c697b1922f965ba7aa19ee539beabe59adc874499da3efd931ee",
          "sha1": "f63beae7fe050510607b1ee86fc55e3b9b788fb3",
          "md5": "a1c6df87c511158446cad2fba8a9ffed"
        }
      ]
    }
  ]
}
