{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "9.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.0.1.jar",
          "url": "core-ng-search-test-9.0.1.jar",
          "size": 12664,
          "sha512": "55ec742cea443d6735f0383ccc9554e514245dc79e6df390cdfa2453f8ba4e354a67370895851b5d23462caed574dc821bb64f9226cde5668370ec527cf5b338",
          "sha256": "0011a7e617d6c0e32c80645e316a0b494e9ebb93403474aafb970e03f9c8df60",
          "sha1": "bb9cb03721712de62298beebad971a360e6ea9df",
          "md5": "f2c5f5a51d21493c12b98e95af395cdb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.0.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "9.0.1"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "transport-netty4",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "reindex",
          "version": {
            "requires": "8.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-9.0.1.jar",
          "url": "core-ng-search-test-9.0.1.jar",
          "size": 12664,
          "sha512": "55ec742cea443d6735f0383ccc9554e514245dc79e6df390cdfa2453f8ba4e354a67370895851b5d23462caed574dc821bb64f9226cde5668370ec527cf5b338",
          "sha256": "0011a7e617d6c0e32c80645e316a0b494e9ebb93403474aafb970e03f9c8df60",
          "sha1": "bb9cb03721712de62298beebad971a360e6ea9df",
          "md5": "f2c5f5a51d21493c12b98e95af395cdb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.0.1-sources.jar",
          "url": "core-ng-search-test-9.0.1-sources.jar",
          "size": 7175,
          "sha512": "b74d597e1d3e39bcff0a1b34f9ae03621f66490553d22cdaa1efbeec75d794dd91e025ceafd571f2b4860526560de6072f4fab33ddf69263b2ce42b62cd03864",
          "sha256": "ec3e46a7ad4b5f2271ec03d356261f004a816aac5221a134b8842ffca2780f7f",
          "sha1": "11622eaad3d3838e0def740c5a0670cf9fed3daf",
          "md5": "e3a6af9673bbbfa8eb579f59dc68f089"
        }
      ]
    }
  ]
}
