{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "9.2.2-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-9.2.2-b0.jar",
          "url": "core-ng-api-9.2.2-b0.jar",
          "size": 11021,
          "sha512": "0209d33cd409af0b57ccaa18e3765308e72fbba3324b9e6df92865c98e1c8ddaa9762e94f352fc5577c6e18239eef91fad0a215cb5e73394fbb58b46c8a5299b",
          "sha256": "1a60db44b9629751208555cf132078264d835ddd7a46a4cc55947867731e8e06",
          "sha1": "9718252ee18188b1e937925cce492ea14f0411f1",
          "md5": "f3060dfad82b00c69c14596c0b8fdfaa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.2.2-b0.jar",
          "url": "core-ng-api-9.2.2-b0.jar",
          "size": 11021,
          "sha512": "0209d33cd409af0b57ccaa18e3765308e72fbba3324b9e6df92865c98e1c8ddaa9762e94f352fc5577c6e18239eef91fad0a215cb5e73394fbb58b46c8a5299b",
          "sha256": "1a60db44b9629751208555cf132078264d835ddd7a46a4cc55947867731e8e06",
          "sha1": "9718252ee18188b1e937925cce492ea14f0411f1",
          "md5": "f3060dfad82b00c69c14596c0b8fdfaa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.2.2-b0-sources.jar",
          "url": "core-ng-api-9.2.2-b0-sources.jar",
          "size": 8665,
          "sha512": "ea753767b3cb2e2d02ec694b79e4b8b298b74134786f3ef207c1585694631040de210bfbb1766b9ceb42b17ebf7828b6c2cd21778e3d09db19e5f5136d540a7a",
          "sha256": "5ab4af7c4b30e5bde3fc3e1a4da029cd6f9d553b173228e8326c8c6d0019b033",
          "sha1": "1d97fb957694c70e992f680b825881ddf5e2f4ad",
          "md5": "bb8a7aa60e1fcb954ea13ab9140d6878"
        }
      ]
    }
  ]
}
