{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "9.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.4.0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.4.0.jar",
          "url": "core-ng-mongo-9.4.0.jar",
          "size": 60076,
          "sha512": "c23de19ce85f4b6fa429753e4c3d9843102c0065d74c1d10a9cdd774edb902f71d3209408e2f67f89b196d087cdd47049525b2d04dadd4247a08d3c76d82bcd3",
          "sha256": "fade1cae204832d4714c1c7ba962278667a33603f82104ae0bb79b2d9fbf048b",
          "sha1": "31b3139f5eabae37970209a664037c81baa1141f",
          "md5": "b28f37afbaae0012eafade750f1d1db4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.4.0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.4.0.jar",
          "url": "core-ng-mongo-9.4.0.jar",
          "size": 60076,
          "sha512": "c23de19ce85f4b6fa429753e4c3d9843102c0065d74c1d10a9cdd774edb902f71d3209408e2f67f89b196d087cdd47049525b2d04dadd4247a08d3c76d82bcd3",
          "sha256": "fade1cae204832d4714c1c7ba962278667a33603f82104ae0bb79b2d9fbf048b",
          "sha1": "31b3139f5eabae37970209a664037c81baa1141f",
          "md5": "b28f37afbaae0012eafade750f1d1db4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-9.4.0-sources.jar",
          "url": "core-ng-mongo-9.4.0-sources.jar",
          "size": 28815,
          "sha512": "6a38e36a25dfde7913f1854fc556c6fdc65b6e2d3cd6bb62f91f31980d81c705c162e487a42399b92697c58166d743da916004f0d276bfcadaeb7f0f3ce424d5",
          "sha256": "ebb0b21036af2689715299ab14a5b6dbda210900a985e25400aba73ec51ae0fd",
          "sha1": "346794adb2fc8958b03dc5ed5d574a736da1719a",
          "md5": "49e7b27614128dc3488b7891a91aac09"
        }
      ]
    }
  ]
}
