{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "7.6.5-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "6ecqkefeljhonffelsxv5ejxx4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-7.6.5-b0.jar",
          "url": "core-ng-api-7.6.5-b0.jar",
          "size": 10433,
          "sha512": "84f7030b878afc5d5f0d73e6d94e69d7d0ca003af04b6117b5a9b3eda7c2876c6ae94070c20fd188c3ec6a68e92216cc58e8c191224e26ed08271ccf30ba4b2c",
          "sha256": "d44edc12f9ba26a939b2f05b8004f5d18921a31dabea3950b98bcde4a0722e3c",
          "sha1": "fb8022a0517edf4ddc5d7d2ab08846920c3ebe3e",
          "md5": "14ec8604489bb225f72d94dcb7c1b8ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.6.5-b0.jar",
          "url": "core-ng-api-7.6.5-b0.jar",
          "size": 10433,
          "sha512": "84f7030b878afc5d5f0d73e6d94e69d7d0ca003af04b6117b5a9b3eda7c2876c6ae94070c20fd188c3ec6a68e92216cc58e8c191224e26ed08271ccf30ba4b2c",
          "sha256": "d44edc12f9ba26a939b2f05b8004f5d18921a31dabea3950b98bcde4a0722e3c",
          "sha1": "fb8022a0517edf4ddc5d7d2ab08846920c3ebe3e",
          "md5": "14ec8604489bb225f72d94dcb7c1b8ce"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.6.5-b0-sources.jar",
          "url": "core-ng-api-7.6.5-b0-sources.jar",
          "size": 8156,
          "sha512": "ce60859b42ebf0bb0a12faeed46ce82770a6b5173e64f9ccc5dfabe68e41d48344989075082c713e65e93aba863153e2da7a53a9f670a48fee32fb7cc810b458",
          "sha256": "d66c6a3417f453e29c9cdf9011954a3f50352cfe350d23ae35b0790f1bcd4c3f",
          "sha1": "84c5cebb2eda06bd38bb4c8b05f116c6d221fd64",
          "md5": "e3af5f6a55dcfe133531f98fb7d362ca"
        }
      ]
    }
  ]
}
