{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.5.1-b4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.5.1-b4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.5.1-b4.jar",
          "url": "core-ng-9.5.1-b4.jar",
          "size": 789769,
          "sha512": "3d452bbbd98f02232a3390d542c066a090c26618b674cc38bd4101f6dd9e222b237e3658edbd577b5197eaa7c2bfcdf5b9ae37eea4711e6745f304759d370910",
          "sha256": "d5d8214244aa9f02d93516765feac08bce5eb677d6ba8c03a303a11304c8491b",
          "sha1": "59ce28d2140e002f6fba3cfdc69f0d96c5c72684",
          "md5": "0681c18812e38cca7e8d7417d74632bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "tools.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "tools.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.24.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "4.2.0"
          },
          "excludes": [
            {
              "group": "org.xerial.snappy",
              "module": "*"
            },
            {
              "group": "at.yawk.lz4",
              "module": "*"
            }
          ]
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.5.1-b4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.5.1-b4.jar",
          "url": "core-ng-9.5.1-b4.jar",
          "size": 789769,
          "sha512": "3d452bbbd98f02232a3390d542c066a090c26618b674cc38bd4101f6dd9e222b237e3658edbd577b5197eaa7c2bfcdf5b9ae37eea4711e6745f304759d370910",
          "sha256": "d5d8214244aa9f02d93516765feac08bce5eb677d6ba8c03a303a11304c8491b",
          "sha1": "59ce28d2140e002f6fba3cfdc69f0d96c5c72684",
          "md5": "0681c18812e38cca7e8d7417d74632bc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.5.1-b4-sources.jar",
          "url": "core-ng-9.5.1-b4-sources.jar",
          "size": 405945,
          "sha512": "83a4c10381345918ee791b2c1e1c48fb5fd9cc8c41141c34e7a1e9da04e6d979a0d584df06ff43c2df3fd667d440a9633c471337bf0b3029f636e8c2924e1f92",
          "sha256": "904bf8fe393743c4c1b8b609a5f4d4cd9e2babf8e7ad761ff75a995ac326339e",
          "sha1": "92343a183d9bd4b0b51de9d42f526c3ebb47afc9",
          "md5": "051a094d39211f101f6cae3f5d9b904e"
        }
      ]
    }
  ]
}
