{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "9.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.7"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.0.7.jar",
          "url": "core-ng-mongo-9.0.7.jar",
          "size": 57155,
          "sha512": "36d0bcfedd3f44de12821ba9bbeac3716a70a543ff7e72c971583495fc39c7848237ee0cba7e13387358438b50b6dafc5a5a8857ffcd30e095a495a85a1f70d2",
          "sha256": "cf28349dec8975489e2942fcf53e82efc9d0ce105099bdc3f7794353525d0d44",
          "sha1": "b9a5ba6b6b86bb3394978f566cd0eeed24367b2d",
          "md5": "022849322357ced581b53840be520729"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.7"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.0.7.jar",
          "url": "core-ng-mongo-9.0.7.jar",
          "size": 57155,
          "sha512": "36d0bcfedd3f44de12821ba9bbeac3716a70a543ff7e72c971583495fc39c7848237ee0cba7e13387358438b50b6dafc5a5a8857ffcd30e095a495a85a1f70d2",
          "sha256": "cf28349dec8975489e2942fcf53e82efc9d0ce105099bdc3f7794353525d0d44",
          "sha1": "b9a5ba6b6b86bb3394978f566cd0eeed24367b2d",
          "md5": "022849322357ced581b53840be520729"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-9.0.7-sources.jar",
          "url": "core-ng-mongo-9.0.7-sources.jar",
          "size": 27011,
          "sha512": "1997deb5ba55dad7903dc8a6fcd5b9289a8f660f3e81c2fdb18fb67ae4c35d3661ddcca248ee386a4c71974b627e5a46995f7c60cdbe55b1bf29768983859f8f",
          "sha256": "228b85cb5b214f90659d64106439e1d4dea225b582fd4fa9574da252e1cd8242",
          "sha1": "b38458c25d94e349e6fe3bc955c0899a31cac1d4",
          "md5": "071ee380a4d19ea7d9751c221972b1ee"
        }
      ]
    }
  ]
}
