{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "9.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.0.6.jar",
          "url": "core-ng-search-test-9.0.6.jar",
          "size": 13097,
          "sha512": "1b2222dbb77e95152d6d38c1079c24f92f01dbf9d78f5b8ad3cf6a41c982c28a72a7e6129079b1fe237ca10e193848feb4d0d6cdbf7b8a54268abf6564694233",
          "sha256": "78af2df7e1c33c785faecc7f9a09e1c10ceb17b4ac4ad8165729521d816f5b02",
          "sha1": "84520902a4518ff81bdb558a599c8b9f315ccb0e",
          "md5": "240e9e57ad54bfb4e6e0fec8f256af96"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.0.6"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "9.0.6"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "8.12.1"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4",
          "version": {
            "requires": "8.12.1"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "8.12.1"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "8.12.1"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "8.12.1"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "reindex",
          "version": {
            "requires": "8.12.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "reindex",
              "type": "jar",
              "extension": "jar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-9.0.6.jar",
          "url": "core-ng-search-test-9.0.6.jar",
          "size": 13097,
          "sha512": "1b2222dbb77e95152d6d38c1079c24f92f01dbf9d78f5b8ad3cf6a41c982c28a72a7e6129079b1fe237ca10e193848feb4d0d6cdbf7b8a54268abf6564694233",
          "sha256": "78af2df7e1c33c785faecc7f9a09e1c10ceb17b4ac4ad8165729521d816f5b02",
          "sha1": "84520902a4518ff81bdb558a599c8b9f315ccb0e",
          "md5": "240e9e57ad54bfb4e6e0fec8f256af96"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.0.6-sources.jar",
          "url": "core-ng-search-test-9.0.6-sources.jar",
          "size": 7160,
          "sha512": "49587b28356b85c5b5f44a88d96e1d4cf487bf9b4e40767494c10d717920d7398e6ef5543b82de7e7d86140994bae2d249c55e0d855140b88a9b613b746b82dc",
          "sha256": "3178b79e8ff714460643b4683b19b165d646106a4ad1668c0a4e04674fcee05a",
          "sha1": "4be869d77883f4b2d4ea0a224dc7bcdb5f4aed68",
          "md5": "a23d7c756256a7042e28587ccce161f0"
        }
      ]
    }
  ]
}
