{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "7.6.8-b2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "proo64g6nrfkppc7ucepn5zmyu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.6.8-b2.jar",
          "url": "core-ng-search-test-7.6.8-b2.jar",
          "size": 9069,
          "sha512": "e2fb22f53b4cd3f02839f4ef2f040edf11294e90daa1c4b89739df312e35d4d76b4ea74b5a1296cb2f7d42ebe9b252e57dde45e36a3ec90b6e320e25234b69c8",
          "sha256": "d37e08a6dc8b7ceddfff5fba8d7b27ea62f7d86a883a34bba3de7ac3fddd4267",
          "sha1": "91b590ac6b9ad3caa83676ea8f59e4fdeeb4447d",
          "md5": "0c24f9c7ddd329ec1c2c1786293e2bfa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.6.8-b2"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.6.8-b2"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4-client",
          "version": {
            "requires": "7.10.1"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "reindex-client",
          "version": {
            "requires": "7.10.1"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "7.10.1"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "7.10.1"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "7.10.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.6.8-b2.jar",
          "url": "core-ng-search-test-7.6.8-b2.jar",
          "size": 9069,
          "sha512": "e2fb22f53b4cd3f02839f4ef2f040edf11294e90daa1c4b89739df312e35d4d76b4ea74b5a1296cb2f7d42ebe9b252e57dde45e36a3ec90b6e320e25234b69c8",
          "sha256": "d37e08a6dc8b7ceddfff5fba8d7b27ea62f7d86a883a34bba3de7ac3fddd4267",
          "sha1": "91b590ac6b9ad3caa83676ea8f59e4fdeeb4447d",
          "md5": "0c24f9c7ddd329ec1c2c1786293e2bfa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.6.8-b2-sources.jar",
          "url": "core-ng-search-test-7.6.8-b2-sources.jar",
          "size": 5480,
          "sha512": "28f195dedf1c3259af03cbfa4c691686f3547c685669f94582ff3385478db5fac1aab3e0786a1247c9c552fe8444caeaff0378f2ccfc1dbfe877f2f7fa38fba7",
          "sha256": "6e024e5cb44dfc1241ceb0776fa9f2c4a7d15fccd62ed738b6f5de9b2f4455a7",
          "sha1": "612c180ce0d377bdcf6b840fdff0ac45dfc86a72",
          "md5": "4def53a9730bf145082f4fbc8122e906"
        }
      ]
    }
  ]
}
