{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.1.1-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.1-b1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.1.1-b1.jar",
          "url": "core-ng-9.1.1-b1.jar",
          "size": 771276,
          "sha512": "02db7040747def3ea9bcaee258be2c8d6bd9ee26db1efa245cdeb21e0969d196b70b319460bacf0de8dff76eca4dfe14305b89b1e8745153737665c1af4326f9",
          "sha256": "af4e42f680ea08ec989cf49f59296dcdbb27b8d4f4f666a8b6f63b573903b2dd",
          "sha1": "b888e318f9ee552fcbf94c6a76d375d8f8a4fd99",
          "md5": "93538da7b750ac53390be95e8865db8d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "okhttp",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.10.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "3.8.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.10.5"
          }
        },
        {
          "group": "com.github.luben",
          "module": "zstd-jni",
          "version": {
            "requires": "1.5.6-4"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.1-b1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.1.1-b1.jar",
          "url": "core-ng-9.1.1-b1.jar",
          "size": 771276,
          "sha512": "02db7040747def3ea9bcaee258be2c8d6bd9ee26db1efa245cdeb21e0969d196b70b319460bacf0de8dff76eca4dfe14305b89b1e8745153737665c1af4326f9",
          "sha256": "af4e42f680ea08ec989cf49f59296dcdbb27b8d4f4f666a8b6f63b573903b2dd",
          "sha1": "b888e318f9ee552fcbf94c6a76d375d8f8a4fd99",
          "md5": "93538da7b750ac53390be95e8865db8d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.1.1-b1-sources.jar",
          "url": "core-ng-9.1.1-b1-sources.jar",
          "size": 394278,
          "sha512": "8c11f3006b68d310d9eaa19848855d1376b5de4ec53149ef076f773532d4340d081eaf8b6d0a830347602ce9a7c7bb5c67a39fbbf53c4887d076909ea7d611ac",
          "sha256": "0659d13b2053dc4a0268320f8a085a5ff8b291b81a99d5ff6533d6d428f57f00",
          "sha1": "12ce61008f179a3bf1d1ec22e7affabe557d986b",
          "md5": "611b96a7cbf303748ffa444cadcf443e"
        }
      ]
    }
  ]
}
