{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.4.0-b4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.4.0-b4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.4.0-b4.jar",
          "url": "core-ng-9.4.0-b4.jar",
          "size": 786775,
          "sha512": "956225900ef9d0fc543b8f09ca22e123ac1b1c2b802e3d1c62c9e55bad9a2a7af9ac18b5894ff6724c0f0c2876e579cbe3d87dd27be4c2ed35bdcaab833db3ad",
          "sha256": "d92486680d9820d493ae9d3ef961849ccfd4e06e5ba461d6b85dedf226b64863",
          "sha1": "ffc784400f881531c084cecc66b5e4de27bb3430",
          "md5": "b8a98b01fc4b635bf6721487360259d3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.22.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "4.1.1"
          },
          "excludes": [
            {
              "group": "org.xerial.snappy",
              "module": "*"
            },
            {
              "group": "org.lz4",
              "module": "*"
            }
          ]
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.4.0-b4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.4.0-b4.jar",
          "url": "core-ng-9.4.0-b4.jar",
          "size": 786775,
          "sha512": "956225900ef9d0fc543b8f09ca22e123ac1b1c2b802e3d1c62c9e55bad9a2a7af9ac18b5894ff6724c0f0c2876e579cbe3d87dd27be4c2ed35bdcaab833db3ad",
          "sha256": "d92486680d9820d493ae9d3ef961849ccfd4e06e5ba461d6b85dedf226b64863",
          "sha1": "ffc784400f881531c084cecc66b5e4de27bb3430",
          "md5": "b8a98b01fc4b635bf6721487360259d3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.4.0-b4-sources.jar",
          "url": "core-ng-9.4.0-b4-sources.jar",
          "size": 404919,
          "sha512": "530456b41fd2a89d94cec33967da55d8e376d3231f6a10f38bbd69f69146de52b4fef36c15bbf5a888d731c3f4ba3762f34bb4d9e270c840d219f16a7ad8f510",
          "sha256": "78c433ddc2290d5e3423f2e8ad92c5a4fbb74c961a02596ceb8a0dc4065b1279",
          "sha1": "4a8b21b2090ac4857e6829a9d8c54a84451df6fd",
          "md5": "9c4c5d37e1ad7d84297181fb9e349a61"
        }
      ]
    }
  ]
}
