{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "9.4.0-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-api-9.4.0-b0.jar",
          "url": "core-ng-api-9.4.0-b0.jar",
          "size": 11020,
          "sha512": "41b3c6a75f47c8eb5ff5ad92d80a6ce8093dc67a29a41c35906f41d9e215020372447927943bbe8b72587cb9c79341e6959d1309779740ae036fedbed07eb50b",
          "sha256": "2942f766fa748b1bb94bf20ba0768d4df74f23fbf0e888e5c63d9c739e09e8bb",
          "sha1": "3e553b5213850f1a8999fa864389e599eda52017",
          "md5": "1eb1361ca52d68b6c270c30a63a4d6bb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-api-9.4.0-b0.jar",
          "url": "core-ng-api-9.4.0-b0.jar",
          "size": 11020,
          "sha512": "41b3c6a75f47c8eb5ff5ad92d80a6ce8093dc67a29a41c35906f41d9e215020372447927943bbe8b72587cb9c79341e6959d1309779740ae036fedbed07eb50b",
          "sha256": "2942f766fa748b1bb94bf20ba0768d4df74f23fbf0e888e5c63d9c739e09e8bb",
          "sha1": "3e553b5213850f1a8999fa864389e599eda52017",
          "md5": "1eb1361ca52d68b6c270c30a63a4d6bb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.4.0-b0-sources.jar",
          "url": "core-ng-api-9.4.0-b0-sources.jar",
          "size": 8665,
          "sha512": "328cef2c2a2ef8ded84493972807147166e47354a3f7d98deb693817534d48e842e901a8325125c9abbd24e078274d977b3d82944ccf6480d06dcf83ef0b07c1",
          "sha256": "a2cf570bacc9b2ea796d2338ea2552136fe064a80f3d5e94689d08838431d29d",
          "sha1": "0c8add53d2770acf67471f59220bdcdaa59344ae",
          "md5": "8b25567b7908d880bc203b34e0b4d9d3"
        }
      ]
    }
  ]
}
