{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "7.6.2-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "5jfivrnadrg73pcyjgmirgtp24"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-7.6.2-b0.jar",
          "url": "core-ng-api-7.6.2-b0.jar",
          "size": 10426,
          "sha512": "3178e771e8f17d3c74c35622f9919376f0315b4bc0623aaa209a626c6225ca300ef30aa20e13cf5965e31145cf56f4282182e2a2b967cf4e6ccbe4a062fa9b64",
          "sha256": "43d33f27cec2a277322f2e3271d21cfb1f34603a4c8c6b6e82d745eb281d80ab",
          "sha1": "4eb569a408399b2230a3f5faa670851339a18447",
          "md5": "dae14e0a75b047c1a82ec864277b91a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.6.2-b0.jar",
          "url": "core-ng-api-7.6.2-b0.jar",
          "size": 10426,
          "sha512": "3178e771e8f17d3c74c35622f9919376f0315b4bc0623aaa209a626c6225ca300ef30aa20e13cf5965e31145cf56f4282182e2a2b967cf4e6ccbe4a062fa9b64",
          "sha256": "43d33f27cec2a277322f2e3271d21cfb1f34603a4c8c6b6e82d745eb281d80ab",
          "sha1": "4eb569a408399b2230a3f5faa670851339a18447",
          "md5": "dae14e0a75b047c1a82ec864277b91a5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.6.2-b0-sources.jar",
          "url": "core-ng-api-7.6.2-b0-sources.jar",
          "size": 8153,
          "sha512": "f3b3cd8e3fed2b9b6f00e4d368687d83c723c6ea6a99a5c6c9598f329d581dcb4fb54e9c67e3d0ecf246826bf64a29ce36a6e0eafcdaa0b5be713b3b8dc5c69c",
          "sha256": "90d8ef0854d1028621a4784d787f27181c0962df8dd568081d78b621d196f1ba",
          "sha1": "7269bac9dfcbc17a61b072a53de76b4e71cf8912",
          "md5": "d7a52ac3a2bf5f6a845953effecf76fc"
        }
      ]
    }
  ]
}
