{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "9.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.6"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.0.6.jar",
          "url": "core-ng-search-9.0.6.jar",
          "size": 52863,
          "sha512": "0796a9831893e2ae8b0b56bc9849cc34ba249bdd90629f4d7fa5d83342df52dbeed53c7818ca13018a2e0517cca24efe177003c890175bada7c60f15347f5231",
          "sha256": "dd4b9b73d3859d579f681c97e0ccf970868409153f111b6a480091183054eb1b",
          "sha1": "a73196cf1d11d6cd6ec47e83504bc969d7087e39",
          "md5": "fb0f2b436278b2850c6714b2c430c307"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.16.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.6"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.0.6.jar",
          "url": "core-ng-search-9.0.6.jar",
          "size": 52863,
          "sha512": "0796a9831893e2ae8b0b56bc9849cc34ba249bdd90629f4d7fa5d83342df52dbeed53c7818ca13018a2e0517cca24efe177003c890175bada7c60f15347f5231",
          "sha256": "dd4b9b73d3859d579f681c97e0ccf970868409153f111b6a480091183054eb1b",
          "sha1": "a73196cf1d11d6cd6ec47e83504bc969d7087e39",
          "md5": "fb0f2b436278b2850c6714b2c430c307"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-9.0.6-sources.jar",
          "url": "core-ng-search-9.0.6-sources.jar",
          "size": 21977,
          "sha512": "53c039fbd98644f2a2d90e302f6afaa187a9acaacc4ada307b135bdba554737bc5d376d17aa80b73e5f285f26814456b2ed277e5ebdc3be47f3c74977afd53a9",
          "sha256": "77f9e0b05bcf133760156966aeb28124717ca6bd3bc9d27acd6ac01e4a360dee",
          "sha1": "7a581113566f93f6db3de6819ac9abd192a5ab55",
          "md5": "f696b458a6e1ae68bdcc4b38c913b800"
        }
      ]
    }
  ]
}
