{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "9.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.10.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.0.6.jar",
          "url": "core-ng-test-9.0.6.jar",
          "size": 45690,
          "sha512": "5ea0a4d0807da9367201b8db8198ad2d143232dedb18c2dd82ff63ff14fb30d9ad68817208114bf4df9b8be7b7f377927c94f5a98ab8b57f56958a3cf346d7e0",
          "sha256": "8f2702da7cf5d2331890d2d63143c87dbf6aecd9421b1e1e4254d13fa9e54d5c",
          "sha1": "f14b29fe41b10e936a2f4c854d920ff61d2044a0",
          "md5": "34d1240f11d5bf1ee98b39203ca923e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.6"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.10.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.0.6.jar",
          "url": "core-ng-test-9.0.6.jar",
          "size": 45690,
          "sha512": "5ea0a4d0807da9367201b8db8198ad2d143232dedb18c2dd82ff63ff14fb30d9ad68817208114bf4df9b8be7b7f377927c94f5a98ab8b57f56958a3cf346d7e0",
          "sha256": "8f2702da7cf5d2331890d2d63143c87dbf6aecd9421b1e1e4254d13fa9e54d5c",
          "sha1": "f14b29fe41b10e936a2f4c854d920ff61d2044a0",
          "md5": "34d1240f11d5bf1ee98b39203ca923e6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-9.0.6-sources.jar",
          "url": "core-ng-test-9.0.6-sources.jar",
          "size": 22166,
          "sha512": "ecb6223782f2f61849be305466ec8348f14d0643ec6d4a1faf814a98cd7fd1489ef6d87ece3acd36031feb419c4c43b33ac3a7c795ed9100b9f03d3ce6121728",
          "sha256": "9b2df0ba0e59c15fa9aec6f8d0c50533f3dd330cbb7ce38dea82f18e3021ed82",
          "sha1": "39d0e9e396966ce65aede6d35ff8b9be827d105d",
          "md5": "bb2f045e3893b254df908747eb828469"
        }
      ]
    }
  ]
}
