{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "9.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.8.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.0.5.jar",
          "url": "core-ng-test-9.0.5.jar",
          "size": 45690,
          "sha512": "d5d862ed914cad0f01f99ccd8d2225777a7ae409be869d05426dd6cf368b3b9bc20970cbb932075a77fb45e446d616d06382d885abd23fb0877077b6f70ca016",
          "sha256": "45e486564e7ac9a379fa2762239041785d711cbcde0482aef569538f1ae5ea24",
          "sha1": "a533cf5be8ecafdd10bb63291eff78cc4b837fec",
          "md5": "fa4329fa6950901613a231c1b59172f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.5"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.10.1"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.8.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.0.5.jar",
          "url": "core-ng-test-9.0.5.jar",
          "size": 45690,
          "sha512": "d5d862ed914cad0f01f99ccd8d2225777a7ae409be869d05426dd6cf368b3b9bc20970cbb932075a77fb45e446d616d06382d885abd23fb0877077b6f70ca016",
          "sha256": "45e486564e7ac9a379fa2762239041785d711cbcde0482aef569538f1ae5ea24",
          "sha1": "a533cf5be8ecafdd10bb63291eff78cc4b837fec",
          "md5": "fa4329fa6950901613a231c1b59172f4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-9.0.5-sources.jar",
          "url": "core-ng-test-9.0.5-sources.jar",
          "size": 22166,
          "sha512": "e28734f058912fce0ea924f4ee2b7e3ca7f11f4f158bcf8ca887062f9e4032d4cbf43652fa158ae7ff249d0c0f9d27c6e9390a4424a68ddf557760920a585c22",
          "sha256": "d89ecd80eb2d0ec075e5be721929a730a777555791eeaa48c5608ced996359e4",
          "sha1": "a03bd38a1d744bcc718521318c91eb41772bdf42",
          "md5": "5fd1d65f61922c92f831830d44932acf"
        }
      ]
    }
  ]
}
