{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "9.1.0-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-9.1.0-b0.jar",
          "url": "core-ng-api-9.1.0-b0.jar",
          "size": 10992,
          "sha512": "b81e96862d495f49b2715dadc9f86711ec50b820dec29295c5da6d72ba9e60e5dcd69f15f5c68551f68ec9949e6b87834ca8e3d4541dbd81e37ee969bdab08b1",
          "sha256": "3d9b4fec8398eacda4d31558a17b7ba5c668827ca060dd24daac8bcc94062254",
          "sha1": "48759ee0bd2a6f104e978ec5c1518f394372f5d2",
          "md5": "0e732b4a9505dca89f2a34acd35fb935"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.1.0-b0.jar",
          "url": "core-ng-api-9.1.0-b0.jar",
          "size": 10992,
          "sha512": "b81e96862d495f49b2715dadc9f86711ec50b820dec29295c5da6d72ba9e60e5dcd69f15f5c68551f68ec9949e6b87834ca8e3d4541dbd81e37ee969bdab08b1",
          "sha256": "3d9b4fec8398eacda4d31558a17b7ba5c668827ca060dd24daac8bcc94062254",
          "sha1": "48759ee0bd2a6f104e978ec5c1518f394372f5d2",
          "md5": "0e732b4a9505dca89f2a34acd35fb935"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.1.0-b0-sources.jar",
          "url": "core-ng-api-9.1.0-b0-sources.jar",
          "size": 8642,
          "sha512": "b7bacafed85b02afd6266a51c16b7ba128f3b377eedb58eae09a0712d93d666b3c655c29989390ee483660afd099c1f410bbb21a17c445b1230560e46a1f6a30",
          "sha256": "b627152ef2433892513f148fb2825fb47234d04c25b5810c42939a77ebe9a472",
          "sha1": "c7a4b555cfcbc7933df1ef065c2c05e24b7634a1",
          "md5": "5de0bbd9f9fb280c17f878e0ce18b300"
        }
      ]
    }
  ]
}
