{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.1.6-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.6-b1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.1.6-b1.jar",
          "url": "core-ng-9.1.6-b1.jar",
          "size": 774624,
          "sha512": "0c6025d6c6d674f0e006bc4717653bfd1027ae553b30684b8f601246b14abd82eb6c1b533bbe3f47d656bf7aba7968a22d4fa9ab917bfd81e55a1263221a9215",
          "sha256": "d85268cdbedf6c62b1257382775d14dbea91c79b5f0544087d77566b771e84fc",
          "sha1": "38fa9b48eed8c5d805e2e1c47b207708f2243f4e",
          "md5": "df75245aa95851da9a75437839cb6892"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "okhttp",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.6-b1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.1.6-b1.jar",
          "url": "core-ng-9.1.6-b1.jar",
          "size": 774624,
          "sha512": "0c6025d6c6d674f0e006bc4717653bfd1027ae553b30684b8f601246b14abd82eb6c1b533bbe3f47d656bf7aba7968a22d4fa9ab917bfd81e55a1263221a9215",
          "sha256": "d85268cdbedf6c62b1257382775d14dbea91c79b5f0544087d77566b771e84fc",
          "sha1": "38fa9b48eed8c5d805e2e1c47b207708f2243f4e",
          "md5": "df75245aa95851da9a75437839cb6892"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.1.6-b1-sources.jar",
          "url": "core-ng-9.1.6-b1-sources.jar",
          "size": 395693,
          "sha512": "01041f2567b344f314e67f9d216aa66d65a9a0a249257d83f23c09b12d3650070de8971bc73e6294e40d0c9a59f99adc22cb89e8841ae3569cf41a1c448cab0e",
          "sha256": "bc0ca6659b59933f072e2a1eafdfa8bb3cd3616dd737c5c69c1871d9a72ca054",
          "sha1": "8d76c77c4634f8b6a4931817288a6a3b9ca75689",
          "md5": "332d5fd8b8f9d6c7ac5c9bf9ea2e399b"
        }
      ]
    }
  ]
}
