{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "9.1.2-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.2-b0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.1.2-b0.jar",
          "url": "core-ng-mongo-9.1.2-b0.jar",
          "size": 57159,
          "sha512": "1f8be0c37fd9c5f5c06147f3ca9df1f18cbb7084cfb8be5991f407a4d658e036ba92d6cd6abf2e3f2d6db863e68c9cd143bc26d3a36e653a51110ae6feacaa55",
          "sha256": "e8900ac35be9ac3612ce2161b3b3b3902b46faab869cf502ff96e8895ce84d5c",
          "sha1": "3d0748aad88600cb8d68bbcfaf5ee615e0ab8577",
          "md5": "605f602f5bc6b21c2f169d20ab632440"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.2-b0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.1.2-b0.jar",
          "url": "core-ng-mongo-9.1.2-b0.jar",
          "size": 57159,
          "sha512": "1f8be0c37fd9c5f5c06147f3ca9df1f18cbb7084cfb8be5991f407a4d658e036ba92d6cd6abf2e3f2d6db863e68c9cd143bc26d3a36e653a51110ae6feacaa55",
          "sha256": "e8900ac35be9ac3612ce2161b3b3b3902b46faab869cf502ff96e8895ce84d5c",
          "sha1": "3d0748aad88600cb8d68bbcfaf5ee615e0ab8577",
          "md5": "605f602f5bc6b21c2f169d20ab632440"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-9.1.2-b0-sources.jar",
          "url": "core-ng-mongo-9.1.2-b0-sources.jar",
          "size": 27016,
          "sha512": "70557bac833751751f7fc9b8fce6dae8fac5bf479a89151e4757b87f9d72a2bbb64453da9ab70f2a1834d417fa337ff5eb9d2ce118f8e9eddd9e2929ee04fb24",
          "sha256": "28b3d2d9d58a42338e80719b864bfee1341caccfd93764da2326f82eee14126c",
          "sha1": "e3466e2627e733dc3264793a62f14eb9a63919f2",
          "md5": "c527a80bd90b7a686657a34bdee27220"
        }
      ]
    }
  ]
}
