{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "9.1.1-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-9.1.1-b1.jar",
          "url": "core-ng-api-9.1.1-b1.jar",
          "size": 10994,
          "sha512": "73bb82e04981ea3d1ea3558bd84d50c11f9ab4075db909331dc0dea060f509ad27f6bfb715f5510771312a484a00eadcb0e2e7143954789eb4eebfbf57f2b52f",
          "sha256": "a8882a6d8eddc1da612dff263fc91dbe0390d873a95655478804f83176e9fe9f",
          "sha1": "d543e531a310e7a004da31c27845f9ca771b68db",
          "md5": "2a20674a936396c459e4d2914220b16f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.1.1-b1.jar",
          "url": "core-ng-api-9.1.1-b1.jar",
          "size": 10994,
          "sha512": "73bb82e04981ea3d1ea3558bd84d50c11f9ab4075db909331dc0dea060f509ad27f6bfb715f5510771312a484a00eadcb0e2e7143954789eb4eebfbf57f2b52f",
          "sha256": "a8882a6d8eddc1da612dff263fc91dbe0390d873a95655478804f83176e9fe9f",
          "sha1": "d543e531a310e7a004da31c27845f9ca771b68db",
          "md5": "2a20674a936396c459e4d2914220b16f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.1.1-b1-sources.jar",
          "url": "core-ng-api-9.1.1-b1-sources.jar",
          "size": 8644,
          "sha512": "0115a747d88e3765bb92c73dd6aaf31c3ae6f6c19e9245cf462432f2949dbfd50da4977e19a57377ef48de7bd70eb76ac723f02baa4a9c70b068d45e4dbfad4e",
          "sha256": "ba14931d6d7a7201ee2ed6ec661211131749c506871f8523d2ea41acf993cf7d",
          "sha1": "2d6e4f62b378f60b732ab4460e1d64a2aed5bab2",
          "md5": "074e784228bc4d9190e6465a0d4a5c76"
        }
      ]
    }
  ]
}
