{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.0.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.0.1.jar",
          "url": "core-ng-9.0.1.jar",
          "size": 738630,
          "sha512": "2400ba58060829d31a715a42e8b2da433a05ce3e472ddb1524d003d8d5cd057a64c10cd9851c85bf127c50cd2b2b0d205e99af66a6b527080ba50b150954071c",
          "sha256": "94a57633045afed94fda05ce2602cd48b4c0b4ca2e4829cb79b5e27e73d56881",
          "sha1": "191e1788b039ed6b50ab9d71b60c94d3eb0b56c6",
          "md5": "8849de92a992c823754704d5afad27ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.15.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.15.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.10.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "3.6.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.10.5"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.0.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.0.1.jar",
          "url": "core-ng-9.0.1.jar",
          "size": 738630,
          "sha512": "2400ba58060829d31a715a42e8b2da433a05ce3e472ddb1524d003d8d5cd057a64c10cd9851c85bf127c50cd2b2b0d205e99af66a6b527080ba50b150954071c",
          "sha256": "94a57633045afed94fda05ce2602cd48b4c0b4ca2e4829cb79b5e27e73d56881",
          "sha1": "191e1788b039ed6b50ab9d71b60c94d3eb0b56c6",
          "md5": "8849de92a992c823754704d5afad27ba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.0.1-sources.jar",
          "url": "core-ng-9.0.1-sources.jar",
          "size": 379637,
          "sha512": "ecde642be146000a8a72772a9c9e1b286aff38b7c5990883547a8b020e4b2d9c9cd2aca4f50486ad9494431bd15c6cfa40b25fd0c0f9636a4bdf205f67c6564e",
          "sha256": "c9d4456667f42761ebfd22186ed9c41bbb4b3d835f27d9727759ae4d152133a7",
          "sha1": "7f9dfbdd6d27dcc042642f48d1e88d5dbe889fec",
          "md5": "5aebea1a0c716ae0a82207c363b8b346"
        }
      ]
    }
  ]
}
