{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "8.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-8.1.6.jar",
          "url": "core-ng-search-test-8.1.6.jar",
          "size": 12674,
          "sha512": "fbf4d897e284fb523a483fcb3ebdd41ec0c8aed331a42221c8da6babe04b5feabc22612aa4d488aeb6a6763ba90ae31b6ce85c9f81df49ec1c46cec1202b51f9",
          "sha256": "71005fce764bae66c688222f3885c5aa682161698760039c8e3738480e81c77d",
          "sha1": "b4ba03b85beaaf089bffb60c164a8f7e2679bc60",
          "md5": "76d574df23f34c7eb690c3300a8a92b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "8.1.6"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "8.1.6"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "8.9.0"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "transport-netty4",
          "version": {
            "requires": "8.9.0"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "8.9.0"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "8.9.0"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "8.9.0"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "reindex",
          "version": {
            "requires": "8.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-8.1.6.jar",
          "url": "core-ng-search-test-8.1.6.jar",
          "size": 12674,
          "sha512": "fbf4d897e284fb523a483fcb3ebdd41ec0c8aed331a42221c8da6babe04b5feabc22612aa4d488aeb6a6763ba90ae31b6ce85c9f81df49ec1c46cec1202b51f9",
          "sha256": "71005fce764bae66c688222f3885c5aa682161698760039c8e3738480e81c77d",
          "sha1": "b4ba03b85beaaf089bffb60c164a8f7e2679bc60",
          "md5": "76d574df23f34c7eb690c3300a8a92b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-8.1.6-sources.jar",
          "url": "core-ng-search-test-8.1.6-sources.jar",
          "size": 7179,
          "sha512": "6c0c9e25bf0d1f603e8f087d3b113b9475dae21db46145872b4ae52bd1d1b231f0faf36fb8018779ac9b39d2e48e2dce9234bb31f4131ade1146e24aa607db90",
          "sha256": "381c8df034005281d0a13f386c63c974889fe2ac6f792055e02a29425b065f11",
          "sha1": "01e0b81130effb7ff3fe457b0edde57e20f79834",
          "md5": "6eaeb01038fd723bd0f5a8f52830dce4"
        }
      ]
    }
  ]
}
