{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "9.5.0-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.5.0-b0.jar",
          "url": "core-ng-mongo-test-9.5.0-b0.jar",
          "size": 2942,
          "sha512": "34401fc6b36e82e7199b3dc28454266c76da60fa3f3a9887e6f59be7d7d58be5b8c797aa77e7f568ea3f255fb5db2c56c892b5a7a26b698805b8041ace88284d",
          "sha256": "82bdc0ef62e3f5317aef7a5662e48a9f3755ce92952037c1e69642700a7bc730",
          "sha1": "ab5951caec3ae1151d4e24690a891a54e1dd481d",
          "md5": "23dd36f0f1c73d29e57ab487aa8aa690"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.5.0-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "9.5.0-b0"
          }
        },
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.47.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-9.5.0-b0.jar",
          "url": "core-ng-mongo-test-9.5.0-b0.jar",
          "size": 2942,
          "sha512": "34401fc6b36e82e7199b3dc28454266c76da60fa3f3a9887e6f59be7d7d58be5b8c797aa77e7f568ea3f255fb5db2c56c892b5a7a26b698805b8041ace88284d",
          "sha256": "82bdc0ef62e3f5317aef7a5662e48a9f3755ce92952037c1e69642700a7bc730",
          "sha1": "ab5951caec3ae1151d4e24690a891a54e1dd481d",
          "md5": "23dd36f0f1c73d29e57ab487aa8aa690"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.5.0-b0-sources.jar",
          "url": "core-ng-mongo-test-9.5.0-b0-sources.jar",
          "size": 2081,
          "sha512": "bbd8c18e8db1dc2f106eeed45e052f521ad5e0294ec15d4133e137bc1f28c38278a597f55a50187e0ac7db215e2250acc5e8d8ac6d39886c459bd38ee203b832",
          "sha256": "9761abe6b38e26793e6742f51c7397d725bfb556051fcf9bb8e05e497466edb1",
          "sha1": "70c94ced23316dece2cfa1a3a59a282135e7066d",
          "md5": "021ef9931affa31882f25064a8622e5a"
        }
      ]
    }
  ]
}
