{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "9.2.3-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.2.3-b0"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.18.1"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.2.3-b0.jar",
          "url": "core-ng-search-9.2.3-b0.jar",
          "size": 54196,
          "sha512": "bb959f6e3bb4816e73dcaead4a7f1ea0d034f9186db224b687f3808194a4546347a61e7d8f7905bb0e8d115febe90014066a5c0d188565e0f0a3390aa7637f57",
          "sha256": "101170a862b9c684559b95ee5f778aeaae822e11f2ff9be925894efd501ccf74",
          "sha1": "91851740340fc24e9e6a37d6fb708124e113cdbd",
          "md5": "c3f4d30b581d60f279b6b24e2347022c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.4"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.2.3-b0"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.18.1"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.2.3-b0.jar",
          "url": "core-ng-search-9.2.3-b0.jar",
          "size": 54196,
          "sha512": "bb959f6e3bb4816e73dcaead4a7f1ea0d034f9186db224b687f3808194a4546347a61e7d8f7905bb0e8d115febe90014066a5c0d188565e0f0a3390aa7637f57",
          "sha256": "101170a862b9c684559b95ee5f778aeaae822e11f2ff9be925894efd501ccf74",
          "sha1": "91851740340fc24e9e6a37d6fb708124e113cdbd",
          "md5": "c3f4d30b581d60f279b6b24e2347022c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-9.2.3-b0-sources.jar",
          "url": "core-ng-search-9.2.3-b0-sources.jar",
          "size": 22334,
          "sha512": "a897e0ec75c61fad0ccbfb2403f660be1a918e0391945ddaedab507181aab3755820615ef60847577e4b0fadacece7ce2e5a2c84549dc99a1b6393e63a22e5bd",
          "sha256": "53fd14fd74067c3a450b4d223699206b47ae59701929225ded1420c76dc197cf",
          "sha1": "e138eb3cd64656f454e572272fea1fa0a178ad7e",
          "md5": "aa86e8d13c94fc8ffb00a30da05aee25"
        }
      ]
    }
  ]
}
