{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "9.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.2.0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.2.0.jar",
          "url": "core-ng-mongo-9.2.0.jar",
          "size": 57986,
          "sha512": "0592b63481225313059bbf0df9e97fdfb13be1dbbdd8761c65d503eb083bb2608d2dad9a36ebae8d0507ff2d782db6c4a39d07683e85bf40502f25880cdf4b4a",
          "sha256": "7953f068e116dec99d1639c8e572ea88c1f8d4f44d6d9a31c86791030977d861",
          "sha1": "339293ab73765ec14e369faab821d043c970b444",
          "md5": "2b5df94d790340cd557e49e642225271"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.2.0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.2.0.jar",
          "url": "core-ng-mongo-9.2.0.jar",
          "size": 57986,
          "sha512": "0592b63481225313059bbf0df9e97fdfb13be1dbbdd8761c65d503eb083bb2608d2dad9a36ebae8d0507ff2d782db6c4a39d07683e85bf40502f25880cdf4b4a",
          "sha256": "7953f068e116dec99d1639c8e572ea88c1f8d4f44d6d9a31c86791030977d861",
          "sha1": "339293ab73765ec14e369faab821d043c970b444",
          "md5": "2b5df94d790340cd557e49e642225271"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-9.2.0-sources.jar",
          "url": "core-ng-mongo-9.2.0-sources.jar",
          "size": 27574,
          "sha512": "2644095f7dfd0e3ee1f66b6754fbbe228d83e51f151eea7e36a7f28d75d62c53f0637f7ab12b09bab34facf75c2b6e7317482ddd54cd5cab58dda89472f31741",
          "sha256": "288a69040f648cfb2dfdd1342cf4d60845d40e3001cbd55148e2dcc8ea18f123",
          "sha1": "c6a53745eada418d004e82a3edf4e5ef0c1d371c",
          "md5": "d9de35cc5793351437274bc57fc73a9d"
        }
      ]
    }
  ]
}
