{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "7.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "tiw26whr7vh43djrdosu3oi4rq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.4.6"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "7.4.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-7.4.6.jar",
          "url": "core-ng-mongo-test-7.4.6.jar",
          "size": 2413,
          "sha512": "dc2461f01d2da16ac068f743d895739524a52274fefbc4bcb488706c6ca7553b29e656b55bc449b4aad215f8c4048d8c9c1127ea45d1d2b98f9e8a5cf01a5885",
          "sha256": "8ece7c308adac10a7ceb18a8849b1b1c21c608867c4c4be328f7bfd5a30755a1",
          "sha1": "7ce3d526f79ecbe16d7565a6029cacfc3568190a",
          "md5": "c5011379e1083847898b516f694b0924"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.28.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.4.6"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "7.4.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-7.4.6.jar",
          "url": "core-ng-mongo-test-7.4.6.jar",
          "size": 2413,
          "sha512": "dc2461f01d2da16ac068f743d895739524a52274fefbc4bcb488706c6ca7553b29e656b55bc449b4aad215f8c4048d8c9c1127ea45d1d2b98f9e8a5cf01a5885",
          "sha256": "8ece7c308adac10a7ceb18a8849b1b1c21c608867c4c4be328f7bfd5a30755a1",
          "sha1": "7ce3d526f79ecbe16d7565a6029cacfc3568190a",
          "md5": "c5011379e1083847898b516f694b0924"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-7.4.6-sources.jar",
          "url": "core-ng-mongo-test-7.4.6-sources.jar",
          "size": 1750,
          "sha512": "91c9b438902e93e398e970a7b6d853800658ef346bd47061ee920b60138170d156a29fb8e49a7761c13830003ff8caaed6bb2872d879d80fb5f270583accdb7e",
          "sha256": "c3eb1d25fe8ffadc810508a1a8b1fc52037871398cfc28e8d4c13ba6ccad5b5e",
          "sha1": "9531d5228f5e6cd7f3034a7a68c0d96590348a45",
          "md5": "a1078f2b1dd64934d942622f6e725cfd"
        }
      ]
    }
  ]
}
