{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "9.3.0-b2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.3.0-b2.jar",
          "url": "core-ng-search-test-9.3.0-b2.jar",
          "size": 10070,
          "sha512": "4b5485712b8e72af84bc8b178031ff096b7b9c22fd78d0dc7f2ec7ac70c04a0463c8815ef285879b8180233e8e8f3e4556a3d5ca7301f87689f957a56e7a6914",
          "sha256": "e5d61b7bc8c18beaf4106cf0a0fec7f36bc0f6ea0dce14af63f98d11bb28a00e",
          "sha1": "7e9c3bbc7a442c4e99760e5e883baa9b6c6b6253",
          "md5": "927959915bdab7f6522c83eb8e0cf526"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.3.0-b2"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "9.3.0-b2"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "8.18.1"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "reindex",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-9.3.0-b2.jar",
          "url": "core-ng-search-test-9.3.0-b2.jar",
          "size": 10070,
          "sha512": "4b5485712b8e72af84bc8b178031ff096b7b9c22fd78d0dc7f2ec7ac70c04a0463c8815ef285879b8180233e8e8f3e4556a3d5ca7301f87689f957a56e7a6914",
          "sha256": "e5d61b7bc8c18beaf4106cf0a0fec7f36bc0f6ea0dce14af63f98d11bb28a00e",
          "sha1": "7e9c3bbc7a442c4e99760e5e883baa9b6c6b6253",
          "md5": "927959915bdab7f6522c83eb8e0cf526"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.3.0-b2-sources.jar",
          "url": "core-ng-search-test-9.3.0-b2-sources.jar",
          "size": 6285,
          "sha512": "502e38e54706540a806e68ed5c95d725024f7925d26ec933cbf826009327e85b06b4ec7313dab75fefbbfc445561bf6df01edaf107c3276340f69b329394a590",
          "sha256": "11b8bba8ae584e798388fe77b135367c4195d6eb1f2fafb6522751b30a4d6ab0",
          "sha1": "2aed284f1791ea1ec5ab1ce4cd3825251766abfc",
          "md5": "27beb95fbcfac5e4d9f96d3e5329c7b1"
        }
      ]
    }
  ]
}
