{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "7.6.2-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "5jfivrnadrg73pcyjgmirgtp24"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.2-b0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.6.2-b0.jar",
          "url": "core-ng-mongo-7.6.2-b0.jar",
          "size": 53973,
          "sha512": "179d27d2ee7150893416cbe29eb6eb8f4c6fec07aeb5e8f0ca644e88323064143fb1c4bd56eb07129c65a5481337e39714264fac437cc03fc22e28f23fbac2ce",
          "sha256": "a746304ddf72c9c6e6787dea38f4b55b9611c0fa605965bfd440b6719f81bee6",
          "sha1": "3a089b3a145f87219857e748eec6af667051ad00",
          "md5": "0eba0d6a1fa2af2cc5dc1dc88cc93c74"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.2-b0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.6.2-b0.jar",
          "url": "core-ng-mongo-7.6.2-b0.jar",
          "size": 53973,
          "sha512": "179d27d2ee7150893416cbe29eb6eb8f4c6fec07aeb5e8f0ca644e88323064143fb1c4bd56eb07129c65a5481337e39714264fac437cc03fc22e28f23fbac2ce",
          "sha256": "a746304ddf72c9c6e6787dea38f4b55b9611c0fa605965bfd440b6719f81bee6",
          "sha1": "3a089b3a145f87219857e748eec6af667051ad00",
          "md5": "0eba0d6a1fa2af2cc5dc1dc88cc93c74"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-7.6.2-b0-sources.jar",
          "url": "core-ng-mongo-7.6.2-b0-sources.jar",
          "size": 25339,
          "sha512": "014fcd297df7262b1a46b433e5eeb85cb50cc65a0ee23ffcb127628088217e143e325604e9f3cedbc6c0fa6d88e4ae0b5fed83a71eccfa0e19aa32fc21c0b84a",
          "sha256": "0276ba101451abb27718ed1e9279294a5bb6993ed16f4006c46565f283e52b60",
          "sha1": "5a391c46340d85380c00057642a14bf164cf1f6e",
          "md5": "a76346779245eeb39441c29374edac34"
        }
      ]
    }
  ]
}
