{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "7.6.5-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "ccyvjnb7orff5dpf6eczxv6e7a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.6.5-b1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.6.5-b1.jar",
          "url": "core-ng-7.6.5-b1.jar",
          "size": 673705,
          "sha512": "970aabcf6edd39f96e8143e2f40547c84e919d1545ce37330988c3f72127c0de01951e0641c1c7d6d193c89b227ca15bf9a46e9af21bd0910bd94c330e91cc8c",
          "sha256": "f2c588f6238e243ba7208f9ad5b1790244576de3ea012b306ecad710f559d92e",
          "sha1": "d1626ce2aa8e37c6a59a9ad5ecfa3fe01bcb9a63",
          "md5": "56b963e2e7fb413dbbbd1b6b09e04864"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.27.0-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.2.3.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.4.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.8.2"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.6.5-b1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.6.5-b1.jar",
          "url": "core-ng-7.6.5-b1.jar",
          "size": 673705,
          "sha512": "970aabcf6edd39f96e8143e2f40547c84e919d1545ce37330988c3f72127c0de01951e0641c1c7d6d193c89b227ca15bf9a46e9af21bd0910bd94c330e91cc8c",
          "sha256": "f2c588f6238e243ba7208f9ad5b1790244576de3ea012b306ecad710f559d92e",
          "sha1": "d1626ce2aa8e37c6a59a9ad5ecfa3fe01bcb9a63",
          "md5": "56b963e2e7fb413dbbbd1b6b09e04864"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-7.6.5-b1-sources.jar",
          "url": "core-ng-7.6.5-b1-sources.jar",
          "size": 344679,
          "sha512": "8b8988e234c7eabdb33538eb006a8cb92f04f1cef7e56c7579cba67968c59699a7d07fedc459b294ca1683846f9eb03e8d875607cc41e7f8a63361fc24895f30",
          "sha256": "250a4bcf09bb9cf248ba6f0cb419a6e50134681150961ee3dde8f91de43afe51",
          "sha1": "c107061f19d1dc49848be13358b80de21e9299dc",
          "md5": "8b0362ca82dcf721dfcd1fc41197f65e"
        }
      ]
    }
  ]
}
