{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "9.4.0-b2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-api-9.4.0-b2.jar",
          "url": "core-ng-api-9.4.0-b2.jar",
          "size": 11021,
          "sha512": "85079d754ebdbfb21ce14a6ebc828d179aa57c685cdb43dafeb564ea36c72141ed021ea73b17846b801ed86bbe1838b8d635eb5a62c7565453a89b06412a4183",
          "sha256": "43a0d624464eb235e8cf69095c1dcff545d2a46f951e7d781cf89892bb2e96a1",
          "sha1": "efabc2133d6ad14deb6ae083ccded006b60813c3",
          "md5": "801e38cce416241ed7eaa93dce740daf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-api-9.4.0-b2.jar",
          "url": "core-ng-api-9.4.0-b2.jar",
          "size": 11021,
          "sha512": "85079d754ebdbfb21ce14a6ebc828d179aa57c685cdb43dafeb564ea36c72141ed021ea73b17846b801ed86bbe1838b8d635eb5a62c7565453a89b06412a4183",
          "sha256": "43a0d624464eb235e8cf69095c1dcff545d2a46f951e7d781cf89892bb2e96a1",
          "sha1": "efabc2133d6ad14deb6ae083ccded006b60813c3",
          "md5": "801e38cce416241ed7eaa93dce740daf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.4.0-b2-sources.jar",
          "url": "core-ng-api-9.4.0-b2-sources.jar",
          "size": 8666,
          "sha512": "7d539aaf3daafd16091e874c364c0199c8ee298034be69c97004c575bf4c9119e812b777e7de1f4f4f860e1064537d9fc20926efc3f470f82bcd51a4a90d2cc7",
          "sha256": "de2bc12f94ea0db1ea00484345ef62744f039e03a1b145f19d158ed9ca0f798a",
          "sha1": "50c07e8c352c5ccca5176b71db1fb353e5fa5332",
          "md5": "18222cb8bf2ae25b68499ad57c0ebc40"
        }
      ]
    }
  ]
}
