{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.1.0-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.0-b1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.1.0-b1.jar",
          "url": "core-ng-9.1.0-b1.jar",
          "size": 765827,
          "sha512": "b7cda9f2f793c44d4b860d443844475fa7518e435cdd16dc1fe23f3e6647973148488eb4dd634df5b7fc3561c37bca784d93fec3b7316d5af868430d849d0ece",
          "sha256": "a4066a3d0b6f29ef8384ba7dd6485ac2aabb4ee8a7d14f103a3d91eee0ddf1c9",
          "sha1": "df2a66bee1bd9ae8d986149149d6dc2d11b8e606",
          "md5": "a0995eda7f26159ed61f52138ef9befb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "okhttp",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.10.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "3.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.10.5"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.0-b1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.1.0-b1.jar",
          "url": "core-ng-9.1.0-b1.jar",
          "size": 765827,
          "sha512": "b7cda9f2f793c44d4b860d443844475fa7518e435cdd16dc1fe23f3e6647973148488eb4dd634df5b7fc3561c37bca784d93fec3b7316d5af868430d849d0ece",
          "sha256": "a4066a3d0b6f29ef8384ba7dd6485ac2aabb4ee8a7d14f103a3d91eee0ddf1c9",
          "sha1": "df2a66bee1bd9ae8d986149149d6dc2d11b8e606",
          "md5": "a0995eda7f26159ed61f52138ef9befb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.1.0-b1-sources.jar",
          "url": "core-ng-9.1.0-b1-sources.jar",
          "size": 391741,
          "sha512": "8d3f9465faa41178513e6a7de8702dc3a2d4e57da28e25ff6f294377f4392b1197c91347c66ff52113344a90a6482a32d366f4375f891c8a3724ff7f565e8e30",
          "sha256": "b1b9b171125bf3a5269cddb68ea90e35832a5745a6074d10423fc35fbe95dab2",
          "sha1": "c4c944ae49814a8e53aaf648f617045eae7377cc",
          "md5": "ba126102b74b5d960d5e859a45e44430"
        }
      ]
    }
  ]
}
