{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "7.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.7.3"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.7.3.jar",
          "url": "core-ng-mongo-7.7.3.jar",
          "size": 53970,
          "sha512": "69419b4114b1e56567410d910bcb6ca2cd18cf5c0f22de82f048510edf5fa20943e2097761fc237cb8af3f0b4b0b001b24b48346d10f05903407e10c407e0aa6",
          "sha256": "c797734b934d4dcee1e3f5c99e2bf8b225154873599c7781f1a5c866297effd5",
          "sha1": "05c9f1b5c3934a64effbfa5fc3b6cc78bcceab05",
          "md5": "f0f2d944b1cfd65b306e5c45247a0332"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.7.3"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.7.3.jar",
          "url": "core-ng-mongo-7.7.3.jar",
          "size": 53970,
          "sha512": "69419b4114b1e56567410d910bcb6ca2cd18cf5c0f22de82f048510edf5fa20943e2097761fc237cb8af3f0b4b0b001b24b48346d10f05903407e10c407e0aa6",
          "sha256": "c797734b934d4dcee1e3f5c99e2bf8b225154873599c7781f1a5c866297effd5",
          "sha1": "05c9f1b5c3934a64effbfa5fc3b6cc78bcceab05",
          "md5": "f0f2d944b1cfd65b306e5c45247a0332"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-7.7.3-sources.jar",
          "url": "core-ng-mongo-7.7.3-sources.jar",
          "size": 25323,
          "sha512": "a52a6e9252e166c3ba695010c281087bf0ec27f7ffde812a2f7aaa958c9b41307adfa798fd87b657df38e973aebb95d62391598ef8f7ed1983c88c4bcf7e8f68",
          "sha256": "d4997fc47abcf98c66a5f94a325aad01441648a6085604b71b9d8049924d0f82",
          "sha1": "5d41e5442317a05105a598dd62d9700c7f7309d3",
          "md5": "ae72451d4aca968a66176af6d355df41"
        }
      ]
    }
  ]
}
