{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "9.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.12.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.2.2.jar",
          "url": "core-ng-test-9.2.2.jar",
          "size": 47345,
          "sha512": "a8da6853b3ed16cee8e86563455b8b5c6ae31f0c6b860d0305faaaafa25cfcc56d1ae24478be2b07ac5484fd93b33aa51e5b52c6a72a1c4316c4c6c2abe17566",
          "sha256": "eb594bf5c8206dc8cc20abc085b29506bdf930677240f77069635085156abf3a",
          "sha1": "0a2d02f74c06a62b2f860d928fbfafd27887d932",
          "md5": "96fcadc9d623ca0c1c61c3990c9f205f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.2.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.12.2"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.12.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.2.2.jar",
          "url": "core-ng-test-9.2.2.jar",
          "size": 47345,
          "sha512": "a8da6853b3ed16cee8e86563455b8b5c6ae31f0c6b860d0305faaaafa25cfcc56d1ae24478be2b07ac5484fd93b33aa51e5b52c6a72a1c4316c4c6c2abe17566",
          "sha256": "eb594bf5c8206dc8cc20abc085b29506bdf930677240f77069635085156abf3a",
          "sha1": "0a2d02f74c06a62b2f860d928fbfafd27887d932",
          "md5": "96fcadc9d623ca0c1c61c3990c9f205f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-9.2.2-sources.jar",
          "url": "core-ng-test-9.2.2-sources.jar",
          "size": 22572,
          "sha512": "c3384e696ce8b310dc720bb7cc62431bb4c194ea10df10db620afc335ae2fab4fa39e222da2ea08805d4218ead59f6ba5e6c89999f1323205e7704aa9711da91",
          "sha256": "d287ff00017cfb41233b0be4357af3e93dd5b735d424aaa14905582fa0e31024",
          "sha1": "a04f9eec82f543b4f2f90ba53e2f80c0d333b235",
          "md5": "d153f88687b040250bf6f514c3cee120"
        }
      ]
    }
  ]
}
