{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "7.4.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "ulgfwrzehzgwtop2m46msbzdtu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-7.4.1.1.jar",
          "url": "core-ng-api-7.4.1.1.jar",
          "size": 10872,
          "sha512": "5f6fc0f98102b4b002366bf607586a76ffebc915ac5f3dbfda8d5261d0e632b101a8dfd388562ac59aacb55a911da0b842f44fc4446873e21a4ad55296321e91",
          "sha256": "3c9bfc5afc2a81aeaa1d29cd0ed99e07b779275d84cc19eada46b081d0e1a59b",
          "sha1": "9673506c0dc41f555893cb0e7de58136f1f00478",
          "md5": "5046dea2ecaa17090179423b5fe54e1a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.4.1.1.jar",
          "url": "core-ng-api-7.4.1.1.jar",
          "size": 10872,
          "sha512": "5f6fc0f98102b4b002366bf607586a76ffebc915ac5f3dbfda8d5261d0e632b101a8dfd388562ac59aacb55a911da0b842f44fc4446873e21a4ad55296321e91",
          "sha256": "3c9bfc5afc2a81aeaa1d29cd0ed99e07b779275d84cc19eada46b081d0e1a59b",
          "sha1": "9673506c0dc41f555893cb0e7de58136f1f00478",
          "md5": "5046dea2ecaa17090179423b5fe54e1a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.4.1.1-sources.jar",
          "url": "core-ng-api-7.4.1.1-sources.jar",
          "size": 8541,
          "sha512": "a5b03db71a2cc85d176504b00690fe2bf6981befcf92cc691ee7998bd78486b6189da09104fa6c1bae851f0c3f4062599e9284d02ec22f978adec0e0b14dedb2",
          "sha256": "f18fd60d053b4ae039c8061baa53af767230b6ac3a809d89a5fdd1e99344269a",
          "sha1": "8068f118ebd55fd11ff9e3c59c447c75cfd7dfd7",
          "md5": "648ca08648afe2f27adfb8b68c9bce10"
        }
      ]
    }
  ]
}
