{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "7.4.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "3mlsin3fvvb55bqty7rjpsuugu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-7.4.1.1.jar",
          "url": "core-ng-api-7.4.1.1.jar",
          "size": 10872,
          "sha512": "90c5d9bce0b3eb8f5969a119fa4faae2145d6a37566b0164692ad2119417d64b3a639da3baf373eb5057c44521c26f0c5a38219bc194a11c67eb3c98df20337b",
          "sha256": "3a87d99e03bf5ba8f4b5652944fa0e77ad8e2b134d78d001aa8fe8f97a855c41",
          "sha1": "e86137ba0c61b06effc682a1113f9e03dd1d776f",
          "md5": "f1bd7b252c645cf41866b72cb1857977"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.4.1.1.jar",
          "url": "core-ng-api-7.4.1.1.jar",
          "size": 10872,
          "sha512": "90c5d9bce0b3eb8f5969a119fa4faae2145d6a37566b0164692ad2119417d64b3a639da3baf373eb5057c44521c26f0c5a38219bc194a11c67eb3c98df20337b",
          "sha256": "3a87d99e03bf5ba8f4b5652944fa0e77ad8e2b134d78d001aa8fe8f97a855c41",
          "sha1": "e86137ba0c61b06effc682a1113f9e03dd1d776f",
          "md5": "f1bd7b252c645cf41866b72cb1857977"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.4.1.1-sources.jar",
          "url": "core-ng-api-7.4.1.1-sources.jar",
          "size": 8542,
          "sha512": "bc3c369666ca63d5882748130a9b040b02631b306bd171945dcc0041f4e97b00f5a0204fb20ba71325dd7966c69e15aa4c2d85c6cfcc8fb1d71f6bd6008905e2",
          "sha256": "fafadec65a153449bdcc2bfe5d1ee7188c6244b3051ed8ecc5e1cb4ebbdb23b7",
          "sha1": "8a9c4c411114ff7afa330f19a7fec3790066c565",
          "md5": "7e9faaf2469b2fbdad9487379a20c150"
        }
      ]
    }
  ]
}
