{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "7.6.5-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "ccyvjnb7orff5dpf6eczxv6e7a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.6.5-b1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.6.5-b1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.6.5-b1.jar",
          "url": "core-ng-search-test-7.6.5-b1.jar",
          "size": 9068,
          "sha512": "b21fdb4ce65e3f31f3a2e1f47e76e800c1a548422173554e292a540c42a964818666668b3b15d2f6785cebfde4d6eccec52287ce422b1a0212ac69fb7c85589b",
          "sha256": "263c729e5305593bf9b0ab913e6ed8fef3b74c992c76a2c0511cf663199e2330",
          "sha1": "7f2125777a05588fb65fdd99c4d1714d52d75734",
          "md5": "30444a3b37feca1fad22b25a89e24e8c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4-client",
          "version": {
            "requires": "7.10.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "reindex-client",
          "version": {
            "requires": "7.10.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "7.10.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "7.10.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "7.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.6.5-b1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.6.5-b1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.6.5-b1.jar",
          "url": "core-ng-search-test-7.6.5-b1.jar",
          "size": 9068,
          "sha512": "b21fdb4ce65e3f31f3a2e1f47e76e800c1a548422173554e292a540c42a964818666668b3b15d2f6785cebfde4d6eccec52287ce422b1a0212ac69fb7c85589b",
          "sha256": "263c729e5305593bf9b0ab913e6ed8fef3b74c992c76a2c0511cf663199e2330",
          "sha1": "7f2125777a05588fb65fdd99c4d1714d52d75734",
          "md5": "30444a3b37feca1fad22b25a89e24e8c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.6.5-b1-sources.jar",
          "url": "core-ng-search-test-7.6.5-b1-sources.jar",
          "size": 5479,
          "sha512": "bb93a5a48132b664fd6e2ae53f9eb9228b260525436453d939a5e5133b49769d34c314869d4bbebb19c9a2e62d02af98897e3169ad226ae084f787cf376fc26a",
          "sha256": "b521eab42b4e4233d45d2c7b859d2d04208d83575f88c13fa8f7430fcbe01267",
          "sha1": "549fa28e90168fc80eea2dfa83c91f302aa4c3a2",
          "md5": "5fe577341380799b3fbd78b881c83932"
        }
      ]
    }
  ]
}
