{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "7.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6",
      "buildId": "uvsmukcbuffqlned52vqbxkbzu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.5.6"
          }
        },
        {
          "group": "org.elasticsearch.client",
          "module": "elasticsearch-rest-high-level-client",
          "version": {
            "requires": "7.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.5.6.jar",
          "url": "core-ng-search-7.5.6.jar",
          "size": 38326,
          "sha512": "8dc126e14e7e07a9e498fe073769f928af13f7f7878bd86808ca97729f74d3f97a18d8a9f517741db84f0d5872eae46aa85905b7eb64387c795fdcbb456b47be",
          "sha256": "092b6e03b7adfbf1fae8ecfbde5dab8a049fa0b4189d7c6df0e85f9e79aa5270",
          "sha1": "e7485541f04a8e744b835c3f8cd2dbbb53ef86c9",
          "md5": "868055daa82116038dfe772acf4b1acd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.5.6"
          }
        },
        {
          "group": "org.elasticsearch.client",
          "module": "elasticsearch-rest-high-level-client",
          "version": {
            "requires": "7.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.5.6.jar",
          "url": "core-ng-search-7.5.6.jar",
          "size": 38326,
          "sha512": "8dc126e14e7e07a9e498fe073769f928af13f7f7878bd86808ca97729f74d3f97a18d8a9f517741db84f0d5872eae46aa85905b7eb64387c795fdcbb456b47be",
          "sha256": "092b6e03b7adfbf1fae8ecfbde5dab8a049fa0b4189d7c6df0e85f9e79aa5270",
          "sha1": "e7485541f04a8e744b835c3f8cd2dbbb53ef86c9",
          "md5": "868055daa82116038dfe772acf4b1acd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-7.5.6-sources.jar",
          "url": "core-ng-search-7.5.6-sources.jar",
          "size": 17108,
          "sha512": "b310e0e6c33ba4d87471266bce92fcd837eba40815cd2cac49de709e4b4b03979d9ed585a62dc63d1e47c7c76494bb33b371ae7298aa3e089b69a0e1cf7685db",
          "sha256": "5e4740096a47dad91636d67a0384a7d2ec30896e9ba0ca12eaf3fad9285cd8c0",
          "sha1": "1128712db88631042c4c658b00a10124fbcc237b",
          "md5": "eb09b55d99d09de3b532fc1d3b4e0e0f"
        }
      ]
    }
  ]
}
