{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "7.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6",
      "buildId": "jdhsmwlbjvg6foywe56zxxdxk4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.5.6"
          }
        },
        {
          "group": "org.elasticsearch.client",
          "module": "elasticsearch-rest-high-level-client",
          "version": {
            "requires": "7.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.5.6.jar",
          "url": "core-ng-search-7.5.6.jar",
          "size": 38326,
          "sha512": "08f0a51d03ddae859101fc0e8a4526de300d68725010c02dd2d8819e6e4dd2c4eb640c8169227178b4c467cbcedc556447fde47100368bbe827df4f31b4c7064",
          "sha256": "a01d9fe790f75d4204ada72855eeb8d1b804566acd89c93c4fd7dbfe1fcfc6a6",
          "sha1": "f746fb9adfd394b9a54333819e6b3b869afff716",
          "md5": "0e16cc07822dc44ed42df9c28edae82f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.5.6"
          }
        },
        {
          "group": "org.elasticsearch.client",
          "module": "elasticsearch-rest-high-level-client",
          "version": {
            "requires": "7.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.5.6.jar",
          "url": "core-ng-search-7.5.6.jar",
          "size": 38326,
          "sha512": "08f0a51d03ddae859101fc0e8a4526de300d68725010c02dd2d8819e6e4dd2c4eb640c8169227178b4c467cbcedc556447fde47100368bbe827df4f31b4c7064",
          "sha256": "a01d9fe790f75d4204ada72855eeb8d1b804566acd89c93c4fd7dbfe1fcfc6a6",
          "sha1": "f746fb9adfd394b9a54333819e6b3b869afff716",
          "md5": "0e16cc07822dc44ed42df9c28edae82f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-7.5.6-sources.jar",
          "url": "core-ng-search-7.5.6-sources.jar",
          "size": 17108,
          "sha512": "227b5eea2f913c30543ae7bec34c9a7e20fd3735f10204070041f55954cff6f411aa39574a1fa6b50768e3429627c2f4594118945887bb2bf23b2ba7c6f98304",
          "sha256": "86fb0d2067d67e888b04401e1cd2cf49d05663d55ae7dd20f41f9da46c341989",
          "sha1": "6c700ec63cc6166e77b10662266851fc7e81f081",
          "md5": "b0ae8afe7f6639624085a5526851827d"
        }
      ]
    }
  ]
}
