{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "9.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.12.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.2.0.jar",
          "url": "core-ng-test-9.2.0.jar",
          "size": 47315,
          "sha512": "bcbd3ca67bd2cf2f50b46619db40f4fc843d99483da4361088e4428e5305822f6aa322cfbddeac242eb491e61abc88ca434486d678f570b7284581980c261faa",
          "sha256": "202e73090f30d75be7edc1b074eb340739f54d28da0d907713a73580baf78c0a",
          "sha1": "da9255d415991c3e71d96122509d4b21ed82baaa",
          "md5": "bd9148bb4a87ea1385fbfcaffe0d6587"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.2.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.12.2"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.12.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.2.0.jar",
          "url": "core-ng-test-9.2.0.jar",
          "size": 47315,
          "sha512": "bcbd3ca67bd2cf2f50b46619db40f4fc843d99483da4361088e4428e5305822f6aa322cfbddeac242eb491e61abc88ca434486d678f570b7284581980c261faa",
          "sha256": "202e73090f30d75be7edc1b074eb340739f54d28da0d907713a73580baf78c0a",
          "sha1": "da9255d415991c3e71d96122509d4b21ed82baaa",
          "md5": "bd9148bb4a87ea1385fbfcaffe0d6587"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-9.2.0-sources.jar",
          "url": "core-ng-test-9.2.0-sources.jar",
          "size": 22552,
          "sha512": "e9ee247499bab341ef206452e55ab5afd385788f379a9f6f3188ac9ee6c55ca47b87fdccf8bbaf2c1687ab65a39a1e011bc336806797f9c6b3080346b946f86d",
          "sha256": "2bf8eab286c44e4565f9648253f535b0a1773f6309d435094bfeb930c08dfdd6",
          "sha1": "6003e3537df8c95b256037c88e361e2369201dd6",
          "md5": "1dc6acf38bc4868beefba4b1c186ebc1"
        }
      ]
    }
  ]
}
