{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "9.1.1-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.1.1-b1.jar",
          "url": "core-ng-search-test-9.1.1-b1.jar",
          "size": 13229,
          "sha512": "e51ca7d28899242875d957c060fddc5a92b5b876727bccfb7d62c9295a9fffca425434fae1c8b8b57e77d698289f136e1b277c7747fb7ec979309c3232b603d8",
          "sha256": "d75bb3700f1913ededd21899a8876643103caee0adf92d15343c8283aae0bba6",
          "sha1": "b1390706b5a180647f7ca98ddf84026b76d91f60",
          "md5": "959dd9f3a85b572ebf9cd5ef7455fd8e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.1.1-b1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "9.1.1-b1"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "8.14.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4",
          "version": {
            "requires": "8.14.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "8.14.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "8.14.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "8.14.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "reindex",
          "version": {
            "requires": "8.14.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "reindex",
              "type": "jar",
              "extension": "jar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-9.1.1-b1.jar",
          "url": "core-ng-search-test-9.1.1-b1.jar",
          "size": 13229,
          "sha512": "e51ca7d28899242875d957c060fddc5a92b5b876727bccfb7d62c9295a9fffca425434fae1c8b8b57e77d698289f136e1b277c7747fb7ec979309c3232b603d8",
          "sha256": "d75bb3700f1913ededd21899a8876643103caee0adf92d15343c8283aae0bba6",
          "sha1": "b1390706b5a180647f7ca98ddf84026b76d91f60",
          "md5": "959dd9f3a85b572ebf9cd5ef7455fd8e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.1.1-b1-sources.jar",
          "url": "core-ng-search-test-9.1.1-b1-sources.jar",
          "size": 7235,
          "sha512": "819eec286d57f8efe7c7767c5f8289eae2f80b24bb27aedcd62a69236297adfac2a2cf7fcf76dbb524d089d3555c6480512a46b789eb633bd6bdfeab8dfd6ac7",
          "sha256": "84b9083c1bde19e802c2a37826bb43385d3f39b14fa497699090191ee3acb25c",
          "sha1": "9882db53bb34e4af687f9338220d3fecc1839c46",
          "md5": "5705b12ba77083997a5f1aeed08c44d7"
        }
      ]
    }
  ]
}
