{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "9.1.1-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.1.1-b1.jar",
          "url": "core-ng-search-test-9.1.1-b1.jar",
          "size": 13229,
          "sha512": "e1981f87646c4a73dc725ee4d26b09af2cf6b3e4113622ebd928c3661d87a0a3bb66a18cae257798752a0b2572557d046b8d175b5e1b752bfc249b5ef9460127",
          "sha256": "9b3d9d27879e46828b1292ccbad98b8df702bcf0beb0aefd15c4a1199b83b6d2",
          "sha1": "9c160b5a137a2a70e342a58614e064963d10bc4b",
          "md5": "064478f7b92502e9513052f503793a44"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.1.1-b1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "9.1.1-b1"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "8.14.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4",
          "version": {
            "requires": "8.14.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "8.14.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "8.14.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "8.14.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "reindex",
          "version": {
            "requires": "8.14.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "reindex",
              "type": "jar",
              "extension": "jar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-9.1.1-b1.jar",
          "url": "core-ng-search-test-9.1.1-b1.jar",
          "size": 13229,
          "sha512": "e1981f87646c4a73dc725ee4d26b09af2cf6b3e4113622ebd928c3661d87a0a3bb66a18cae257798752a0b2572557d046b8d175b5e1b752bfc249b5ef9460127",
          "sha256": "9b3d9d27879e46828b1292ccbad98b8df702bcf0beb0aefd15c4a1199b83b6d2",
          "sha1": "9c160b5a137a2a70e342a58614e064963d10bc4b",
          "md5": "064478f7b92502e9513052f503793a44"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.1.1-b1-sources.jar",
          "url": "core-ng-search-test-9.1.1-b1-sources.jar",
          "size": 7235,
          "sha512": "c9d8b1dda17d67dc89673c79b317847bbf37b55a0cc112f29accabea70774b697d3858e251f0100dd479a4c2ae49984878053826e455493cdfd82aacc50d599e",
          "sha256": "34de8ccb5e70fa5e6e6d36d1abbe7fce3b848cab28207b4916f7d8ccef5e9816",
          "sha1": "88a21ff12f31257c3924ee40a0a699ed4ded5440",
          "md5": "a045f4234d5de801fd6fe879dc1cabd7"
        }
      ]
    }
  ]
}
