{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "9.4.0-b4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.20.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.4.0-b4.jar",
          "url": "core-ng-test-9.4.0-b4.jar",
          "size": 50955,
          "sha512": "98f05946baf9996a5b491d5f17a6238fe2f969fb8b6028ed246e349bc7862d95e3cf954289146ac1b25f87240bc0707c8bf07864007e503820090aab0da630c2",
          "sha256": "909f2489c230484526147797711179ca1f2b47cf6278740399353f5b0728a34d",
          "sha1": "10d130a57359edcfcfd7d18b800396d93eb9d9d1",
          "md5": "fbb8b79f33b14e31d00cca657c316a49"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.4.0-b4"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.20.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.4.0-b4.jar",
          "url": "core-ng-test-9.4.0-b4.jar",
          "size": 50955,
          "sha512": "98f05946baf9996a5b491d5f17a6238fe2f969fb8b6028ed246e349bc7862d95e3cf954289146ac1b25f87240bc0707c8bf07864007e503820090aab0da630c2",
          "sha256": "909f2489c230484526147797711179ca1f2b47cf6278740399353f5b0728a34d",
          "sha1": "10d130a57359edcfcfd7d18b800396d93eb9d9d1",
          "md5": "fbb8b79f33b14e31d00cca657c316a49"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-9.4.0-b4-sources.jar",
          "url": "core-ng-test-9.4.0-b4-sources.jar",
          "size": 25058,
          "sha512": "11b4bdf5745fc9e472f2418f93f9f14ae5549b1a649d05b4993352e54ebadc800dd2d60e417fa358e73d38a28bff3b5dee10ced5d8bff191bc0a1efed88f31f5",
          "sha256": "d5c8ee20d03b37820acb81659b902a3acc0dbd1edbc7f46e06f152433d3e24cd",
          "sha1": "5f2377b1f4c84c1ac843064b0c0ba2d839d848ae",
          "md5": "ece7ff8e94d133ffadabc8ec6f723db0"
        }
      ]
    }
  ]
}
