{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "7.6.4-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "d4bpwwgkvbhk5k3pu7mvcd3od4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.4-b0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.6.4-b0.jar",
          "url": "core-ng-test-7.6.4-b0.jar",
          "size": 39070,
          "sha512": "c765a96a6eb0217a02722095498ddfc3fc73cc5d56e04a4b47a87a4833e4552f76cd13faf2ebbe659fa55e197d22c7e464dc61775812c0577485fed94586ffe5",
          "sha256": "edbc8b9af605b2831b18be653ae996363662f5b4c6b387e0407681d6b84e452e",
          "sha1": "e0c22b627adb51c1fe9c8202b68a22c9943b093b",
          "md5": "b4e7e539cd52c4a8aac6a8dfe02d8f4f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.4.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.4-b0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.6.4-b0.jar",
          "url": "core-ng-test-7.6.4-b0.jar",
          "size": 39070,
          "sha512": "c765a96a6eb0217a02722095498ddfc3fc73cc5d56e04a4b47a87a4833e4552f76cd13faf2ebbe659fa55e197d22c7e464dc61775812c0577485fed94586ffe5",
          "sha256": "edbc8b9af605b2831b18be653ae996363662f5b4c6b387e0407681d6b84e452e",
          "sha1": "e0c22b627adb51c1fe9c8202b68a22c9943b093b",
          "md5": "b4e7e539cd52c4a8aac6a8dfe02d8f4f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-7.6.4-b0-sources.jar",
          "url": "core-ng-test-7.6.4-b0-sources.jar",
          "size": 19186,
          "sha512": "339c1a86e275dbf0aff504472def2ef488ac7d05bbaf80becd45834c06ade8dbea24c42e41d0fb7a554fe2f9b3bb11119cb623f69fd053e176a7a914e8116931",
          "sha256": "d3117b28fc1c4a599ab60610dc61abc7cef049e5d40cdb723b18973ad279e649",
          "sha1": "84595efa5a4d0e4f6442b108ad9a7a2e23c06446",
          "md5": "8174bab7a4ef27834674bad76ca13cce"
        }
      ]
    }
  ]
}
