{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "9.1.6-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.11.3"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.14.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.26.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.1.6-b1.jar",
          "url": "core-ng-test-9.1.6-b1.jar",
          "size": 47330,
          "sha512": "f9e9b3f4b0f963e59c96b6c0fb87997fc02b93323b096b8ae763f0cc7307ac09fa1f1533e3642b612e0a72f9c98a95bdf1e7e906c0721e5c6808466631c15144",
          "sha256": "5f966980e6e620a1b2752c8eac9dd01fd9ba01e83a26eea7080985e4c6948804",
          "sha1": "4cd54b67f3aa97e81b3552f549cfa91c4f91e90f",
          "md5": "5c8ce833b527f1598d4bc250b15f46c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.6-b1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.11.3"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.11.3"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.14.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.26.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.1.6-b1.jar",
          "url": "core-ng-test-9.1.6-b1.jar",
          "size": 47330,
          "sha512": "f9e9b3f4b0f963e59c96b6c0fb87997fc02b93323b096b8ae763f0cc7307ac09fa1f1533e3642b612e0a72f9c98a95bdf1e7e906c0721e5c6808466631c15144",
          "sha256": "5f966980e6e620a1b2752c8eac9dd01fd9ba01e83a26eea7080985e4c6948804",
          "sha1": "4cd54b67f3aa97e81b3552f549cfa91c4f91e90f",
          "md5": "5c8ce833b527f1598d4bc250b15f46c9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-9.1.6-b1-sources.jar",
          "url": "core-ng-test-9.1.6-b1-sources.jar",
          "size": 22554,
          "sha512": "50a31c77d25fc2d3cda9ced185dea78c8e71c883fe73a847e8ffabde9e4bc73ab2940531bafc9b08ba53da859ae654ea5fca24573f660b0b3a93d1dfa6a2337b",
          "sha256": "0aa5549185b2fc611a4d3d34bc800de29c5313f0553502ed74237817f5050154",
          "sha1": "0fb8ef2190d8dd20c09914652d6935a08d87d622",
          "md5": "e5536e686f1de59346dfbf5e0597e4e2"
        }
      ]
    }
  ]
}
