{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "9.1.7-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.1.7-b1.jar",
          "url": "core-ng-search-test-9.1.7-b1.jar",
          "size": 13291,
          "sha512": "11db7f27c85944a852b7d21f01e17a92c30bf69d0c4a4351c3ac142eca86009814e26657a4773bebf7f30e1bb2b8b0d7faacb979d6015ab3dcf512c8eac2ad00",
          "sha256": "3c71aa0bec6b40c44b4ee6ee362d58b614b2cfa538a3469b6ae1ce52cf01fc83",
          "sha1": "1ebca580e3bb4da80629ea95c127bfc48d7e0bcd",
          "md5": "3d8b073a0aef73768f814ea64bf5c0dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.1.7-b1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "9.1.7-b1"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "8.15.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4",
          "version": {
            "requires": "8.15.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "8.15.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "8.15.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "8.15.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "reindex",
          "version": {
            "requires": "8.15.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "reindex",
              "type": "jar",
              "extension": "jar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-9.1.7-b1.jar",
          "url": "core-ng-search-test-9.1.7-b1.jar",
          "size": 13291,
          "sha512": "11db7f27c85944a852b7d21f01e17a92c30bf69d0c4a4351c3ac142eca86009814e26657a4773bebf7f30e1bb2b8b0d7faacb979d6015ab3dcf512c8eac2ad00",
          "sha256": "3c71aa0bec6b40c44b4ee6ee362d58b614b2cfa538a3469b6ae1ce52cf01fc83",
          "sha1": "1ebca580e3bb4da80629ea95c127bfc48d7e0bcd",
          "md5": "3d8b073a0aef73768f814ea64bf5c0dc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.1.7-b1-sources.jar",
          "url": "core-ng-search-test-9.1.7-b1-sources.jar",
          "size": 7351,
          "sha512": "4ec4c86202201184fd5502e02c28dd994910c9c245adce7af227acf06802564ba52a2909c2142943065425cb5713212873636e17a0df5ed4912b0bea0ec9f429",
          "sha256": "e63aba4431668ba8a8090c7af79c34c83f33245c5506a0e4230cd556a9b2ec3f",
          "sha1": "83538329bfe35033b8355a79b85a90db32d3f24f",
          "md5": "ba9d3310beb717a6a55db3a2f6fb1451"
        }
      ]
    }
  ]
}
