{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "9.5.1-b4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.5.1-b4"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.5.1-b4.jar",
          "url": "core-ng-mongo-9.5.1-b4.jar",
          "size": 60080,
          "sha512": "efc495ae67b702fe62485e782237eea49916d35eba5bdaa1278266135108d4314064390d2e3bf9c3a68f0bae1c87ad97ba8ed1ba4a9dc81c212c1aec68ec1353",
          "sha256": "96652d194a4b233c2bede362b6787715e0fb5967411f7d0b5ce2c86cae24fd18",
          "sha1": "aef3ab80bb18158788645f600f13deaccba63b7e",
          "md5": "0ce92717bb92fe2f82137dc8b14d2e44"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.5.1-b4"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.5.1-b4.jar",
          "url": "core-ng-mongo-9.5.1-b4.jar",
          "size": 60080,
          "sha512": "efc495ae67b702fe62485e782237eea49916d35eba5bdaa1278266135108d4314064390d2e3bf9c3a68f0bae1c87ad97ba8ed1ba4a9dc81c212c1aec68ec1353",
          "sha256": "96652d194a4b233c2bede362b6787715e0fb5967411f7d0b5ce2c86cae24fd18",
          "sha1": "aef3ab80bb18158788645f600f13deaccba63b7e",
          "md5": "0ce92717bb92fe2f82137dc8b14d2e44"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-9.5.1-b4-sources.jar",
          "url": "core-ng-mongo-9.5.1-b4-sources.jar",
          "size": 28819,
          "sha512": "c4eabbafc7d189595731e6bfb84a8a5f6c809b9438fd2f46e57c975d2b67914d6a1c54973a64f5ef6fdb0c41af8cac2063de70d1e9e21a0adfaa6d4dc4e54cb3",
          "sha256": "6488825785ba2b6f16c3c223b15b35d1d4439d5e5c0965ba14c9fdeb5dbac087",
          "sha1": "4a12e62cabfb3a9878e93b518b52513c07dd7fba",
          "md5": "4c81af4cbef8389d25e717f619eb4c74"
        }
      ]
    }
  ]
}
