{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "9.3.0-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.3.0-b1"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.3.0-b1.jar",
          "url": "core-ng-mongo-9.3.0-b1.jar",
          "size": 60078,
          "sha512": "d5281e1af4653424288694bedd449300efc89dfc043cee61720e6633ffdf465544fe3e416e8c6875a2cf1eebdf68a1a76f31eae55770c766ffedede4ee366f2e",
          "sha256": "2a02c8aabe995f35a732cdb4b67d65070c1dea012b2f4e5549b57d61ecf7257a",
          "sha1": "8c303d66c5117815624739f8edc486387406415a",
          "md5": "b2fe84aac4614af10e8ddcc63ce637b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.3.0-b1"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.3.0-b1.jar",
          "url": "core-ng-mongo-9.3.0-b1.jar",
          "size": 60078,
          "sha512": "d5281e1af4653424288694bedd449300efc89dfc043cee61720e6633ffdf465544fe3e416e8c6875a2cf1eebdf68a1a76f31eae55770c766ffedede4ee366f2e",
          "sha256": "2a02c8aabe995f35a732cdb4b67d65070c1dea012b2f4e5549b57d61ecf7257a",
          "sha1": "8c303d66c5117815624739f8edc486387406415a",
          "md5": "b2fe84aac4614af10e8ddcc63ce637b3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-9.3.0-b1-sources.jar",
          "url": "core-ng-mongo-9.3.0-b1-sources.jar",
          "size": 28816,
          "sha512": "be9b3b3111486a412e23446986c667ca9bfd7677ee3b33f3f373ed4c42403250fa4afeff93c231946fa451918d4f937134c90e7152770192610be2660a8dc1e8",
          "sha256": "da9704bd7bfc7c6244ffec21199f80b2543895a99ea21e8a35586de745a7776d",
          "sha1": "0e1dedcf2850172f7d4fea5c63b912cc718b93f8",
          "md5": "8030c144ba4c686c732dfcce94578bb6"
        }
      ]
    }
  ]
}
