{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "9.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.10"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.0.10.jar",
          "url": "core-ng-search-9.0.10.jar",
          "size": 52823,
          "sha512": "d199cb032db58617654d650307962f403ceb3f6eb424a7773202df259a2b568774a522f5219ade1ee4dc08baab39bf28a21190fab4358180872e693322d9b153",
          "sha256": "270c78b929a05dafcf18e32b41b579752bb84fc639dcff440b6770a6f46a41a6",
          "sha1": "c03ab13673ec9c059326d22760dc651f90b3f237",
          "md5": "f91092dbee9717df4f929ff1e93aad65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.10"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.0.10.jar",
          "url": "core-ng-search-9.0.10.jar",
          "size": 52823,
          "sha512": "d199cb032db58617654d650307962f403ceb3f6eb424a7773202df259a2b568774a522f5219ade1ee4dc08baab39bf28a21190fab4358180872e693322d9b153",
          "sha256": "270c78b929a05dafcf18e32b41b579752bb84fc639dcff440b6770a6f46a41a6",
          "sha1": "c03ab13673ec9c059326d22760dc651f90b3f237",
          "md5": "f91092dbee9717df4f929ff1e93aad65"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-9.0.10-sources.jar",
          "url": "core-ng-search-9.0.10-sources.jar",
          "size": 21978,
          "sha512": "9d56ec7793c5643f07cd7bae2d11999e4439158f21fdb16b6e4ef2940d131d045d3a1472045a7cf91d6c0fb2e88821bab076b1614641e70143e37d41d5231945",
          "sha256": "d725082f08cbb5bb3e6e51057c93652d3f525cb327ea16eb40737045aa951f85",
          "sha1": "bda9ed2718c3fded95db64b1b7be3dbf3601e016",
          "md5": "7e454f9ae20711abe2870acf4a344f03"
        }
      ]
    }
  ]
}
