{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "7.5.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6",
      "buildId": "nu265bcuqzeppmcpnogmptzsna"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-7.5.12.jar",
          "url": "core-ng-api-7.5.12.jar",
          "size": 10423,
          "sha512": "2fec475085696e2cdf385faf5e768dcfc284da84a74a657ab7b3623dca9276d3a3503cbbe3fcbfb4fcb1c81cb4bb010cd63bb2f868934a7bc28822d24fbd6212",
          "sha256": "3dbe9e3181e96ca17b14b5d82e7703b9a9aba041bfcc65b26880b4102ddfb5a2",
          "sha1": "b00a97287a9a146ee1a080f7393c42e73eee494e",
          "md5": "cdc772b8a69d0b214f0bcb4ae968c30c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.5.12.jar",
          "url": "core-ng-api-7.5.12.jar",
          "size": 10423,
          "sha512": "2fec475085696e2cdf385faf5e768dcfc284da84a74a657ab7b3623dca9276d3a3503cbbe3fcbfb4fcb1c81cb4bb010cd63bb2f868934a7bc28822d24fbd6212",
          "sha256": "3dbe9e3181e96ca17b14b5d82e7703b9a9aba041bfcc65b26880b4102ddfb5a2",
          "sha1": "b00a97287a9a146ee1a080f7393c42e73eee494e",
          "md5": "cdc772b8a69d0b214f0bcb4ae968c30c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.5.12-sources.jar",
          "url": "core-ng-api-7.5.12-sources.jar",
          "size": 8155,
          "sha512": "1bb58cf33406b6819bdce7d33bb8da9b816c2bd5de7bfbe1f229d968e6564f1f1c2552eb217c074035a5857808315de33e2420f70535e4606f3e8fce9de1117a",
          "sha256": "4cb8f3466c41121804d3b8de0f407757e66703796786632d4d944a3bcb8bf7aa",
          "sha1": "69a9f5a69be20e0f1a33de4a7a12f0b3cb1a52fc",
          "md5": "c35d6d54f6877574aef5a6dba073e32b"
        }
      ]
    }
  ]
}
