{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "9.1.6-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.11.3"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.14.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.26.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.1.6-b0.jar",
          "url": "core-ng-test-9.1.6-b0.jar",
          "size": 47331,
          "sha512": "6f872ddb71420bc979c34d780ad16c092a42ec4eb25f7a1e010fe71d3933b2dc5447358193295776b34ff23191d059fcb0e395000becb286c648a3f6e606c584",
          "sha256": "ad84f55763b01a4ade1f2c5f17f7b5a92baaacadee594ab31a9b79a628cf3049",
          "sha1": "fe76e7b30135ffe0db9f429178016cae6ad3786a",
          "md5": "e50023e4bc1489b7e6c6f5adbfaa3d94"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.6-b0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.11.3"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.11.3"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.14.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.26.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.1.6-b0.jar",
          "url": "core-ng-test-9.1.6-b0.jar",
          "size": 47331,
          "sha512": "6f872ddb71420bc979c34d780ad16c092a42ec4eb25f7a1e010fe71d3933b2dc5447358193295776b34ff23191d059fcb0e395000becb286c648a3f6e606c584",
          "sha256": "ad84f55763b01a4ade1f2c5f17f7b5a92baaacadee594ab31a9b79a628cf3049",
          "sha1": "fe76e7b30135ffe0db9f429178016cae6ad3786a",
          "md5": "e50023e4bc1489b7e6c6f5adbfaa3d94"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-9.1.6-b0-sources.jar",
          "url": "core-ng-test-9.1.6-b0-sources.jar",
          "size": 22555,
          "sha512": "ac510532d33f985b8f7a8c20dd97d58c68692a41193f05f74d8c61dd20c25a2f8f4c0ef492c2f9a7a52ce92065ce496e6221d0b855e9a7ecf48cb50215d84f43",
          "sha256": "0bc498b7183e143e16a8a7c95fe194dd344402e9e8296e8c8443c6e512ef4309",
          "sha1": "6062d2de1d6ba63990a12069bcc3ac9988f5ef0e",
          "md5": "267866e50e59f2d0307d72f1a2c0b89d"
        }
      ]
    }
  ]
}
