{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "9.1.0-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.3"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.12.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.26.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.1.0-b1.jar",
          "url": "core-ng-test-9.1.0-b1.jar",
          "size": 45684,
          "sha512": "9622f1bf2b3cfb71403f26eb17cbd8a550c0589f706a9f4eaf50dfd7cc054247b7cbc4bcfd89602174109108f1ebdd48682ccba750f0daa6a52df7e8875d234f",
          "sha256": "a7e8c7f12a1c50bcdb4ddaaf0bc7e79e895a290bd109d6caac4705c7e7a4d73b",
          "sha1": "e69efce8bfebfb69e1fa1e566b4ced8b32b1367f",
          "md5": "e57379f3d6eee7d22ce8a701ca28a987"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.0-b1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.10.3"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.3"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.12.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.26.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.1.0-b1.jar",
          "url": "core-ng-test-9.1.0-b1.jar",
          "size": 45684,
          "sha512": "9622f1bf2b3cfb71403f26eb17cbd8a550c0589f706a9f4eaf50dfd7cc054247b7cbc4bcfd89602174109108f1ebdd48682ccba750f0daa6a52df7e8875d234f",
          "sha256": "a7e8c7f12a1c50bcdb4ddaaf0bc7e79e895a290bd109d6caac4705c7e7a4d73b",
          "sha1": "e69efce8bfebfb69e1fa1e566b4ced8b32b1367f",
          "md5": "e57379f3d6eee7d22ce8a701ca28a987"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-9.1.0-b1-sources.jar",
          "url": "core-ng-test-9.1.0-b1-sources.jar",
          "size": 22202,
          "sha512": "bdf76d4388932880fe4b011a76ac11410f9d36da7151870df33b705e86e6ed0e3123c91f9498705aecd67786df8e18f7ea691eeb98f7e37375124fa1698202dc",
          "sha256": "76bdc168b0da08c5ef51e173e783a8a7e2b31072e57dd291b82a8015c1866af9",
          "sha1": "cc5b7eef657a965120ab2e2b8224c605543775ad",
          "md5": "fc55dceaa94457c41d5b1ba7029a6c27"
        }
      ]
    }
  ]
}
