{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "9.6.1-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.6.1-b1"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "9.4.3"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            },
            {
              "group": "io.opentelemetry.semconv",
              "module": "*"
            },
            {
              "group": "com.fasterxml.jackson.core",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.6.1-b1.jar",
          "url": "core-ng-search-9.6.1-b1.jar",
          "size": 59734,
          "sha512": "5692d95c1928382bc87c17d4141e5a0858c277fa91b8213884233394aaaefcc29d898c2c504f8a135b5270e7b68a0b7bb6b1b9bd57ff536f90fd7a644e4655ec",
          "sha256": "39013a46399b24a5e8e2ec580a53707c3928065e75f67f4a9a4dacc030e777a1",
          "sha1": "fa8a7b7a4ed94cdb3fbb1013c79883d3be2b2ee0",
          "md5": "41dfdbeac60cbeb5027ecaf48dfe16f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-rest5-client",
          "version": {
            "requires": "9.4.3"
          }
        },
        {
          "group": "tools.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.6.1-b1"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "9.4.3"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            },
            {
              "group": "io.opentelemetry.semconv",
              "module": "*"
            },
            {
              "group": "com.fasterxml.jackson.core",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.6.1-b1.jar",
          "url": "core-ng-search-9.6.1-b1.jar",
          "size": 59734,
          "sha512": "5692d95c1928382bc87c17d4141e5a0858c277fa91b8213884233394aaaefcc29d898c2c504f8a135b5270e7b68a0b7bb6b1b9bd57ff536f90fd7a644e4655ec",
          "sha256": "39013a46399b24a5e8e2ec580a53707c3928065e75f67f4a9a4dacc030e777a1",
          "sha1": "fa8a7b7a4ed94cdb3fbb1013c79883d3be2b2ee0",
          "md5": "41dfdbeac60cbeb5027ecaf48dfe16f1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-9.6.1-b1-sources.jar",
          "url": "core-ng-search-9.6.1-b1-sources.jar",
          "size": 24980,
          "sha512": "6a31514ad70335513789ff13c768f659fa5371608b1d80b6614620f5612a113d4d5c2e6fc7c25355353e4a72f524789010c4c26d0d167e56069ed357b5e43c58",
          "sha256": "999a30e0a9a31dfebf8499db2c5e80c5bf8cdf81e21ea7d39e32d264c9166159",
          "sha1": "d302c1ab94bf92951b512362864a297cd20e9a9f",
          "md5": "0f4f36dc1e5f2d357f2570dbd8c125f5"
        }
      ]
    }
  ]
}
