{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "9.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.8"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.12.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.0.8.jar",
          "url": "core-ng-search-9.0.8.jar",
          "size": 52864,
          "sha512": "f217f2afbd988f09d8ab5d0167e25f81515d4a4c09443e0bfd6ccbcaea97c8cf4fa729be97142c37b298de5fd6fa227c97edfb6f35ad0fcb183d0b9c59cdd805",
          "sha256": "6e205d3c7d38719d3485e675f453d19f6e6ac9f657a5bf6cf0a83861ad745d28",
          "sha1": "70f376e8b1662181f2be3cf8480731bb6ddf6cc6",
          "md5": "3802220e64368460cf80d9c1d9f43019"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.16.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.8"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.12.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.0.8.jar",
          "url": "core-ng-search-9.0.8.jar",
          "size": 52864,
          "sha512": "f217f2afbd988f09d8ab5d0167e25f81515d4a4c09443e0bfd6ccbcaea97c8cf4fa729be97142c37b298de5fd6fa227c97edfb6f35ad0fcb183d0b9c59cdd805",
          "sha256": "6e205d3c7d38719d3485e675f453d19f6e6ac9f657a5bf6cf0a83861ad745d28",
          "sha1": "70f376e8b1662181f2be3cf8480731bb6ddf6cc6",
          "md5": "3802220e64368460cf80d9c1d9f43019"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-9.0.8-sources.jar",
          "url": "core-ng-search-9.0.8-sources.jar",
          "size": 21978,
          "sha512": "bd56095cda17bed93f342f02c3b9a16d2daf2376696a429d7f676a6fb5e85dcc60ba9724cc706aed349bf4a533dccfef2d84faaf9bd5d719096653045e348314",
          "sha256": "ccf1d8502132f80161db59a8c1bc9fa85f167811435c97918c28c61e33ad03df",
          "sha1": "e6c53b376a518a3c52387f58e901a6b8cf3bb3f9",
          "md5": "f5baa079b78dd0af56664d86c8aa3011"
        }
      ]
    }
  ]
}
