{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "7.7.1-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-7.7.1-b1.jar",
          "url": "core-ng-mongo-test-7.7.1-b1.jar",
          "size": 2383,
          "sha512": "f1d6ccab3c1f46c5ed7ec4717598c3f6e7a686c90589ca0f7a5e17a4c8242aa918ff2438121ba89526dec9e4ff8e284b13f32c80233f16e55125a2ed38efe18f",
          "sha256": "d57ed2ab3aafd78ecf7d03fa25b3c2c7001bc02a5a9505b264d6630c2c4753ea",
          "sha1": "cf889676a5e27bc9d27e88063b8219544010728e",
          "md5": "16c81924bfd877fde7b9018679a25e00"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.7.1-b1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "7.7.1-b1"
          }
        },
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.38.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-7.7.1-b1.jar",
          "url": "core-ng-mongo-test-7.7.1-b1.jar",
          "size": 2383,
          "sha512": "f1d6ccab3c1f46c5ed7ec4717598c3f6e7a686c90589ca0f7a5e17a4c8242aa918ff2438121ba89526dec9e4ff8e284b13f32c80233f16e55125a2ed38efe18f",
          "sha256": "d57ed2ab3aafd78ecf7d03fa25b3c2c7001bc02a5a9505b264d6630c2c4753ea",
          "sha1": "cf889676a5e27bc9d27e88063b8219544010728e",
          "md5": "16c81924bfd877fde7b9018679a25e00"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-7.7.1-b1-sources.jar",
          "url": "core-ng-mongo-test-7.7.1-b1-sources.jar",
          "size": 1721,
          "sha512": "65a90056ddbc0ae8408b45033f60a47ab8a6e66d294b0f5067a81de2d33f280889a3978f2726968065a2b8acdfb4f54c1dd7e1ccb01495065817348fad1d65fb",
          "sha256": "07d1ccdadc50fc4422a0bf12c4a1635594d4c8955c4b265d3bd6e2d36aa4ef96",
          "sha1": "306e916cfbc790432bcab31c5197cf567ddc8f2e",
          "md5": "c33387dacedc4296cab15d86668a9783"
        }
      ]
    }
  ]
}
