{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "9.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-9.0.5.jar",
          "url": "core-ng-api-9.0.5.jar",
          "size": 10988,
          "sha512": "2c2b6a6c7e3eb4b9dc5dc4d18074a2b08894c1ade0a23b1b97ded5333371f88841dd10e1543226b7c43aa6ddb259f8f03b04a4583f268a6a56b4285d8a1e9a2a",
          "sha256": "f6efe82d5ac70f927c65ce47aeb382f949b0f767b725987fe90155044f688374",
          "sha1": "a791a4bc8a226d7b7b4ef31fcc53e9fe44fa4c3a",
          "md5": "67b35da09c1f3d83aa9a2791a55d1a86"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.0.5.jar",
          "url": "core-ng-api-9.0.5.jar",
          "size": 10988,
          "sha512": "2c2b6a6c7e3eb4b9dc5dc4d18074a2b08894c1ade0a23b1b97ded5333371f88841dd10e1543226b7c43aa6ddb259f8f03b04a4583f268a6a56b4285d8a1e9a2a",
          "sha256": "f6efe82d5ac70f927c65ce47aeb382f949b0f767b725987fe90155044f688374",
          "sha1": "a791a4bc8a226d7b7b4ef31fcc53e9fe44fa4c3a",
          "md5": "67b35da09c1f3d83aa9a2791a55d1a86"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.0.5-sources.jar",
          "url": "core-ng-api-9.0.5-sources.jar",
          "size": 8642,
          "sha512": "c715c4464036bf73aca4dc47172f11a5136a49df28ca4ed5d2580a9bc92ea3d0edddbd977881ce3bc3ef6caa9de04147af8692d52d5b0891f7e2acf3de1bb168",
          "sha256": "c65aa806d9960f8873d5f735ce7fbf410c49ad0af62fd2aaf51979d68734d473",
          "sha1": "52a048c08c0389e39d0ea0e1f68b5e257e563212",
          "md5": "1426d6b45727887570f341a9e8e6ec36"
        }
      ]
    }
  ]
}
