{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "9.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.5.0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.5.0.jar",
          "url": "core-ng-mongo-9.5.0.jar",
          "size": 60075,
          "sha512": "3654b8f5dc2cbe38d2525de261fb53f058fdcf5f241513b2e0884763cdfeba969f641ccf384df772bf28f0a5343c9cf359f25caf817060fa77405c76678a26ae",
          "sha256": "a65eaaeab6cae02293526b38d158d1a19c027c3925e1b5187cd26c078dcc09a6",
          "sha1": "74bbb9761b1cb51a756b25cb339f860cbbeece62",
          "md5": "5b9475c895daac82758d3f983092ca00"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.5.0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.5.0.jar",
          "url": "core-ng-mongo-9.5.0.jar",
          "size": 60075,
          "sha512": "3654b8f5dc2cbe38d2525de261fb53f058fdcf5f241513b2e0884763cdfeba969f641ccf384df772bf28f0a5343c9cf359f25caf817060fa77405c76678a26ae",
          "sha256": "a65eaaeab6cae02293526b38d158d1a19c027c3925e1b5187cd26c078dcc09a6",
          "sha1": "74bbb9761b1cb51a756b25cb339f860cbbeece62",
          "md5": "5b9475c895daac82758d3f983092ca00"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-9.5.0-sources.jar",
          "url": "core-ng-mongo-9.5.0-sources.jar",
          "size": 28814,
          "sha512": "d76070aedd1ddd268c1af78d01dcf83d7f05523f429d02dba441ac59c9942712abb8cfaadf8731fcf410734c5775e8c699a50f455923e02145f7e76253b4adb1",
          "sha256": "bbfa567d36e040231330dd1576312b6b4804a80c4c0cbe1859a5bc14c87a5b35",
          "sha1": "4568a1ed862bbcc3187609a8c2fbb75fd9ad7b2a",
          "md5": "f5d8ddfb5ecd4ba53956b8f92524f1fa"
        }
      ]
    }
  ]
}
