{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "9.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-9.0.6.jar",
          "url": "core-ng-api-9.0.6.jar",
          "size": 10988,
          "sha512": "c73ddf5258a8c873a89244ad9db751ecc37ce2bd981fbcadbcda75516191fee3690a007483562eaeb1d6293db787562840b7abc549c5b776f027d546fdfe9031",
          "sha256": "01dbdea92f8359a89984ca1e20e983dbc98d91e35edacc5fec802f2fc5f77a58",
          "sha1": "93faf49f8b0f7aa1582f1f064cf8b01efee1c968",
          "md5": "7dc0fbdac099eb6e8f043f166817e921"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.0.6.jar",
          "url": "core-ng-api-9.0.6.jar",
          "size": 10988,
          "sha512": "c73ddf5258a8c873a89244ad9db751ecc37ce2bd981fbcadbcda75516191fee3690a007483562eaeb1d6293db787562840b7abc549c5b776f027d546fdfe9031",
          "sha256": "01dbdea92f8359a89984ca1e20e983dbc98d91e35edacc5fec802f2fc5f77a58",
          "sha1": "93faf49f8b0f7aa1582f1f064cf8b01efee1c968",
          "md5": "7dc0fbdac099eb6e8f043f166817e921"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.0.6-sources.jar",
          "url": "core-ng-api-9.0.6-sources.jar",
          "size": 8642,
          "sha512": "25704bb51fd539b434213ac0bc517e292320e292750dba3018631b848e2e72b90c787c635b9b90dd3e15ee6f223679793b8001d7dd825975436c20e4e5b1b7cd",
          "sha256": "9498a575de9fbbbffbfa0c728847edc3acf968c1184214fa47768e63a555197c",
          "sha1": "b62d4f7b7c7b93d50a9c4f84bcc22a4ca66fd31a",
          "md5": "205c5677b7ea9b0904f9741e8cfd2ba4"
        }
      ]
    }
  ]
}
