{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "7.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "tiw26whr7vh43djrdosu3oi4rq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.4.6"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.6.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.4.6.jar",
          "url": "core-ng-test-7.4.6.jar",
          "size": 35967,
          "sha512": "259d41d42519b73a80241bfeba78d857c1f767e314b00d7a51f387ef754b044d9713a8390b6feff2e5eb790180d4e2f0bcc1cf9472a2b3a1eed4834c26a31743",
          "sha256": "634dac1c259c9be4eff40be9012c250c3c883abf121ed93d8844bedfeb0f5f3a",
          "sha1": "11bea25b696e84c4d0fecae608a48fa6a7913b4a",
          "md5": "263fc3806846c1c13c517a015ddbf5bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.6.2"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.4.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.4.6"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.6.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.4.6.jar",
          "url": "core-ng-test-7.4.6.jar",
          "size": 35967,
          "sha512": "259d41d42519b73a80241bfeba78d857c1f767e314b00d7a51f387ef754b044d9713a8390b6feff2e5eb790180d4e2f0bcc1cf9472a2b3a1eed4834c26a31743",
          "sha256": "634dac1c259c9be4eff40be9012c250c3c883abf121ed93d8844bedfeb0f5f3a",
          "sha1": "11bea25b696e84c4d0fecae608a48fa6a7913b4a",
          "md5": "263fc3806846c1c13c517a015ddbf5bc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-7.4.6-sources.jar",
          "url": "core-ng-test-7.4.6-sources.jar",
          "size": 18214,
          "sha512": "0f476172510b49b420179dffb6b3438c29dac8caf457c7d4a07dbc0282532c5c7fdf0daa122ece960993e00fb2b38c7d03537bc946ed9f1b1c0cdaf1129f16cb",
          "sha256": "9778bb4f0b6ce56a75ec4b171999b1f7defe57fb6af47bbeb34c2ef9679a8d95",
          "sha1": "354086126cf24fec0baf89f4e2b98c7826b4d895",
          "md5": "fd76f91564075967b422c58baf759154"
        }
      ]
    }
  ]
}
