{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.1.4.jar",
          "url": "core-ng-9.1.4.jar",
          "size": 773188,
          "sha512": "df89b882cc7709d1ea6da06fee2fe3cc05c1482133ba85be312f9af5c777a1d87acc0753e98ff549a6065858e64322891bf7ffb99559dc19d3b56357bd70bd28",
          "sha256": "b476347f1c106eb6e1ba8d07d197deb261d7f82148af5e18fc34011caa81b68b",
          "sha1": "64f77c7dd28815ef5208b2b15428342d19e8e4e6",
          "md5": "3b4f61ed6a1dd9612122d3cf2208ca21"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "okhttp",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.10.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.1.4.jar",
          "url": "core-ng-9.1.4.jar",
          "size": 773188,
          "sha512": "df89b882cc7709d1ea6da06fee2fe3cc05c1482133ba85be312f9af5c777a1d87acc0753e98ff549a6065858e64322891bf7ffb99559dc19d3b56357bd70bd28",
          "sha256": "b476347f1c106eb6e1ba8d07d197deb261d7f82148af5e18fc34011caa81b68b",
          "sha1": "64f77c7dd28815ef5208b2b15428342d19e8e4e6",
          "md5": "3b4f61ed6a1dd9612122d3cf2208ca21"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.1.4-sources.jar",
          "url": "core-ng-9.1.4-sources.jar",
          "size": 394907,
          "sha512": "303986d2f3eeffd3505f2cf3089af6db7db96c3a1242f5ffe2d4f08053414374a3c019fd2ffcf7328b07d7f4ff88c526d35fee6511f15a80523573b7eb3b3e7d",
          "sha256": "32fb63dd2277290187ea639bcf65c73a9a2a7c3fee3a26a551d227b481c6e19c",
          "sha1": "8cfd42ab76c6586dd45859ad97a37ed75cc78384",
          "md5": "b970e3e52b1aa218b816a40622b4f1bc"
        }
      ]
    }
  ]
}
