{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "7.6.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "5ouw753gz5cgbnubxggdyz4bvu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.12"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "7.11.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "elasticsearch",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch-x-content",
          "version": {
            "requires": "7.11.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "elasticsearch-x-content",
              "type": "jar",
              "extension": "jar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.6.12.jar",
          "url": "core-ng-search-7.6.12.jar",
          "size": 38504,
          "sha512": "56514240be372e5543324a2aac3c1ba7e842a0e00867364c342a55757b3af22f6790c76e3f67cf41337c0abd4ac0a3e677d0f2158647c5e8c393e009ffbea075",
          "sha256": "1b61b6996f2a35dab5594a4e9619fea040a4581ef822642436f473a7a1554627",
          "sha1": "2666cbe9ebefe42a9db2b5771d610592e0ac757a",
          "md5": "8217d7d7622103f634f789ccdd6131b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.elasticsearch.client",
          "module": "elasticsearch-rest-high-level-client",
          "version": {
            "requires": "7.11.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.12"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "7.11.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "elasticsearch",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch-x-content",
          "version": {
            "requires": "7.11.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "elasticsearch-x-content",
              "type": "jar",
              "extension": "jar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.6.12.jar",
          "url": "core-ng-search-7.6.12.jar",
          "size": 38504,
          "sha512": "56514240be372e5543324a2aac3c1ba7e842a0e00867364c342a55757b3af22f6790c76e3f67cf41337c0abd4ac0a3e677d0f2158647c5e8c393e009ffbea075",
          "sha256": "1b61b6996f2a35dab5594a4e9619fea040a4581ef822642436f473a7a1554627",
          "sha1": "2666cbe9ebefe42a9db2b5771d610592e0ac757a",
          "md5": "8217d7d7622103f634f789ccdd6131b6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-7.6.12-sources.jar",
          "url": "core-ng-search-7.6.12-sources.jar",
          "size": 17330,
          "sha512": "bdbcff167003e5773403830b604c3e46d38ad204d773a79880e3a196eb784a389aac51bf15a344fd84387cad04ba805eedbb681644e13759488efad3efd91960",
          "sha256": "7a2f31da9e02ca5a1f63c3736acd4eaedd9f17b55900f9e91b9d5da80d0d5d33",
          "sha1": "91b66d69a8f5baa68a42b955af27cb81e725406d",
          "md5": "8ebf4b995531e5edd2b56d11be3e2cc7"
        }
      ]
    }
  ]
}
