{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "9.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.5"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.0.5.jar",
          "url": "core-ng-search-9.0.5.jar",
          "size": 52863,
          "sha512": "dc6623d929ca369bd689f91135ce1de6eb300392982efc64ef61540fb12770939a5689d681ba2a8c15ec8b56a0b853fc08e6c6df4ad5074d0f95c2c9dc727490",
          "sha256": "7977b5ac06913959f4186a097bd5f7af42912f6352129853fc5cdaad94e43ce8",
          "sha1": "5d99cefe4b61935ddbe0927299bf152580445ed8",
          "md5": "03eac7499cb43b2ec0895a507083b1be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.16.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.5"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.0.5.jar",
          "url": "core-ng-search-9.0.5.jar",
          "size": 52863,
          "sha512": "dc6623d929ca369bd689f91135ce1de6eb300392982efc64ef61540fb12770939a5689d681ba2a8c15ec8b56a0b853fc08e6c6df4ad5074d0f95c2c9dc727490",
          "sha256": "7977b5ac06913959f4186a097bd5f7af42912f6352129853fc5cdaad94e43ce8",
          "sha1": "5d99cefe4b61935ddbe0927299bf152580445ed8",
          "md5": "03eac7499cb43b2ec0895a507083b1be"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-9.0.5-sources.jar",
          "url": "core-ng-search-9.0.5-sources.jar",
          "size": 21977,
          "sha512": "b85dac82923f82979c9c409c9177412f0edeeb16f795418617aa882284292f6d72c25d17a24e065272c3dbfd89a1471803204e34c4ce9a839d70d50860ea602c",
          "sha256": "ae4751e894c1b13c96fe2a50986eba5ce8e31153cec11d9f1372996c3d2893f9",
          "sha1": "eff49d331f1d37fb38ae2a40aac3c85f904de9d4",
          "md5": "9d920d296d5811c411792bf52e27e35c"
        }
      ]
    }
  ]
}
