{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework.mysql",
    "module": "mysql-connector-j",
    "version": "8.4.0-r4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mysql-connector-j-8.4.0-r4.jar",
          "url": "mysql-connector-j-8.4.0-r4.jar",
          "size": 517230,
          "sha512": "4ddc89462ff6425b7900d0face0c634f57b49aee4de8f9a9611e4deb4f7b4f2153a04a5ca092a1212be0c0b8198d26a30d24c1c188d46541b8daf31875e8ad48",
          "sha256": "7a790b8f0d70e515e5a02b21a876ab5fdd1aa237cabc88f964b48e88bcc0ae10",
          "sha1": "fcd0ec0404efe1d453bd1a930a21dcac4b93ecf4",
          "md5": "db98de541a9c7316dd2feb4e987d5217"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mysql-connector-j-8.4.0-r4.jar",
          "url": "mysql-connector-j-8.4.0-r4.jar",
          "size": 517230,
          "sha512": "4ddc89462ff6425b7900d0face0c634f57b49aee4de8f9a9611e4deb4f7b4f2153a04a5ca092a1212be0c0b8198d26a30d24c1c188d46541b8daf31875e8ad48",
          "sha256": "7a790b8f0d70e515e5a02b21a876ab5fdd1aa237cabc88f964b48e88bcc0ae10",
          "sha1": "fcd0ec0404efe1d453bd1a930a21dcac4b93ecf4",
          "md5": "db98de541a9c7316dd2feb4e987d5217"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mysql-connector-j-8.4.0-r4-sources.jar",
          "url": "mysql-connector-j-8.4.0-r4-sources.jar",
          "size": 520278,
          "sha512": "ca5f93c9b3aaa2767c1014ad187590f134acfa89a6ef31d8ad8001ab9b06beda44faa42caa54dcc52278a3bc312eb530469de0645979d0b221e87fb4c12d1ca9",
          "sha256": "a74a12f047a51ec2fb567706e0f2cdaa45f579fb38872db4ce25373b22c3591d",
          "sha1": "b88ed688417657c2ace8fc41a05f2f6e7988950b",
          "md5": "e8d2dbc9d3b26774890a38e0fb141083"
        }
      ]
    }
  ]
}
