{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "9.4.0-b2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.4.0-b2.jar",
          "url": "core-ng-search-test-9.4.0-b2.jar",
          "size": 10074,
          "sha512": "b59088fe9136375fa3b12d2a3d40fb5495722a8da2ec9db4ff08952155bbd9f7e95192a309653821a03aefad2710ad0309d2eb3738d157d32f94ed0937c8cea8",
          "sha256": "d5be14221bde4abf158c79c5cd68f9da92f7dbc3c94b2d3245cde8e67ddf5252",
          "sha1": "cc9963842a973c4ba10c09a32d200ff207e5043d",
          "md5": "42ed5d5bfb65d7f4938e4fb61f04abe3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.4.0-b2"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "9.4.0-b2"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "8.18.1"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "reindex",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-9.4.0-b2.jar",
          "url": "core-ng-search-test-9.4.0-b2.jar",
          "size": 10074,
          "sha512": "b59088fe9136375fa3b12d2a3d40fb5495722a8da2ec9db4ff08952155bbd9f7e95192a309653821a03aefad2710ad0309d2eb3738d157d32f94ed0937c8cea8",
          "sha256": "d5be14221bde4abf158c79c5cd68f9da92f7dbc3c94b2d3245cde8e67ddf5252",
          "sha1": "cc9963842a973c4ba10c09a32d200ff207e5043d",
          "md5": "42ed5d5bfb65d7f4938e4fb61f04abe3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.4.0-b2-sources.jar",
          "url": "core-ng-search-test-9.4.0-b2-sources.jar",
          "size": 6289,
          "sha512": "caff89ae4c34489fcad21c82bd6a9ecb5982bf49465eb9b2c5307d5ede771b43784f426bc6a32ce846ce3283587c4bafdbf85341c321a15750ec3990f221f2a6",
          "sha256": "c333cbfd3afbc906494154eabf8cbcca7b07631078da0e939ef55ae193a8c5b0",
          "sha1": "3e499187bf490bc36c20352e9fbf9a72b1287343",
          "md5": "e129331b618f608deaabe13535fc2b85"
        }
      ]
    }
  ]
}
