{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "9.5.1-b2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.5.1-b2.jar",
          "url": "core-ng-search-test-9.5.1-b2.jar",
          "size": 11066,
          "sha512": "248f423d545a7e95ffb81c82a3328f54efa6439c73bffaebde2f85f81b5df477bf21316b3eed7126516b68de1b66d1020e2ff428ec24289d9606cafe5b0081a5",
          "sha256": "a8f845e9e9fe96b1ff5afb261178d1711d909ca497c78d65cee8d7e04cad0fbb",
          "sha1": "ce18507eff97cf7f5de2346a684f763813a7b530",
          "md5": "6218d0b1e4b44388d4e7d4ebaeaef8a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.5.1-b2"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "9.5.1-b2"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "9.3.2"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "reindex",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-9.5.1-b2.jar",
          "url": "core-ng-search-test-9.5.1-b2.jar",
          "size": 11066,
          "sha512": "248f423d545a7e95ffb81c82a3328f54efa6439c73bffaebde2f85f81b5df477bf21316b3eed7126516b68de1b66d1020e2ff428ec24289d9606cafe5b0081a5",
          "sha256": "a8f845e9e9fe96b1ff5afb261178d1711d909ca497c78d65cee8d7e04cad0fbb",
          "sha1": "ce18507eff97cf7f5de2346a684f763813a7b530",
          "md5": "6218d0b1e4b44388d4e7d4ebaeaef8a9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.5.1-b2-sources.jar",
          "url": "core-ng-search-test-9.5.1-b2-sources.jar",
          "size": 7106,
          "sha512": "4c9400533f32cfb5382b3c3915c810ba3dd87a488a4ccf2c2fc3e55e038ff9f121e3deebd753b142344f8512260165f0a511f92c31c027938ae85b1c8e764a32",
          "sha256": "594a96c09bd15207f044c66cb2ba87917ec6b98200bcdb1099333bfab4dd0aec",
          "sha1": "66b5d5df38b8b22bf03be523c10cfdc2472f32bd",
          "md5": "614ac6a9d3216c9c9b5f3d458c080f94"
        }
      ]
    }
  ]
}
