{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.4.0-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.4.0-b0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.4.0-b0.jar",
          "url": "core-ng-9.4.0-b0.jar",
          "size": 788617,
          "sha512": "5421a5a346e569224556e2d365d8778fd1d5dd16da4fd7081a646a48f8a55f9fb18cf222f3c169f0b734b42246cb626d43ee9c87ead515571df694c9ea81f462",
          "sha256": "985115802fafbc5519046a8be6b57460760c27c72b8302b3a3fc0ba4bb18c4bd",
          "sha1": "95367afabdb83279eb000679b459dfd54a317961",
          "md5": "19a534a93022e316d388686b4054465e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.22.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "4.1.1"
          },
          "excludes": [
            {
              "group": "org.xerial.snappy",
              "module": "*"
            },
            {
              "group": "org.lz4",
              "module": "*"
            }
          ]
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.4.0-b0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.4.0-b0.jar",
          "url": "core-ng-9.4.0-b0.jar",
          "size": 788617,
          "sha512": "5421a5a346e569224556e2d365d8778fd1d5dd16da4fd7081a646a48f8a55f9fb18cf222f3c169f0b734b42246cb626d43ee9c87ead515571df694c9ea81f462",
          "sha256": "985115802fafbc5519046a8be6b57460760c27c72b8302b3a3fc0ba4bb18c4bd",
          "sha1": "95367afabdb83279eb000679b459dfd54a317961",
          "md5": "19a534a93022e316d388686b4054465e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.4.0-b0-sources.jar",
          "url": "core-ng-9.4.0-b0-sources.jar",
          "size": 405268,
          "sha512": "0ab0869c20b97ec570cfff6cd0b0ce8a216c57581c0170ff1a07319066ee88eb3595ee3a3d21095420fafe92a9756d48db1473613d2674bab6d5b164564e38e8",
          "sha256": "59f33f6cd34318519c1ae08a5517f7a7ea8b1173c2c2d6eaa5c88f367e62cf2a",
          "sha1": "222e3b95e817e5673bce5578b68be856f6118478",
          "md5": "62dbc95ee39fe7811f70705f4af182f8"
        }
      ]
    }
  ]
}
