{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "8.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-8.1.6.jar",
          "url": "core-ng-api-8.1.6.jar",
          "size": 10968,
          "sha512": "0801a347bd3b38397e1ac4bbe0ac35124ea093ef6932f5fa1db7a88f860c530e2a64c818cc4c52779c83d4b6e569e379f7c880cc416721bb5c4069f455db11c4",
          "sha256": "b36e9314f96805ecc6422964acace70c717060b62b24d6dffa51ec99546b3ddc",
          "sha1": "2abf94bf577ded663a4642b5fea23f7384ff3f9f",
          "md5": "849de366ef3b6a4096c6f2e5492959bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-8.1.6.jar",
          "url": "core-ng-api-8.1.6.jar",
          "size": 10968,
          "sha512": "0801a347bd3b38397e1ac4bbe0ac35124ea093ef6932f5fa1db7a88f860c530e2a64c818cc4c52779c83d4b6e569e379f7c880cc416721bb5c4069f455db11c4",
          "sha256": "b36e9314f96805ecc6422964acace70c717060b62b24d6dffa51ec99546b3ddc",
          "sha1": "2abf94bf577ded663a4642b5fea23f7384ff3f9f",
          "md5": "849de366ef3b6a4096c6f2e5492959bf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-8.1.6-sources.jar",
          "url": "core-ng-api-8.1.6-sources.jar",
          "size": 8644,
          "sha512": "b2dfa51d8485b4aa30ef03fd27620962a7d8f2e71261c89b00d0259150730a0b5111456a337d7d172c376edc46367390641cbad58f44d31f98f49851e02a5bbe",
          "sha256": "735c2d6fdad64f7806cae1ce077b0ba1ce97488ebfba133608d3545a362b689d",
          "sha1": "c2f428f94587d5af033aa183840bf45718c25053",
          "md5": "df844cdd06d6bc1ec66b0bccbe8878ee"
        }
      ]
    }
  ]
}
