{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "7.4.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "4tfdwyaxinhlzpijsn6ngjhx4a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.4.11"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.4.11.jar",
          "url": "core-ng-7.4.11.jar",
          "size": 625129,
          "sha512": "9e538f45bd5996f9ed4117b0abd3678a1d4d32e1722357014f4ea7d695bd73e6e1f881305837d93b9c0a4e7f98ed49d9fcd29a6f42c1d5b276d2970b61d3d6e0",
          "sha256": "f781edfc70b590b5505947b220b169c0f7a1dc899859e2074920a26ca09a7a2c",
          "sha1": "0d542f60351fa98af57e92bd1578ade6d5db747f",
          "md5": "40bed801d0f3041ed6916662aa008d5a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.27.0-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.10.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.10.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.1.3.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.4.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.7.5"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.4.11"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.4.11.jar",
          "url": "core-ng-7.4.11.jar",
          "size": 625129,
          "sha512": "9e538f45bd5996f9ed4117b0abd3678a1d4d32e1722357014f4ea7d695bd73e6e1f881305837d93b9c0a4e7f98ed49d9fcd29a6f42c1d5b276d2970b61d3d6e0",
          "sha256": "f781edfc70b590b5505947b220b169c0f7a1dc899859e2074920a26ca09a7a2c",
          "sha1": "0d542f60351fa98af57e92bd1578ade6d5db747f",
          "md5": "40bed801d0f3041ed6916662aa008d5a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-7.4.11-sources.jar",
          "url": "core-ng-7.4.11-sources.jar",
          "size": 320603,
          "sha512": "1be4d0a4757f3c0bc67450146845b1aa07244dddf97835f9f2b59f15f9d1e5f8ebe86ff304349238d68845ba0730c6fa5910b52ba90127a556486944a0fb0dbd",
          "sha256": "fc23062aee9a5ed1f9785067a860f52735f341fbd8dbc33920cdc645831ec04b",
          "sha1": "b22226c6463e4a1778529858484f39bc70d957f3",
          "md5": "1ab1b0b4b5fb5b85e4e13a256b0fc5b7"
        }
      ]
    }
  ]
}
