{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "7.6.2-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "5jfivrnadrg73pcyjgmirgtp24"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.6.2-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "7.6.2-b0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-7.6.2-b0.jar",
          "url": "core-ng-mongo-test-7.6.2-b0.jar",
          "size": 2382,
          "sha512": "fc832b198aa26900b16a66cc0660e343105993b2bc71599efad76a1f83c84825e62ca55d5e2a44bd9069500ad5596405d374f22e835bd3753d55dbf560c693b5",
          "sha256": "05a23eaf14ce9fe2bfae4ae1bb6f13a18416ba4da88a306d6bc36798f1ec6119",
          "sha1": "d26071caab5dff359e0b573d094b83727e10d544",
          "md5": "1729a47cf36330235c0a57665934f876"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.34.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.6.2-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "7.6.2-b0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-7.6.2-b0.jar",
          "url": "core-ng-mongo-test-7.6.2-b0.jar",
          "size": 2382,
          "sha512": "fc832b198aa26900b16a66cc0660e343105993b2bc71599efad76a1f83c84825e62ca55d5e2a44bd9069500ad5596405d374f22e835bd3753d55dbf560c693b5",
          "sha256": "05a23eaf14ce9fe2bfae4ae1bb6f13a18416ba4da88a306d6bc36798f1ec6119",
          "sha1": "d26071caab5dff359e0b573d094b83727e10d544",
          "md5": "1729a47cf36330235c0a57665934f876"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-7.6.2-b0-sources.jar",
          "url": "core-ng-mongo-test-7.6.2-b0-sources.jar",
          "size": 1720,
          "sha512": "ef3336a29a7799cb943067e5b45a03ba00f157653b7f5b11a2a04daef68c76dea2a8bbaa06844e177e3732b58db8c032c35202ef98197596b799544c4a93397e",
          "sha256": "bb4376c622a2e954c47a78950a3183e963b14ab83ce98164ada52cb911ab1370",
          "sha1": "487bc0fa81b964c8bdf7ccb726f46e0dc7f894e7",
          "md5": "95f584170da2b287c160663801738ab6"
        }
      ]
    }
  ]
}
