{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "9.1.1-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-9.1.1-b0.jar",
          "url": "core-ng-api-9.1.1-b0.jar",
          "size": 10994,
          "sha512": "8f050259526983aa1389fdd0d9bc99d8da31182f8b1f60f6abad834042fbfed406e0c7226cce4937c9549354263a431cb50ed340ccb7d4b18d9ac74e8dbde6b5",
          "sha256": "0b326d7a843591d0870a78d77c959f8524f6b6d076f5621cb8a2a7cf7a3add68",
          "sha1": "cb6cb023438e2ece961cd20aff28e5f3b5697bdc",
          "md5": "5716cbf2cf68d209da8b85608a4c4f70"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.1.1-b0.jar",
          "url": "core-ng-api-9.1.1-b0.jar",
          "size": 10994,
          "sha512": "8f050259526983aa1389fdd0d9bc99d8da31182f8b1f60f6abad834042fbfed406e0c7226cce4937c9549354263a431cb50ed340ccb7d4b18d9ac74e8dbde6b5",
          "sha256": "0b326d7a843591d0870a78d77c959f8524f6b6d076f5621cb8a2a7cf7a3add68",
          "sha1": "cb6cb023438e2ece961cd20aff28e5f3b5697bdc",
          "md5": "5716cbf2cf68d209da8b85608a4c4f70"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.1.1-b0-sources.jar",
          "url": "core-ng-api-9.1.1-b0-sources.jar",
          "size": 8644,
          "sha512": "5f73f992de9873e22aefe3e594fa8216b74de64cd1edf53931ddeda2abeda29911330a80c406fc5844313136c17aa34e8a0081950b7ae38203dc3541d3bb605b",
          "sha256": "04ebd51f4f3f611eb4291ea1bc6a2c98ed3c6356027eebcb091198732d0e7f08",
          "sha1": "2238a048d3551c1b1a8f2ae8e8f6c8f94e7ce457",
          "md5": "7cd7cb3f18fbba0546ef23c5fbf2c5bb"
        }
      ]
    }
  ]
}
