{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "7.4.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "3mlsin3fvvb55bqty7rjpsuugu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.4.1.1"
          }
        },
        {
          "group": "org.elasticsearch.client",
          "module": "elasticsearch-rest-high-level-client",
          "version": {
            "requires": "7.6.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.4.1.1.jar",
          "url": "core-ng-search-7.4.1.1.jar",
          "size": 36854,
          "sha512": "32766d27e40391c74caf3e19ac41325124aa37c291a4013b7ea50ebe8ed4ed6231372fdd073b4c4e14711f724f47dee9d8090aae3fd800eafe61f4c6c7b389e4",
          "sha256": "46836ecea68c02e917cb4ac0fb917d68b0afc2906af4affd2a1417ea40115083",
          "sha1": "03e72b9e20d4df5f69972632a380a664652cc6df",
          "md5": "a6e5af91f696f133d1d171a26e2074ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.4.1.1"
          }
        },
        {
          "group": "org.elasticsearch.client",
          "module": "elasticsearch-rest-high-level-client",
          "version": {
            "requires": "7.6.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-smile",
          "version": {
            "requires": "2.10.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.10.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-cbor",
          "version": {
            "requires": "2.10.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.25"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.4.1.1.jar",
          "url": "core-ng-search-7.4.1.1.jar",
          "size": 36854,
          "sha512": "32766d27e40391c74caf3e19ac41325124aa37c291a4013b7ea50ebe8ed4ed6231372fdd073b4c4e14711f724f47dee9d8090aae3fd800eafe61f4c6c7b389e4",
          "sha256": "46836ecea68c02e917cb4ac0fb917d68b0afc2906af4affd2a1417ea40115083",
          "sha1": "03e72b9e20d4df5f69972632a380a664652cc6df",
          "md5": "a6e5af91f696f133d1d171a26e2074ed"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-7.4.1.1-sources.jar",
          "url": "core-ng-search-7.4.1.1-sources.jar",
          "size": 16228,
          "sha512": "782b67331f49ab47763d4d077ee095808a656a8b61ec82af9d85f862e446b1a1826bd819bd60b4eac5b98f14d356291f2dc3a893da53dbf5487f50b4a73778b8",
          "sha256": "5337c76353ab5576d24d01cd9370391112a5b1a4037a5cf35476b01102ec4961",
          "sha1": "e20931a3bc5f52b60f91bfc2d267a1ac7782dbfc",
          "md5": "381bb2e03e4941ab1eefe5865b3f61fc"
        }
      ]
    }
  ]
}
