{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "9.5.1-b5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-api-9.5.1-b5.jar",
          "url": "core-ng-api-9.5.1-b5.jar",
          "size": 11019,
          "sha512": "bad11a9558a036a596010b8ce2d90c6814c67709886b2125ceb4e14d1e465e6213f9ef26d5c96388ba74389041bd0138992592cef3e8c65cdb16e11b4a66e5a4",
          "sha256": "95b57d76fc5ec87be274898ba9f50ff22c2f833498e7a791614080728978c58d",
          "sha1": "599ab52e09c9c658e2b6bf0a6bc04a7de5849279",
          "md5": "e5016514f70c1851d1ffe0549e244c38"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-api-9.5.1-b5.jar",
          "url": "core-ng-api-9.5.1-b5.jar",
          "size": 11019,
          "sha512": "bad11a9558a036a596010b8ce2d90c6814c67709886b2125ceb4e14d1e465e6213f9ef26d5c96388ba74389041bd0138992592cef3e8c65cdb16e11b4a66e5a4",
          "sha256": "95b57d76fc5ec87be274898ba9f50ff22c2f833498e7a791614080728978c58d",
          "sha1": "599ab52e09c9c658e2b6bf0a6bc04a7de5849279",
          "md5": "e5016514f70c1851d1ffe0549e244c38"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.5.1-b5-sources.jar",
          "url": "core-ng-api-9.5.1-b5-sources.jar",
          "size": 8664,
          "sha512": "fb62715d8daa4311a064bb5b52324390e7084ff90ecbb709c42e8134fb7e3a3a081a8337423b7f93dc0f17dc35e229f4b2cf5c2ec6bb3180701bba5a18852e8f",
          "sha256": "75d5b7bc207eadb53c6016d94f0ce133af5bf3b01341e45ec3242da9222c5374",
          "sha1": "14347d1bc1fce6ca79a65cbc8c8bc3d258856e45",
          "md5": "d40632d0af2d2a598419069ecaf2ffb2"
        }
      ]
    }
  ]
}
