{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "9.4.0-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.4.0-b0"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.18.1"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.4.0-b0.jar",
          "url": "core-ng-search-9.4.0-b0.jar",
          "size": 56013,
          "sha512": "ab632e45c792473f02f1f623727742081109af20121692ee5cf7bff2cb8b2ca4d091dc2d4252de829af41ee7101fc282c11124429f4955483970e818afbd0533",
          "sha256": "1f01e4a85fb068016299c84d669dc917d7e377d64a3e2ea8b61ead8ec195d976",
          "sha1": "ec314301cc5abadc72b0334c0b4e184a55dfbefd",
          "md5": "ea5e4e0f37ac6e35c376d708443f3ccf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.4.0-b0"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.18.1"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.4.0-b0.jar",
          "url": "core-ng-search-9.4.0-b0.jar",
          "size": 56013,
          "sha512": "ab632e45c792473f02f1f623727742081109af20121692ee5cf7bff2cb8b2ca4d091dc2d4252de829af41ee7101fc282c11124429f4955483970e818afbd0533",
          "sha256": "1f01e4a85fb068016299c84d669dc917d7e377d64a3e2ea8b61ead8ec195d976",
          "sha1": "ec314301cc5abadc72b0334c0b4e184a55dfbefd",
          "md5": "ea5e4e0f37ac6e35c376d708443f3ccf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-9.4.0-b0-sources.jar",
          "url": "core-ng-search-9.4.0-b0-sources.jar",
          "size": 23531,
          "sha512": "8e753dc127d4045f68393aa940635f574e0d8e4de558bf0f092ac05f788913c691eae20f20ba31f5801ad5a97a6b224d30b6146bd847c8502da081094b88a91f",
          "sha256": "f2c74fe04bbd9009c7c210d4cdb1f30a184c20946b4bdb017f2b6fe9bc766c0d",
          "sha1": "425486f63b558f48deea647f45d33501db64e1f2",
          "md5": "e1de6502592ca4aa2c48084143e53f0c"
        }
      ]
    }
  ]
}
