{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "7.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "64luh6lcivg6zgog357ghpewfm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-7.3.1.jar",
          "url": "core-ng-api-7.3.1.jar",
          "size": 10889,
          "sha512": "4bd305f667ab6461dbff4e84fff1e40009b077b2556c96b142f4eba78ea3a91003a190712852d950c13c61a5641dffad2a7492e3b0d353018943c4f20431aae9",
          "sha256": "d1fe35a085563b75ca1140ab1046ec62d40f5886a3baa75fa256883549e3e1ed",
          "sha1": "3d9049b233a679b1b1ab8fbe07cc9deb8eac49a5",
          "md5": "7d3396dec240a16033acdc6313840cba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.3.1.jar",
          "url": "core-ng-api-7.3.1.jar",
          "size": 10889,
          "sha512": "4bd305f667ab6461dbff4e84fff1e40009b077b2556c96b142f4eba78ea3a91003a190712852d950c13c61a5641dffad2a7492e3b0d353018943c4f20431aae9",
          "sha256": "d1fe35a085563b75ca1140ab1046ec62d40f5886a3baa75fa256883549e3e1ed",
          "sha1": "3d9049b233a679b1b1ab8fbe07cc9deb8eac49a5",
          "md5": "7d3396dec240a16033acdc6313840cba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.3.1-sources.jar",
          "url": "core-ng-api-7.3.1-sources.jar",
          "size": 8544,
          "sha512": "d363548e8a6cddc7686de90fd227122f1f0e45fd560da0f200a1909addfed9bb3a14ec5bb690a703c2e0bd4803f922d7780e528e6aeb1376fd1ea7cab23dc82a",
          "sha256": "ecc0fb14184222dabb4e8df01ca2ba78829bcd1de281a1279bf513eb9fb6ee37",
          "sha1": "e34a14dd2d9713d1e8471658f8aa3973398181b5",
          "md5": "20d3dfdae401d4de52af066b1ec3210a"
        }
      ]
    }
  ]
}
