{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "9.1.0-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-9.1.0-b1.jar",
          "url": "core-ng-api-9.1.0-b1.jar",
          "size": 10993,
          "sha512": "5b79232a227aebce2bb4dc10277e96059b01ff06b9c278e2df503ef68bdf4e440935df79dd15ae50783136c7d05239f4c6da7953992376fcb08094e42b41506a",
          "sha256": "d430d9c437476fbeb8c4ed67cb3a4d7fa1f999c1a39bd0bc220875c8c2ff2096",
          "sha1": "d0cf7d7dd049a1d3656af576685b21d4b2ddfdd4",
          "md5": "3abe152854954c69e090a69526b85edc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.1.0-b1.jar",
          "url": "core-ng-api-9.1.0-b1.jar",
          "size": 10993,
          "sha512": "5b79232a227aebce2bb4dc10277e96059b01ff06b9c278e2df503ef68bdf4e440935df79dd15ae50783136c7d05239f4c6da7953992376fcb08094e42b41506a",
          "sha256": "d430d9c437476fbeb8c4ed67cb3a4d7fa1f999c1a39bd0bc220875c8c2ff2096",
          "sha1": "d0cf7d7dd049a1d3656af576685b21d4b2ddfdd4",
          "md5": "3abe152854954c69e090a69526b85edc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.1.0-b1-sources.jar",
          "url": "core-ng-api-9.1.0-b1-sources.jar",
          "size": 8643,
          "sha512": "855601bbe62ea284b93074ac9e762c64112ea9822b9b6ec8c277616961c2ab11f16c8b506d2564a9c00efd89b858abe26ea86706aad357e807622d8791473517",
          "sha256": "5c7a975a89b3d7e6635e2dc4a0c32bedfd629585dd81a94577ab792ad24e18f3",
          "sha1": "f998ef7c5f475c8fa6194ac60e5912e18d0f6ccc",
          "md5": "89f69da905c41f2d1ec990999922c79c"
        }
      ]
    }
  ]
}
