{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "7.6.5-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "6ecqkefeljhonffelsxv5ejxx4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.6.5-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "7.6.5-b0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-7.6.5-b0.jar",
          "url": "core-ng-mongo-test-7.6.5-b0.jar",
          "size": 2385,
          "sha512": "4cc7291ae20475cf32a922db2e82ba54c824da0466998074de84ffbd47f6adde7e31ce9d5d48e42ff7483ca8f7c6a59a76188e134f3b2da867250b73f796320e",
          "sha256": "6db4050ccadfd1ea1fc8198413f8d31f678b98af8037aa4a73983532f1c09dc5",
          "sha1": "14ae5f8e424eee3993e3fbec88b6f20e6e17cc30",
          "md5": "180587b54f16f80f2c04882dc3b18561"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.36.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.6.5-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "7.6.5-b0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-7.6.5-b0.jar",
          "url": "core-ng-mongo-test-7.6.5-b0.jar",
          "size": 2385,
          "sha512": "4cc7291ae20475cf32a922db2e82ba54c824da0466998074de84ffbd47f6adde7e31ce9d5d48e42ff7483ca8f7c6a59a76188e134f3b2da867250b73f796320e",
          "sha256": "6db4050ccadfd1ea1fc8198413f8d31f678b98af8037aa4a73983532f1c09dc5",
          "sha1": "14ae5f8e424eee3993e3fbec88b6f20e6e17cc30",
          "md5": "180587b54f16f80f2c04882dc3b18561"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-7.6.5-b0-sources.jar",
          "url": "core-ng-mongo-test-7.6.5-b0-sources.jar",
          "size": 1723,
          "sha512": "098fa9eacfc21eae9c7e421d8e8049cf5df85deaee527641c3223c11567b52741f0b61f0f8a31d412aac57cafbdd56dc8c4a6bacabad0ca9169822d645f7b835",
          "sha256": "76797941174034dd7acb388cfb903f20f4831c839829e146449bef7b36564678",
          "sha1": "fb0e91e7374d14ede73b85a1dedb506a18a301cf",
          "md5": "477590bb893d1e26dba7ab3bdcf058f4"
        }
      ]
    }
  ]
}
