{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "9.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.1"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.0.1.jar",
          "url": "core-ng-search-9.0.1.jar",
          "size": 52862,
          "sha512": "fd0f7e894ed743c5b42e5a37e4ce7f0a4de8709efb04212ccf7d5da675affd67f52598e76c5782b0878fd440cc986de07ba689733264b395d5cd3f5b13eaec60",
          "sha256": "fbcfd6f058dbfeadbf2368eb51992a9bad9fedc0777aa2f9eca42eb460739744",
          "sha1": "dfa4e0e16f6ff237e35f9fdb6c2d30ed57a570d1",
          "md5": "dacd94bf9591f501f47f485f332d2888"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.3"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.1"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.0.1.jar",
          "url": "core-ng-search-9.0.1.jar",
          "size": 52862,
          "sha512": "fd0f7e894ed743c5b42e5a37e4ce7f0a4de8709efb04212ccf7d5da675affd67f52598e76c5782b0878fd440cc986de07ba689733264b395d5cd3f5b13eaec60",
          "sha256": "fbcfd6f058dbfeadbf2368eb51992a9bad9fedc0777aa2f9eca42eb460739744",
          "sha1": "dfa4e0e16f6ff237e35f9fdb6c2d30ed57a570d1",
          "md5": "dacd94bf9591f501f47f485f332d2888"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-9.0.1-sources.jar",
          "url": "core-ng-search-9.0.1-sources.jar",
          "size": 21976,
          "sha512": "843f9c1f926680a0865dce8127c34e760c13b1da565a7449713642ad28e5cabacf6eff0ac9fbb18426be3321696f15fc4e2e1ab72c00533c875828ff85b1b291",
          "sha256": "26d8156badc6c2df84b2a110e3f32faefd47143f25184b910edd5b6eb4333881",
          "sha1": "36f986cccd904a188a73b043ce4ef2ee01d9aee5",
          "md5": "c456a4829fd50ff5e2c62578999eebf8"
        }
      ]
    }
  ]
}
