{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "9.1.7-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.7-b1"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.1.7-b1.jar",
          "url": "core-ng-search-9.1.7-b1.jar",
          "size": 54148,
          "sha512": "1331849a4ff9aad3a32da117765f5d9234f376314e82089cc0f28de52a9510b09b4a1b98d7f874a445ca8e5c5400c35e1ee3ff472fbda23aa3cdfc179791a7d2",
          "sha256": "11c42a7401c4af1c2e953c04defbba0bf76d1824971d674ab0e924030148f1ae",
          "sha1": "2b9ec0370a29b065f7b4d56c679644e3df6964a2",
          "md5": "44aa2701ba2d9d811bdf03dc84bcf4d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.7-b1"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.1.7-b1.jar",
          "url": "core-ng-search-9.1.7-b1.jar",
          "size": 54148,
          "sha512": "1331849a4ff9aad3a32da117765f5d9234f376314e82089cc0f28de52a9510b09b4a1b98d7f874a445ca8e5c5400c35e1ee3ff472fbda23aa3cdfc179791a7d2",
          "sha256": "11c42a7401c4af1c2e953c04defbba0bf76d1824971d674ab0e924030148f1ae",
          "sha1": "2b9ec0370a29b065f7b4d56c679644e3df6964a2",
          "md5": "44aa2701ba2d9d811bdf03dc84bcf4d0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-9.1.7-b1-sources.jar",
          "url": "core-ng-search-9.1.7-b1-sources.jar",
          "size": 22302,
          "sha512": "f3ade173a16576af065cca6cff1cfa8999be300960a890843621e80795e54d9a6063715930a8a3f4cd58c89e674f1dad25b52b444a5d65e68ef56c07ff8e2f22",
          "sha256": "869e563ba792ff2380a2ab07e1667a9d14a8a6c54e6cdb2fc47f15ed20da4225",
          "sha1": "f23c74c418062cd54f402b7aa8f6fd970d03a5bf",
          "md5": "14fe33d69ff974709042ef15a1eaf54d"
        }
      ]
    }
  ]
}
