{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "7.7.1-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-7.7.1-b1.jar",
          "url": "core-ng-api-7.7.1-b1.jar",
          "size": 10958,
          "sha512": "7f0d497cd007ddcd3b312029bb2234659963b0c8b96c6ca04926052973529e2094d446494aff058057420adab02d65427fbcef400fc471765272a2faced6570d",
          "sha256": "0cf1bf645ec3a209023b4be4d4e308436ce1570fc67defdc55c52d39945688c2",
          "sha1": "d198498bf0e5a3c14cedf31b109f5ea427ae8f45",
          "md5": "d31edba2af7fab5f60cc138e483e10fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.7.1-b1.jar",
          "url": "core-ng-api-7.7.1-b1.jar",
          "size": 10958,
          "sha512": "7f0d497cd007ddcd3b312029bb2234659963b0c8b96c6ca04926052973529e2094d446494aff058057420adab02d65427fbcef400fc471765272a2faced6570d",
          "sha256": "0cf1bf645ec3a209023b4be4d4e308436ce1570fc67defdc55c52d39945688c2",
          "sha1": "d198498bf0e5a3c14cedf31b109f5ea427ae8f45",
          "md5": "d31edba2af7fab5f60cc138e483e10fa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.7.1-b1-sources.jar",
          "url": "core-ng-api-7.7.1-b1-sources.jar",
          "size": 8643,
          "sha512": "ead7640b1162952c03def376868e76300169df1400ce391d70e749cf4368c8b5a109840c9b110fa062b31cbc83381c9420b4c32f38804e63591041161f23f297",
          "sha256": "a61d86307debaf288049d23c3bb73d1807686fd23d0fd90dce27a1ad1115de05",
          "sha1": "a2c180c92cb98753449f91ef0ed0fec3125a4d18",
          "md5": "5ac082311d876dc3a8b8fd9cab2070f4"
        }
      ]
    }
  ]
}
