{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "9.2.3-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.12.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.2.3-b0.jar",
          "url": "core-ng-test-9.2.3-b0.jar",
          "size": 47308,
          "sha512": "fb7d12b33df44bcd7d327beb3c24b35afec4794cc068a9ee102a2449247a051b7744cc9a4596da2efbd9b6012aef1841e93f53e92df00e513cf616bbf3e206fc",
          "sha256": "7a4f51c2d443ce457bda188ee3f3547a796b98899de1f0dc187c835f1ae9a034",
          "sha1": "dde2e9ca02b2c88aa83a733323800feac634830e",
          "md5": "7d106ac9b799206986830a982997475c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.2.3-b0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.12.2"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.12.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.2.3-b0.jar",
          "url": "core-ng-test-9.2.3-b0.jar",
          "size": 47308,
          "sha512": "fb7d12b33df44bcd7d327beb3c24b35afec4794cc068a9ee102a2449247a051b7744cc9a4596da2efbd9b6012aef1841e93f53e92df00e513cf616bbf3e206fc",
          "sha256": "7a4f51c2d443ce457bda188ee3f3547a796b98899de1f0dc187c835f1ae9a034",
          "sha1": "dde2e9ca02b2c88aa83a733323800feac634830e",
          "md5": "7d106ac9b799206986830a982997475c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-9.2.3-b0-sources.jar",
          "url": "core-ng-test-9.2.3-b0-sources.jar",
          "size": 22559,
          "sha512": "713c5160a06d39617028dbcc74aa7cd88506bf14b94a40a862bcd032ac5411efccc9befc03c360b2e833375a6b38a99be3ae4730a04f5bbe9a60e2d12e6f4854",
          "sha256": "5870aa4783fb58ff081f85dbf8245dd768cfcbafba0e2b61dbb259638d7d52b9",
          "sha1": "4f66eccef7ddf5d0c7edec2aeeef3abd1c08917f",
          "md5": "5e644be939e375fe984baa507cb30b32"
        }
      ]
    }
  ]
}
