{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "9.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.0.5.jar",
          "url": "core-ng-mongo-test-9.0.5.jar",
          "size": 2386,
          "sha512": "5c1277cab558df38c50e36810ef09c972a51ec443aeea10e3932cc2b2f7a4c04cda3b3449f770c39d985d7264ac1418f9a7dc230caddbec4d5f4505e0539e1f9",
          "sha256": "e44bcb750d0a8a5a9f3ba2fca1dc2c163a3eee6f8221a0539072e8212090bb84",
          "sha1": "dc11df009c6849b9cbeea0a8a48bc17902078035",
          "md5": "de2a546a0270ad2b913a2f6f0800ff8d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.0.5"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "9.0.5"
          }
        },
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.44.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-9.0.5.jar",
          "url": "core-ng-mongo-test-9.0.5.jar",
          "size": 2386,
          "sha512": "5c1277cab558df38c50e36810ef09c972a51ec443aeea10e3932cc2b2f7a4c04cda3b3449f770c39d985d7264ac1418f9a7dc230caddbec4d5f4505e0539e1f9",
          "sha256": "e44bcb750d0a8a5a9f3ba2fca1dc2c163a3eee6f8221a0539072e8212090bb84",
          "sha1": "dc11df009c6849b9cbeea0a8a48bc17902078035",
          "md5": "de2a546a0270ad2b913a2f6f0800ff8d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.0.5-sources.jar",
          "url": "core-ng-mongo-test-9.0.5-sources.jar",
          "size": 1720,
          "sha512": "0c3ee9e1e389a0e89f56fd6ec4f6bff8b7f9554b8a02c54b39ea143f80967013fa21959a2147ecb12c77cf10aa3fa6c649fe1865c9aeab321ca6a1980255b17a",
          "sha256": "c57834e26301c3187e8de8a5946bfc845ebedd948fde0ccae8c9e65a457aa91d",
          "sha1": "df1206e03e1e9ffc502259f4ac984025237b0a4f",
          "md5": "8bd2d3ff4b0516c91219c7eee0dc2017"
        }
      ]
    }
  ]
}
