{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "7.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6",
      "buildId": "jdhsmwlbjvg6foywe56zxxdxk4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.5.6"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.5.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.5.6.jar",
          "url": "core-ng-search-test-7.5.6.jar",
          "size": 9044,
          "sha512": "3ba9f2aa99d617d962b83237a8e8b3693aabea60942fca130c0a86deed3cdbbf17ee37e4254e328ba35203d4d36a5a737a16aebdeb8d27ba897be9dcaa02128a",
          "sha256": "461f19d15d03f407f6b003cc5ed1811351001b33d4a054d5a80085ab21480973",
          "sha1": "c9130eb37468e6b49374c251aef0c93a9b7b217d",
          "md5": "01e3eb2ca4176774ebd0f531664ca767"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4-client",
          "version": {
            "requires": "7.9.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "reindex-client",
          "version": {
            "requires": "7.9.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "7.9.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "7.9.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "7.9.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.5.6"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.5.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.5.6.jar",
          "url": "core-ng-search-test-7.5.6.jar",
          "size": 9044,
          "sha512": "3ba9f2aa99d617d962b83237a8e8b3693aabea60942fca130c0a86deed3cdbbf17ee37e4254e328ba35203d4d36a5a737a16aebdeb8d27ba897be9dcaa02128a",
          "sha256": "461f19d15d03f407f6b003cc5ed1811351001b33d4a054d5a80085ab21480973",
          "sha1": "c9130eb37468e6b49374c251aef0c93a9b7b217d",
          "md5": "01e3eb2ca4176774ebd0f531664ca767"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.5.6-sources.jar",
          "url": "core-ng-search-test-7.5.6-sources.jar",
          "size": 5424,
          "sha512": "bdd515e1ef5afb97dc8e62dc8c40e2bfdead14f3a6b25e61142545604d72b995b7959ce5b0eb35ecac495597e8eb504f0ae3fb07049688913acfba23169ae0aa",
          "sha256": "9656e9fd0b079d13fcd8a75ce05e8008187de15882624a6f33cb812e5fbcc690",
          "sha1": "a8639ce36a8fb37cccf5ff2e8f2148ca7f199ff7",
          "md5": "2b80a706f8628d8d9252dfbb3f61d353"
        }
      ]
    }
  ]
}
