{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "7.4.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "3mlsin3fvvb55bqty7rjpsuugu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.4.1.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.4.1.1.jar",
          "url": "core-ng-search-test-7.4.1.1.jar",
          "size": 8918,
          "sha512": "eae25ece6fe08e0f62f43c6511bb0339bd2717deede3f16632e65408ca67a9b38b4ee8dd888b5ae539966cd2358376316b5b68fed27d2a0d99aef7ca98c34718",
          "sha256": "956248246a1a7383265147b4979a6afd9332e6b3a906ff4f9972c719d2b0732d",
          "sha1": "d4802ced15b2fdd6b1f43513f6c87fb9e1b71c72",
          "md5": "9d65a8090291025a82435abb5313df98"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4-client",
          "version": {
            "requires": "7.6.2"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "reindex-client",
          "version": {
            "requires": "7.6.2"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "7.6.2"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "7.6.2"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "7.6.2"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.4.1.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.4.1.1.jar",
          "url": "core-ng-search-test-7.4.1.1.jar",
          "size": 8918,
          "sha512": "eae25ece6fe08e0f62f43c6511bb0339bd2717deede3f16632e65408ca67a9b38b4ee8dd888b5ae539966cd2358376316b5b68fed27d2a0d99aef7ca98c34718",
          "sha256": "956248246a1a7383265147b4979a6afd9332e6b3a906ff4f9972c719d2b0732d",
          "sha1": "d4802ced15b2fdd6b1f43513f6c87fb9e1b71c72",
          "md5": "9d65a8090291025a82435abb5313df98"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.4.1.1-sources.jar",
          "url": "core-ng-search-test-7.4.1.1-sources.jar",
          "size": 5093,
          "sha512": "3433ef1a99f54e67683e4254ee0f7582eadc79a5408e8cba25612ce52fefc15852da45f8b8a99b2004258184c121d6b9e090f7bbaba6a5adfb0dffaf2df4010c",
          "sha256": "8b1fb6d5b5652c9fd47094d87e69f4e928d83ee85d4beef16498d6735d6e27bb",
          "sha1": "2d8435c6b52b42391bf7e3fe1a680574e96058f8",
          "md5": "9dbad6fbe7ba7ea85e5e5cf4fcb4959e"
        }
      ]
    }
  ]
}
