{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "9.1.7-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.7-b0"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.1.7-b0.jar",
          "url": "core-ng-search-9.1.7-b0.jar",
          "size": 54148,
          "sha512": "b0eb33076304a58f1d91a487c3a4ca3a4c7cecce6ea6f397eaa41ae1ce65804787048240b56f725999552473c41f68b852fc44206627c579ba4e4e40577d7f56",
          "sha256": "6844715a766421d70950c6a7c92f97be38f13422c21ff332e6064f6a54f04948",
          "sha1": "df7ad0f0cb3e589b65ff52dfd3cab712f0cccb9d",
          "md5": "787db2fd51a27c9e8436b6d0d50661f3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.7-b0"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.1.7-b0.jar",
          "url": "core-ng-search-9.1.7-b0.jar",
          "size": 54148,
          "sha512": "b0eb33076304a58f1d91a487c3a4ca3a4c7cecce6ea6f397eaa41ae1ce65804787048240b56f725999552473c41f68b852fc44206627c579ba4e4e40577d7f56",
          "sha256": "6844715a766421d70950c6a7c92f97be38f13422c21ff332e6064f6a54f04948",
          "sha1": "df7ad0f0cb3e589b65ff52dfd3cab712f0cccb9d",
          "md5": "787db2fd51a27c9e8436b6d0d50661f3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-9.1.7-b0-sources.jar",
          "url": "core-ng-search-9.1.7-b0-sources.jar",
          "size": 22302,
          "sha512": "9b5ee1891cdf90255b04519c4eb158f2a74fabb69e1328d466007f1168d20b37a8c7b2bc3f9c94e334ba851c5e8e36f55ad81c038f780df62e94f6013d2a5a2f",
          "sha256": "8c82194e4b9a33eb7731a3356d40eac8af1f3d22861001aab3db64487211b1a0",
          "sha1": "7ad273cdb38f69dea437aba2c924d88b069fb66c",
          "md5": "25c3efd068f0ed84155eff821d83ac15"
        }
      ]
    }
  ]
}
