{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "7.6.8-b2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "proo64g6nrfkppc7ucepn5zmyu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.8-b2"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "7.10.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "elasticsearch",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch-x-content",
          "version": {
            "requires": "7.10.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "elasticsearch-x-content",
              "type": "jar",
              "extension": "jar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.6.8-b2.jar",
          "url": "core-ng-search-7.6.8-b2.jar",
          "size": 38506,
          "sha512": "fd45a7b35b3ec1dd60a79103e5a9851515692181ac9924cfa1429ee8bbbb0273e6e47bb0f5532772f887e195b74420eb1ce470e5c5e308d8993e2bfb494b9a99",
          "sha256": "42f41bfeda1c9e2e5da164a3b63fca6db1a592d2a0a94c7ef1f602f552985067",
          "sha1": "46995503bc569681f24698eed84ef06a142e3937",
          "md5": "a13183e007f45d31f55b5f0987a53bee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.elasticsearch.client",
          "module": "elasticsearch-rest-high-level-client",
          "version": {
            "requires": "7.10.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.8-b2"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "7.10.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "elasticsearch",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch-x-content",
          "version": {
            "requires": "7.10.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "elasticsearch-x-content",
              "type": "jar",
              "extension": "jar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.6.8-b2.jar",
          "url": "core-ng-search-7.6.8-b2.jar",
          "size": 38506,
          "sha512": "fd45a7b35b3ec1dd60a79103e5a9851515692181ac9924cfa1429ee8bbbb0273e6e47bb0f5532772f887e195b74420eb1ce470e5c5e308d8993e2bfb494b9a99",
          "sha256": "42f41bfeda1c9e2e5da164a3b63fca6db1a592d2a0a94c7ef1f602f552985067",
          "sha1": "46995503bc569681f24698eed84ef06a142e3937",
          "md5": "a13183e007f45d31f55b5f0987a53bee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-7.6.8-b2-sources.jar",
          "url": "core-ng-search-7.6.8-b2-sources.jar",
          "size": 17332,
          "sha512": "c2f1d4977446fe675b9b28caa24a30d3b4ff05bac6ed75d9c6837f23b9e46b0c0f4a4684914ddd9e1bf80c5b62de210eac4e4eb18c87ab927817ae8446f32e74",
          "sha256": "78dfec3062f16d594a7a362319e04b8fef69ad3f7bc89a59742fa539dc83b84d",
          "sha1": "5d6a8e8726f132a3ad2a14ce18b65da95e0fb413",
          "md5": "907c4bf81ba85260e3b5fade3b19498d"
        }
      ]
    }
  ]
}
