{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "7.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6",
      "buildId": "h3ykjmscdjhkxmcdqeg36exz5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.6.0.jar",
          "url": "core-ng-mongo-7.6.0.jar",
          "size": 53969,
          "sha512": "fea4f25273e24ac901de0f00e4f94d2a92c6481eeaa55c8aa66907799d3df6aebce210e12d56ea43a187015b454fe9f5ba416b1d1a7b11ed848395a2227d8cd0",
          "sha256": "00daf9f687667833c9c7f7519e74ea6c70f61ecba9379ccabb6640a503423e9c",
          "sha1": "17093640be9ae4190e58470568de6a26b95f1af5",
          "md5": "fb7894683038b37caac35d42182be320"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.6.0.jar",
          "url": "core-ng-mongo-7.6.0.jar",
          "size": 53969,
          "sha512": "fea4f25273e24ac901de0f00e4f94d2a92c6481eeaa55c8aa66907799d3df6aebce210e12d56ea43a187015b454fe9f5ba416b1d1a7b11ed848395a2227d8cd0",
          "sha256": "00daf9f687667833c9c7f7519e74ea6c70f61ecba9379ccabb6640a503423e9c",
          "sha1": "17093640be9ae4190e58470568de6a26b95f1af5",
          "md5": "fb7894683038b37caac35d42182be320"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-7.6.0-sources.jar",
          "url": "core-ng-mongo-7.6.0-sources.jar",
          "size": 25335,
          "sha512": "bbf447d3b3d09c9f9721f1a9cd08649791a7c97e1b850f99bcd2e2b80b9c970153be1c53c398df8abd52d5993de041fdf61fb7b82b3552a392d37fd600a2c11b",
          "sha256": "8eb06fd24fdb0ff8e29f4d758a5cf02c75a5559e3200a4d5f0692572fcc0a95d",
          "sha1": "2eda1976e215bb931e6006cd90561355bf5933d1",
          "md5": "534d352cbdae7627bf0c74ddd2c9b339"
        }
      ]
    }
  ]
}
