{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "7.6.5-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "6ecqkefeljhonffelsxv5ejxx4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.5-b0"
          }
        },
        {
          "group": "org.elasticsearch.client",
          "module": "elasticsearch-rest-high-level-client",
          "version": {
            "requires": "7.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.6.5-b0.jar",
          "url": "core-ng-search-7.6.5-b0.jar",
          "size": 38504,
          "sha512": "8edb142ed511d42ad23a16999820df0fc0397ebbf9bd60575d22fccb23ffd7e841588941f231f3f20c09295de1fbcd6a1a70a684b2af2e313ff3c0262e9751eb",
          "sha256": "ad71fe16fb34e3b8ea6f8cc9d8ef86b71e917b6f194752322d5b0183cb006359",
          "sha1": "d3392c9906d7ffcd77d5862dc81a4db08b614b5d",
          "md5": "b54cf840485799c131fcfef89fa9ec79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.5-b0"
          }
        },
        {
          "group": "org.elasticsearch.client",
          "module": "elasticsearch-rest-high-level-client",
          "version": {
            "requires": "7.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.6.5-b0.jar",
          "url": "core-ng-search-7.6.5-b0.jar",
          "size": 38504,
          "sha512": "8edb142ed511d42ad23a16999820df0fc0397ebbf9bd60575d22fccb23ffd7e841588941f231f3f20c09295de1fbcd6a1a70a684b2af2e313ff3c0262e9751eb",
          "sha256": "ad71fe16fb34e3b8ea6f8cc9d8ef86b71e917b6f194752322d5b0183cb006359",
          "sha1": "d3392c9906d7ffcd77d5862dc81a4db08b614b5d",
          "md5": "b54cf840485799c131fcfef89fa9ec79"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-7.6.5-b0-sources.jar",
          "url": "core-ng-search-7.6.5-b0-sources.jar",
          "size": 17330,
          "sha512": "6642b6d8cf311dce85557badb414b42158f45126373256387b42bb2ffc20de3c1e2e04d52fdb4126039ee80110c204c6e7eae6c662a194ccd2069c376e804dfb",
          "sha256": "a5ee561c426db8e0c6bd83f354e0dba359249d52fe24aa5d354c9b2fb60ef546",
          "sha1": "5dbbc240557bae6d8365314e757018cae3ad3c22",
          "md5": "a3870fb613d8960620c313a0774cb19a"
        }
      ]
    }
  ]
}
