{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "7.4.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "tqy7fljmmbcltjbqhzgqot55se"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.4.14"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.4.14.jar",
          "url": "core-ng-7.4.14.jar",
          "size": 639481,
          "sha512": "bd6f20a4270d3e9366e4ff63463102d92fcaa5560b8d3130dd71b66738536a9686aadb72f1fc717d33de74eb7d77c8a8009e6c280247746744773094b7f99c29",
          "sha256": "8abd86be340508b75cca2586a740ced7e3a537bf479dc901df6dae433d608fb4",
          "sha1": "3ff651c52acb5e86f097f2a94221989640eac229",
          "md5": "ea09d9b5f6e5b67c8cd22654ff194702"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.27.0-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.10.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.10.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.1.3.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.4.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.7.5"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.4.14"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.4.14.jar",
          "url": "core-ng-7.4.14.jar",
          "size": 639481,
          "sha512": "bd6f20a4270d3e9366e4ff63463102d92fcaa5560b8d3130dd71b66738536a9686aadb72f1fc717d33de74eb7d77c8a8009e6c280247746744773094b7f99c29",
          "sha256": "8abd86be340508b75cca2586a740ced7e3a537bf479dc901df6dae433d608fb4",
          "sha1": "3ff651c52acb5e86f097f2a94221989640eac229",
          "md5": "ea09d9b5f6e5b67c8cd22654ff194702"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-7.4.14-sources.jar",
          "url": "core-ng-7.4.14-sources.jar",
          "size": 327734,
          "sha512": "81ee775eabe197d5ee801d0530ffe92fee5ed03127043455c6b10bed08ded7dcb92bcb15c1848d8c399185f78af39e42d259771f5222d29e081693484301a06c",
          "sha256": "159b71e6b8ed4453c8d40fc28423819b2ecf6a42024544ef48cd62a7786a037d",
          "sha1": "bfd50ed64f1c74760e103f84ac16fc110a62c003",
          "md5": "5b1ade3a9d78ea8b103b5cd4c88ca87c"
        }
      ]
    }
  ]
}
