{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "9.4.0-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.4.0-b1"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.18.1"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.4.0-b1.jar",
          "url": "core-ng-search-9.4.0-b1.jar",
          "size": 56011,
          "sha512": "a4b0100832c96daa4d86f6f92eeba24a29e842e8c6cf37d2bd996e9c699162b0301233964057915e50bf70634476dc26d7f6b5678ad71deace5f2f96c8cc0ad3",
          "sha256": "360c9ae59629a138c194df5391b905c4ec8f32a122b66cf692ebeeb7197b1ae5",
          "sha1": "a6b7e9df29e7d5b7ee9ff84aae7eeeca3445c263",
          "md5": "a0138f4889ed772c516f2a76d2617648"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.4.0-b1"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.18.1"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.4.0-b1.jar",
          "url": "core-ng-search-9.4.0-b1.jar",
          "size": 56011,
          "sha512": "a4b0100832c96daa4d86f6f92eeba24a29e842e8c6cf37d2bd996e9c699162b0301233964057915e50bf70634476dc26d7f6b5678ad71deace5f2f96c8cc0ad3",
          "sha256": "360c9ae59629a138c194df5391b905c4ec8f32a122b66cf692ebeeb7197b1ae5",
          "sha1": "a6b7e9df29e7d5b7ee9ff84aae7eeeca3445c263",
          "md5": "a0138f4889ed772c516f2a76d2617648"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-9.4.0-b1-sources.jar",
          "url": "core-ng-search-9.4.0-b1-sources.jar",
          "size": 23529,
          "sha512": "bfcb8bc144c0da4296fe080d50e927367503fe06ca15f5923abaa48095c1094679195fb202275686dd3a814147a91c6d0f8dcfe5ad41e38bbdd06604a27c4e8b",
          "sha256": "da36921fed5f8db5f1b8a39c0a39ccf134246a38371917a6cf03f097ec35e71a",
          "sha1": "728609cdc609e942cb7f47896f27bfa569ea05bf",
          "md5": "0fbbadb0ee9073db51d48c54e06a1a0b"
        }
      ]
    }
  ]
}
