{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.0.10"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.0.10.jar",
          "url": "core-ng-9.0.10.jar",
          "size": 740339,
          "sha512": "39f7e0116c554b814a33a7c3ccc13d0f823e184209ca0b1fceb5ce59e2f46cc641a62086aebbc3a2170566a63374eca0b66f7e0e4ab96a026b37998a06994600",
          "sha256": "de6895457e1ddc6db443738f433e894a10afeb795926e8233a8ff7fe2d40b7d6",
          "sha1": "5c552eed1dcf2cc3e70c5825af677e64a615eddf",
          "md5": "faaeff2ebbe9157cf9b7dd16c40eadc6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "okhttp",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.10.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "3.7.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.10.5"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.0.10"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.0.10.jar",
          "url": "core-ng-9.0.10.jar",
          "size": 740339,
          "sha512": "39f7e0116c554b814a33a7c3ccc13d0f823e184209ca0b1fceb5ce59e2f46cc641a62086aebbc3a2170566a63374eca0b66f7e0e4ab96a026b37998a06994600",
          "sha256": "de6895457e1ddc6db443738f433e894a10afeb795926e8233a8ff7fe2d40b7d6",
          "sha1": "5c552eed1dcf2cc3e70c5825af677e64a615eddf",
          "md5": "faaeff2ebbe9157cf9b7dd16c40eadc6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.0.10-sources.jar",
          "url": "core-ng-9.0.10-sources.jar",
          "size": 380916,
          "sha512": "a245b4e2eb44034b2ade240443d79bd4942157c917d290209c4fd3b81c8781576dc10fa49b5bf839b0826168df3a2bfd0c699bba1fda98f0d0ef9b4f96e82c42",
          "sha256": "2b69b745e32ce7037d702972ae8586e473f502c3eeef0cc7ee35fa3e46c5e654",
          "sha1": "e3762ed3e294cb54b34e111e4117e9eb271e9f63",
          "md5": "391f2f774759205e5f19d0addc6d0010"
        }
      ]
    }
  ]
}
