{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "7.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.7.1"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.7.1.jar",
          "url": "core-ng-mongo-7.7.1.jar",
          "size": 53968,
          "sha512": "7bcafef7d2433854a8b18fd7bf812bfe240b9102601c88366b345e119493635a5ada23348c378070c711dd8e149685bd5bdab32ab314c859b820def629893033",
          "sha256": "ab118b9fd2401642a7a3e6c0561bb5bf6f51c8082aedfb9989d17ea0e56e222a",
          "sha1": "1b76f9d80efc68f52e1adb6233526d133ef0d1e7",
          "md5": "13f72d50621b651cc594b82f1af81cea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.7.1"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.7.1.jar",
          "url": "core-ng-mongo-7.7.1.jar",
          "size": 53968,
          "sha512": "7bcafef7d2433854a8b18fd7bf812bfe240b9102601c88366b345e119493635a5ada23348c378070c711dd8e149685bd5bdab32ab314c859b820def629893033",
          "sha256": "ab118b9fd2401642a7a3e6c0561bb5bf6f51c8082aedfb9989d17ea0e56e222a",
          "sha1": "1b76f9d80efc68f52e1adb6233526d133ef0d1e7",
          "md5": "13f72d50621b651cc594b82f1af81cea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-7.7.1-sources.jar",
          "url": "core-ng-mongo-7.7.1-sources.jar",
          "size": 25321,
          "sha512": "79b9ecaa16fb74580dbc64892b6ba8d2d2432cb0732c34e94ecf5a5f8518b170e99136bf993c63a6131c29b57cc5c5abead0710e585f683bf0bab2a35ac0cd63",
          "sha256": "e65f9d47a653a14c4205e1b39095e228b308df68593e9e374630a7f090ca39f1",
          "sha1": "7f2a49e51197f161f178e0731faee85beec417d2",
          "md5": "afbe1c76df6f443ff6cf604b08c24cd8"
        }
      ]
    }
  ]
}
