{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "7.6.2-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "5jfivrnadrg73pcyjgmirgtp24"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.2-b0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.5.13"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.6.2-b0.jar",
          "url": "core-ng-test-7.6.2-b0.jar",
          "size": 39068,
          "sha512": "698efe5b6ab73aabb6935d86c9d447eb4aeb5a22a7a5573e0d46ca0960567da24898df202178b5c8c43c326618a6baf94e45d01314ccc1cbc89d51f8f2175ae2",
          "sha256": "15dddb06126d4d5395660ac419158b4c08528ec5a1dd3bb4bb90849c8e514633",
          "sha1": "a6d66864c2aaeca0f0ebbbbbc16e640dbc2b38d2",
          "md5": "ceb1c816d83586947f2a1d3ab48546a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.4.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.2-b0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.5.13"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.6.2-b0.jar",
          "url": "core-ng-test-7.6.2-b0.jar",
          "size": 39068,
          "sha512": "698efe5b6ab73aabb6935d86c9d447eb4aeb5a22a7a5573e0d46ca0960567da24898df202178b5c8c43c326618a6baf94e45d01314ccc1cbc89d51f8f2175ae2",
          "sha256": "15dddb06126d4d5395660ac419158b4c08528ec5a1dd3bb4bb90849c8e514633",
          "sha1": "a6d66864c2aaeca0f0ebbbbbc16e640dbc2b38d2",
          "md5": "ceb1c816d83586947f2a1d3ab48546a6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-7.6.2-b0-sources.jar",
          "url": "core-ng-test-7.6.2-b0-sources.jar",
          "size": 19184,
          "sha512": "e25cf172abd9f5239d5a8577bfd1baf1a0cbb553d685a8ce212196afcedf403b51e988399f4a9cd99a20e21900fbfae4baafd2202b90e631c5fae499a790814c",
          "sha256": "28591e38ac5461488505b82ce6c50bdfaaf60356de605339ee6cd042202b4013",
          "sha1": "1fea62a3f0637953adfbf2f6caa538bbe4309bb9",
          "md5": "661a5d66e36bc01e67c90f7881afe366"
        }
      ]
    }
  ]
}
