{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "9.1.1-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.1-b1"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.1.1-b1.jar",
          "url": "core-ng-search-9.1.1-b1.jar",
          "size": 52826,
          "sha512": "ad84f129feab5bdd138174a13fe0ed84df943df2b1245319fbeb6445d43fde7125e70351b98bc324cb32c5dd546ba56fdb0ca5bfaf26bfa0b6101960f973e1b4",
          "sha256": "1bb45cd4e048a9933ae3c926a7115824dde349721972d31b43c75a7165cfd4d0",
          "sha1": "426e4d17523b11211342fd9c1752fe4938b78e1d",
          "md5": "fabd9385973b654c8cfb1e2546fbbce6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.1-b1"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.1.1-b1.jar",
          "url": "core-ng-search-9.1.1-b1.jar",
          "size": 52826,
          "sha512": "ad84f129feab5bdd138174a13fe0ed84df943df2b1245319fbeb6445d43fde7125e70351b98bc324cb32c5dd546ba56fdb0ca5bfaf26bfa0b6101960f973e1b4",
          "sha256": "1bb45cd4e048a9933ae3c926a7115824dde349721972d31b43c75a7165cfd4d0",
          "sha1": "426e4d17523b11211342fd9c1752fe4938b78e1d",
          "md5": "fabd9385973b654c8cfb1e2546fbbce6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-9.1.1-b1-sources.jar",
          "url": "core-ng-search-9.1.1-b1-sources.jar",
          "size": 21981,
          "sha512": "d4800e0c9fbb4bea00e6e998d6665a335fe1722ec6e58a6ae741b3ee23574f860f1f206bcbe14441050971439c5ed3ddd22c928d5eb9e6f41102aa0d6378ea80",
          "sha256": "eeb78abbd2b65661aaa7cda5c43fde2984f81b513030f5f174926cd3306d8c89",
          "sha1": "38b8240bc54097c8206452ab09f4482af6aabc96",
          "md5": "9e9c876234485041a6c7a7ccf00e9ab0"
        }
      ]
    }
  ]
}
