{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "9.1.1-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.1-b1"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.1.1-b1.jar",
          "url": "core-ng-search-9.1.1-b1.jar",
          "size": 52826,
          "sha512": "4ff649566d9348e3c1fcac0c0bd20acffff745f298092545b2f961220ca6d27dafdc243d34f8c388521642cc3209eda5ef850acc8fc829135017cdda9eb93743",
          "sha256": "c78caf5bbbbe7ed27e2c59cc17b302099cb096816f157c9cb87ee85a5e0787ec",
          "sha1": "c064f3cc80264b3ef8121ee42c53bdcc2af2d91e",
          "md5": "73aee1d8fee6ef685b5b8b15fa1cb472"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.1-b1"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.1.1-b1.jar",
          "url": "core-ng-search-9.1.1-b1.jar",
          "size": 52826,
          "sha512": "4ff649566d9348e3c1fcac0c0bd20acffff745f298092545b2f961220ca6d27dafdc243d34f8c388521642cc3209eda5ef850acc8fc829135017cdda9eb93743",
          "sha256": "c78caf5bbbbe7ed27e2c59cc17b302099cb096816f157c9cb87ee85a5e0787ec",
          "sha1": "c064f3cc80264b3ef8121ee42c53bdcc2af2d91e",
          "md5": "73aee1d8fee6ef685b5b8b15fa1cb472"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-9.1.1-b1-sources.jar",
          "url": "core-ng-search-9.1.1-b1-sources.jar",
          "size": 21981,
          "sha512": "ab9c3ad9e7e12f8c0aefc5dd9f5cd4a5048c8f3510c913f561ccad8344ac869b380c518825fc0dc7efa44e2d56643d8332a423aa6c568a06949caeb6f675a171",
          "sha256": "4c5591364bd7a21661153299f9ffa551ba5d4e42aaa208e8f662e6839ae3e5a5",
          "sha1": "8fd3aa2c0e1b698fdf738d132b06e89cb319e9bc",
          "md5": "1bbea6a4dc9263fc0dbee84ef2851b06"
        }
      ]
    }
  ]
}
