{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "9.5.1-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-api-9.5.1-b1.jar",
          "url": "core-ng-api-9.5.1-b1.jar",
          "size": 11018,
          "sha512": "f06709c927b4210f7e2e47a499a2301164e591150c6cc67bfc9cc81238441de4f5e5c44f25e26fc6021ae10819a6421be1657fc69d32a05973e7f0aa83116154",
          "sha256": "b354357e198f9d547565cc07dd9b662b38ac22d2056341ff80ecd841e7d468be",
          "sha1": "55d910b5385e8964b3e7f56fbb294a4744c5cb52",
          "md5": "e7913078a783c2b549d37ec2bf98ef13"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-api-9.5.1-b1.jar",
          "url": "core-ng-api-9.5.1-b1.jar",
          "size": 11018,
          "sha512": "f06709c927b4210f7e2e47a499a2301164e591150c6cc67bfc9cc81238441de4f5e5c44f25e26fc6021ae10819a6421be1657fc69d32a05973e7f0aa83116154",
          "sha256": "b354357e198f9d547565cc07dd9b662b38ac22d2056341ff80ecd841e7d468be",
          "sha1": "55d910b5385e8964b3e7f56fbb294a4744c5cb52",
          "md5": "e7913078a783c2b549d37ec2bf98ef13"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.5.1-b1-sources.jar",
          "url": "core-ng-api-9.5.1-b1-sources.jar",
          "size": 8663,
          "sha512": "8611b8002dd31be07cb81b78aac9506fba4896bf0331062c976a598f51e57506773cf716f00bcdabde847fde7c7a7d87e9c3002de0652f8aa25f702248456878",
          "sha256": "bb26002f9522330fd28100453fdf240a1747ede102b63bb302378127aedda51a",
          "sha1": "8265996f21b3784da968ad32e5f679c7ef3d9bdd",
          "md5": "db21a21442f83c8994c148dae67cb6b9"
        }
      ]
    }
  ]
}
