{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "7.4.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "tu5zh2lsu5chpeteqmpc5tiek4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.4.8"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.4.8.jar",
          "url": "core-ng-mongo-7.4.8.jar",
          "size": 54208,
          "sha512": "c81791fa3ccac4ac53c4d5d3578cfb2dab4bc829a55e5bb879eceeab85e110db7280bf650f6567246e30dcfa53293437b52cf581776e4a30f8cc6d9903a53ddd",
          "sha256": "cc3a752a371adbd933561844a2c7b0a62d9c0d6ca3312b475f0d52c3db0f8c93",
          "sha1": "1977ce603fb107c015369f237a2c5ce79113a733",
          "md5": "4d6c1460fcdea8df72c9ea862d814c98"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.4.8"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.4.8.jar",
          "url": "core-ng-mongo-7.4.8.jar",
          "size": 54208,
          "sha512": "c81791fa3ccac4ac53c4d5d3578cfb2dab4bc829a55e5bb879eceeab85e110db7280bf650f6567246e30dcfa53293437b52cf581776e4a30f8cc6d9903a53ddd",
          "sha256": "cc3a752a371adbd933561844a2c7b0a62d9c0d6ca3312b475f0d52c3db0f8c93",
          "sha1": "1977ce603fb107c015369f237a2c5ce79113a733",
          "md5": "4d6c1460fcdea8df72c9ea862d814c98"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-7.4.8-sources.jar",
          "url": "core-ng-mongo-7.4.8-sources.jar",
          "size": 25673,
          "sha512": "4521582ae612b299532d3b4d44465c0dd5c893faf6215c020f81ea7b41c833ebb2993b9711371875bbdbd5fe31bafed434addc6cd02c9adfbe38267d17363f07",
          "sha256": "5060ef51de7ce4c6403065a561fb62b812b3f3db21606ecc0464c3bff643c9ae",
          "sha1": "7c304d4f372b7c04ef0612a48523198b740413f3",
          "md5": "26f7b753ae89494bf8a542da930b8c5e"
        }
      ]
    }
  ]
}
