{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.5.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.5.1.jar",
          "url": "core-ng-9.5.1.jar",
          "size": 789964,
          "sha512": "80df0d13e9213b6afe1773565f28b04ff187e67d0621622dab454b02989dd5610619576d7212de33b4a74c71801b76d9a0b20be77af9a9fb813f713a39be6ed5",
          "sha256": "3d9a8b9f7ec5103725663b8bd0ae9e782d1a73e31118d98b022f25869f379f7d",
          "sha1": "042ecbb38ab9328fe3fcbadb78d8d7bd7fa21ab2",
          "md5": "43d85697f29dfb66e11019eb4af178d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "tools.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "tools.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.24.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "4.2.0"
          },
          "excludes": [
            {
              "group": "org.xerial.snappy",
              "module": "*"
            },
            {
              "group": "at.yawk.lz4",
              "module": "*"
            }
          ]
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.5.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.5.1.jar",
          "url": "core-ng-9.5.1.jar",
          "size": 789964,
          "sha512": "80df0d13e9213b6afe1773565f28b04ff187e67d0621622dab454b02989dd5610619576d7212de33b4a74c71801b76d9a0b20be77af9a9fb813f713a39be6ed5",
          "sha256": "3d9a8b9f7ec5103725663b8bd0ae9e782d1a73e31118d98b022f25869f379f7d",
          "sha1": "042ecbb38ab9328fe3fcbadb78d8d7bd7fa21ab2",
          "md5": "43d85697f29dfb66e11019eb4af178d5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.5.1-sources.jar",
          "url": "core-ng-9.5.1-sources.jar",
          "size": 406082,
          "sha512": "bb236d2dd57d73e529d309b469c0e4f2497c31418c796a142b56ef31ffba85930c36c645aacbc0bcffc39c10171c98c05faeaa377af618cbf756316967b2ff4b",
          "sha256": "192e0b7e488a3696f0bfa3de5461fa090aa3ae40d59333b1e0f0b08b00542fac",
          "sha1": "575b30263f7edbd6eefc6e053c4274cd671305f4",
          "md5": "851039055607c18ef446e2c8add94264"
        }
      ]
    }
  ]
}
