{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.1.6-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.6-b0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.1.6-b0.jar",
          "url": "core-ng-9.1.6-b0.jar",
          "size": 774430,
          "sha512": "e2ad638a5eb372844da363c8bc9621443bb96e80bd23dd11b53d337fdcbac3bcf24169e0b4c9757b5518fd849a7d4ab3e2a7ce9c236abe71e489ac9e7a2bc32d",
          "sha256": "feaeefaaa9d39519d0e392954ecf5694c1a13453f833f4659930e84e245d1770",
          "sha1": "0b88366de61b88e9b9bb0743d0e9cb13e52dd54c",
          "md5": "b893635db45d3b2671a4248e98d20011"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "okhttp",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.6-b0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.1.6-b0.jar",
          "url": "core-ng-9.1.6-b0.jar",
          "size": 774430,
          "sha512": "e2ad638a5eb372844da363c8bc9621443bb96e80bd23dd11b53d337fdcbac3bcf24169e0b4c9757b5518fd849a7d4ab3e2a7ce9c236abe71e489ac9e7a2bc32d",
          "sha256": "feaeefaaa9d39519d0e392954ecf5694c1a13453f833f4659930e84e245d1770",
          "sha1": "0b88366de61b88e9b9bb0743d0e9cb13e52dd54c",
          "md5": "b893635db45d3b2671a4248e98d20011"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.1.6-b0-sources.jar",
          "url": "core-ng-9.1.6-b0-sources.jar",
          "size": 395596,
          "sha512": "32ca91445a209569debb16e6d1d34793fc27089e168c2c681185f03b37cb6a90f17c468b0bd8981f1e2ad2dab69613898df47c38587cbe3fc7edac6596743a19",
          "sha256": "9997b6dfcea45848e24807b4e084da656e5dbe6ba938171409564fb334274767",
          "sha1": "e1436bc1e27e775b3b7a269173f76c7dcc3a2583",
          "md5": "dacd540bd3b1576b648e813d621c16ee"
        }
      ]
    }
  ]
}
