{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "7.6.4-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "d4bpwwgkvbhk5k3pu7mvcd3od4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.6.4-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "7.6.4-b0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-7.6.4-b0.jar",
          "url": "core-ng-mongo-test-7.6.4-b0.jar",
          "size": 2385,
          "sha512": "c43b3bc6e3f7e341617387529be64a1ab049392e46fbe96509c0063fac69a61d58dbd9ac95da7079fde6309a826e1c5b1fb81ea86f19d2a8988599dafdd5f06e",
          "sha256": "6fb15b58f38a3881a42bae7c62d9985798d0bbe1f6444b4bd2d607691e39312a",
          "sha1": "46eab4b5c6a45b2f17f39c8dde9efe0f3f982601",
          "md5": "f9ef7d9ada4e8b1e7274c98e0e6d9932"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.36.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.6.4-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "7.6.4-b0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-7.6.4-b0.jar",
          "url": "core-ng-mongo-test-7.6.4-b0.jar",
          "size": 2385,
          "sha512": "c43b3bc6e3f7e341617387529be64a1ab049392e46fbe96509c0063fac69a61d58dbd9ac95da7079fde6309a826e1c5b1fb81ea86f19d2a8988599dafdd5f06e",
          "sha256": "6fb15b58f38a3881a42bae7c62d9985798d0bbe1f6444b4bd2d607691e39312a",
          "sha1": "46eab4b5c6a45b2f17f39c8dde9efe0f3f982601",
          "md5": "f9ef7d9ada4e8b1e7274c98e0e6d9932"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-7.6.4-b0-sources.jar",
          "url": "core-ng-mongo-test-7.6.4-b0-sources.jar",
          "size": 1723,
          "sha512": "40f026deefa191df4dd041671ca51b452840e1ccd4ef2e69a587f7bd84f6d284d0140b71eb2990fd57599835fef1ef3b6487e13e6a3eb519b2936a5c3cd12a9f",
          "sha256": "75170d6dde586229da678b4f95cb930672ac8fb3c9d3463221db5026938e5989",
          "sha1": "a9f730d795e207f413d06fed80d07eeb0612cc50",
          "md5": "930c4f9733eacf16f24047db435d3cba"
        }
      ]
    }
  ]
}
