{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "9.5.1-b2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.5.1-b2"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.5.1-b2.jar",
          "url": "core-ng-mongo-9.5.1-b2.jar",
          "size": 60080,
          "sha512": "e51b94fc039a381ef5c8a4315831d0f406a160e967c6983cd88008cd935cb047eef224df5ed6224568f32966e412781abd41c79b3cb79407330f920d5e64c1aa",
          "sha256": "dc94060e5a0fdbe9d610901d5d14df3c9e830c0847ea9a1aed97064e671afc82",
          "sha1": "9b8608a1a258a3ab9083b57f610fcbcc3643e0ca",
          "md5": "b1a119ee94c9d216d48c7cae7b353793"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.5.1-b2"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.5.1-b2.jar",
          "url": "core-ng-mongo-9.5.1-b2.jar",
          "size": 60080,
          "sha512": "e51b94fc039a381ef5c8a4315831d0f406a160e967c6983cd88008cd935cb047eef224df5ed6224568f32966e412781abd41c79b3cb79407330f920d5e64c1aa",
          "sha256": "dc94060e5a0fdbe9d610901d5d14df3c9e830c0847ea9a1aed97064e671afc82",
          "sha1": "9b8608a1a258a3ab9083b57f610fcbcc3643e0ca",
          "md5": "b1a119ee94c9d216d48c7cae7b353793"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-9.5.1-b2-sources.jar",
          "url": "core-ng-mongo-9.5.1-b2-sources.jar",
          "size": 28819,
          "sha512": "8ebb735684558ae7c27328b261dd71b3a926ef38d1d29087d518cf7ebed1cf1cd8029daa178d0dcc0675ad5956f179e08cb3d560cad495da112daa18ed49cdab",
          "sha256": "25f4ac2cd2962431ccdae26c03b3bdb3a3db52de84df5e5e8c0fd7cfc40e76c5",
          "sha1": "685b171fe0f8b9e3e3e401f02241c48afd916794",
          "md5": "e855168b64ec061a5ce4e9c77770036a"
        }
      ]
    }
  ]
}
