{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "9.3.0-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-api-9.3.0-b1.jar",
          "url": "core-ng-api-9.3.0-b1.jar",
          "size": 11009,
          "sha512": "40e74b545ce84aecd06e414d30efe0d83f286e269eab601ebd2e7465f01170ecedc54072d21bf504f9d0e382ef9f7362b7b1244e6655f36fdf6c2b9649f9f1f0",
          "sha256": "de6244807e0b9ee27f3d2801e25a37c9aee08591fc1783d8774f54b1e34f8775",
          "sha1": "9fa683d7a1afa765dba67b2c718b2ad94ffdb7af",
          "md5": "f6d4b6febb40457a98551b18b1856cb9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-api-9.3.0-b1.jar",
          "url": "core-ng-api-9.3.0-b1.jar",
          "size": 11009,
          "sha512": "40e74b545ce84aecd06e414d30efe0d83f286e269eab601ebd2e7465f01170ecedc54072d21bf504f9d0e382ef9f7362b7b1244e6655f36fdf6c2b9649f9f1f0",
          "sha256": "de6244807e0b9ee27f3d2801e25a37c9aee08591fc1783d8774f54b1e34f8775",
          "sha1": "9fa683d7a1afa765dba67b2c718b2ad94ffdb7af",
          "md5": "f6d4b6febb40457a98551b18b1856cb9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.3.0-b1-sources.jar",
          "url": "core-ng-api-9.3.0-b1-sources.jar",
          "size": 8661,
          "sha512": "1f499ddff270ec7cf983581713ddb087f236de154332ba65fbb2dc77a857058f5a977f15b1f8711824312ba51e8a5faf2b2d4ae7380c27d17eb933233b17408a",
          "sha256": "dd7aa8c45d7dc00fd1cdadf8b107a14fcbddfdcb625d2519e1e4ce54790b55ca",
          "sha1": "142546876f2ec10b6278ac5abb63191a59742163",
          "md5": "c112cc2bdb0cf660b7ffe142f617091a"
        }
      ]
    }
  ]
}
