{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "9.1.7-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.1.7-b1.jar",
          "url": "core-ng-mongo-test-9.1.7-b1.jar",
          "size": 2488,
          "sha512": "d29fc8373060959780832ec78f463de470df20851d8dcfe2605f6d5cdb37a0a2e128fa64c26ffd4fec0a4a5bf19dd359d298ccd12f8c92ecfb90bc1172274b3f",
          "sha256": "d5b6611f264369f9ab2dc59606fadee024b22cbaf63b7aa86e25b30b3be88663",
          "sha1": "5ceecee8d30b4cee87edd5393a8a2f342576ddd8",
          "md5": "dc03dcdad058ddd57394b4e6a64bbaba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.1.7-b1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "9.1.7-b1"
          }
        },
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.46.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-9.1.7-b1.jar",
          "url": "core-ng-mongo-test-9.1.7-b1.jar",
          "size": 2488,
          "sha512": "d29fc8373060959780832ec78f463de470df20851d8dcfe2605f6d5cdb37a0a2e128fa64c26ffd4fec0a4a5bf19dd359d298ccd12f8c92ecfb90bc1172274b3f",
          "sha256": "d5b6611f264369f9ab2dc59606fadee024b22cbaf63b7aa86e25b30b3be88663",
          "sha1": "5ceecee8d30b4cee87edd5393a8a2f342576ddd8",
          "md5": "dc03dcdad058ddd57394b4e6a64bbaba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.1.7-b1-sources.jar",
          "url": "core-ng-mongo-test-9.1.7-b1-sources.jar",
          "size": 1780,
          "sha512": "c71de8c2a399ff969e2c6a3ee43f8992b36c18c1c904a4f41ada06c3ca3543130d499edf4d5c0ca86e4667492d87bbd2bd5fb77a7371fa29b0d6ca7c9b2acdc4",
          "sha256": "7f20d7cfa96744577a6af89c5fead609d60453be9d9221d15cd9c1c4c2024990",
          "sha1": "2a6137f59cf6da603a81a944815f5d4f006d2e94",
          "md5": "c2b92458439cb0cd7b8e64d9babbd2a7"
        }
      ]
    }
  ]
}
