{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "9.1.2-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.1.2-b0.jar",
          "url": "core-ng-search-test-9.1.2-b0.jar",
          "size": 13291,
          "sha512": "f2915e843a2bcbfbfbdaef2b26ec8dde192dd84d2cc482f0b5e6ea4e8d24812a42ca285b6d29bf7cb9670f2d5b006b371743e9c37315bae26041986e7398639e",
          "sha256": "f573c46e17dc0f0299827838e301ec2a8fd9b3f7712f55656ea49612ae97597d",
          "sha1": "eaba6cc6148be785cce6a7d7316f2f20fd6f2c3c",
          "md5": "95cf785d1bff891f57aacba279409190"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.1.2-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "9.1.2-b0"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "8.15.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4",
          "version": {
            "requires": "8.15.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "8.15.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "8.15.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "8.15.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "reindex",
          "version": {
            "requires": "8.15.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "reindex",
              "type": "jar",
              "extension": "jar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-9.1.2-b0.jar",
          "url": "core-ng-search-test-9.1.2-b0.jar",
          "size": 13291,
          "sha512": "f2915e843a2bcbfbfbdaef2b26ec8dde192dd84d2cc482f0b5e6ea4e8d24812a42ca285b6d29bf7cb9670f2d5b006b371743e9c37315bae26041986e7398639e",
          "sha256": "f573c46e17dc0f0299827838e301ec2a8fd9b3f7712f55656ea49612ae97597d",
          "sha1": "eaba6cc6148be785cce6a7d7316f2f20fd6f2c3c",
          "md5": "95cf785d1bff891f57aacba279409190"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.1.2-b0-sources.jar",
          "url": "core-ng-search-test-9.1.2-b0-sources.jar",
          "size": 7351,
          "sha512": "ffd42afb04671a1d2a8a953a9639a31e433665d5eee6b7073209b4403fee658f1ff64274a461a76c8c02f52cc0b379c5637dde2271041268b71c7415b4b3cbd7",
          "sha256": "faad6927c4647f91b9e1215b2ba9351b1da76df27fb365a6c978022e8faa863b",
          "sha1": "396cfbc26e7a6b98776acd5e2f6506fd9bb981e7",
          "md5": "7b48a6db11d7972944c29cbe55a6d1ef"
        }
      ]
    }
  ]
}
