{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework.mysql",
    "module": "mysql-connector-j",
    "version": "8.2.0-r2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mysql-connector-j-8.2.0-r2.jar",
          "url": "mysql-connector-j-8.2.0-r2.jar",
          "size": 820638,
          "sha512": "204c19ba7366ec2b57d3dd6fd6c9c8a36a7c154083a2883f71f547a861c56db9092dd21832cd9be61a2842fe6ab852cb75464dd45e4f740885a7b34f63150a8f",
          "sha256": "d97dcbbcc57b2ffafcc77d479c3cb45ac8809353c4b6c987663c21ccd013d6ea",
          "sha1": "f13e056e0e5fd0e6db378fbe4e3a27f5511775e0",
          "md5": "f02b8e1134f55c5e1e24f4b32c9d5e76"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mysql-connector-j-8.2.0-r2.jar",
          "url": "mysql-connector-j-8.2.0-r2.jar",
          "size": 820638,
          "sha512": "204c19ba7366ec2b57d3dd6fd6c9c8a36a7c154083a2883f71f547a861c56db9092dd21832cd9be61a2842fe6ab852cb75464dd45e4f740885a7b34f63150a8f",
          "sha256": "d97dcbbcc57b2ffafcc77d479c3cb45ac8809353c4b6c987663c21ccd013d6ea",
          "sha1": "f13e056e0e5fd0e6db378fbe4e3a27f5511775e0",
          "md5": "f02b8e1134f55c5e1e24f4b32c9d5e76"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mysql-connector-j-8.2.0-r2-sources.jar",
          "url": "mysql-connector-j-8.2.0-r2-sources.jar",
          "size": 778862,
          "sha512": "54c79b31347be3cc3a6f922c6f5ebf17904761dcb3ec8560ee4b7d5edf51672f90c604c274f77a180f1904a3ac34d0eedfe9eedd14df1b5b7ad15b665171354b",
          "sha256": "63cfd5cc57957a55f4e01fb353e117fa0b5e48c63a473082837a8d97e743e4e7",
          "sha1": "eb64d2edcc4473d46a107e268c52916b40851d63",
          "md5": "43ba29bd2fb9fc2b3ad61ef1f1a2877c"
        }
      ]
    }
  ]
}
