{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "9.1.0-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.11.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.1.0-b0.jar",
          "url": "core-ng-test-9.1.0-b0.jar",
          "size": 45684,
          "sha512": "5fbe1e78063e73a99228090d029efa0e96c706d747be7a1f024bef0f27c4647a9fae1ae9ee7dd3371900c170613a8fc5b424215afac237b1463ff2b7a38a0b90",
          "sha256": "b5e75c158eafa1aaa7f72a88f38c2dcd79379dc89852b0bb3335616e0850a15f",
          "sha1": "a1ce5a1d526fd5f86f06f66153890a7cd96e8f29",
          "md5": "1f1df9d85234f99124eb88b261b97aa9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.0-b0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.11.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.1.0-b0.jar",
          "url": "core-ng-test-9.1.0-b0.jar",
          "size": 45684,
          "sha512": "5fbe1e78063e73a99228090d029efa0e96c706d747be7a1f024bef0f27c4647a9fae1ae9ee7dd3371900c170613a8fc5b424215afac237b1463ff2b7a38a0b90",
          "sha256": "b5e75c158eafa1aaa7f72a88f38c2dcd79379dc89852b0bb3335616e0850a15f",
          "sha1": "a1ce5a1d526fd5f86f06f66153890a7cd96e8f29",
          "md5": "1f1df9d85234f99124eb88b261b97aa9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-9.1.0-b0-sources.jar",
          "url": "core-ng-test-9.1.0-b0-sources.jar",
          "size": 22202,
          "sha512": "cc60f9b32f9ae3b94f371070e00770a8d534d01357c4a6b61d5cb1835354cd943a2e25f7fb4314fc98c25343fee9f553b42117933400b6117c254294f9508cf0",
          "sha256": "e684cf37ace6169db11f4f482f22da7ec7831052723db268cd926a8e74f39f73",
          "sha1": "6b04f1b3f1a8fdfe627c1370a2081c68239313c7",
          "md5": "eb66563e711abd9971dab2c924add1ce"
        }
      ]
    }
  ]
}
