{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "9.5.1-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.5.1-b0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.5.1-b0.jar",
          "url": "core-ng-mongo-9.5.1-b0.jar",
          "size": 60079,
          "sha512": "6cd007693959bbe05d60655008a544ff8ee94c668db6013348371a4366028bd71aec079d068d1629a827e30f650b3dc1a7480c94a47b26c24e1070fefb3ecaf5",
          "sha256": "8102248450891d582b71cf870cfc60dcc9d99eda91e40fe42a41d6c6cb00ec12",
          "sha1": "1ea420689c56c5b5f40fdbeb0d7585a2d5739b95",
          "md5": "5224395e191f2e74bcb1b1c85df78c61"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.5.1-b0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.5.1-b0.jar",
          "url": "core-ng-mongo-9.5.1-b0.jar",
          "size": 60079,
          "sha512": "6cd007693959bbe05d60655008a544ff8ee94c668db6013348371a4366028bd71aec079d068d1629a827e30f650b3dc1a7480c94a47b26c24e1070fefb3ecaf5",
          "sha256": "8102248450891d582b71cf870cfc60dcc9d99eda91e40fe42a41d6c6cb00ec12",
          "sha1": "1ea420689c56c5b5f40fdbeb0d7585a2d5739b95",
          "md5": "5224395e191f2e74bcb1b1c85df78c61"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-9.5.1-b0-sources.jar",
          "url": "core-ng-mongo-9.5.1-b0-sources.jar",
          "size": 28818,
          "sha512": "5d0d140c212c440881106191f58e1469709a005bb6b9af1a9dd9513ecfe7c987bb414ff5f2b0d35779802c580e13645d5304c6174e3592772f861d3cebd7a370",
          "sha256": "babd6a52e69f81ba90ddb75807cb60120e7a594fb38c91e85e5d726451b2c7d5",
          "sha1": "03a4ea36c29f103372cbd0b78faad00aa988d8c5",
          "md5": "80ab7d9f634adf22117f507a59d86ea9"
        }
      ]
    }
  ]
}
