{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "7.6.8-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "fbkkyz4bmredpnyliz2efiny7u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.8-b0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.6.8-b0.jar",
          "url": "core-ng-mongo-7.6.8-b0.jar",
          "size": 54022,
          "sha512": "01233e832ca8eac9d212a16b0b78ad18b0e3064517eaee3aa1bd8dc7f7e46db7123de25cf80d7105d84e1dc0c0ac37e2d95167c1a1857a7d18c5e93511c1f835",
          "sha256": "123867ea7d6feabb1ce3cd425a44bc1b6a8c927461795be289f72a39dafef789",
          "sha1": "318b594d7d67e600ee6287a0998b61fd74dc8141",
          "md5": "0833d403cca29367d36621eaba6df3c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.8-b0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.6.8-b0.jar",
          "url": "core-ng-mongo-7.6.8-b0.jar",
          "size": 54022,
          "sha512": "01233e832ca8eac9d212a16b0b78ad18b0e3064517eaee3aa1bd8dc7f7e46db7123de25cf80d7105d84e1dc0c0ac37e2d95167c1a1857a7d18c5e93511c1f835",
          "sha256": "123867ea7d6feabb1ce3cd425a44bc1b6a8c927461795be289f72a39dafef789",
          "sha1": "318b594d7d67e600ee6287a0998b61fd74dc8141",
          "md5": "0833d403cca29367d36621eaba6df3c3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-7.6.8-b0-sources.jar",
          "url": "core-ng-mongo-7.6.8-b0-sources.jar",
          "size": 25362,
          "sha512": "0ea86c1a7d1757f89a4172f4b9d13c23b265626b17f713730d88af5cbfd0abff61afcae92b11f267cbc809aeef8ee8f9ef2f0ed5d364def49cbb602a8af29a25",
          "sha256": "9e6d02253da97727f01c0371781c5bfd9f3c1a3a498c133d4cccc46f265ad383",
          "sha1": "80937eeeb119a0c2b30fc6c3a771c6e9b97cd7f2",
          "md5": "80726a4e4f7eb3dbac5d3bb4ff077a8e"
        }
      ]
    }
  ]
}
