{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "7.6.16-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-7.6.16-b0.jar",
          "url": "core-ng-mongo-test-7.6.16-b0.jar",
          "size": 2383,
          "sha512": "8e7ab9741ed56bd806951a9d51ab2a64d3beeaa6034317bec2cac8ec5d1261b9c2056983725a0cd155f42b7879a8f648def793b8578822be414cfd3eca67d3ec",
          "sha256": "e3e9abc407f06c722195b14b448ea627e6e52b0b45b319eccdaf9c20df536e40",
          "sha1": "4cc217e9720b39e516e80cc5ea1b2b1379bbb2e9",
          "md5": "ebfe277a31b6da7e7b61a5141f0fb672"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.6.16-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "7.6.16-b0"
          }
        },
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.38.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-7.6.16-b0.jar",
          "url": "core-ng-mongo-test-7.6.16-b0.jar",
          "size": 2383,
          "sha512": "8e7ab9741ed56bd806951a9d51ab2a64d3beeaa6034317bec2cac8ec5d1261b9c2056983725a0cd155f42b7879a8f648def793b8578822be414cfd3eca67d3ec",
          "sha256": "e3e9abc407f06c722195b14b448ea627e6e52b0b45b319eccdaf9c20df536e40",
          "sha1": "4cc217e9720b39e516e80cc5ea1b2b1379bbb2e9",
          "md5": "ebfe277a31b6da7e7b61a5141f0fb672"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-7.6.16-b0-sources.jar",
          "url": "core-ng-mongo-test-7.6.16-b0-sources.jar",
          "size": 1721,
          "sha512": "f5910db688a4a159cda1240a7eee43f9abd54ff113e82ff21dfb46be08888dcb376db9be5d607f9648e4ab4bad977ebfc62b8adcf307357080e7253f4d7f5ea4",
          "sha256": "00af70226dabec4771f6ea68f83b78e28a050e018b005e9f137de4c500c7aa32",
          "sha1": "5d5da396323f183d331581a9fa6f18daa56add67",
          "md5": "e6fd9ed29f2f570aff2ce43f0dfb884b"
        }
      ]
    }
  ]
}
