{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "7.6.2-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "5jfivrnadrg73pcyjgmirgtp24"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.6.2-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.6.2-b0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.6.2-b0.jar",
          "url": "core-ng-search-test-7.6.2-b0.jar",
          "size": 9066,
          "sha512": "dcf955d9009a565e44f4dc06478648b61c155945dc037c6f2281b3eff936e27b3a76b7cec129cf80b3382c1428168dcd50c1421019c9fd0be6b69c5619214642",
          "sha256": "eaf29bda8998e3f20eae3705a61805459b40e98dad57039edf0f2eb878f8e002",
          "sha1": "d466793bbc115d3fdf91834bc5eed3e8ed001a7e",
          "md5": "89a2c79a4e101e3c44f61d2057a5a7af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4-client",
          "version": {
            "requires": "7.10.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "reindex-client",
          "version": {
            "requires": "7.10.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "7.10.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "7.10.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "7.10.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.6.2-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.6.2-b0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.6.2-b0.jar",
          "url": "core-ng-search-test-7.6.2-b0.jar",
          "size": 9066,
          "sha512": "dcf955d9009a565e44f4dc06478648b61c155945dc037c6f2281b3eff936e27b3a76b7cec129cf80b3382c1428168dcd50c1421019c9fd0be6b69c5619214642",
          "sha256": "eaf29bda8998e3f20eae3705a61805459b40e98dad57039edf0f2eb878f8e002",
          "sha1": "d466793bbc115d3fdf91834bc5eed3e8ed001a7e",
          "md5": "89a2c79a4e101e3c44f61d2057a5a7af"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.6.2-b0-sources.jar",
          "url": "core-ng-search-test-7.6.2-b0-sources.jar",
          "size": 5477,
          "sha512": "c8b9638736ef4d4a34b31e57128db0fc2d78f08bc61422de9bc5618230ad70ee16de1656e5f6409af9b388dd41f6295f72bfab715f40328d0584b4ecfce61f16",
          "sha256": "d1fadeca079a68d58eb602e1bdaf41e6dcda7fcd60208701713df049b751254b",
          "sha1": "d2f21efc4a2267ef69149607b0dfc815fc0724f9",
          "md5": "c56408b4859e382533f3adc2f56cf2fa"
        }
      ]
    }
  ]
}
