{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "7.6.2-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "xd54h2egmrab5k7pkkb7oigyyq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.6.2-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.6.2-b0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.6.2-b0.jar",
          "url": "core-ng-search-test-7.6.2-b0.jar",
          "size": 9046,
          "sha512": "fd620bbb85ad0ef76d167f0b41384da86dc30d8f0fdfeda01d6ba81cd41e9fc4f290baf124b5e507defc123b7a93102f677a481c1eca6e6506a90ec41caffd0a",
          "sha256": "112cd02d23d03207c44a30dcbfad34373252651271199d9591bca5754bb39482",
          "sha1": "44a09854fe9fb4c5c1ff148ea666a238e8067cc1",
          "md5": "c1a62ef25d505307115ff629bf3ad5c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4-client",
          "version": {
            "requires": "7.9.3"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "reindex-client",
          "version": {
            "requires": "7.9.3"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "7.9.3"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "7.9.3"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "7.9.3"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.6.2-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.6.2-b0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.6.2-b0.jar",
          "url": "core-ng-search-test-7.6.2-b0.jar",
          "size": 9046,
          "sha512": "fd620bbb85ad0ef76d167f0b41384da86dc30d8f0fdfeda01d6ba81cd41e9fc4f290baf124b5e507defc123b7a93102f677a481c1eca6e6506a90ec41caffd0a",
          "sha256": "112cd02d23d03207c44a30dcbfad34373252651271199d9591bca5754bb39482",
          "sha1": "44a09854fe9fb4c5c1ff148ea666a238e8067cc1",
          "md5": "c1a62ef25d505307115ff629bf3ad5c0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.6.2-b0-sources.jar",
          "url": "core-ng-search-test-7.6.2-b0-sources.jar",
          "size": 5425,
          "sha512": "9ebc1ab0b1034ea968fa987df7e85c37a3444ebef801143205af8930e4699f0e87d638f7e7e37cf57e7627ab8acabef16e5196e23193fa50588986c590a8cc91",
          "sha256": "4ba734a9ff72847c32f3e4fcf79c647c8aed7037dd35df61335162cfb1652de0",
          "sha1": "8c578d63e40ef167515b6d856189ace281f73fb8",
          "md5": "849a1fe3623a0f4e1dc1e860e295cf46"
        }
      ]
    }
  ]
}
