{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework.mysql",
    "module": "mysql-connector-j",
    "version": "8.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mysql-connector-j-8.3.0.jar",
          "url": "mysql-connector-j-8.3.0.jar",
          "size": 563157,
          "sha512": "dccdc1c4a294be0019771209ac73815a921e8bc038c94afb6a54950b63913dcd1e4db254cea69a304fdae02d099da2194f361ddb0a9ebbaea92b36ba75ce8dd5",
          "sha256": "1e70c9108aaed0323163c77260a2eff50f272f535072084d89ca2dc7d485cc1f",
          "sha1": "fc78fb86776c64100e5d308d22e1869da220ca03",
          "md5": "bde2071eb16d05efc9867feae88d88cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mysql-connector-j-8.3.0.jar",
          "url": "mysql-connector-j-8.3.0.jar",
          "size": 563157,
          "sha512": "dccdc1c4a294be0019771209ac73815a921e8bc038c94afb6a54950b63913dcd1e4db254cea69a304fdae02d099da2194f361ddb0a9ebbaea92b36ba75ce8dd5",
          "sha256": "1e70c9108aaed0323163c77260a2eff50f272f535072084d89ca2dc7d485cc1f",
          "sha1": "fc78fb86776c64100e5d308d22e1869da220ca03",
          "md5": "bde2071eb16d05efc9867feae88d88cc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mysql-connector-j-8.3.0-sources.jar",
          "url": "mysql-connector-j-8.3.0-sources.jar",
          "size": 561322,
          "sha512": "eb620fc40f3623edcd88b64c3b8f09f95ad39ddc8b383d1a1b78f445decaba7567b843e340e5ac1b5d73c8faf4a840291a05a0f6a79d78e150bfb3d00a998d0a",
          "sha256": "12d018af0900bca9cee35d57cc8f177680aadb41f2437e3a0f3f81e7af0cca6d",
          "sha1": "be149e96d8b3afc1d0d405d9cb1899910953c1ab",
          "md5": "61340017edf9f8d6cb348e3ae28b6ed4"
        }
      ]
    }
  ]
}
