{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "9.4.0-b2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.20.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.4.0-b2.jar",
          "url": "core-ng-test-9.4.0-b2.jar",
          "size": 50955,
          "sha512": "f345f63f2aa5810d0b6f31b04ff1d955303399ee459debea516a1d117720959ae57e930d6ff3c37c1d2cb0897c2d32d9122d0cd62545f1cc0bac0c5256eb64e9",
          "sha256": "4bafd7f9055f7533aaa62d2a7fdc1dd921f2108ac1111f8e6de0f56a1de1fff6",
          "sha1": "0918971e442afc2cbc23aeaa511703cf8f3aae6e",
          "md5": "11a0db37fda23f9adf2f603ca993a52c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.4.0-b2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.20.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.4.0-b2.jar",
          "url": "core-ng-test-9.4.0-b2.jar",
          "size": 50955,
          "sha512": "f345f63f2aa5810d0b6f31b04ff1d955303399ee459debea516a1d117720959ae57e930d6ff3c37c1d2cb0897c2d32d9122d0cd62545f1cc0bac0c5256eb64e9",
          "sha256": "4bafd7f9055f7533aaa62d2a7fdc1dd921f2108ac1111f8e6de0f56a1de1fff6",
          "sha1": "0918971e442afc2cbc23aeaa511703cf8f3aae6e",
          "md5": "11a0db37fda23f9adf2f603ca993a52c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-9.4.0-b2-sources.jar",
          "url": "core-ng-test-9.4.0-b2-sources.jar",
          "size": 25058,
          "sha512": "8b13ae077215ccddcefa2530b7eb77b41fa005cf080565b37722ec558f0a5d40e304358c8783cbd83c6257920bebc14dd3199df31c68af884e31ce3f857eb34b",
          "sha256": "d6cf8e31a669cae24862943a99321089e1f6c9a7d07f2963bd334cf8c949e648",
          "sha1": "6aaaf05e5bd81cd4c8f300e67785fd007372ecb5",
          "md5": "072bb999b3d52d8552514e0fa104a2cb"
        }
      ]
    }
  ]
}
