{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "9.1.1-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.1-b0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.1.1-b0.jar",
          "url": "core-ng-mongo-9.1.1-b0.jar",
          "size": 57160,
          "sha512": "735c1e3702ca904497818ba8406f82f23047df270349c1bbeaa305e234ceadb78dd512ba9b62802de4634b9aed1d62dbbf77e3d7b1f1aa9a19e77854790fe598",
          "sha256": "cdd6637491b1eee8cbd3d442cc0339ea101e6b6e1aa2cf3bcd8f7ee35ea68337",
          "sha1": "fa4805f99c9a1ba66be3f9fcbcafcf57e6d7abf5",
          "md5": "4b3d78c9e129fa6f8d14d826cdd7ae95"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.1-b0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.1.1-b0.jar",
          "url": "core-ng-mongo-9.1.1-b0.jar",
          "size": 57160,
          "sha512": "735c1e3702ca904497818ba8406f82f23047df270349c1bbeaa305e234ceadb78dd512ba9b62802de4634b9aed1d62dbbf77e3d7b1f1aa9a19e77854790fe598",
          "sha256": "cdd6637491b1eee8cbd3d442cc0339ea101e6b6e1aa2cf3bcd8f7ee35ea68337",
          "sha1": "fa4805f99c9a1ba66be3f9fcbcafcf57e6d7abf5",
          "md5": "4b3d78c9e129fa6f8d14d826cdd7ae95"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-9.1.1-b0-sources.jar",
          "url": "core-ng-mongo-9.1.1-b0-sources.jar",
          "size": 27012,
          "sha512": "ca080fb4fc17ca1eb03e99fc965331a0fd338cd8ca9b41c58a2e989c042717a4a4b1893b9d7603bccbdf45c362957bd577ba3096bdcee6ff59f7eca2440f5862",
          "sha256": "0d2d40097dfacdc8636479401ddfe6530d0b8a4e85c58ddd7ec106c40f322cab",
          "sha1": "8f68601f71fa0cbd684e1eb6a14b3dd5fd9f9a86",
          "md5": "de29e8790eaf33b278de29c85fe714c7"
        }
      ]
    }
  ]
}
