{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "9.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.0.0.jar",
          "url": "core-ng-mongo-9.0.0.jar",
          "size": 57152,
          "sha512": "5d52521ce761776c15f41eecbf1fa62f15d27b66233c3ebf8bfc783bd23c7f0343b5471561c970fd12370d8fa91c852aa238f1ce365bfacf4cb82c968fe8b6ed",
          "sha256": "e18deac9c141e6f03d208c7f73a2b30e7b08770058e6379f348216d1d6dd3314",
          "sha1": "ae0f53e23028b5f15705227721d3791a145529b6",
          "md5": "470bd6471d110967d4e21c7c2f70c4d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.0.0.jar",
          "url": "core-ng-mongo-9.0.0.jar",
          "size": 57152,
          "sha512": "5d52521ce761776c15f41eecbf1fa62f15d27b66233c3ebf8bfc783bd23c7f0343b5471561c970fd12370d8fa91c852aa238f1ce365bfacf4cb82c968fe8b6ed",
          "sha256": "e18deac9c141e6f03d208c7f73a2b30e7b08770058e6379f348216d1d6dd3314",
          "sha1": "ae0f53e23028b5f15705227721d3791a145529b6",
          "md5": "470bd6471d110967d4e21c7c2f70c4d9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-9.0.0-sources.jar",
          "url": "core-ng-mongo-9.0.0-sources.jar",
          "size": 27008,
          "sha512": "5c52b0038cdc12aa629960c94df11ab264a93fb49ccb36be65ffa3b2bed6a6cb27679d6e89f8d47cb9efd61856cc05787353265107c825851c7422fb35a50b21",
          "sha256": "d47891a7814bdf9936ab35f7b791572c97fa2acbe92e4eba5713ebfbfdf80d68",
          "sha1": "22b668903432ebad3edcbe55eb7e90a744f6eed6",
          "md5": "f20acd945caefbce70d31710d9f740b7"
        }
      ]
    }
  ]
}
