{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.5.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.5.4.jar",
          "url": "core-ng-9.5.4.jar",
          "size": 791414,
          "sha512": "6cd19d05bb593f4d1572c23539e9097ef21dd9577f94fe197cc01862b4794da50eb74607842e8e45c66ea68e930aee83967b5c2b2e4dcae78e59e6f51ee24243",
          "sha256": "cfd509b77c1614e96f004c8ea4ac4cd8aeae5a88bf03406cc7da2243bbe322b9",
          "sha1": "6a1ca2811f29665173ed80d6112690f13b1e3160",
          "md5": "8c9d62b912756cc5bc93c56f29a3fe45"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.31.0-GA"
          }
        },
        {
          "group": "tools.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "tools.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.4.1.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "4.3.0"
          },
          "excludes": [
            {
              "group": "org.xerial.snappy",
              "module": "*"
            },
            {
              "group": "at.yawk.lz4",
              "module": "*"
            }
          ]
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.5.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.5.4.jar",
          "url": "core-ng-9.5.4.jar",
          "size": 791414,
          "sha512": "6cd19d05bb593f4d1572c23539e9097ef21dd9577f94fe197cc01862b4794da50eb74607842e8e45c66ea68e930aee83967b5c2b2e4dcae78e59e6f51ee24243",
          "sha256": "cfd509b77c1614e96f004c8ea4ac4cd8aeae5a88bf03406cc7da2243bbe322b9",
          "sha1": "6a1ca2811f29665173ed80d6112690f13b1e3160",
          "md5": "8c9d62b912756cc5bc93c56f29a3fe45"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.5.4-sources.jar",
          "url": "core-ng-9.5.4-sources.jar",
          "size": 407105,
          "sha512": "4e6f94f022b02f49a2f42381cf5f5e9bcdd5d9da5d7a1c3102f58b8fd470657e9b2d5ec3887e11ebbff74b0b2a68b9adbbca2771d7ea8bb6d75b5673796df7a3",
          "sha256": "736b8d3f108730a7d7844305acd97b7685686f5ae38bf96274a2d7a68d81f965",
          "sha1": "80c9dbba048c009c64069506facd155df9d407e6",
          "md5": "6defbf401ece9f169e20bb9594dda212"
        }
      ]
    }
  ]
}
