{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "9.5.1-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.5.1-b1"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.5.1-b1.jar",
          "url": "core-ng-mongo-9.5.1-b1.jar",
          "size": 60079,
          "sha512": "d2ee73d36f66bdab8834bf68feeb6cef99e5a7983f747e868fab47259adc42dfa654ea217140aff332163d6a3d7116f9b1f61b34b017e035d73682d1afe5b3dc",
          "sha256": "1076d75813e25bb94cfdf8664a823d0ad443da9f0e7df6cd977dd3e5b48ea9b7",
          "sha1": "b1018e6abf62588c3d1a0dd4afcd48742a93ee98",
          "md5": "7c9a1f4a4afb3723e881ab968287cf1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.5.1-b1"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.5.1-b1.jar",
          "url": "core-ng-mongo-9.5.1-b1.jar",
          "size": 60079,
          "sha512": "d2ee73d36f66bdab8834bf68feeb6cef99e5a7983f747e868fab47259adc42dfa654ea217140aff332163d6a3d7116f9b1f61b34b017e035d73682d1afe5b3dc",
          "sha256": "1076d75813e25bb94cfdf8664a823d0ad443da9f0e7df6cd977dd3e5b48ea9b7",
          "sha1": "b1018e6abf62588c3d1a0dd4afcd48742a93ee98",
          "md5": "7c9a1f4a4afb3723e881ab968287cf1e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-9.5.1-b1-sources.jar",
          "url": "core-ng-mongo-9.5.1-b1-sources.jar",
          "size": 28818,
          "sha512": "7391f57185ad30e26fa9140bb1cd64259bc2096d30c1221f3ddd482a77d63233043de6cbf2734b054f603253e90c0a04f1a9d28b7a66118ff037a6699de3d178",
          "sha256": "b70fd56764ced5a6133b24018e207cabdf89c00ad7041bde9aa58645aa49de4b",
          "sha1": "dec9134943f7b92655e64944ab003657811fd3fa",
          "md5": "2d4979f5046eee5547a6cf31b7885c57"
        }
      ]
    }
  ]
}
