{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "9.2.3-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-9.2.3-b0.jar",
          "url": "core-ng-api-9.2.3-b0.jar",
          "size": 11021,
          "sha512": "0960760a06b87c64a575f233b2ca3b52a562705db86795935f34f441ac2203343f4fd2cefe14be785ce0ccdeb3b0fd4241beb22efaa9a0d5595337098a7acafa",
          "sha256": "8bed56c8fc8d98f139087b75914eac0339f554834384ba1073158617a990ee07",
          "sha1": "26c5de889a9e8828ccbbb31c70dc76227d26fbdc",
          "md5": "ccbf192ac9ab77749bede786cd646836"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.2.3-b0.jar",
          "url": "core-ng-api-9.2.3-b0.jar",
          "size": 11021,
          "sha512": "0960760a06b87c64a575f233b2ca3b52a562705db86795935f34f441ac2203343f4fd2cefe14be785ce0ccdeb3b0fd4241beb22efaa9a0d5595337098a7acafa",
          "sha256": "8bed56c8fc8d98f139087b75914eac0339f554834384ba1073158617a990ee07",
          "sha1": "26c5de889a9e8828ccbbb31c70dc76227d26fbdc",
          "md5": "ccbf192ac9ab77749bede786cd646836"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.2.3-b0-sources.jar",
          "url": "core-ng-api-9.2.3-b0-sources.jar",
          "size": 8665,
          "sha512": "74a61fd9b1ce21d5764ff565c700e532af3944a7fbcce501f3dd14d0def01cc7ba1a297bd740c3966a2c38ed749580fb0f5bbbf8bcdbc594972b97915d68ad2e",
          "sha256": "1b24f58f38991168f2b8acd91bc22d4e12cf9461924bc413da4a59a2ac8355fb",
          "sha1": "9e28d560d228c82dd35e1981502596fcdd3a892b",
          "md5": "8ac9fdd5b3c90ae79415f12225baba55"
        }
      ]
    }
  ]
}
