{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "9.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.0.4.jar",
          "url": "core-ng-search-test-9.0.4.jar",
          "size": 12666,
          "sha512": "14cd268ba6c07e64317ae3ac82a305dbd70ea79c6c2460fa498e24ff8676d9b0bd7b16ec5a3f1ba9c8c7aea01f3619643f211be223966ac2bd5a19c32be76f77",
          "sha256": "99cd24e9524a7c64886568e8d3bfe9c440a8499a2101cb8216ced2c3b0d536f3",
          "sha1": "1a56ad84faeec5cedff7f837c1a7edc62306ceeb",
          "md5": "3563e1803d40f2d656b437e3f47e6bab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.0.4"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "9.0.4"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "transport-netty4",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "reindex",
          "version": {
            "requires": "8.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-9.0.4.jar",
          "url": "core-ng-search-test-9.0.4.jar",
          "size": 12666,
          "sha512": "14cd268ba6c07e64317ae3ac82a305dbd70ea79c6c2460fa498e24ff8676d9b0bd7b16ec5a3f1ba9c8c7aea01f3619643f211be223966ac2bd5a19c32be76f77",
          "sha256": "99cd24e9524a7c64886568e8d3bfe9c440a8499a2101cb8216ced2c3b0d536f3",
          "sha1": "1a56ad84faeec5cedff7f837c1a7edc62306ceeb",
          "md5": "3563e1803d40f2d656b437e3f47e6bab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.0.4-sources.jar",
          "url": "core-ng-search-test-9.0.4-sources.jar",
          "size": 7177,
          "sha512": "7b2d068a39c1c582a80c2a979e2772cd27df4fed187bd31e4e5b96ae068087c5c8fb601fbe7971436e6e2e758a7896997a2cf9a2baada3b0e3afb18eedc8d914",
          "sha256": "b06a0738d73b7f1e013b54a4db9de4136ada8744df745cdd7799fa0361c2ffa0",
          "sha1": "286c1d3891e13a25aeeeabbcae599baeca8e2e93",
          "md5": "5ad22a9432a5cf2fb04783c48eb81116"
        }
      ]
    }
  ]
}
