{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "7.4.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "3mlsin3fvvb55bqty7rjpsuugu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.4.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.4.1.1.jar",
          "url": "core-ng-7.4.1.1.jar",
          "size": 613906,
          "sha512": "cddec4243e40d8ebc2b87d3baaf79af93e3e99fcd615e8e845673f78412dc1380f174fb329e71c2ef9a538791e00de742a98cdf6bcc31f6951a2f86dfaf01f4a",
          "sha256": "329480650e10fafaedc288023e4fe5f3e16f31c39135ca97bdfd42247526ba5f",
          "sha1": "a4fed7ca618a6d6aea566fe11d775da725050ff0",
          "md5": "eae9623028e0ed1dbc33e0cc43a96ce7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.27.0-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.10.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.10.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.1.0.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.4.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.7.3"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.4.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.4.1.1.jar",
          "url": "core-ng-7.4.1.1.jar",
          "size": 613906,
          "sha512": "cddec4243e40d8ebc2b87d3baaf79af93e3e99fcd615e8e845673f78412dc1380f174fb329e71c2ef9a538791e00de742a98cdf6bcc31f6951a2f86dfaf01f4a",
          "sha256": "329480650e10fafaedc288023e4fe5f3e16f31c39135ca97bdfd42247526ba5f",
          "sha1": "a4fed7ca618a6d6aea566fe11d775da725050ff0",
          "md5": "eae9623028e0ed1dbc33e0cc43a96ce7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-7.4.1.1-sources.jar",
          "url": "core-ng-7.4.1.1-sources.jar",
          "size": 313696,
          "sha512": "47866015c0b45bcb3ba50fcd6ce80be5eb1a28cf9b20cd9913d6ceede468d073b06fca29156694be008d58a2c180e3b4292bfd76d153867f230789a753a0f01b",
          "sha256": "d548fa03a8cb313b4045808e789c1b7fe1a0b117eca33a90a81803dcbeb22fb8",
          "sha1": "edf7bb734f33ffc4b5916b13b246bd9fa96acb7d",
          "md5": "73c376f435400cd029be4d388896031e"
        }
      ]
    }
  ]
}
