{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "7.4.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "ulgfwrzehzgwtop2m46msbzdtu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.4.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.4.1.1.jar",
          "url": "core-ng-7.4.1.1.jar",
          "size": 613905,
          "sha512": "2a0cead2c24a78f896309a57eb80a8283523cee76bf49ec6e00f24d4fbb3aa919137b172f56e2c47edd0c585dd6083bc0b75be6e877ebc4387ee602bf5068b4c",
          "sha256": "c4f36ddee675d02f018bdb9d395ced9ffcba980ea69a141eb053306845c9c844",
          "sha1": "930b42ed52c547542caa81ff4e6596101702facd",
          "md5": "1448c2949dfff510e3085a70f802ac34"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.27.0-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.10.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.10.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.1.0.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.5.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.7.3"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.4.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.4.1.1.jar",
          "url": "core-ng-7.4.1.1.jar",
          "size": 613905,
          "sha512": "2a0cead2c24a78f896309a57eb80a8283523cee76bf49ec6e00f24d4fbb3aa919137b172f56e2c47edd0c585dd6083bc0b75be6e877ebc4387ee602bf5068b4c",
          "sha256": "c4f36ddee675d02f018bdb9d395ced9ffcba980ea69a141eb053306845c9c844",
          "sha1": "930b42ed52c547542caa81ff4e6596101702facd",
          "md5": "1448c2949dfff510e3085a70f802ac34"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-7.4.1.1-sources.jar",
          "url": "core-ng-7.4.1.1-sources.jar",
          "size": 313695,
          "sha512": "995398962ba5df4418b40532c15a076c301469d6b2fe7a0fc88c86ef45a0ab193c3337e69d591a97255ba9f04496fc0872cc22926a67e7d78f53589eade0a064",
          "sha256": "1e93900eca6749bd8d31fe25415ffc7d79f8bbe644d1c4d054868836202c075c",
          "sha1": "ba483e98897fb6c5f8a3c54bd43f8c0b7352f752",
          "md5": "ac56ec1228967e6c933ec458fa7f2875"
        }
      ]
    }
  ]
}
