{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "9.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.1"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.0.1.jar",
          "url": "core-ng-mongo-9.0.1.jar",
          "size": 57152,
          "sha512": "18b1ff640a8615e9008532ba51659cb906c5b759b7be8c34e5f1c17adcd62046608b3a4ab987c7cb2c4e431203ad098101852cd62ffb0f978f954b22de4d9721",
          "sha256": "a10e7ca990e80abd1e35e0054dd13c0ee272e132dd323fd70c3d93730fd5451b",
          "sha1": "fcaa2296f7fac1b4805e075e83e8eab218c54962",
          "md5": "78010da8853814d653970a47d824b07d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.1"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.0.1.jar",
          "url": "core-ng-mongo-9.0.1.jar",
          "size": 57152,
          "sha512": "18b1ff640a8615e9008532ba51659cb906c5b759b7be8c34e5f1c17adcd62046608b3a4ab987c7cb2c4e431203ad098101852cd62ffb0f978f954b22de4d9721",
          "sha256": "a10e7ca990e80abd1e35e0054dd13c0ee272e132dd323fd70c3d93730fd5451b",
          "sha1": "fcaa2296f7fac1b4805e075e83e8eab218c54962",
          "md5": "78010da8853814d653970a47d824b07d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-9.0.1-sources.jar",
          "url": "core-ng-mongo-9.0.1-sources.jar",
          "size": 27008,
          "sha512": "6e307c25a735edd52af7a546ce38735c1edee87b168ada23f5c51d8d7cb124254ce22752d22a60db6c82bf8ff8728a75f14562c230edf66855fe26bf2ba1b585",
          "sha256": "b8b47f6c50825dc355747975cd149d0a66eb29c7f2f27b59a114b6321f8a6e84",
          "sha1": "ceb190aee47319a4f7c1e75839b322a28e7c4c10",
          "md5": "a2b435f3f4b0d2ff4a416e70d96176af"
        }
      ]
    }
  ]
}
