{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "7.7.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.7.4"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.7.4.jar",
          "url": "core-ng-mongo-7.7.4.jar",
          "size": 53968,
          "sha512": "dea3ba6f0c2a8c12347da63f594f3fc80fec8706d1ce14a7f68244a4fadcc22752eacd66c5bebdd714505684cad6ee63208293777575880260dbf4aff9197400",
          "sha256": "0bae73abd301ed4ee42dab8b2cf5d699083aa23d9c8570b0e42291d920c0010b",
          "sha1": "b4142312ce0a41343fce2681e69af64ee85f7c73",
          "md5": "b2ce46f35d905cbc9f1a54762cfbd51b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.7.4"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.7.4.jar",
          "url": "core-ng-mongo-7.7.4.jar",
          "size": 53968,
          "sha512": "dea3ba6f0c2a8c12347da63f594f3fc80fec8706d1ce14a7f68244a4fadcc22752eacd66c5bebdd714505684cad6ee63208293777575880260dbf4aff9197400",
          "sha256": "0bae73abd301ed4ee42dab8b2cf5d699083aa23d9c8570b0e42291d920c0010b",
          "sha1": "b4142312ce0a41343fce2681e69af64ee85f7c73",
          "md5": "b2ce46f35d905cbc9f1a54762cfbd51b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-7.7.4-sources.jar",
          "url": "core-ng-mongo-7.7.4-sources.jar",
          "size": 25321,
          "sha512": "ab5ab8e86cf785f0a27302185f48f55eca8134593ffc59a58deeae514f0bd8f90cb566a180ad973eeca5e13a45c38fce69e0d01198c1e6c04dfe87de4f2b2ae1",
          "sha256": "3627d5afc3a5016e030efd08acaf99b8ffff5d9a04592c3e19864e088c0f66b6",
          "sha1": "a5c05ebc3253374547a6e6e15a49c05d61ec8270",
          "md5": "36e09aeda453fc04e15650b379b2fbfd"
        }
      ]
    }
  ]
}
