{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "9.4.0-b4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.4.0-b4.jar",
          "url": "core-ng-mongo-test-9.4.0-b4.jar",
          "size": 2944,
          "sha512": "c2da18a2ce7cbd6cc4c27c88daa0b0ada865d7c471c7c60c18427f7e29922a1e9f74e0e1e7f83266c42fb7c92cb781626799233ce9669c56d75689fd2cdd1490",
          "sha256": "c5a4169a08b4cd71fd1adbb2d21d216c3a14f0e7aa3c83e898e41626f42f7fc9",
          "sha1": "987f1b04e2901593b82e1d5cc445cb251234cd0e",
          "md5": "33714c9bf99ca4fcb142eca7b593cb0c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.4.0-b4"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "9.4.0-b4"
          }
        },
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.47.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-9.4.0-b4.jar",
          "url": "core-ng-mongo-test-9.4.0-b4.jar",
          "size": 2944,
          "sha512": "c2da18a2ce7cbd6cc4c27c88daa0b0ada865d7c471c7c60c18427f7e29922a1e9f74e0e1e7f83266c42fb7c92cb781626799233ce9669c56d75689fd2cdd1490",
          "sha256": "c5a4169a08b4cd71fd1adbb2d21d216c3a14f0e7aa3c83e898e41626f42f7fc9",
          "sha1": "987f1b04e2901593b82e1d5cc445cb251234cd0e",
          "md5": "33714c9bf99ca4fcb142eca7b593cb0c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.4.0-b4-sources.jar",
          "url": "core-ng-mongo-test-9.4.0-b4-sources.jar",
          "size": 2083,
          "sha512": "c4f710701bd3b1f50a78300face872465f4cdb3ff3765f7ec1c1d1364fbe6ff3039c4b6c893dc8cdd41131e406c3c7bd0327e7ba5943cb7e89b2f4c7bbd7cf76",
          "sha256": "6c36cd2d9e2931cd7538ade738fcacca35f1893761a8132aadf325c6ad9d9fc2",
          "sha1": "0c57e2e18359a694460f8f2789acf91cb623f5ae",
          "md5": "16f2eac40fc9ae521c74f1475879b14e"
        }
      ]
    }
  ]
}
