{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "7.4.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "3mlsin3fvvb55bqty7rjpsuugu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.4.1.1"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongo-java-driver",
          "version": {
            "requires": "3.12.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.4.1.1.jar",
          "url": "core-ng-mongo-7.4.1.1.jar",
          "size": 54185,
          "sha512": "fc3efb690011ee500b32c499669fd466cbc2e18bbe7e679369f7df5529aa257367d7a9e1d60b8ce8dfbc7d5eaed18cdb61e14810b70355ea29ec9eeb0e147dd7",
          "sha256": "a0bdd3570cf8457a69e3ab72338eca9340ce23bfda06d6f5bdaae4985d73b9cc",
          "sha1": "f1f4bfe2de67c06ee26d910cc633c06be3554de6",
          "md5": "6ddf6e5238b3d37eace8117ba94a2f23"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.4.1.1"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongo-java-driver",
          "version": {
            "requires": "3.12.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.4.1.1.jar",
          "url": "core-ng-mongo-7.4.1.1.jar",
          "size": 54185,
          "sha512": "fc3efb690011ee500b32c499669fd466cbc2e18bbe7e679369f7df5529aa257367d7a9e1d60b8ce8dfbc7d5eaed18cdb61e14810b70355ea29ec9eeb0e147dd7",
          "sha256": "a0bdd3570cf8457a69e3ab72338eca9340ce23bfda06d6f5bdaae4985d73b9cc",
          "sha1": "f1f4bfe2de67c06ee26d910cc633c06be3554de6",
          "md5": "6ddf6e5238b3d37eace8117ba94a2f23"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-7.4.1.1-sources.jar",
          "url": "core-ng-mongo-7.4.1.1-sources.jar",
          "size": 25671,
          "sha512": "b2128a44c364cc4fee064fcfe00219d40cf041bed910c47e4ef066e53f72fafe595a65577c7107daac0a3537c0668653867aad360f82a6193b04a6cc1fbcf412",
          "sha256": "8ba634fd7a128f3297892d82c5b8a683c052337ff5440e5ffdab461c3e9bd42a",
          "sha1": "03ebed6a248f78f20aee1bb50ccb52f0ba5bbb5a",
          "md5": "d96e1c1d440678a3f629eec699ed2188"
        }
      ]
    }
  ]
}
