{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "9.3.0-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.3.0-b0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.3.0-b0.jar",
          "url": "core-ng-mongo-9.3.0-b0.jar",
          "size": 60077,
          "sha512": "ca6ff3dbeb688f5515c9ae94546937f37be91dfe500f07ada28a56027ceb38daece7a66404793e48ccaa0eb777e3ee055d2b2645289676a51390caca90cd3c37",
          "sha256": "002ae990836402ab84b4f18a571e6783827cbac465a6dbdb9c340e1f325599b3",
          "sha1": "520174a55a109c25bf1e89ff2cc331a85b550b31",
          "md5": "d8bae6b06d7fbfe16e9057ac7b816947"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.3.0-b0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.3.0-b0.jar",
          "url": "core-ng-mongo-9.3.0-b0.jar",
          "size": 60077,
          "sha512": "ca6ff3dbeb688f5515c9ae94546937f37be91dfe500f07ada28a56027ceb38daece7a66404793e48ccaa0eb777e3ee055d2b2645289676a51390caca90cd3c37",
          "sha256": "002ae990836402ab84b4f18a571e6783827cbac465a6dbdb9c340e1f325599b3",
          "sha1": "520174a55a109c25bf1e89ff2cc331a85b550b31",
          "md5": "d8bae6b06d7fbfe16e9057ac7b816947"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-9.3.0-b0-sources.jar",
          "url": "core-ng-mongo-9.3.0-b0-sources.jar",
          "size": 28815,
          "sha512": "775c20d3709e5376046b2f9a56a00f440e5b19285c00b2fae8b1023153a93d5a12e90ac88ae1750f889dd573372cabf8f1e1583aad94e9f0d0e3ea430f166543",
          "sha256": "f85116d10b83af38ddc1a2d1d37e116635093fa5affd8906f7d3485cf54a7278",
          "sha1": "0363e7116413980ace58d169df798287342350a2",
          "md5": "4257d91ae724cf6835861c5d3d29d2bf"
        }
      ]
    }
  ]
}
