{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.0.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.0.2.jar",
          "url": "core-ng-9.0.2.jar",
          "size": 735662,
          "sha512": "cd2bc188f33f7e1249aef494fa8ce6341c4461298be2eb4d49a8d192440cfb4d71d2a53bead96ccf6c09209cfc1ccef287d5d4772b35a4c0880ee85d91196840",
          "sha256": "8050f5422e46d30f1cdbfc7f96325e6423d5c5f9e2e5ed57ed5ae78c3d640c76",
          "sha1": "fd06f52d7cb2d874792c76fe52a864c81ee3beee",
          "md5": "d16973a13445ca20721fe401333f6892"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.15.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.15.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.10.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "3.6.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.10.5"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.0.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.0.2.jar",
          "url": "core-ng-9.0.2.jar",
          "size": 735662,
          "sha512": "cd2bc188f33f7e1249aef494fa8ce6341c4461298be2eb4d49a8d192440cfb4d71d2a53bead96ccf6c09209cfc1ccef287d5d4772b35a4c0880ee85d91196840",
          "sha256": "8050f5422e46d30f1cdbfc7f96325e6423d5c5f9e2e5ed57ed5ae78c3d640c76",
          "sha1": "fd06f52d7cb2d874792c76fe52a864c81ee3beee",
          "md5": "d16973a13445ca20721fe401333f6892"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.0.2-sources.jar",
          "url": "core-ng-9.0.2-sources.jar",
          "size": 378232,
          "sha512": "56a537b2c098aac371fd1595d52cfbf20a041ea7f9e7f7e984aa7cd29b5f3b2d4a990429443df57b4ad318825f8c69e51e843b023aa77137b7c2efd56fc05c67",
          "sha256": "69e53cb4471c4e99d14cd47b53344c43918ea51de2b32bea7c2559a624c5b3de",
          "sha1": "ced64a3213e9059be04308c1d5d5765ff3510681",
          "md5": "e2213987d8c975dadcfb6e87931c9a24"
        }
      ]
    }
  ]
}
