{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "7.6.16-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.16-b0"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "7.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "elasticsearch",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch-x-content",
          "version": {
            "requires": "7.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "elasticsearch-x-content",
              "type": "jar",
              "extension": "jar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.6.16-b0.jar",
          "url": "core-ng-search-7.6.16-b0.jar",
          "size": 38548,
          "sha512": "1d45fb545390783f25b3aca778f5466d4ba1ea846fb76c4a252a5a9a009bb509713e775a99e3cedc83eb75f1effc221abef035fc4ec8030b9ad6398039179b37",
          "sha256": "d9bfdb35136c4358267c03fdd08ec95947b438bc473303b573fcfb330348d7fb",
          "sha1": "543f7a613d0b8ac40973d972465589be129f9567",
          "md5": "eb75db72170a86490650db50f233f308"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.elasticsearch.client",
          "module": "elasticsearch-rest-high-level-client",
          "version": {
            "requires": "7.12.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.16-b0"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "7.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "elasticsearch",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch-x-content",
          "version": {
            "requires": "7.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "elasticsearch-x-content",
              "type": "jar",
              "extension": "jar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.6.16-b0.jar",
          "url": "core-ng-search-7.6.16-b0.jar",
          "size": 38548,
          "sha512": "1d45fb545390783f25b3aca778f5466d4ba1ea846fb76c4a252a5a9a009bb509713e775a99e3cedc83eb75f1effc221abef035fc4ec8030b9ad6398039179b37",
          "sha256": "d9bfdb35136c4358267c03fdd08ec95947b438bc473303b573fcfb330348d7fb",
          "sha1": "543f7a613d0b8ac40973d972465589be129f9567",
          "md5": "eb75db72170a86490650db50f233f308"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-7.6.16-b0-sources.jar",
          "url": "core-ng-search-7.6.16-b0-sources.jar",
          "size": 17341,
          "sha512": "21cf5bd4f12ccc867711c590b7006ba02e6fc0b9e7b221b43220ca06e33897730da18ef571d87c17fa21fd3d6390d5bd3f227ab7cf0c4fdcba532e4ac9de44e8",
          "sha256": "f7cae2734de8e8fe976443a3633670d89cc83ec79797d88679b4e7917d330eea",
          "sha1": "78c5f3acaf99b59fc087c4ff36943638c67c690c",
          "md5": "5268a1d5959577c6e04640e4a78eac51"
        }
      ]
    }
  ]
}
