{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "9.1.7-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-9.1.7-b0.jar",
          "url": "core-ng-api-9.1.7-b0.jar",
          "size": 11022,
          "sha512": "1f765fd04a32fa2530991a984575ff5f0b22ed430e7e9f12d7b26669876acc920807841859f9914a4d9b35333b89719f59c928cc2528a101309856eaedbc50f5",
          "sha256": "6865c5e8f1cb7839de7c4a9800877f536eac438a82fb80f75d0ee534cbded565",
          "sha1": "f60b21124e9a92e6ae75837d1b79640e97cb5043",
          "md5": "2989b91fdb21fe37476fae36175fc5a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.1.7-b0.jar",
          "url": "core-ng-api-9.1.7-b0.jar",
          "size": 11022,
          "sha512": "1f765fd04a32fa2530991a984575ff5f0b22ed430e7e9f12d7b26669876acc920807841859f9914a4d9b35333b89719f59c928cc2528a101309856eaedbc50f5",
          "sha256": "6865c5e8f1cb7839de7c4a9800877f536eac438a82fb80f75d0ee534cbded565",
          "sha1": "f60b21124e9a92e6ae75837d1b79640e97cb5043",
          "md5": "2989b91fdb21fe37476fae36175fc5a9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.1.7-b0-sources.jar",
          "url": "core-ng-api-9.1.7-b0-sources.jar",
          "size": 8665,
          "sha512": "e9ba7498bef72012e5b1e31e87a04ebadea989a2612eaeb3c9dbe437693a35cd011df937be512cb6d5af34d515e8667eeb42f0add359bcc38356a84dfb14c718",
          "sha256": "1f2e1c7e3b96cef2225754a16db003603cc371f8dce7a9882caf01f21b6f8c84",
          "sha1": "09b365aad506f1418ed0f960eecd4ea5c457bde8",
          "md5": "00b4a3854ac8f8971f42082b959a1d90"
        }
      ]
    }
  ]
}
