{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "9.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.0.8.jar",
          "url": "core-ng-mongo-test-9.0.8.jar",
          "size": 2387,
          "sha512": "5637f74971e66c944e973100748aa9ed1371510f03050ff1c845784c761cbdffb9371632a24c066022dec0e84b78cea5464779891414f1b79a5df7c53dd73c98",
          "sha256": "0f07c8550d8394a9c18b26b392c25271de21538d15266d37e376c0185c408e6b",
          "sha1": "5321f010acadeaf2b6484fc6e09098f6b9794030",
          "md5": "d217338ebab9df9f238544dc13c653bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.0.8"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "9.0.8"
          }
        },
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.44.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-9.0.8.jar",
          "url": "core-ng-mongo-test-9.0.8.jar",
          "size": 2387,
          "sha512": "5637f74971e66c944e973100748aa9ed1371510f03050ff1c845784c761cbdffb9371632a24c066022dec0e84b78cea5464779891414f1b79a5df7c53dd73c98",
          "sha256": "0f07c8550d8394a9c18b26b392c25271de21538d15266d37e376c0185c408e6b",
          "sha1": "5321f010acadeaf2b6484fc6e09098f6b9794030",
          "md5": "d217338ebab9df9f238544dc13c653bf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.0.8-sources.jar",
          "url": "core-ng-mongo-test-9.0.8-sources.jar",
          "size": 1721,
          "sha512": "83c6b428bc7d83839a6613507f5e8cdb55bee6bd2e3165c5508069fead235aabd0262a9bad3f61a5b5de0f90cde0c083707d96ab932896d299ab4e47840f01db",
          "sha256": "12c62b82b928b491b79055ca1ac619432de7ad2c9114dafc20f1cc3857cbce8d",
          "sha1": "ab6d326b070f92288f41e44c7cdf092a77e4c51f",
          "md5": "d9e0673299b6fbe88b6ef9923844ca81"
        }
      ]
    }
  ]
}
