{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "7.6.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "5ouw753gz5cgbnubxggdyz4bvu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.6.12.jar",
          "url": "core-ng-search-test-7.6.12.jar",
          "size": 9067,
          "sha512": "f75a180fa501d3d143b13e74ef8c482a4844d11a55dfd6389a8ba1d402f7871f8c63c5cf6b70a3e6b9642db0c92146aac55e3d9984b69c450c41a08730bdfa10",
          "sha256": "28c67b05609cffcc02745356f211826f885b3e370b3673d9503fb33729bc603a",
          "sha1": "6331e67098ab49efa0d38b4ab6d82776be00244d",
          "md5": "e415acbad8eded3776f92bd0eeda5f1b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.6.12"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.6.12"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "7.11.2"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4-client",
          "version": {
            "requires": "7.11.2"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "reindex-client",
          "version": {
            "requires": "7.11.2"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "mapper-extras-client",
          "version": {
            "requires": "7.11.2"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "7.11.2"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "7.11.2"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.6.12.jar",
          "url": "core-ng-search-test-7.6.12.jar",
          "size": 9067,
          "sha512": "f75a180fa501d3d143b13e74ef8c482a4844d11a55dfd6389a8ba1d402f7871f8c63c5cf6b70a3e6b9642db0c92146aac55e3d9984b69c450c41a08730bdfa10",
          "sha256": "28c67b05609cffcc02745356f211826f885b3e370b3673d9503fb33729bc603a",
          "sha1": "6331e67098ab49efa0d38b4ab6d82776be00244d",
          "md5": "e415acbad8eded3776f92bd0eeda5f1b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.6.12-sources.jar",
          "url": "core-ng-search-test-7.6.12-sources.jar",
          "size": 5478,
          "sha512": "5e8a8882a4e01013ea7a7bc2a809c78317ae78d8b903d825f25409772f3492946ebfa6a695ec2598d2e01d2afa719ffe9b35e08bcb01651bfe1fab29a5957120",
          "sha256": "070c50d0b87b8aa8eea4955dd06f609b06e8dd17b786c4f52e302d37d4d1c3fc",
          "sha1": "9557ad24690674c1e96d1cfd2eff3067c03ef1b2",
          "md5": "bfd62f1b79ab5f243f6b03ef60c7be04"
        }
      ]
    }
  ]
}
