{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "7.6.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "y4jpvy47ejel5oivsnxw6bxvra"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.6.12.jar",
          "url": "core-ng-search-test-7.6.12.jar",
          "size": 9067,
          "sha512": "fad6a686d6a6c055a84a26f4e053c4e9ad7444e980ee8c28ae5f3f645ff47e0d7e4d58c6a453a3086109fd41560c8649e381d134788a90d2b152cbdef36f0f43",
          "sha256": "37dc4d87985dd74b36d95d396cac2860f70f42f984ff3538da90a2a9f3657b6e",
          "sha1": "5ed29330e8b373fdbc216c283d546e7374f01348",
          "md5": "5449f26faf19ba6baaff28469ac3afb1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.6.12"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.6.12"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4-client",
          "version": {
            "requires": "7.10.2"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "reindex-client",
          "version": {
            "requires": "7.10.2"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "7.10.2"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "7.10.2"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "7.10.2"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.6.12.jar",
          "url": "core-ng-search-test-7.6.12.jar",
          "size": 9067,
          "sha512": "fad6a686d6a6c055a84a26f4e053c4e9ad7444e980ee8c28ae5f3f645ff47e0d7e4d58c6a453a3086109fd41560c8649e381d134788a90d2b152cbdef36f0f43",
          "sha256": "37dc4d87985dd74b36d95d396cac2860f70f42f984ff3538da90a2a9f3657b6e",
          "sha1": "5ed29330e8b373fdbc216c283d546e7374f01348",
          "md5": "5449f26faf19ba6baaff28469ac3afb1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.6.12-sources.jar",
          "url": "core-ng-search-test-7.6.12-sources.jar",
          "size": 5478,
          "sha512": "5b98a0f0602949746f642587df9becb7c8ca03cfab3ffc03665c1666870e640547f20081c87576e87c57dad43f43377e1c85bf7e23b5501b8646eac09ed7fde5",
          "sha256": "25afc7b5ed4a391fcde679455b4fea87c6b286bc3a56c2658c2c1e2b8add12dc",
          "sha1": "5cc8c70e2e9df9ba91168ef47141fe419b88a9ef",
          "md5": "9088725e9f5bb12fb07f5cb658f92d0c"
        }
      ]
    }
  ]
}
