{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "9.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.8"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.0.8.jar",
          "url": "core-ng-mongo-9.0.8.jar",
          "size": 57155,
          "sha512": "15ff007add0998dfdd0a243c7a9739a246a5cc2f14240ae0ee7227b294c6458a7f30cc7b60acaea36ca892b8381e8240f72c11aade93d38601535e37d457dbf1",
          "sha256": "4752227da8b630e5cbad2d0ac3a05b973e678646bab758103603dd8f943eec1b",
          "sha1": "284f8b71e14e140db5c0b296c00dbd96f663f104",
          "md5": "2f6cfdbd8358f8262d82234d442b4a9a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.8"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.0.8.jar",
          "url": "core-ng-mongo-9.0.8.jar",
          "size": 57155,
          "sha512": "15ff007add0998dfdd0a243c7a9739a246a5cc2f14240ae0ee7227b294c6458a7f30cc7b60acaea36ca892b8381e8240f72c11aade93d38601535e37d457dbf1",
          "sha256": "4752227da8b630e5cbad2d0ac3a05b973e678646bab758103603dd8f943eec1b",
          "sha1": "284f8b71e14e140db5c0b296c00dbd96f663f104",
          "md5": "2f6cfdbd8358f8262d82234d442b4a9a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-9.0.8-sources.jar",
          "url": "core-ng-mongo-9.0.8-sources.jar",
          "size": 27011,
          "sha512": "e79be47095da4f6dd8ab591ee308cf5d4ef877ad370f08f850611683f7136b2b536ce3728cf226bd16e77da4a2ccc86b58d08fd8dd785d6e93f05b49f0420ffc",
          "sha256": "f8da11e67c66debd2a788e1c8c9a4f00cd3f930d26e1a3f91d63a1726d82e9a6",
          "sha1": "aab128d60349864a1f2fa415dcd756d3f01343bc",
          "md5": "57e3f1a85fb50d48f8b28dc25d385478"
        }
      ]
    }
  ]
}
