{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "9.4.0-b3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.4.0-b3.jar",
          "url": "core-ng-search-test-9.4.0-b3.jar",
          "size": 10074,
          "sha512": "8de117efe58d00002040506474c97e3f9e70545d6c3ba085151f327d3d8c76643c329d46bb3f704cb0b3d50270433c73d92ba2e3a4cd98f56915b801f74e7e6e",
          "sha256": "443225b58d3a67c0498af8e6db81a7ea4bd04b52bc7aa7775f417a5ab1e2194b",
          "sha1": "a3779bca0e5c8d81efadb35f3f9ebdf9d0ecfea5",
          "md5": "6770349c6ad822e341409802d5ceaf19"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.4.0-b3"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "9.4.0-b3"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "8.18.1"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "reindex",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-9.4.0-b3.jar",
          "url": "core-ng-search-test-9.4.0-b3.jar",
          "size": 10074,
          "sha512": "8de117efe58d00002040506474c97e3f9e70545d6c3ba085151f327d3d8c76643c329d46bb3f704cb0b3d50270433c73d92ba2e3a4cd98f56915b801f74e7e6e",
          "sha256": "443225b58d3a67c0498af8e6db81a7ea4bd04b52bc7aa7775f417a5ab1e2194b",
          "sha1": "a3779bca0e5c8d81efadb35f3f9ebdf9d0ecfea5",
          "md5": "6770349c6ad822e341409802d5ceaf19"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.4.0-b3-sources.jar",
          "url": "core-ng-search-test-9.4.0-b3-sources.jar",
          "size": 6289,
          "sha512": "de7ee42322b31523870197bfb148e5f8a8284f1da48f54c585a3598ebc10698a48bd44b0c2a2688f15362ec308c401600b0c9c6bf520ba027a52e036b186c29e",
          "sha256": "612771b917e8733b1ece5b3146793028ebed42acb6b6630cdb45c4d4a25c2c97",
          "sha1": "8d3c474fff6260b6eea7aa91fc36b586f5682c28",
          "md5": "bc4461133947b4820bf063e1e8e4696e"
        }
      ]
    }
  ]
}
