{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "7.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6",
      "buildId": "jdhsmwlbjvg6foywe56zxxdxk4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.5.6"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.5.6.jar",
          "url": "core-ng-7.5.6.jar",
          "size": 656266,
          "sha512": "931e17f7e4ee3c8159c98ce2d146ab0644d9d2e94199a7db6fe46010f0b8d7855d5882772fe82b287ec1b5738d88eec10ae07a60f24abe51d5cfa8ec418d0654",
          "sha256": "a4a17ce35f9665efd675b52980fa144c8e7ca6614635ed139e21f127691fd539",
          "sha1": "b84fe1e7f81951413bfca255132af4838f4a37a7",
          "md5": "1b2548826be16e3d5e0b56599b527759"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.27.0-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.10.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.10.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.8.1"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.1.3.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.4.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.7.6"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.5.6"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.5.6.jar",
          "url": "core-ng-7.5.6.jar",
          "size": 656266,
          "sha512": "931e17f7e4ee3c8159c98ce2d146ab0644d9d2e94199a7db6fe46010f0b8d7855d5882772fe82b287ec1b5738d88eec10ae07a60f24abe51d5cfa8ec418d0654",
          "sha256": "a4a17ce35f9665efd675b52980fa144c8e7ca6614635ed139e21f127691fd539",
          "sha1": "b84fe1e7f81951413bfca255132af4838f4a37a7",
          "md5": "1b2548826be16e3d5e0b56599b527759"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-7.5.6-sources.jar",
          "url": "core-ng-7.5.6-sources.jar",
          "size": 335141,
          "sha512": "65084a28c1f5f26d508d7faafc1a2d12fc047d768b397305327eb3af5fe1d46688cecdbdd08f049735abc76809a3ea03bcabf7fe53fe0ef1eb48f5cd5e42f455",
          "sha256": "bb1ee73d0577081c946c6657e5bc21ed34dccf1891cddb5391ea6405c51ab037",
          "sha1": "a3f035e1272a1867085d0de973099479c0f0f88e",
          "md5": "d2aaf0ca305fd7c40a9d5a4bf0dc7f5b"
        }
      ]
    }
  ]
}
