{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "9.0.8-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.8-b0"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.12.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.0.8-b0.jar",
          "url": "core-ng-search-9.0.8-b0.jar",
          "size": 52867,
          "sha512": "477531f92793ba3836bdf68f6b4a3c26a7b7affde6215a40422caf1e07683aaa13ec5497dccdf1fc674dd6b69b28046289470ea0ce14ccfd2203aef06b88e6f8",
          "sha256": "5c31340c7d082f83b57a48f7efdd10ebfafd296aaeaabe3f210b5daa40f44dca",
          "sha1": "891b4d33174e82e9d5461f7989d88ee3f631abb6",
          "md5": "792030d0ce89b9d120b20e9205ed98c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.16.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.8-b0"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.12.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.0.8-b0.jar",
          "url": "core-ng-search-9.0.8-b0.jar",
          "size": 52867,
          "sha512": "477531f92793ba3836bdf68f6b4a3c26a7b7affde6215a40422caf1e07683aaa13ec5497dccdf1fc674dd6b69b28046289470ea0ce14ccfd2203aef06b88e6f8",
          "sha256": "5c31340c7d082f83b57a48f7efdd10ebfafd296aaeaabe3f210b5daa40f44dca",
          "sha1": "891b4d33174e82e9d5461f7989d88ee3f631abb6",
          "md5": "792030d0ce89b9d120b20e9205ed98c5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-9.0.8-b0-sources.jar",
          "url": "core-ng-search-9.0.8-b0-sources.jar",
          "size": 21981,
          "sha512": "f9e3d05b1865f0f0b6f6b235642c3f30f16a42c1dedbc9c9255dc4612b8c778c928cd29cf8a379182d5e99830664000d1e006486cb369afbfeb67d6ebbc08444",
          "sha256": "b683f0280510c06142d4ae1f49f8074ff3da710f04e0d344950210769effa9b5",
          "sha1": "8b6510533a38862c755b3d489d0ff6339f148843",
          "md5": "b457499ee1b768b6aeb665c06ad591eb"
        }
      ]
    }
  ]
}
