{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "9.5.0-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-api-9.5.0-b0.jar",
          "url": "core-ng-api-9.5.0-b0.jar",
          "size": 11018,
          "sha512": "4a587f61f0eaa9678cd72e1986c3d9acad40f67bcb66065919d98df95a45beae46b7e8528538dfeaa7f911048754e5a2f57876539b9282275122b474fd5cb6bc",
          "sha256": "ecd3e07848b9924dd02458a9bd08b800a28e426f9334cb5f6b92550ed00782ac",
          "sha1": "c0c221ffc4faabcc4effa4d5d98b3b4ce78fdc2c",
          "md5": "3faca211f85564e3ffde813ef2f8476d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-api-9.5.0-b0.jar",
          "url": "core-ng-api-9.5.0-b0.jar",
          "size": 11018,
          "sha512": "4a587f61f0eaa9678cd72e1986c3d9acad40f67bcb66065919d98df95a45beae46b7e8528538dfeaa7f911048754e5a2f57876539b9282275122b474fd5cb6bc",
          "sha256": "ecd3e07848b9924dd02458a9bd08b800a28e426f9334cb5f6b92550ed00782ac",
          "sha1": "c0c221ffc4faabcc4effa4d5d98b3b4ce78fdc2c",
          "md5": "3faca211f85564e3ffde813ef2f8476d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.5.0-b0-sources.jar",
          "url": "core-ng-api-9.5.0-b0-sources.jar",
          "size": 8663,
          "sha512": "caf9d157012115c753ecd0b1e4394da992f49189e9eb6c351e55ce994f1af0624332e3cd97996c57b339387427ac4189642cf71a58d8d2ec140e2dcb50e58859",
          "sha256": "9297e21412c87934e68afe928cee1dd4940841d3a4edf75d1bcc829ecef35ac2",
          "sha1": "1d1198f7e6a3f4f048e5e73ae15d5d5008d5c984",
          "md5": "71f859ff49ad4eb082da3446b8769dd8"
        }
      ]
    }
  ]
}
