{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "9.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.5.3"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "9.3.2"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            },
            {
              "group": "io.opentelemetry.semconv",
              "module": "*"
            },
            {
              "group": "com.fasterxml.jackson.core",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.5.3.jar",
          "url": "core-ng-search-9.5.3.jar",
          "size": 59733,
          "sha512": "fa3d4363d414cbf339a80a6dcfbbbd5d1f4f40677e7107f9e6fc68f98f37ab23331be69b98975bc036a99a423baef0ee3e10261e8e8ace06f94176b42ac6b71a",
          "sha256": "6492a0c232b37de814a837567a7acdcccc75933ef631358a45ea88e694151411",
          "sha1": "73484bbfbf30a4de036e63f01d44a4f1fca0d7d0",
          "md5": "c8119ff1dc39a4225194ea54976b7ec2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-rest5-client",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "tools.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.5.3"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "9.3.2"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            },
            {
              "group": "io.opentelemetry.semconv",
              "module": "*"
            },
            {
              "group": "com.fasterxml.jackson.core",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.5.3.jar",
          "url": "core-ng-search-9.5.3.jar",
          "size": 59733,
          "sha512": "fa3d4363d414cbf339a80a6dcfbbbd5d1f4f40677e7107f9e6fc68f98f37ab23331be69b98975bc036a99a423baef0ee3e10261e8e8ace06f94176b42ac6b71a",
          "sha256": "6492a0c232b37de814a837567a7acdcccc75933ef631358a45ea88e694151411",
          "sha1": "73484bbfbf30a4de036e63f01d44a4f1fca0d7d0",
          "md5": "c8119ff1dc39a4225194ea54976b7ec2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-9.5.3-sources.jar",
          "url": "core-ng-search-9.5.3-sources.jar",
          "size": 24979,
          "sha512": "2f8dddee6433d56f0b5496e14197e299393e6d95499f79532fdb4f3693f8b4e1f63b1666541f044290312d6192b253a7187c63e0b00d4ea48e3e46a3e31c3353",
          "sha256": "3676b0dc872af00451524a7bc92dde0dab197bc0d734c10aad719e678fa802a9",
          "sha1": "c193c7524726e26996d84e8b89dd2ea798f07343",
          "md5": "589e511dd81b5b8bf44277c242bea8f4"
        }
      ]
    }
  ]
}
