{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "9.3.0-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.3.0-b0.jar",
          "url": "core-ng-search-test-9.3.0-b0.jar",
          "size": 10069,
          "sha512": "f46fbc0ca45286ab4227dc40b53b6ecbd50a5a341be82ba2b2264c3d69819779f15a1e880226ae837536b6327cc72c2fa417fe81274204cb24834992598ee9e5",
          "sha256": "3c948ce201c920bf3bc5932df0b2f882aa886bcc717015168334333eb872f197",
          "sha1": "7fb950999dfdfdbc9d701743cff843ed8c1a82b7",
          "md5": "dbec11bf2f8d067e0b468a82f5f6bfad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.3.0-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "9.3.0-b0"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "8.18.1"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "reindex",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-9.3.0-b0.jar",
          "url": "core-ng-search-test-9.3.0-b0.jar",
          "size": 10069,
          "sha512": "f46fbc0ca45286ab4227dc40b53b6ecbd50a5a341be82ba2b2264c3d69819779f15a1e880226ae837536b6327cc72c2fa417fe81274204cb24834992598ee9e5",
          "sha256": "3c948ce201c920bf3bc5932df0b2f882aa886bcc717015168334333eb872f197",
          "sha1": "7fb950999dfdfdbc9d701743cff843ed8c1a82b7",
          "md5": "dbec11bf2f8d067e0b468a82f5f6bfad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.3.0-b0-sources.jar",
          "url": "core-ng-search-test-9.3.0-b0-sources.jar",
          "size": 6284,
          "sha512": "5ddc56f8411a2d8165a88601f8d20fe198a8f6419c378ac750c2213edc37a12295eaf5439c4698ee22ebc8a151bb99fa6ceef18f6438fd85c708709ef72107a8",
          "sha256": "227f43c55ca1bde1d8337a6f9abdb7e5a80082c17416d52a17cb329b6b21e06d",
          "sha1": "95ca515bf8279e6f43dee6955548a367e07991b7",
          "md5": "6bcc97407b608f3d20c8d2ef1217c0c9"
        }
      ]
    }
  ]
}
