{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "9.1.6-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-9.1.6-b1.jar",
          "url": "core-ng-api-9.1.6-b1.jar",
          "size": 11022,
          "sha512": "04728898998ec14d0bfab754e048414bcc3ca65caa8c0c75d53a4003a3b007f1a56a312b75ee2bb66bc67f04d52f8af0811a42bf677862c7c79259d5f580a027",
          "sha256": "c51b7f3cdcaa7081d216c2c63b47225bfc050fbbd3250fdb1d45c348826b9d8b",
          "sha1": "55181da82fec65c1261f109ab22d9c954a34ba59",
          "md5": "a0996cab0ab349db1ef531f5b53fb5eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.1.6-b1.jar",
          "url": "core-ng-api-9.1.6-b1.jar",
          "size": 11022,
          "sha512": "04728898998ec14d0bfab754e048414bcc3ca65caa8c0c75d53a4003a3b007f1a56a312b75ee2bb66bc67f04d52f8af0811a42bf677862c7c79259d5f580a027",
          "sha256": "c51b7f3cdcaa7081d216c2c63b47225bfc050fbbd3250fdb1d45c348826b9d8b",
          "sha1": "55181da82fec65c1261f109ab22d9c954a34ba59",
          "md5": "a0996cab0ab349db1ef531f5b53fb5eb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.1.6-b1-sources.jar",
          "url": "core-ng-api-9.1.6-b1-sources.jar",
          "size": 8665,
          "sha512": "8c39b02ed4f694eb346b90972b8c3a9594b9864bee4b5f5ea019994050a3b7767792be310ab4ea58e1f92c53ebcad208710e50955d0daa68789e73e19b297537",
          "sha256": "4f090ac64019152ab995edf9999ba741ccf200a43ce6afed6cfe6b68aabc0091",
          "sha1": "80f3cb93bd010203650ec358114d4e0953c4968c",
          "md5": "58df1701ea89e441820bb6afc2ef9587"
        }
      ]
    }
  ]
}
