{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "9.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.1.7.jar",
          "url": "core-ng-mongo-test-9.1.7.jar",
          "size": 2486,
          "sha512": "933e8da26c0f05ba5037556fbc66a4362bf2b6af96bc6bb7c1ecd41857987247455e66ea185161a8d51659dbde46dbb46c5a33370dc4826a653684354fc2db88",
          "sha256": "dd9fbd53a73f156b40fc70c85d907c72b249c4d13df47f51ca7711cd44a3aa39",
          "sha1": "960f0699bfacb8fdee8a3d550c6c6fd98a8f4c47",
          "md5": "bd3c7f545528ec6b6455b86873f3c17e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.1.7"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "9.1.7"
          }
        },
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.46.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-9.1.7.jar",
          "url": "core-ng-mongo-test-9.1.7.jar",
          "size": 2486,
          "sha512": "933e8da26c0f05ba5037556fbc66a4362bf2b6af96bc6bb7c1ecd41857987247455e66ea185161a8d51659dbde46dbb46c5a33370dc4826a653684354fc2db88",
          "sha256": "dd9fbd53a73f156b40fc70c85d907c72b249c4d13df47f51ca7711cd44a3aa39",
          "sha1": "960f0699bfacb8fdee8a3d550c6c6fd98a8f4c47",
          "md5": "bd3c7f545528ec6b6455b86873f3c17e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.1.7-sources.jar",
          "url": "core-ng-mongo-test-9.1.7-sources.jar",
          "size": 1778,
          "sha512": "f1a61863f9d68dd0cb9dfdce0b1618e25ba4e791c7d25a397c0b82ff52ff63e760b88fa9f8ef80cace78bf49a0a75f76d696418bc6db8b9274847a0074b1ca6a",
          "sha256": "437840075733f4925ba06300288e414a720be00f9835556c300d4a5069a5960d",
          "sha1": "d1279052c1b39e274ad6dfdbd96ca027ce2f6c20",
          "md5": "338f114df238b83d914a127cdf2160c8"
        }
      ]
    }
  ]
}
