{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "9.1.7-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.7-b0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.1.7-b0.jar",
          "url": "core-ng-mongo-9.1.7-b0.jar",
          "size": 57159,
          "sha512": "3f1917b36295aaa888814217195019d48f6618c1c79f674cb65aa561d5610bf3058aa0336d553eaf70be7a29f995ae314c44f8d3aaa80d6219de6b5a5f7c75ee",
          "sha256": "66ce109efed891830aa606fe0abe724a22e8cd216f318997e1539942a94c965d",
          "sha1": "03d68734b0ee488bb8fef3e46076e595958d564b",
          "md5": "1fa8fab76b7a5ca88bcadb6eef793823"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.7-b0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.1.7-b0.jar",
          "url": "core-ng-mongo-9.1.7-b0.jar",
          "size": 57159,
          "sha512": "3f1917b36295aaa888814217195019d48f6618c1c79f674cb65aa561d5610bf3058aa0336d553eaf70be7a29f995ae314c44f8d3aaa80d6219de6b5a5f7c75ee",
          "sha256": "66ce109efed891830aa606fe0abe724a22e8cd216f318997e1539942a94c965d",
          "sha1": "03d68734b0ee488bb8fef3e46076e595958d564b",
          "md5": "1fa8fab76b7a5ca88bcadb6eef793823"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-9.1.7-b0-sources.jar",
          "url": "core-ng-mongo-9.1.7-b0-sources.jar",
          "size": 27034,
          "sha512": "13c4833fc9174dc0a159cf592636680913b0125a19cfd8bbeb6ca091df3e2a2287ba74f6f73e0bb4b31115d1716efd3cb6ded0f19b39f2b8a25dd0760a49c34a",
          "sha256": "169780945829fe7f05c654a20565ab0e6a4e16dbf69d8f85b55598945f08ab02",
          "sha1": "917053d9c70bdc16deee31952c88a5a09218d111",
          "md5": "a9b817d1d0a172dbfc4c56ea7f18b57e"
        }
      ]
    }
  ]
}
