{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "9.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-api-9.5.0.jar",
          "url": "core-ng-api-9.5.0.jar",
          "size": 11015,
          "sha512": "246c43be6bb872a1d9e49e4324582563bac1557b4e23d370f1e41615c91fc1e43ae4bd9525ed8e2cea2e1d3717ff24582733ff0b78797661065ce051bca84822",
          "sha256": "c1c4978203821e335147e993b03a44a81ae137339154e8a58478ef25f584ab2a",
          "sha1": "f609b8302d80ea75a3e1e794c1a8d2e5d82b5dc4",
          "md5": "3a9d51298a12d9be0fb6292db23ecc73"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-api-9.5.0.jar",
          "url": "core-ng-api-9.5.0.jar",
          "size": 11015,
          "sha512": "246c43be6bb872a1d9e49e4324582563bac1557b4e23d370f1e41615c91fc1e43ae4bd9525ed8e2cea2e1d3717ff24582733ff0b78797661065ce051bca84822",
          "sha256": "c1c4978203821e335147e993b03a44a81ae137339154e8a58478ef25f584ab2a",
          "sha1": "f609b8302d80ea75a3e1e794c1a8d2e5d82b5dc4",
          "md5": "3a9d51298a12d9be0fb6292db23ecc73"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.5.0-sources.jar",
          "url": "core-ng-api-9.5.0-sources.jar",
          "size": 8660,
          "sha512": "a024a0a9827191302891232db2f65dc663d43e186fbd730e46c75b39fa34ba80ff3839197598afa6f9b4ca63f716ea530d01e53debcf90b441dc48c7eee12e50",
          "sha256": "b6c5bad7478c4d9483844a9e10e2be68ab8c8b9812f12fd424647834475732e8",
          "sha1": "c8b4c20d1eee76a871b1bbaf218ec2b118b6388b",
          "md5": "e6651b4d849ba09bb26c7d4af538ca80"
        }
      ]
    }
  ]
}
