{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "9.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.0.3.jar",
          "url": "core-ng-search-test-9.0.3.jar",
          "size": 12664,
          "sha512": "a0a63f6c5c3ae067c6d9bc4d6a45ebcb6c8f4a8386cb53c2c80a20b554c3f1a1d5da0a11603afa0c7756c19d7556f13288a5e798f0c749c3400c517996c77c99",
          "sha256": "f78179ce83ab5f5283881284af1649cd76c3f4077395995e60f6660889b96a95",
          "sha1": "b4119a751dca14450dffb474da1bc8f92574646e",
          "md5": "d180acfbba2893dce39342e538cab990"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.0.3"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "9.0.3"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "transport-netty4",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "reindex",
          "version": {
            "requires": "8.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-9.0.3.jar",
          "url": "core-ng-search-test-9.0.3.jar",
          "size": 12664,
          "sha512": "a0a63f6c5c3ae067c6d9bc4d6a45ebcb6c8f4a8386cb53c2c80a20b554c3f1a1d5da0a11603afa0c7756c19d7556f13288a5e798f0c749c3400c517996c77c99",
          "sha256": "f78179ce83ab5f5283881284af1649cd76c3f4077395995e60f6660889b96a95",
          "sha1": "b4119a751dca14450dffb474da1bc8f92574646e",
          "md5": "d180acfbba2893dce39342e538cab990"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.0.3-sources.jar",
          "url": "core-ng-search-test-9.0.3-sources.jar",
          "size": 7175,
          "sha512": "8532bb5bc00cd02c76119307b56676d191fee86369ce6a22a044383482820552fe0ae9d79f1ac346f0159b716607c592bd5622b235d23c8ad08e288141409837",
          "sha256": "e08eac67285a0eb831fcaeb74d66afc4818d00bcfeed80178c76779db3c4a481",
          "sha1": "7c7c4a6e9b2e49d5e00a31bfb250dc110614981b",
          "md5": "97d7271ab56d49e32fcb301036ca5673"
        }
      ]
    }
  ]
}
