{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "7.5.13-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6",
      "buildId": "2uzdmxjnafdqllzk2zdacqveqe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.5.13-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.5.13-b0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.5.13-b0.jar",
          "url": "core-ng-search-test-7.5.13-b0.jar",
          "size": 9050,
          "sha512": "07e1699a79d6d54799830e87d08201c237ed798b6255056e7c721b345a75b3c9d50f634f73b44cc7b13a97ee796f52fa87065fa11335001a513a891b7fce14f9",
          "sha256": "dde20bb714111a921cd169c6cc97ea936cae0f643cf11aca4aff7fa51f79387b",
          "sha1": "1e461d84fdd997b9e541edc5998f8568d20590de",
          "md5": "b7e2565e3135eb4696c5869e2807aece"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4-client",
          "version": {
            "requires": "7.9.2"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "reindex-client",
          "version": {
            "requires": "7.9.2"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "7.9.2"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "7.9.2"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "7.9.2"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.5.13-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.5.13-b0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.5.13-b0.jar",
          "url": "core-ng-search-test-7.5.13-b0.jar",
          "size": 9050,
          "sha512": "07e1699a79d6d54799830e87d08201c237ed798b6255056e7c721b345a75b3c9d50f634f73b44cc7b13a97ee796f52fa87065fa11335001a513a891b7fce14f9",
          "sha256": "dde20bb714111a921cd169c6cc97ea936cae0f643cf11aca4aff7fa51f79387b",
          "sha1": "1e461d84fdd997b9e541edc5998f8568d20590de",
          "md5": "b7e2565e3135eb4696c5869e2807aece"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.5.13-b0-sources.jar",
          "url": "core-ng-search-test-7.5.13-b0-sources.jar",
          "size": 5430,
          "sha512": "ba841dd437119096c677452d80e371122d317cef20317d3de3ba558154469d6096f78637251f28d2666f31e3f869dded4cd4367f921b5993aa5647e29a544c97",
          "sha256": "57f87568fb210ef0123034f4c90c4c4cb970740891fc698e29070d34d1e8c30f",
          "sha1": "77b5068287b7e3d7de5113654990b175d92e150d",
          "md5": "85ede4ebf80df27ce823cf39f1e31fd4"
        }
      ]
    }
  ]
}
