{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "9.5.1-b4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.5.1-b4.jar",
          "url": "core-ng-mongo-test-9.5.1-b4.jar",
          "size": 2942,
          "sha512": "d430bdc7d3cc6ff25967de8ab71ce0f7ed75d82df0f6dc05ed09c39539649e1bcf69ed188f90b4a42b461f5e295082f0d74220ab2f3fe68ce83ff4c0247f6613",
          "sha256": "56b1842374e7151820c9326dc0414489f6bb30521037c9d044d5e7680eddf03c",
          "sha1": "d7eee708a12be9658237ba72a005c468dca435ce",
          "md5": "c3a0d04d465c28df6fe90f84e422070a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.5.1-b4"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "9.5.1-b4"
          }
        },
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.47.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-9.5.1-b4.jar",
          "url": "core-ng-mongo-test-9.5.1-b4.jar",
          "size": 2942,
          "sha512": "d430bdc7d3cc6ff25967de8ab71ce0f7ed75d82df0f6dc05ed09c39539649e1bcf69ed188f90b4a42b461f5e295082f0d74220ab2f3fe68ce83ff4c0247f6613",
          "sha256": "56b1842374e7151820c9326dc0414489f6bb30521037c9d044d5e7680eddf03c",
          "sha1": "d7eee708a12be9658237ba72a005c468dca435ce",
          "md5": "c3a0d04d465c28df6fe90f84e422070a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.5.1-b4-sources.jar",
          "url": "core-ng-mongo-test-9.5.1-b4-sources.jar",
          "size": 2081,
          "sha512": "fd0c1b34080a20c2faf9f4c77ddfe11bf26ebdde741d018b47d152d5fad4e4196af7fb5fb07ea74925564159a2cc33f3524cedbb512d4267aa49f5602894b147",
          "sha256": "050753da1b2cd52c1789536f05d5be1b288a17491a65a7327c5090614f0d302e",
          "sha1": "7c0af83ec52f303574c37d9a7839bcb32ac95557",
          "md5": "03b27f118c8b6b0050e7d32a5110f56e"
        }
      ]
    }
  ]
}
