{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "9.3.0-b2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.3.0-b2.jar",
          "url": "core-ng-mongo-test-9.3.0-b2.jar",
          "size": 2940,
          "sha512": "a6027e65611f8d3661839f1a84f2e5505f212cec11410d6b6523787bd6a1db5d81e013b8b2a3b33132adb9c18d5e92e56ed7a9d7ac1dee6828310c222263bca7",
          "sha256": "e9c160b0faf61aa240c4e0e263c5f7408014f5a0cd841c5e73ddf99f32d92017",
          "sha1": "b4c15b2e319fdc3ee5441e7ae683cb7d0f53d8b4",
          "md5": "ad52b161fa3d7b51ff37c972806d612b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.3.0-b2"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "9.3.0-b2"
          }
        },
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.47.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-9.3.0-b2.jar",
          "url": "core-ng-mongo-test-9.3.0-b2.jar",
          "size": 2940,
          "sha512": "a6027e65611f8d3661839f1a84f2e5505f212cec11410d6b6523787bd6a1db5d81e013b8b2a3b33132adb9c18d5e92e56ed7a9d7ac1dee6828310c222263bca7",
          "sha256": "e9c160b0faf61aa240c4e0e263c5f7408014f5a0cd841c5e73ddf99f32d92017",
          "sha1": "b4c15b2e319fdc3ee5441e7ae683cb7d0f53d8b4",
          "md5": "ad52b161fa3d7b51ff37c972806d612b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.3.0-b2-sources.jar",
          "url": "core-ng-mongo-test-9.3.0-b2-sources.jar",
          "size": 2079,
          "sha512": "4b7b1063ad45a2c0460c8cd480cdd7f9520e9412f7e5788f965499eec08ee034717a0ea01e8a55c2a26f898e5f29796070c5643a57941cb01b7a39efaebae59c",
          "sha256": "d5232db2fe664bbed907cc6a8d8e294ff66107aa4628e11ad8ec32c64b4e1f2f",
          "sha1": "fa4a42a78c70ac1c552c339c4f0af64127d1068e",
          "md5": "f7ff975dedbf5bcb49b2ed6590794eb7"
        }
      ]
    }
  ]
}
