{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "7.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6",
      "buildId": "jdhsmwlbjvg6foywe56zxxdxk4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.5.6"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "7.5.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-7.5.6.jar",
          "url": "core-ng-mongo-test-7.5.6.jar",
          "size": 2381,
          "sha512": "6b7bcb82142a59ddf773d042f2d2d1e797b7e576f639021b1487212cc2b8eca328cd23d8ea07c77003b4306d73f6cde66a5e45e7182594ad92204e85a0cb62ac",
          "sha256": "df19ad0c4e74fa11ce05bb0c3f6630613a25d5f91afd8982d78acf5e0332f942",
          "sha1": "0c1b1e58882fd2ab83d9b846b4de8c9f345f0982",
          "md5": "e8eeb67e0c5366cf417944595980b63d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.34.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.5.6"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "7.5.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-7.5.6.jar",
          "url": "core-ng-mongo-test-7.5.6.jar",
          "size": 2381,
          "sha512": "6b7bcb82142a59ddf773d042f2d2d1e797b7e576f639021b1487212cc2b8eca328cd23d8ea07c77003b4306d73f6cde66a5e45e7182594ad92204e85a0cb62ac",
          "sha256": "df19ad0c4e74fa11ce05bb0c3f6630613a25d5f91afd8982d78acf5e0332f942",
          "sha1": "0c1b1e58882fd2ab83d9b846b4de8c9f345f0982",
          "md5": "e8eeb67e0c5366cf417944595980b63d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-7.5.6-sources.jar",
          "url": "core-ng-mongo-test-7.5.6-sources.jar",
          "size": 1719,
          "sha512": "a49a804f80735c61f409b01a52598a81cb1dd3a21dc3fc8996d80b4aacca55650cec7f5b812fc50de91cd689e9bbfa07b6cb7c732a32175258b34d06beaf2251",
          "sha256": "96299fcc461a0d956e2598a025016b2c0148444fecd97e47e723c68a1830176e",
          "sha1": "9948bd6ad1e6ca1f262fdb718060b9230d6ab4f5",
          "md5": "8344709ef485f7e93cff818f87952592"
        }
      ]
    }
  ]
}
