{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "9.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.0.2.jar",
          "url": "core-ng-mongo-test-9.0.2.jar",
          "size": 2385,
          "sha512": "01ea4061d5698ab21dcd52be4fa06266f6ab0d1a1f938fef7d85c9230c5dc28a67e17292a54193a1c9d21955774a6e103c495fc4964ebaecdf7483fc92a1a0d6",
          "sha256": "dccfdb51e8bd2435e941246d526b76be890482049e8d870267388c710e4ad554",
          "sha1": "3cf81154fd4b734f5e3ee2696bee8a2edff4c1ca",
          "md5": "13f21c8136a1ec1cd5c5b28110fa3e4c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.0.2"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "9.0.2"
          }
        },
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.44.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-9.0.2.jar",
          "url": "core-ng-mongo-test-9.0.2.jar",
          "size": 2385,
          "sha512": "01ea4061d5698ab21dcd52be4fa06266f6ab0d1a1f938fef7d85c9230c5dc28a67e17292a54193a1c9d21955774a6e103c495fc4964ebaecdf7483fc92a1a0d6",
          "sha256": "dccfdb51e8bd2435e941246d526b76be890482049e8d870267388c710e4ad554",
          "sha1": "3cf81154fd4b734f5e3ee2696bee8a2edff4c1ca",
          "md5": "13f21c8136a1ec1cd5c5b28110fa3e4c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.0.2-sources.jar",
          "url": "core-ng-mongo-test-9.0.2-sources.jar",
          "size": 1719,
          "sha512": "75c57a9156d8d52dc16cc0b2c2a54dabd5e511909ab70faca22de03b648dc66c2d0dacfabfecf652726fd0a3b2d9165b9a8bbf12bd48fe404b32198ec0d5f6ba",
          "sha256": "69252f9ef13c0f615052b7c8c1d44f9a98a12452176973a4edbd79d85ef4086f",
          "sha1": "48ac02dd0d2eb28c00467d0953f2fc27f7f584f0",
          "md5": "7a821dd031bd7947017b269dd16f0bf2"
        }
      ]
    }
  ]
}
