{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "9.2.2-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.2.2-b0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.2.2-b0.jar",
          "url": "core-ng-mongo-9.2.2-b0.jar",
          "size": 57989,
          "sha512": "3820751874cb80a2c5b20c172160e9dce7e4ec7e5213b1310aa4fd667591ce8b20c4285a869c32374b1524d86c6fcb1958b1ab87950827e18cfe5e44c235e0a4",
          "sha256": "a01035659043fe00acdf033c53550b35dd081307a7f3919f839d86c2a60917dc",
          "sha1": "ed1d3f548e8b62ccab229277fe63f3a0d8de37af",
          "md5": "1863bb2a90e77d3bc16798bf0ac0ea88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.2.2-b0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.2.2-b0.jar",
          "url": "core-ng-mongo-9.2.2-b0.jar",
          "size": 57989,
          "sha512": "3820751874cb80a2c5b20c172160e9dce7e4ec7e5213b1310aa4fd667591ce8b20c4285a869c32374b1524d86c6fcb1958b1ab87950827e18cfe5e44c235e0a4",
          "sha256": "a01035659043fe00acdf033c53550b35dd081307a7f3919f839d86c2a60917dc",
          "sha1": "ed1d3f548e8b62ccab229277fe63f3a0d8de37af",
          "md5": "1863bb2a90e77d3bc16798bf0ac0ea88"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-9.2.2-b0-sources.jar",
          "url": "core-ng-mongo-9.2.2-b0-sources.jar",
          "size": 27577,
          "sha512": "a2e475522263b8eb305c3b74c35791606a55aa7e90a535da1e089c6e02e3217c6bc8dbdda941cf904d5ec650e2d8b2ee3bf021da45d02ff2414122148037bef9",
          "sha256": "f9997445782f6077f685a409cb9ad36296f87e429735af74dabb44172e9e5ab0",
          "sha1": "c690446753eb3857c5331b794138b1d41ca95e2d",
          "md5": "920805f23190a61a681ec694c42ae742"
        }
      ]
    }
  ]
}
