{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "9.1.2-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.1.2-b0.jar",
          "url": "core-ng-mongo-test-9.1.2-b0.jar",
          "size": 2488,
          "sha512": "6e88f6742ab3505e3ebde94b425fbbdaba5c206932dca93bcc7fdaa5e5761153b809fd6adcb7d38d65864aae0123b1f75cdab25f3d29bdae0ccf00731eb01f39",
          "sha256": "638c190ec0253994fc5856473f33cc1479f7f273a46f7410122403c1b3652ab5",
          "sha1": "2cec5d66bb660603da0f811deed3082af720bff8",
          "md5": "3524e8b5e54836acd61589896c9c5c21"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.1.2-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "9.1.2-b0"
          }
        },
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.45.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-9.1.2-b0.jar",
          "url": "core-ng-mongo-test-9.1.2-b0.jar",
          "size": 2488,
          "sha512": "6e88f6742ab3505e3ebde94b425fbbdaba5c206932dca93bcc7fdaa5e5761153b809fd6adcb7d38d65864aae0123b1f75cdab25f3d29bdae0ccf00731eb01f39",
          "sha256": "638c190ec0253994fc5856473f33cc1479f7f273a46f7410122403c1b3652ab5",
          "sha1": "2cec5d66bb660603da0f811deed3082af720bff8",
          "md5": "3524e8b5e54836acd61589896c9c5c21"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.1.2-b0-sources.jar",
          "url": "core-ng-mongo-test-9.1.2-b0-sources.jar",
          "size": 1780,
          "sha512": "083f5dc3aa4633c9dd55e9d28a767e192e4ce0196b4d2eaab058be2b9ec22c57c8059d7d40c6d761dd37ecf55d37e321cb0a9ae3fa60b1e745e98713dc03ee85",
          "sha256": "e418d1d77b364e7f551a38374698bc937a542ece5877d61d435b44f3d13a5ac4",
          "sha1": "eded50d6ed586b07e2a2ea996bc0db1d5f256029",
          "md5": "b1815cf180edf3957bf4172f804ec361"
        }
      ]
    }
  ]
}
