{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "9.1.7-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.1.7-b0.jar",
          "url": "core-ng-mongo-test-9.1.7-b0.jar",
          "size": 2489,
          "sha512": "69cec561919ce1a09c0cd3c6c7aac12f3a57c4d0954a9f8418c8c295c8e4db882126476350fa3437883d9aadb0b9beae8a98f7491ed16bfd55907845b198ca3b",
          "sha256": "36a850ac36d5085b63e073998424a7d007ca71541bc66629ca81cbff8bc6f3e0",
          "sha1": "4828cbe11c5c35b06ec3cf634df2a292cf118604",
          "md5": "93198dd16a19e3a0d5f6bcba6d4ab68e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.1.7-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "9.1.7-b0"
          }
        },
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.46.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-9.1.7-b0.jar",
          "url": "core-ng-mongo-test-9.1.7-b0.jar",
          "size": 2489,
          "sha512": "69cec561919ce1a09c0cd3c6c7aac12f3a57c4d0954a9f8418c8c295c8e4db882126476350fa3437883d9aadb0b9beae8a98f7491ed16bfd55907845b198ca3b",
          "sha256": "36a850ac36d5085b63e073998424a7d007ca71541bc66629ca81cbff8bc6f3e0",
          "sha1": "4828cbe11c5c35b06ec3cf634df2a292cf118604",
          "md5": "93198dd16a19e3a0d5f6bcba6d4ab68e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.1.7-b0-sources.jar",
          "url": "core-ng-mongo-test-9.1.7-b0-sources.jar",
          "size": 1781,
          "sha512": "e86707e2124bab4585aef9148ea712e30c81dfe8e831873600def09b8e3ffc5f1e35dce70f107852e2b0a1194a1a12b49e1dbebe61be4a0dd8e94cf30b3a2c83",
          "sha256": "e31cfe5fbc04bf4822611081d0ea40280b7ab33ec6457c346258dba3a08b2886",
          "sha1": "7a080d8989d48cbef3a8f64630822c3107f8af39",
          "md5": "68eabe00b6d9a9eed643c1219e643cd3"
        }
      ]
    }
  ]
}
