{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "7.6.5-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "6ecqkefeljhonffelsxv5ejxx4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.5-b0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.6.5-b0.jar",
          "url": "core-ng-mongo-7.6.5-b0.jar",
          "size": 54022,
          "sha512": "f2b31bf09287ff056c46d45057573010dd7700a8c53730bf54c9b2dd5c2f2f2a5bdc1a606e1c0f1657f61f80720a222a0e49dca8355cef89cdc4dc3f9ba98a37",
          "sha256": "f2d1b37dbda8d687c80986d5a38ea0323523d9de3ea2ae40a5febc23abbf6e34",
          "sha1": "a1b81c0793ad356950cc166505798f1782cf328d",
          "md5": "11d10530345e90f11d77c165711a94e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.5-b0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.6.5-b0.jar",
          "url": "core-ng-mongo-7.6.5-b0.jar",
          "size": 54022,
          "sha512": "f2b31bf09287ff056c46d45057573010dd7700a8c53730bf54c9b2dd5c2f2f2a5bdc1a606e1c0f1657f61f80720a222a0e49dca8355cef89cdc4dc3f9ba98a37",
          "sha256": "f2d1b37dbda8d687c80986d5a38ea0323523d9de3ea2ae40a5febc23abbf6e34",
          "sha1": "a1b81c0793ad356950cc166505798f1782cf328d",
          "md5": "11d10530345e90f11d77c165711a94e5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-7.6.5-b0-sources.jar",
          "url": "core-ng-mongo-7.6.5-b0-sources.jar",
          "size": 25362,
          "sha512": "a487be32e11d378fda0237a1c3d03425897e5e95ab6441a67464ce30888f95bca31dd1ea63176fdcf9153914109bfa51b961f1354a0dc77546f2dd931f3e57df",
          "sha256": "16f8bf4d2d02c4ede0041cdc5bcbced1ca3bdf0b0e27d0168a33a2a06dbf01c4",
          "sha1": "b8b363276b6444fac02dd21b1ffe34c0fa7795bd",
          "md5": "5dc2cfd52df69ed7c8f6a2dbf0324d07"
        }
      ]
    }
  ]
}
