{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "9.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.0.7.jar",
          "url": "core-ng-search-test-9.0.7.jar",
          "size": 13098,
          "sha512": "a822f82c39bb279e1b3c982ea73f82e021844d69b0c34b0984168d64702ec556ad1625470e321b3cd4eea1de1b9a474426f9b4504281def6e80fe24145f3423f",
          "sha256": "cdb051fa2262486e1056da69b54932cc75da803187a2c0ae504aebdde89e4866",
          "sha1": "f7b12a676c892b4d638c372eaacfc6c6029f0523",
          "md5": "8cf908f2d7323a6151e0d1ebc013ff51"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.0.7"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "9.0.7"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "8.12.1"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4",
          "version": {
            "requires": "8.12.1"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "8.12.1"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "8.12.1"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "8.12.1"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "reindex",
          "version": {
            "requires": "8.12.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "reindex",
              "type": "jar",
              "extension": "jar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-9.0.7.jar",
          "url": "core-ng-search-test-9.0.7.jar",
          "size": 13098,
          "sha512": "a822f82c39bb279e1b3c982ea73f82e021844d69b0c34b0984168d64702ec556ad1625470e321b3cd4eea1de1b9a474426f9b4504281def6e80fe24145f3423f",
          "sha256": "cdb051fa2262486e1056da69b54932cc75da803187a2c0ae504aebdde89e4866",
          "sha1": "f7b12a676c892b4d638c372eaacfc6c6029f0523",
          "md5": "8cf908f2d7323a6151e0d1ebc013ff51"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.0.7-sources.jar",
          "url": "core-ng-search-test-9.0.7-sources.jar",
          "size": 7161,
          "sha512": "10b7899095f0de27beb0b49f7567abb1ea73face724d95271484de304121d65dccabf16e9bfc843fe7465d6c98199156c60f5d2fa4a8c53716e96b94b90b67ec",
          "sha256": "15de2498d50bb12348ad1e64081ecb8e96449ffcab74f20159804222b33d2e8c",
          "sha1": "884cbf967f66599489539b753c8418d572b37f60",
          "md5": "c07da420b100d595a2175e10d7f84e8b"
        }
      ]
    }
  ]
}
