{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "7.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6",
      "buildId": "fw2dxe2b5bffjb2dgmfdq5orje"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.5.7"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.5.7.jar",
          "url": "core-ng-mongo-7.5.7.jar",
          "size": 53940,
          "sha512": "1b58faa12074157cade28c5e6afc80aa9e69915a27b383e7532e3e605bf6b1f8e8b6d85ffe0c376701243f3c3b3b6afc2e7e976b08344317b60b88a03f9658b5",
          "sha256": "d1635dad280cd6723a450ab1b86755d45d431d6376f6546e844c1389e7967017",
          "sha1": "78ba6d9e90aadf4c1268265344cf696db4ca0bcb",
          "md5": "d4934566765221b0f1bbd70f0c307655"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.5.7"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.5.7.jar",
          "url": "core-ng-mongo-7.5.7.jar",
          "size": 53940,
          "sha512": "1b58faa12074157cade28c5e6afc80aa9e69915a27b383e7532e3e605bf6b1f8e8b6d85ffe0c376701243f3c3b3b6afc2e7e976b08344317b60b88a03f9658b5",
          "sha256": "d1635dad280cd6723a450ab1b86755d45d431d6376f6546e844c1389e7967017",
          "sha1": "78ba6d9e90aadf4c1268265344cf696db4ca0bcb",
          "md5": "d4934566765221b0f1bbd70f0c307655"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-7.5.7-sources.jar",
          "url": "core-ng-mongo-7.5.7-sources.jar",
          "size": 25320,
          "sha512": "18fa985078d1538278f1ef1b51cc8494b6fb3eb16b19f89c76849f6afd10d0f84880ee66a708c9365785ecf3ac473fc27d5b8f2f701f113b1afc1f576754f282",
          "sha256": "e8f43a3f57e5ffab72d3c8b9b3177fb90e578c2d8910c8179d39d8889acc124b",
          "sha1": "7ab8f3282ec389f9907d4f97e70db002f68c5c09",
          "md5": "37cbd4b048b4cb2bbd2c4c5520d866a2"
        }
      ]
    }
  ]
}
