{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "9.3.1-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-api-9.3.1-b0.jar",
          "url": "core-ng-api-9.3.1-b0.jar",
          "size": 11010,
          "sha512": "fa6beb389f82ce392418b12811b1efaa2d51f66c4ef085af655defb20458da069b90993669261f8c46bbde6fb621e6a926377db8bc79835cd24ca56b18c981eb",
          "sha256": "4cab54431063902170e149336d404bfe965ce6943c3059297266c292e9c5bc8b",
          "sha1": "e5eff69e15b9fc4e9663f47eb2da381e0fba15f1",
          "md5": "efb3ef00c97b9a34c2d67f5a950296db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-api-9.3.1-b0.jar",
          "url": "core-ng-api-9.3.1-b0.jar",
          "size": 11010,
          "sha512": "fa6beb389f82ce392418b12811b1efaa2d51f66c4ef085af655defb20458da069b90993669261f8c46bbde6fb621e6a926377db8bc79835cd24ca56b18c981eb",
          "sha256": "4cab54431063902170e149336d404bfe965ce6943c3059297266c292e9c5bc8b",
          "sha1": "e5eff69e15b9fc4e9663f47eb2da381e0fba15f1",
          "md5": "efb3ef00c97b9a34c2d67f5a950296db"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.3.1-b0-sources.jar",
          "url": "core-ng-api-9.3.1-b0-sources.jar",
          "size": 8662,
          "sha512": "774f8a3ff24a8e613c48c5380ca299c9359491c967ca0b755443d9e07fdb20d99a5a21c048908e6a0bbbf3021bacfd5cb37c636c8b570532bd746531e964520e",
          "sha256": "2cb97bc254abcb2b5e5a353cc8f6ce70007e644b30af3fa024a791dc66cecc16",
          "sha1": "1753e78bac58b4095507e5d525d25d3e3f4427b4",
          "md5": "0db1ad8cc2205b9deb5ed8dae4ada40e"
        }
      ]
    }
  ]
}
