{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.1.2-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.2-b0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.1.2-b0.jar",
          "url": "core-ng-9.1.2-b0.jar",
          "size": 771283,
          "sha512": "7d9a6bba25b7d2fe0b02421ba6e513ad0abf2513e46b8a71d92b00432727809ba25d50a51de2086f3a6faa0c560148745a48a2f3c3fd4fe8b0ddb97789a27b9d",
          "sha256": "0493b0698a862a2e767965deba0f88ca446b21ed7d7e1a8760f0fdc293bf2228",
          "sha1": "b247b406be472d71d15ee094b1c5906598f92966",
          "md5": "76c5d7e93654e976e762da6ba8381098"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "okhttp",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.17.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.2-b0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.1.2-b0.jar",
          "url": "core-ng-9.1.2-b0.jar",
          "size": 771283,
          "sha512": "7d9a6bba25b7d2fe0b02421ba6e513ad0abf2513e46b8a71d92b00432727809ba25d50a51de2086f3a6faa0c560148745a48a2f3c3fd4fe8b0ddb97789a27b9d",
          "sha256": "0493b0698a862a2e767965deba0f88ca446b21ed7d7e1a8760f0fdc293bf2228",
          "sha1": "b247b406be472d71d15ee094b1c5906598f92966",
          "md5": "76c5d7e93654e976e762da6ba8381098"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.1.2-b0-sources.jar",
          "url": "core-ng-9.1.2-b0-sources.jar",
          "size": 394287,
          "sha512": "c44349e120a9fe80dc61ee95e101d884d1242769f887e81181e39ed3f0babef7d4a2d754c0739d46fce117254d8bc44a4fc4f01e6e16de7ffef7b7b1e2af71ce",
          "sha256": "10d5abb87283dede326eb4b5cef579da148fb7ff3603e4a3a5272d59898bfdfe",
          "sha1": "daca9a4963f25246141d6f9f43e9109de5fb805e",
          "md5": "0b9bec2035750583a8abc6df24ea967c"
        }
      ]
    }
  ]
}
