{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "7.7.1-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.7.1-b0.jar",
          "url": "core-ng-test-7.7.1-b0.jar",
          "size": 41888,
          "sha512": "342e3c840eef5385eb0ec58f5a781a9340bad9bf5b05c900c16e60bfe79c984e68f4642f90f524e354337be1596aa198a3a511de3af6229da90495ffbee233a6",
          "sha256": "59d4b9692df626011758cc0978d941a802fd44b07c2373b41e382fc22d0b3167",
          "sha1": "09a7b60ea24948db31cec5f8f4e0603f61438e75",
          "md5": "6d079a0859dee85bffcd45ff63e3c2a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.7.1-b0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.7.2"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.8.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.7.1-b0.jar",
          "url": "core-ng-test-7.7.1-b0.jar",
          "size": 41888,
          "sha512": "342e3c840eef5385eb0ec58f5a781a9340bad9bf5b05c900c16e60bfe79c984e68f4642f90f524e354337be1596aa198a3a511de3af6229da90495ffbee233a6",
          "sha256": "59d4b9692df626011758cc0978d941a802fd44b07c2373b41e382fc22d0b3167",
          "sha1": "09a7b60ea24948db31cec5f8f4e0603f61438e75",
          "md5": "6d079a0859dee85bffcd45ff63e3c2a0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-7.7.1-b0-sources.jar",
          "url": "core-ng-test-7.7.1-b0-sources.jar",
          "size": 20152,
          "sha512": "a0e54434ca2a90220ab56903cbec748cd33f941af02ca2a27000057e10a42eb973c08e698f2202a6ffbcfdde6bef36773ab54076ba7c57c6949d32f15d8ab7d3",
          "sha256": "73a7b7e1e4190bd7d58af805c6b102a61d2321413adf57608b4415df5fbae142",
          "sha1": "a07be49613d67a062400d4c7ec875023b12c0c98",
          "md5": "9e8c33e0ce33191a81fe50c134eccee5"
        }
      ]
    }
  ]
}
