{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "7.6.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "cj4ceplftrgnjo6zmp4mmewmni"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.6.13.jar",
          "url": "core-ng-test-7.6.13.jar",
          "size": 41608,
          "sha512": "d05a739dc5ce4608cdd24ddb0ca9e8690f13edbd30231c7a37751278b9059865edacbee567e3d9883ec44f5b8bd00decadbfd72ca982728e3e83bfae5703f6cc",
          "sha256": "036a899de1042cfe4935c24fcef8e9d83fbba301301a0db9c4e93e4c86ddcec1",
          "sha1": "bdb896ee008a4f170a620b77251d187b8ed73e37",
          "md5": "a8751cc9340ac6028b8459d1c560fe02"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.13"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.7.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.6.13.jar",
          "url": "core-ng-test-7.6.13.jar",
          "size": 41608,
          "sha512": "d05a739dc5ce4608cdd24ddb0ca9e8690f13edbd30231c7a37751278b9059865edacbee567e3d9883ec44f5b8bd00decadbfd72ca982728e3e83bfae5703f6cc",
          "sha256": "036a899de1042cfe4935c24fcef8e9d83fbba301301a0db9c4e93e4c86ddcec1",
          "sha1": "bdb896ee008a4f170a620b77251d187b8ed73e37",
          "md5": "a8751cc9340ac6028b8459d1c560fe02"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-7.6.13-sources.jar",
          "url": "core-ng-test-7.6.13-sources.jar",
          "size": 20042,
          "sha512": "ede65a39c5cfb5582a9dc51496c02153e911b0a589046039e01150d73ea394f02a15bede2c67b0de0bd04f17e4978d7db0acce6ccf946883e7ff061c98fe30d2",
          "sha256": "361b955bd8a0f959cefe4467f5ac2d72fe866b0a1054d147914dae363b08f9ba",
          "sha1": "c14f2fb40433fc8a0b78a453c6a3469015f6c2cc",
          "md5": "5b7277370724907ac885559c7e021e54"
        }
      ]
    }
  ]
}
