{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "7.6.8-b2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "proo64g6nrfkppc7ucepn5zmyu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.6.8-b2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.6.8-b2.jar",
          "url": "core-ng-7.6.8-b2.jar",
          "size": 678899,
          "sha512": "aa78aa20c16e46cdb05dbee4c0a1e59f2105c10eca362748fc1cd0f65e8616cd181fcb18e612ced4318b5129b8120dd578ef3c05de2e7f9c4e36e9eacab6487e",
          "sha256": "695f3d762cf3da958c7fed1730ae9c2f85539c57dc31ca22ffd066e9d4ee754e",
          "sha1": "1aa45c9fc184d391e1ecb88f36af88df122dd808",
          "md5": "9f41e1d0fd956c2e778ecf62790863a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.27.0-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.2.3.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.7.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.8.2"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.6.8-b2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.6.8-b2.jar",
          "url": "core-ng-7.6.8-b2.jar",
          "size": 678899,
          "sha512": "aa78aa20c16e46cdb05dbee4c0a1e59f2105c10eca362748fc1cd0f65e8616cd181fcb18e612ced4318b5129b8120dd578ef3c05de2e7f9c4e36e9eacab6487e",
          "sha256": "695f3d762cf3da958c7fed1730ae9c2f85539c57dc31ca22ffd066e9d4ee754e",
          "sha1": "1aa45c9fc184d391e1ecb88f36af88df122dd808",
          "md5": "9f41e1d0fd956c2e778ecf62790863a2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-7.6.8-b2-sources.jar",
          "url": "core-ng-7.6.8-b2-sources.jar",
          "size": 347262,
          "sha512": "22128fd59f2195cf374bfa2f7ea8efe45df7f62c5e21eca1bc7bb839a57b83b2e862335f73e4d9844054ed2616cbdd59ee5461c5fc4562d2a21df070e85788ce",
          "sha256": "9847abd9dda829d9311e66cb9e10f881d4c486b542fab5817970bcc9675fe756",
          "sha1": "6b8829ea27ca13c5e72e76523cbddbe767ea64a7",
          "md5": "29ef4735cd28a55dea8c69446570d471"
        }
      ]
    }
  ]
}
