{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "7.6.16-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.6.16-b0.jar",
          "url": "core-ng-test-7.6.16-b0.jar",
          "size": 41607,
          "sha512": "5dde8682a03280989c791e1761fab403ad2d2489a9351b123f28945375929cb9e83567ca81fce8c1b40c8ac914ce0bcc64ab4c63a71adfaad796ea9b7ee94d2b",
          "sha256": "c06db7f2d02c76c5678d5238bdbc059d563835846db74430f0b8ed390a97474e",
          "sha1": "38b1b765d2b0cf24249d7a0e332a2de881f2e3f0",
          "md5": "5a333ff7ed3b0fc72f25a52cd91b7b15"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.16-b0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.8.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.6.16-b0.jar",
          "url": "core-ng-test-7.6.16-b0.jar",
          "size": 41607,
          "sha512": "5dde8682a03280989c791e1761fab403ad2d2489a9351b123f28945375929cb9e83567ca81fce8c1b40c8ac914ce0bcc64ab4c63a71adfaad796ea9b7ee94d2b",
          "sha256": "c06db7f2d02c76c5678d5238bdbc059d563835846db74430f0b8ed390a97474e",
          "sha1": "38b1b765d2b0cf24249d7a0e332a2de881f2e3f0",
          "md5": "5a333ff7ed3b0fc72f25a52cd91b7b15"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-7.6.16-b0-sources.jar",
          "url": "core-ng-test-7.6.16-b0-sources.jar",
          "size": 20041,
          "sha512": "78c3bc67ae9cde3cdaec0593134861493aacdca727eee8ee59ec146e0f2d777dfd00469a0b7ef83e2dd422fe424d6911125dad8288f7d0676680c6f22dbbb50f",
          "sha256": "5961a9e5acf2e6ae34fdc4f53af50ff39ec1b6c0ed971c786a53383b292c1cb4",
          "sha1": "f96035845b90e94265f980227a5f7801b2b2c380",
          "md5": "398a6945ab763aa8b050b239957ff477"
        }
      ]
    }
  ]
}
