{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "7.7.4-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.7.4-b0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.7.4-b0.jar",
          "url": "core-ng-mongo-7.7.4-b0.jar",
          "size": 53971,
          "sha512": "18176cb0b9240131b371c08254037255a6d9666eccbde244aac75e35a178688819c6a6684ff9e89be4cc607f1fbf7458e67b7320bd0f412c4c2cb6f37573b160",
          "sha256": "ad8385a8a085ab75d32f218c100caf7e546ed567d19829f10bbdb3c436bd1b27",
          "sha1": "f617cd5b658feec8195d7dd86cf75f811d9f87bf",
          "md5": "e8a3ce40014d4ab4a07fe5d949096ac1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.7.4-b0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.7.4-b0.jar",
          "url": "core-ng-mongo-7.7.4-b0.jar",
          "size": 53971,
          "sha512": "18176cb0b9240131b371c08254037255a6d9666eccbde244aac75e35a178688819c6a6684ff9e89be4cc607f1fbf7458e67b7320bd0f412c4c2cb6f37573b160",
          "sha256": "ad8385a8a085ab75d32f218c100caf7e546ed567d19829f10bbdb3c436bd1b27",
          "sha1": "f617cd5b658feec8195d7dd86cf75f811d9f87bf",
          "md5": "e8a3ce40014d4ab4a07fe5d949096ac1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-7.7.4-b0-sources.jar",
          "url": "core-ng-mongo-7.7.4-b0-sources.jar",
          "size": 25324,
          "sha512": "74c96fd4fa1280f586c6691c05e0167091b6019b35c350ebc680a9f237a1e6548d88996abc26feb8fe20b133250ee857d22bda9eb7a0a43a2dd5f73ab2c9039c",
          "sha256": "5271202b3df5c3b430332aef4011a48c63dccbdab13c6a6af98de42251cded3b",
          "sha1": "ac67cc09270b9052d04bd90fad95d0fb409d69e6",
          "md5": "59f847e55cef650593af7472c00d5a77"
        }
      ]
    }
  ]
}
