{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "9.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.8.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.0.4.jar",
          "url": "core-ng-test-9.0.4.jar",
          "size": 45691,
          "sha512": "0a0bed74feb2e5767d17a9746cb8db1abd907000eb05d7315fe466511e16b8af163bf616dd4f363c033dc17eaab4f64947941217bd687396b25ae2e2b2101ef7",
          "sha256": "772fe770253cf4ffc8ec0c45e97b6714f6f314d80091b1c92153a1ac8240ff5b",
          "sha1": "0a0d95ebe0a95153f168f6955a109a2f257d4ac8",
          "md5": "85ef082f86e20c6a2f48a3e87a4a1ace"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.4"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.10.1"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.8.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.0.4.jar",
          "url": "core-ng-test-9.0.4.jar",
          "size": 45691,
          "sha512": "0a0bed74feb2e5767d17a9746cb8db1abd907000eb05d7315fe466511e16b8af163bf616dd4f363c033dc17eaab4f64947941217bd687396b25ae2e2b2101ef7",
          "sha256": "772fe770253cf4ffc8ec0c45e97b6714f6f314d80091b1c92153a1ac8240ff5b",
          "sha1": "0a0d95ebe0a95153f168f6955a109a2f257d4ac8",
          "md5": "85ef082f86e20c6a2f48a3e87a4a1ace"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-9.0.4-sources.jar",
          "url": "core-ng-test-9.0.4-sources.jar",
          "size": 22167,
          "sha512": "32dfd819a95b22dc54141d067bb10fce091ece73a0fa30ca569e45f2d2a918e20e321894ecdf3b331a12072669528b53a3ed3cae01ef5c945e0554c7a62fa6dd",
          "sha256": "b061d6c03f761121ece208413b9a971ae3e2eff29621ce1a7159c81157710cee",
          "sha1": "039821857bdcfc50ff51ef2fe12a62a0447738d8",
          "md5": "8ae4b3c2ecb6e082f0833f23cda11ad8"
        }
      ]
    }
  ]
}
