{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "9.5.1-b5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.23.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.7"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.5.1-b5.jar",
          "url": "core-ng-test-9.5.1-b5.jar",
          "size": 51140,
          "sha512": "d9f3d06d8ae655de3df5f0255646baede502f54a9bf464f1694fd470e0b5db0a20675499802aaa0d202b53c536119220f3bd46d0bef179c05cb458288877ab3e",
          "sha256": "4ddb588dc1ace88c865520350fd68ab6d531dccc339fe7c2f098d3d5be8a4971",
          "sha1": "5d2749d0ce9f33c04c4e66aba37b1f2a992a1915",
          "md5": "30870069ae2805f8d9a80fc0c2c23a82"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.5.1-b5"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.23.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.7"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.5.1-b5.jar",
          "url": "core-ng-test-9.5.1-b5.jar",
          "size": 51140,
          "sha512": "d9f3d06d8ae655de3df5f0255646baede502f54a9bf464f1694fd470e0b5db0a20675499802aaa0d202b53c536119220f3bd46d0bef179c05cb458288877ab3e",
          "sha256": "4ddb588dc1ace88c865520350fd68ab6d531dccc339fe7c2f098d3d5be8a4971",
          "sha1": "5d2749d0ce9f33c04c4e66aba37b1f2a992a1915",
          "md5": "30870069ae2805f8d9a80fc0c2c23a82"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-9.5.1-b5-sources.jar",
          "url": "core-ng-test-9.5.1-b5-sources.jar",
          "size": 25107,
          "sha512": "1613098193e448394b3dc7bceb148d199f3aa80d87496bae65098ed219e6fee5b69424f40bfb3850e6ec3bd6bf7f79fd5f301ae95f49787fc73507430d387e4f",
          "sha256": "8cff0d298323e24eac81e42ce661a5be12a682cf6280917f8893a02d33650308",
          "sha1": "8c612de358f4c9ce431d28de47dc8050258a7025",
          "md5": "3b70fdc6b37a10686b0b7321bee58d5b"
        }
      ]
    }
  ]
}
