{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "7.6.8-b2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "proo64g6nrfkppc7ucepn5zmyu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.8-b2"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.6.8-b2.jar",
          "url": "core-ng-mongo-7.6.8-b2.jar",
          "size": 54024,
          "sha512": "54856e05e2587c79a7a09ae87ff48ed311b6cb80fd378a232fb3f15bf48108d2b40504833a2e6238427dc3c3d4471f4a86f4d2db25ac9f45b3ce4c9fe18989cb",
          "sha256": "9f22fd87e4fad4f65a7f1d198208f591d393eca5e1c703c185587bb8232a277c",
          "sha1": "e0ca0add989a22d2d073e0c3119068e9c62d88c5",
          "md5": "65b1556dd02a4057983e02bad10d6934"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.8-b2"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.6.8-b2.jar",
          "url": "core-ng-mongo-7.6.8-b2.jar",
          "size": 54024,
          "sha512": "54856e05e2587c79a7a09ae87ff48ed311b6cb80fd378a232fb3f15bf48108d2b40504833a2e6238427dc3c3d4471f4a86f4d2db25ac9f45b3ce4c9fe18989cb",
          "sha256": "9f22fd87e4fad4f65a7f1d198208f591d393eca5e1c703c185587bb8232a277c",
          "sha1": "e0ca0add989a22d2d073e0c3119068e9c62d88c5",
          "md5": "65b1556dd02a4057983e02bad10d6934"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-7.6.8-b2-sources.jar",
          "url": "core-ng-mongo-7.6.8-b2-sources.jar",
          "size": 25364,
          "sha512": "49f8aba14df93c1b415cfc9ebee7b0d6650ca4303cd38d345f7770353dabfff39092b3ad4a40e10019cddc09c4dfd0e4185658d3508c18a8c75d656483a04a3e",
          "sha256": "a6c26d1a76ccffb07224907d5ade6118b7f1b9c238c31cc19c6c5e04c5129c70",
          "sha1": "79777268ee88af7deb30cb7c09a823c092aeb7de",
          "md5": "31a5130cfedce8f26f030795d632319f"
        }
      ]
    }
  ]
}
