{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "9.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-9.0.7.jar",
          "url": "core-ng-api-9.0.7.jar",
          "size": 10989,
          "sha512": "988a79929ed1d08e5395a4716f3bedea18f7649c5078592456d14cff5ac804e93e8fb2d86bb8675641b1f40cd67cf7a0947f50072692bf2bd33da09c45a856a7",
          "sha256": "8cefae92849384115dcef0c05fae7c53e01809489c768192000b05936c3214ab",
          "sha1": "096ad847945904a3cfa83747f2b3a3a391bba543",
          "md5": "400284d57667de4b232a01ff5b87a63d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.0.7.jar",
          "url": "core-ng-api-9.0.7.jar",
          "size": 10989,
          "sha512": "988a79929ed1d08e5395a4716f3bedea18f7649c5078592456d14cff5ac804e93e8fb2d86bb8675641b1f40cd67cf7a0947f50072692bf2bd33da09c45a856a7",
          "sha256": "8cefae92849384115dcef0c05fae7c53e01809489c768192000b05936c3214ab",
          "sha1": "096ad847945904a3cfa83747f2b3a3a391bba543",
          "md5": "400284d57667de4b232a01ff5b87a63d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.0.7-sources.jar",
          "url": "core-ng-api-9.0.7-sources.jar",
          "size": 8643,
          "sha512": "080ba4f4e0d284fee4848e0bfe92897acab4f846725dc1606aed9886488232052c118b185b871b7ad868d44ba17b4bf0ffef31744b57442bd9b10ef2b032a61c",
          "sha256": "a209baf328f0bb2c78f5fada89c9d1965d2a8f2e5940ea1c5f71d95d0ca50dcd",
          "sha1": "519460e5ea29bd0a3464e56219552547af0d6a0d",
          "md5": "9ed882d2e7cae9096ab074617d8bcae5"
        }
      ]
    }
  ]
}
