{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.5.1-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.5.1-b0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.5.1-b0.jar",
          "url": "core-ng-9.5.1-b0.jar",
          "size": 789768,
          "sha512": "593e8fe60df6f01475fb7d52eb6ca010629157d73556556a21939d8290f0a485069fdd40e408c1573c86c225da4f73c88a4f1736af65ccc207e9d74f1208ec32",
          "sha256": "bd288e13ec2d273a0bb8ceff945ceb950b89b6daf77a477fb53770bb223e248b",
          "sha1": "71c4878aa980af90160e6b4604f71bcba03ed5d8",
          "md5": "3494a0b58f64f2b691e37dc1eed7053b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "tools.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "tools.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.24.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "4.2.0"
          },
          "excludes": [
            {
              "group": "org.xerial.snappy",
              "module": "*"
            },
            {
              "group": "at.yawk.lz4",
              "module": "*"
            }
          ]
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.5.1-b0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.5.1-b0.jar",
          "url": "core-ng-9.5.1-b0.jar",
          "size": 789768,
          "sha512": "593e8fe60df6f01475fb7d52eb6ca010629157d73556556a21939d8290f0a485069fdd40e408c1573c86c225da4f73c88a4f1736af65ccc207e9d74f1208ec32",
          "sha256": "bd288e13ec2d273a0bb8ceff945ceb950b89b6daf77a477fb53770bb223e248b",
          "sha1": "71c4878aa980af90160e6b4604f71bcba03ed5d8",
          "md5": "3494a0b58f64f2b691e37dc1eed7053b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.5.1-b0-sources.jar",
          "url": "core-ng-9.5.1-b0-sources.jar",
          "size": 405944,
          "sha512": "1590e974a681457ae93ad11113317460b0d0bbac73be4e7df62207b68b911cb2cf8c78447847df4de482a78b950e182230818ee0b306b9eb1bd6c636d3244ced",
          "sha256": "e9f51001fffe01931cb7ce54b273cce104a9062387495c4eea9c37942d62f644",
          "sha1": "4611cd8bf6d8374a2671369e5b70f21a8b654f2e",
          "md5": "d09054c2781383a67ff2dcf56a9f868f"
        }
      ]
    }
  ]
}
