{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "9.1.1-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.1.1-b0.jar",
          "url": "core-ng-mongo-test-9.1.1-b0.jar",
          "size": 2488,
          "sha512": "b3d5a2b67f3d03a8e75e87732255fe9366c98208cec2d0223de706e966323d4a840b9a43354bba586ab9ccbcc2680333d18cca2c96e5ed7407b54288d145e0b1",
          "sha256": "a570acdbce9e52428e88ec469d1044cfa5f2d661c5fd0a083f8ce252937b153e",
          "sha1": "961b3747314b23a953e335978754f9e1af69ba74",
          "md5": "cbe01afd38b04120ee8edb561c118cd7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.1.1-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "9.1.1-b0"
          }
        },
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.45.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-9.1.1-b0.jar",
          "url": "core-ng-mongo-test-9.1.1-b0.jar",
          "size": 2488,
          "sha512": "b3d5a2b67f3d03a8e75e87732255fe9366c98208cec2d0223de706e966323d4a840b9a43354bba586ab9ccbcc2680333d18cca2c96e5ed7407b54288d145e0b1",
          "sha256": "a570acdbce9e52428e88ec469d1044cfa5f2d661c5fd0a083f8ce252937b153e",
          "sha1": "961b3747314b23a953e335978754f9e1af69ba74",
          "md5": "cbe01afd38b04120ee8edb561c118cd7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.1.1-b0-sources.jar",
          "url": "core-ng-mongo-test-9.1.1-b0-sources.jar",
          "size": 1780,
          "sha512": "9e3b463bc11f25f70e2653ba41838ccb3caa8fac5cdd7f9081ffc899834c49870728de46c5630a40b81b6d8fdddebf2dc6f7a1658478b991554397d38b68a489",
          "sha256": "87a0a2b68e247c25e58db2c4ce33153ef7feecfff44497896fd2edd4de613548",
          "sha1": "78a1cf3d002adada4141150dcb93970f36ab26a3",
          "md5": "03e5f3855f183512bc2531b13ea083d1"
        }
      ]
    }
  ]
}
