{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "7.5.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6",
      "buildId": "vkv6kago7nahrgoxkqu67wxbnu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.5.8"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.5.8"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.5.8.jar",
          "url": "core-ng-search-test-7.5.8.jar",
          "size": 9045,
          "sha512": "21191212aff5bc3085b0dccfb76321375e2d351032f89593ea8c654802055d70df5289c95cd9990315c9d90739de0be0e6265eef1efaec96fb9e84b25d8fa01b",
          "sha256": "67e383d1cdaafbe60a85bc522aed9bd940321af44d631f0a76dea00b37080a78",
          "sha1": "01877552f75cc47f8ac01f1dc4b1c0bbe7b854b8",
          "md5": "68aed8ca1afcef364447dbd640bc62b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4-client",
          "version": {
            "requires": "7.9.1"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "reindex-client",
          "version": {
            "requires": "7.9.1"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "7.9.1"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "7.9.1"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "7.9.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.5.8"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.5.8"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.5.8.jar",
          "url": "core-ng-search-test-7.5.8.jar",
          "size": 9045,
          "sha512": "21191212aff5bc3085b0dccfb76321375e2d351032f89593ea8c654802055d70df5289c95cd9990315c9d90739de0be0e6265eef1efaec96fb9e84b25d8fa01b",
          "sha256": "67e383d1cdaafbe60a85bc522aed9bd940321af44d631f0a76dea00b37080a78",
          "sha1": "01877552f75cc47f8ac01f1dc4b1c0bbe7b854b8",
          "md5": "68aed8ca1afcef364447dbd640bc62b5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.5.8-sources.jar",
          "url": "core-ng-search-test-7.5.8-sources.jar",
          "size": 5425,
          "sha512": "d792f01e1e33f5cca567f5e46b0cbd93efaa89d8a2d89fbeb471be1ba43e21a789f471e053abd7ddf70313af4fd654ac3e5cfcee5c018d4d9ee70b5ecfc5b439",
          "sha256": "a40b7d428aa3d894809725a3425872e7358fd8c016267f80f53bdfc63911aa31",
          "sha1": "63e3ecb44b31d4128cbf54173773dbf9f0a06e8d",
          "md5": "7cf5553b2aaf42035b1a73669a934115"
        }
      ]
    }
  ]
}
