{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "7.7.1-b2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.7.1-b2"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.7.1-b2.jar",
          "url": "core-ng-mongo-7.7.1-b2.jar",
          "size": 53971,
          "sha512": "61320588f5cdb864661847dd97a2e1a0a66e54d740b96e9a578bcd6eff997001b0cec1ec44dcf1980687e0e631ad7d9aeecb5f3090b12f23e7d519a0067d7973",
          "sha256": "9826b69b89e1cc695f7649e23d37a7b8d01e374228d62125fe25e2afef2a65e2",
          "sha1": "20022464c648edf2262e310c4c0f6d656d9a28dc",
          "md5": "20664ad8e6f6ef1449c16bcade4acf80"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.7.1-b2"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.7.1-b2.jar",
          "url": "core-ng-mongo-7.7.1-b2.jar",
          "size": 53971,
          "sha512": "61320588f5cdb864661847dd97a2e1a0a66e54d740b96e9a578bcd6eff997001b0cec1ec44dcf1980687e0e631ad7d9aeecb5f3090b12f23e7d519a0067d7973",
          "sha256": "9826b69b89e1cc695f7649e23d37a7b8d01e374228d62125fe25e2afef2a65e2",
          "sha1": "20022464c648edf2262e310c4c0f6d656d9a28dc",
          "md5": "20664ad8e6f6ef1449c16bcade4acf80"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-7.7.1-b2-sources.jar",
          "url": "core-ng-mongo-7.7.1-b2-sources.jar",
          "size": 25324,
          "sha512": "1d9674cd862b2b729b59fe75bdb11752f3bbb967a4b3230bf66e4a3e179d6fb11db823659e16dd27756c56d311a0f4f2dac8d368a84039d9764b9d9902969c80",
          "sha256": "5273e1147e13bbe7c38bc317f05c6d1515d9d5b8c1042689c1bf9f62e7c807b3",
          "sha1": "603b66c5b8e0f637e0cfbb862cb86b91d3772dc3",
          "md5": "6b5aa98ee6eff0955485ba54839310d6"
        }
      ]
    }
  ]
}
