{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "9.5.1-b2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.23.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.7"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.5.1-b2.jar",
          "url": "core-ng-test-9.5.1-b2.jar",
          "size": 51141,
          "sha512": "62dec2a2566689a6b96787c64cae3afae5035b817ca5403d051a7c1f7ae1ae4ddecd54fa6a9bfa48c183595240800a0ec8ff77d8fc9666fe47afdb20b6857226",
          "sha256": "9513daece3e83a1be90220da49896d6cacab4f76e71c02ba33b70e658ebf99b2",
          "sha1": "b21be30bbc3b70d832b87b6adc039ca332f46794",
          "md5": "a70c6b499c34240ea7123e0c20c0c167"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.5.1-b2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.23.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.7"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.5.1-b2.jar",
          "url": "core-ng-test-9.5.1-b2.jar",
          "size": 51141,
          "sha512": "62dec2a2566689a6b96787c64cae3afae5035b817ca5403d051a7c1f7ae1ae4ddecd54fa6a9bfa48c183595240800a0ec8ff77d8fc9666fe47afdb20b6857226",
          "sha256": "9513daece3e83a1be90220da49896d6cacab4f76e71c02ba33b70e658ebf99b2",
          "sha1": "b21be30bbc3b70d832b87b6adc039ca332f46794",
          "md5": "a70c6b499c34240ea7123e0c20c0c167"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-9.5.1-b2-sources.jar",
          "url": "core-ng-test-9.5.1-b2-sources.jar",
          "size": 25108,
          "sha512": "3f9a823303249b34a0b42e1c1446a33a1f4f059eede016e143e83a3b4450851f39a9c999ac75e1ec6e88fbc7bdf0a1aa0c30e5b9267f0ddca89c274671b4c2c2",
          "sha256": "0a184b28dd322942b0d86155c310bf796c03bc23998f86df2aa783c8f030ad40",
          "sha1": "428db6b12a9c8ce9e0d40a8988501b5d7bbbeffb",
          "md5": "30c39cc7fa92395714d88e9ac29cd5b4"
        }
      ]
    }
  ]
}
