{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "7.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6",
      "buildId": "jdhsmwlbjvg6foywe56zxxdxk4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.5.6"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.5.6.jar",
          "url": "core-ng-mongo-7.5.6.jar",
          "size": 53939,
          "sha512": "d7c60a2b4ca3890defe363eb91468ffeeb5b60b6f4463e43b9fc7c5e7b5a31474be176e369e551081a1647e003f44aa74048d432783772db18fd581a8db15de9",
          "sha256": "1382b6fe49dd868d524c59e487ab76cd6507555fd93449ff6fb345edf3f753bb",
          "sha1": "1e0fe4ba4e14c6377183e2e2f1f32a577102f963",
          "md5": "855f27025d4aaec41f0170b94bffddde"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.5.6"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-7.5.6.jar",
          "url": "core-ng-mongo-7.5.6.jar",
          "size": 53939,
          "sha512": "d7c60a2b4ca3890defe363eb91468ffeeb5b60b6f4463e43b9fc7c5e7b5a31474be176e369e551081a1647e003f44aa74048d432783772db18fd581a8db15de9",
          "sha256": "1382b6fe49dd868d524c59e487ab76cd6507555fd93449ff6fb345edf3f753bb",
          "sha1": "1e0fe4ba4e14c6377183e2e2f1f32a577102f963",
          "md5": "855f27025d4aaec41f0170b94bffddde"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-7.5.6-sources.jar",
          "url": "core-ng-mongo-7.5.6-sources.jar",
          "size": 25319,
          "sha512": "5072a81b4236e2f0abd74694a8c6e265ef16a9958d2ce7105370dd75ead4f4053bc7fe9ec96988e817164fb0e886c8bf74e547a1088137e2d1d32dd75f161310",
          "sha256": "2729e779e13e09245163fb97062bee3483dbc1edfb406c6b8e9a8f7c68c2b972",
          "sha1": "d86267e4adba2a0f2ec42dc01decc73a7ca248c6",
          "md5": "b2a049c25cdf59a70de70b5dc2d58801"
        }
      ]
    }
  ]
}
