{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "7.6.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "5ouw753gz5cgbnubxggdyz4bvu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.6.12.jar",
          "url": "core-ng-test-7.6.12.jar",
          "size": 41607,
          "sha512": "3e69bf25cdd5677013ee2496c2895f2e5c7f80fc6be65292aa744465a63b3e65b071f7adfcd03acdf4852a343d6461b97c294a8b8ea5e5f9ddc0af80840c8519",
          "sha256": "63928c9de6a80e9e13f5591f4d8bc67e3aa3eaf607b8dbe02f5c26be997434c6",
          "sha1": "e867f837a0d837cb2d7ae1a302fa385b91791a46",
          "md5": "f42522aba1d4dfafb7d0b24d3fa3b1ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.12"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.7.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.6.12.jar",
          "url": "core-ng-test-7.6.12.jar",
          "size": 41607,
          "sha512": "3e69bf25cdd5677013ee2496c2895f2e5c7f80fc6be65292aa744465a63b3e65b071f7adfcd03acdf4852a343d6461b97c294a8b8ea5e5f9ddc0af80840c8519",
          "sha256": "63928c9de6a80e9e13f5591f4d8bc67e3aa3eaf607b8dbe02f5c26be997434c6",
          "sha1": "e867f837a0d837cb2d7ae1a302fa385b91791a46",
          "md5": "f42522aba1d4dfafb7d0b24d3fa3b1ca"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-7.6.12-sources.jar",
          "url": "core-ng-test-7.6.12-sources.jar",
          "size": 20041,
          "sha512": "d0e7bfe76b0588bc0b7950c3508c2858bc0cc848997bc319cb560366270266fc9558b58b157deebf2a5685019e5c61f4f77a948d9a84c419f2df7b9f0ae54537",
          "sha256": "942b9996e25b08f3d7ed2c20393d3a281c04b93f45b5844729ab6e9079729782",
          "sha1": "189742a6dc1612bef705f333c86516090152555b",
          "md5": "eda556dd6977454b123d842600121de6"
        }
      ]
    }
  ]
}
