{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "7.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "khklefg2nva3beahmqh2vw57ea"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.3.7"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.3.7.jar",
          "url": "core-ng-search-test-7.3.7.jar",
          "size": 8919,
          "sha512": "b44f7e2e430ef87c42e29b96d2a30abe9de086b253ce31f36612d0ccfa02ff3e446b888bd08b3492b53edf9fe54ca6700896d8ad014f812e9d7ede5248c26b05",
          "sha256": "d86b7d5eaac375585e5d5d00152de8d90216449017485390a6a9ae66d24ef6c5",
          "sha1": "de93edcb1f7df386b49e02b1d654f99c4b419db7",
          "md5": "ca817fc73878c8aeed9d265dc8810040"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4-client",
          "version": {
            "requires": "7.6.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "reindex-client",
          "version": {
            "requires": "7.6.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "7.6.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "7.6.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "7.6.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.3.7"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.3.7.jar",
          "url": "core-ng-search-test-7.3.7.jar",
          "size": 8919,
          "sha512": "b44f7e2e430ef87c42e29b96d2a30abe9de086b253ce31f36612d0ccfa02ff3e446b888bd08b3492b53edf9fe54ca6700896d8ad014f812e9d7ede5248c26b05",
          "sha256": "d86b7d5eaac375585e5d5d00152de8d90216449017485390a6a9ae66d24ef6c5",
          "sha1": "de93edcb1f7df386b49e02b1d654f99c4b419db7",
          "md5": "ca817fc73878c8aeed9d265dc8810040"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.3.7-sources.jar",
          "url": "core-ng-search-test-7.3.7-sources.jar",
          "size": 5094,
          "sha512": "cf570f6efffd07b36eff0ea092bfbb14b20b2345451cff6e69e145d217fa56b89c6160c56e8e4a6ddd7676f618b9bbf8ef8f1cc92b46fab03ce7b889c54ef8cb",
          "sha256": "8c72e995a3e06aaa80a1a201f89ef5863970d42977418c1b3bbff6594a653e03",
          "sha1": "51cbf3ad0556d04778fe1feb4bda6278a081043f",
          "md5": "bb4038c36d1de0fd5be5ad4bc609eb71"
        }
      ]
    }
  ]
}
