{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.1.1-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.1-b0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.1.1-b0.jar",
          "url": "core-ng-9.1.1-b0.jar",
          "size": 766266,
          "sha512": "6f1baed71c7ee68a23600ba3818a272aa440d5cecdfbe47653345ca1a27120154b9e8353d83ee3a197dcc7c215ab18b4defc8861ebbb2fe6ad76fbb1408701da",
          "sha256": "addf1853f84fe0b26d08544beb7a1045859a209277cedcf5d68b2d17784de287",
          "sha1": "cfd5f8c2ce8fdca4d9976d7330cbe597951a9905",
          "md5": "e6a7de0a3f2ac6189ea28e29bc711554"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "okhttp",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.10.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "3.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.10.5"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.1-b0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.1.1-b0.jar",
          "url": "core-ng-9.1.1-b0.jar",
          "size": 766266,
          "sha512": "6f1baed71c7ee68a23600ba3818a272aa440d5cecdfbe47653345ca1a27120154b9e8353d83ee3a197dcc7c215ab18b4defc8861ebbb2fe6ad76fbb1408701da",
          "sha256": "addf1853f84fe0b26d08544beb7a1045859a209277cedcf5d68b2d17784de287",
          "sha1": "cfd5f8c2ce8fdca4d9976d7330cbe597951a9905",
          "md5": "e6a7de0a3f2ac6189ea28e29bc711554"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.1.1-b0-sources.jar",
          "url": "core-ng-9.1.1-b0-sources.jar",
          "size": 392149,
          "sha512": "76cdafd555d600966187161ca5532b886ee7e4ddb77a9ddbe6e0984f1129059c321e8b1127f042fc43946dd267a49b58777e59417693be249c43252c5c06dc05",
          "sha256": "ca0273bff135bb196b68b161d72c3de2f4a428edaaa2c8d4a8e348222e8b6539",
          "sha1": "5c04754b329d700585b6b2ea830770843cc00935",
          "md5": "87692604fb0700edd3a3ef57c94c7950"
        }
      ]
    }
  ]
}
