{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "9.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.0.0.jar",
          "url": "core-ng-search-test-9.0.0.jar",
          "size": 12663,
          "sha512": "033a25a69bec0fc081c54e716ac9957129260283d8e39b1437691f9378964c1a16bcbc3bd64b3dc188e84854cf09c7f906e957c7b0462c5e395af382ee8e1cb2",
          "sha256": "3c9c0a717da995c4f523c6d6b4dc867e8ef43350e465c7c9d02a693d441dff8d",
          "sha1": "fd74f73d27c179840394234f7a6ce1c70c0f8446",
          "md5": "a4d6835516acee5dff0be7fa8412765b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.0.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "9.0.0"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "transport-netty4",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "reindex",
          "version": {
            "requires": "8.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-9.0.0.jar",
          "url": "core-ng-search-test-9.0.0.jar",
          "size": 12663,
          "sha512": "033a25a69bec0fc081c54e716ac9957129260283d8e39b1437691f9378964c1a16bcbc3bd64b3dc188e84854cf09c7f906e957c7b0462c5e395af382ee8e1cb2",
          "sha256": "3c9c0a717da995c4f523c6d6b4dc867e8ef43350e465c7c9d02a693d441dff8d",
          "sha1": "fd74f73d27c179840394234f7a6ce1c70c0f8446",
          "md5": "a4d6835516acee5dff0be7fa8412765b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.0.0-sources.jar",
          "url": "core-ng-search-test-9.0.0-sources.jar",
          "size": 7174,
          "sha512": "a1dc39c6cd2a87eec5e9eaf3b7cccd3d71e10c11c9fe62c669df271ff720620e58c166f311a628fc5e387415b830d8e1e77765961ad1d8bcdd6892a02d8e76ed",
          "sha256": "659e627c3b1805ec273afcbefbed4998a8d20f7a0e1f852a473864b9c4ed9443",
          "sha1": "6e464a9669ef6d3ad6705bd2ddb8dcff268d1cb8",
          "md5": "3d3a9f690617d41a2a8f016b0d180add"
        }
      ]
    }
  ]
}
