{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "9.6.1-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.6.1-b1"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.6.1-b1.jar",
          "url": "core-ng-mongo-9.6.1-b1.jar",
          "size": 60078,
          "sha512": "d6b2e8b7a7e9be235c076ad1402e8ae026380824ddb25cde80a105ff9508cc2fdad19cd81a6af5ec00a894efcf94b6a161e3a22d63589c4cc0529fc4edf7710b",
          "sha256": "50f1ebcc8b3403406e351071991c41ed3c019391cdb513dab7c10ed954053c25",
          "sha1": "f1c1a1ad44e81eeb726da4fc3b4b713bd35db240",
          "md5": "5634a557ce644f5d59f1744e7faf8498"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.6.1-b1"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.6.1-b1.jar",
          "url": "core-ng-mongo-9.6.1-b1.jar",
          "size": 60078,
          "sha512": "d6b2e8b7a7e9be235c076ad1402e8ae026380824ddb25cde80a105ff9508cc2fdad19cd81a6af5ec00a894efcf94b6a161e3a22d63589c4cc0529fc4edf7710b",
          "sha256": "50f1ebcc8b3403406e351071991c41ed3c019391cdb513dab7c10ed954053c25",
          "sha1": "f1c1a1ad44e81eeb726da4fc3b4b713bd35db240",
          "md5": "5634a557ce644f5d59f1744e7faf8498"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-9.6.1-b1-sources.jar",
          "url": "core-ng-mongo-9.6.1-b1-sources.jar",
          "size": 28817,
          "sha512": "db3dd673664576758a7a2f4a303b9ffd8f83959a856d02f398292b03fca15aea0cd644744036dfe6269f6d9ef3c6eaa0707b9d64806f480e780323ba410c69a0",
          "sha256": "5656babe6b43c61498bf498055c6a0fcca91b56f32e12c4d4348a8052db606d2",
          "sha1": "5805883e17266f8d13cf52ee1c76b1144d97fc8a",
          "md5": "f205617290610ddd892d80a75e902109"
        }
      ]
    }
  ]
}
