{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.0.3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.0.3.jar",
          "url": "core-ng-9.0.3.jar",
          "size": 735593,
          "sha512": "19012024542768d51bf097054b7f74706b9aaef7e9deea747f333007087aa83e08167c83c22548e82ec9db9dff1c74fdf9e878f535b7be3f07904c5bd8d73122",
          "sha256": "89c831bf3b8433e2bd75bcab70d56c1310ce1d9645053d74ae88493b1a490a2f",
          "sha1": "263eb007f3e14260817adc515f5650a1708c6b8b",
          "md5": "eb5654df15eaf9d09431a1db9dbae17a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.15.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.15.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.10.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "3.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.10.5"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.0.3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.0.3.jar",
          "url": "core-ng-9.0.3.jar",
          "size": 735593,
          "sha512": "19012024542768d51bf097054b7f74706b9aaef7e9deea747f333007087aa83e08167c83c22548e82ec9db9dff1c74fdf9e878f535b7be3f07904c5bd8d73122",
          "sha256": "89c831bf3b8433e2bd75bcab70d56c1310ce1d9645053d74ae88493b1a490a2f",
          "sha1": "263eb007f3e14260817adc515f5650a1708c6b8b",
          "md5": "eb5654df15eaf9d09431a1db9dbae17a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.0.3-sources.jar",
          "url": "core-ng-9.0.3-sources.jar",
          "size": 378210,
          "sha512": "a973b4c15884289e2cba7595675cdbcfeb3e0b6abd78f85d1e5fdda805982feb5d0e8566ed634e760cfb9ec1d64d5ed9e05daddd408337701b2a72c7e3de6186",
          "sha256": "14b3f0f9cf03058995478bef780cca0ecb80cdcb5c2dd3626c6f3d3048f667c7",
          "sha1": "db6b967a41f63b89317917d059fe56866a70968e",
          "md5": "90ffcf579664360954dcb48a0ce3265b"
        }
      ]
    }
  ]
}
