{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "9.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.5.0.jar",
          "url": "core-ng-search-test-9.5.0.jar",
          "size": 11064,
          "sha512": "63ed34b1d8118fadb37a937e655bf1c85c9b64d4e4d302819ae6799e7701af3a350ea5d16e89fd1c657e12b6f8d895244132b2df7179576e1f915bb790cf80bc",
          "sha256": "4edf199db7e84b2acaef229c7b8c145a6d54f60468ae2e7d67135c066b8ddeb2",
          "sha1": "8fb05b121937b2466a6e0f3a2ca2a142bcaccb73",
          "md5": "5b22d74cc6931694cc933d6658410408"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.5.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "9.5.0"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "9.3.2"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "reindex",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-9.5.0.jar",
          "url": "core-ng-search-test-9.5.0.jar",
          "size": 11064,
          "sha512": "63ed34b1d8118fadb37a937e655bf1c85c9b64d4e4d302819ae6799e7701af3a350ea5d16e89fd1c657e12b6f8d895244132b2df7179576e1f915bb790cf80bc",
          "sha256": "4edf199db7e84b2acaef229c7b8c145a6d54f60468ae2e7d67135c066b8ddeb2",
          "sha1": "8fb05b121937b2466a6e0f3a2ca2a142bcaccb73",
          "md5": "5b22d74cc6931694cc933d6658410408"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.5.0-sources.jar",
          "url": "core-ng-search-test-9.5.0-sources.jar",
          "size": 7104,
          "sha512": "442020e27af34aff58ef413f4b9ccb2aab245ec12a6a2ebe9407ef7fece44c20997fc52e396b7b24dd6117b3bba1c3fede00df5c8c97391d9d460c93235fc08f",
          "sha256": "f5035e8dd2c0ee29fa37d7a2f703f8c97086a308f71ad65aa6cdbaf7f17dbe62",
          "sha1": "e2ef0ab20f5a37b22ca5928a430f8babf51a93ce",
          "md5": "2415e18ff1474a0e020df67bf0630ab8"
        }
      ]
    }
  ]
}
