{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "7.5.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6",
      "buildId": "sefro2iuazgoxnjl56voapinay"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.5.11"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.5.11"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.5.11.jar",
          "url": "core-ng-search-test-7.5.11.jar",
          "size": 9046,
          "sha512": "439e0410eb4b7a9d4fe88e7877355e7dbeb089ce7e07404faaee9e971d33a0036e258d4ffd9cd527159751e4bbadfd357f13367da65f13d7f3531fd3ac843b33",
          "sha256": "f0c63a729b9be8ee9a78ff763f231393fef0ee9422c1de06ff959248413a562a",
          "sha1": "8461e638626e021b74daf2be22f728776030936f",
          "md5": "21b6bc10671a8189372ce9b0d6921224"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4-client",
          "version": {
            "requires": "7.9.1"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "reindex-client",
          "version": {
            "requires": "7.9.1"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "7.9.1"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "7.9.1"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "7.9.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.5.11"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.5.11"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.5.11.jar",
          "url": "core-ng-search-test-7.5.11.jar",
          "size": 9046,
          "sha512": "439e0410eb4b7a9d4fe88e7877355e7dbeb089ce7e07404faaee9e971d33a0036e258d4ffd9cd527159751e4bbadfd357f13367da65f13d7f3531fd3ac843b33",
          "sha256": "f0c63a729b9be8ee9a78ff763f231393fef0ee9422c1de06ff959248413a562a",
          "sha1": "8461e638626e021b74daf2be22f728776030936f",
          "md5": "21b6bc10671a8189372ce9b0d6921224"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.5.11-sources.jar",
          "url": "core-ng-search-test-7.5.11-sources.jar",
          "size": 5426,
          "sha512": "5e831c414fd6d7c6955838d2251bc5de8e4838ed59b1b262d9643b5437b1d620767a91b1cc166837b4c778ccd8b2ab6dcfad637bcda052cc8c89f7baba616cab",
          "sha256": "117ef8583bf0bd41124d1a74bbf30a27befbfea679a8a6b2cfa92b716d6e4f30",
          "sha1": "e5edd6df750546cb75810b6ce36f599aaf01e26b",
          "md5": "9bcaa9bd6dd2d4eee5678c5577db06a7"
        }
      ]
    }
  ]
}
