{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "9.3.0-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.3.0-b1.jar",
          "url": "core-ng-mongo-test-9.3.0-b1.jar",
          "size": 2940,
          "sha512": "da4e60161c1980d80a0d20e227f678ba4c61423d8a86107951ef942f3c3d09862a5eed9ebaa9dc879fd65cc5b95a5571ffc455e548f462144666ddec0266ed45",
          "sha256": "e5f4b007628e14660c7a0f88132755a2abbb226558c871cf2d8c294f3ebf3b99",
          "sha1": "668107cc7e5250e9646ec635959180cf6108b080",
          "md5": "7b97ed6e50caca68b94e8125a6dc85c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.3.0-b1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "9.3.0-b1"
          }
        },
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.47.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-9.3.0-b1.jar",
          "url": "core-ng-mongo-test-9.3.0-b1.jar",
          "size": 2940,
          "sha512": "da4e60161c1980d80a0d20e227f678ba4c61423d8a86107951ef942f3c3d09862a5eed9ebaa9dc879fd65cc5b95a5571ffc455e548f462144666ddec0266ed45",
          "sha256": "e5f4b007628e14660c7a0f88132755a2abbb226558c871cf2d8c294f3ebf3b99",
          "sha1": "668107cc7e5250e9646ec635959180cf6108b080",
          "md5": "7b97ed6e50caca68b94e8125a6dc85c1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.3.0-b1-sources.jar",
          "url": "core-ng-mongo-test-9.3.0-b1-sources.jar",
          "size": 2079,
          "sha512": "b804b0d58ec8bb63e3330297cef381f86be3a33585469f10bdbedabf0fef84b71596b8fd41731adf8c188acaa6ff3cde8b71430fdfad12ef75b820d10afc70a7",
          "sha256": "cd7661a040316024fc50aa1d8c4dab06270a6b62237f7c3e4fd669bc144deb2f",
          "sha1": "710da423cb4012bb6fb9c565d5d0c59372c03d1e",
          "md5": "9737ee2166d49c270c9432c46dadca5a"
        }
      ]
    }
  ]
}
