{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "9.0.8-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.0.8-b0.jar",
          "url": "core-ng-mongo-test-9.0.8-b0.jar",
          "size": 2390,
          "sha512": "f30192b5dd1a2ed864dcf1687b075b6e1826a288b2a4294d86c58ce49cc0f8677ac2d26a2913c52c552b317510091f68111ffdd5c5404ad632af54c9062fb182",
          "sha256": "321b7d5553b6e9b31f7bc9030ce420791b3a9aafd6a25a11371dcb3b2857c6c8",
          "sha1": "892e79ebf29c6b282220a66fa6c532f84f95b51b",
          "md5": "f44eb3762d012b506920db3fc5f4ae1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.0.8-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "9.0.8-b0"
          }
        },
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.44.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-9.0.8-b0.jar",
          "url": "core-ng-mongo-test-9.0.8-b0.jar",
          "size": 2390,
          "sha512": "f30192b5dd1a2ed864dcf1687b075b6e1826a288b2a4294d86c58ce49cc0f8677ac2d26a2913c52c552b317510091f68111ffdd5c5404ad632af54c9062fb182",
          "sha256": "321b7d5553b6e9b31f7bc9030ce420791b3a9aafd6a25a11371dcb3b2857c6c8",
          "sha1": "892e79ebf29c6b282220a66fa6c532f84f95b51b",
          "md5": "f44eb3762d012b506920db3fc5f4ae1f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.0.8-b0-sources.jar",
          "url": "core-ng-mongo-test-9.0.8-b0-sources.jar",
          "size": 1724,
          "sha512": "3cc4d2ed2b82dfed8fafa775112f7cb3318129742e57adc86e3843661f18efe10147cca4554c492fb4d6f491390c9eaa4adbf9dbadd5d34193351664d7815375",
          "sha256": "1d45ddff09d0930f2be1cefbfce4ed463057f22a81a02ead9a3552ac4353ba94",
          "sha1": "ddfae5c8b105637711fb6bb902ef3ce37d3dd28e",
          "md5": "8c9bcbb1f41e42140c9a6a0e12bd8853"
        }
      ]
    }
  ]
}
