{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "9.2.3-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.2.3-b0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.2.3-b0.jar",
          "url": "core-ng-mongo-9.2.3-b0.jar",
          "size": 57989,
          "sha512": "87c4c7341157504cb667e325b6a6f2711bf1a55db4fe3aba99dc0d923b888fbf89b28e166cd1cfe30ad12c531c5b91681d2c2905ade2dd60acd857b358d6c01e",
          "sha256": "87c1a661f6ff5faf234e0f9a05896c3cf2b2c7905647f8fd32f86fd63bca093a",
          "sha1": "91a93c5c7cdbeef34178f0a06b9fffa04c499b9b",
          "md5": "ca91daa57dc2dafe3b9cdce2f4232f9e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.2.3-b0"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.2.3-b0.jar",
          "url": "core-ng-mongo-9.2.3-b0.jar",
          "size": 57989,
          "sha512": "87c4c7341157504cb667e325b6a6f2711bf1a55db4fe3aba99dc0d923b888fbf89b28e166cd1cfe30ad12c531c5b91681d2c2905ade2dd60acd857b358d6c01e",
          "sha256": "87c1a661f6ff5faf234e0f9a05896c3cf2b2c7905647f8fd32f86fd63bca093a",
          "sha1": "91a93c5c7cdbeef34178f0a06b9fffa04c499b9b",
          "md5": "ca91daa57dc2dafe3b9cdce2f4232f9e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-9.2.3-b0-sources.jar",
          "url": "core-ng-mongo-9.2.3-b0-sources.jar",
          "size": 27577,
          "sha512": "046023038d2c42bf89cdc77835f8464a81da93bb2a345d838ee6fec12f4705bd820dacc234b025e7d88f41ae058aa246fa23722ef9f04c5ad577226be8460691",
          "sha256": "626641015522db0313a487d96022879d275e519d8f8a165a0b076d8abb5d18c0",
          "sha1": "5ff51aa712c52f17fa758703d0f1eae4d7447a2d",
          "md5": "cbf032225f7a54a04e8da76d682ca2ac"
        }
      ]
    }
  ]
}
