{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "9.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.0.9.jar",
          "url": "core-ng-search-test-9.0.9.jar",
          "size": 13196,
          "sha512": "c2ab3547979e21c407894b64fa9b2d469d25ea16f743ae66d8155b6083ec9dd037a15198f2e2fc60b3a6fd70dc4173b0c66716ddda0744417d49c3fc5839602f",
          "sha256": "225472cd0dc341ca0cef247bdac1a064da1d4ca590b9165a1876cabed12770b1",
          "sha1": "0fde4b29e462245fc718e8e0cde62052e8d8f8f6",
          "md5": "3d0ded5d4bbe3fb7e49e384d97c279c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.0.9"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "9.0.9"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "8.13.2"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4",
          "version": {
            "requires": "8.13.2"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "8.13.2"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "8.13.2"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "8.13.2"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "reindex",
          "version": {
            "requires": "8.13.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "reindex",
              "type": "jar",
              "extension": "jar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-9.0.9.jar",
          "url": "core-ng-search-test-9.0.9.jar",
          "size": 13196,
          "sha512": "c2ab3547979e21c407894b64fa9b2d469d25ea16f743ae66d8155b6083ec9dd037a15198f2e2fc60b3a6fd70dc4173b0c66716ddda0744417d49c3fc5839602f",
          "sha256": "225472cd0dc341ca0cef247bdac1a064da1d4ca590b9165a1876cabed12770b1",
          "sha1": "0fde4b29e462245fc718e8e0cde62052e8d8f8f6",
          "md5": "3d0ded5d4bbe3fb7e49e384d97c279c0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.0.9-sources.jar",
          "url": "core-ng-search-test-9.0.9-sources.jar",
          "size": 7220,
          "sha512": "76d929bcb6ea372f7306a93a489fbaa3afcc2996b607fce2a034fbd84b4d5d3982239f338b11ed04bb57d25b17fbb1d16bcf2f2d4f8bcac0e50b2843059f43cd",
          "sha256": "5361e3b736ddeadf188a0b56b9529bd254a46516840e7a891e8bad262395b19b",
          "sha1": "3bbcf004f19ae4ea5015671eea69fb5269502db8",
          "md5": "aed74edfc23b31c44590a91a4a4c660f"
        }
      ]
    }
  ]
}
