{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.0.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.12"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.0.7.jar",
          "url": "core-ng-9.0.7.jar",
          "size": 739198,
          "sha512": "85f224125e6d822bac0353f72b247df58c1f3c24d1dca7d5be07ade27b43530841044632d977b35f928909b2a80e7742d1b9720f952682d8059799a156ac8e7e",
          "sha256": "f6b6e8fd30a32994c7687dec227d6f7fb1515ddcaddb0c0760b08d39cd0b0d01",
          "sha1": "25f27dfef743d024867fb92012931096005e1d7c",
          "md5": "4a1528a758bee5eb40142e647471354e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.16.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.16.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.10.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "3.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.10.5"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.0.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.12"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.0.7.jar",
          "url": "core-ng-9.0.7.jar",
          "size": 739198,
          "sha512": "85f224125e6d822bac0353f72b247df58c1f3c24d1dca7d5be07ade27b43530841044632d977b35f928909b2a80e7742d1b9720f952682d8059799a156ac8e7e",
          "sha256": "f6b6e8fd30a32994c7687dec227d6f7fb1515ddcaddb0c0760b08d39cd0b0d01",
          "sha1": "25f27dfef743d024867fb92012931096005e1d7c",
          "md5": "4a1528a758bee5eb40142e647471354e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.0.7-sources.jar",
          "url": "core-ng-9.0.7-sources.jar",
          "size": 379999,
          "sha512": "c77ea5eaedd27a3191cb35ac767389840c6eaf2495609c30cc39fa2f8e1faad9df93a4f80873fb65abfbc03586d3746e28c8afb182e873ad1b55afe0a69f6175",
          "sha256": "2cd97d0d6a77d8f429bdb8c885799da3cebd1cc659e9ac4c6993da5230560927",
          "sha1": "ef430c735ffeccd5670831e1aa9e2100f528425d",
          "md5": "c9b0a2d9f0fadfd967b7eef8a2a3de7c"
        }
      ]
    }
  ]
}
