{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "7.6.5-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "ccyvjnb7orff5dpf6eczxv6e7a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.5-b1"
          }
        },
        {
          "group": "org.elasticsearch.client",
          "module": "elasticsearch-rest-high-level-client",
          "version": {
            "requires": "7.10.0"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.core",
              "module": "jackson-core"
            },
            {
              "group": "com.fasterxml.jackson.dataformat",
              "module": "jackson-dataformat-smile"
            },
            {
              "group": "com.fasterxml.jackson.dataformat",
              "module": "jackson-dataformat-cbor"
            },
            {
              "group": "com.fasterxml.jackson.dataformat",
              "module": "jackson-dataformat-yaml"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.6.5-b1.jar",
          "url": "core-ng-search-7.6.5-b1.jar",
          "size": 38505,
          "sha512": "c9ffb5ccc88766aa4bc39f579af1288d1668ff2c0ba222f7a4b0589e8d2ac1b6b3a6f82537679086c524f173413049782b64434f012271b410b9d04c3b5d470d",
          "sha256": "1f9cdac9b78ba75fc7071b8119f6fea0c72853fdb8f4e3a33824fa046086afda",
          "sha1": "79c18f2b5a323a745807c93c51b0469600519b91",
          "md5": "062820d6803742ede5dd114a1f58ed02"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.5-b1"
          }
        },
        {
          "group": "org.elasticsearch.client",
          "module": "elasticsearch-rest-high-level-client",
          "version": {
            "requires": "7.10.0"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.core",
              "module": "jackson-core"
            },
            {
              "group": "com.fasterxml.jackson.dataformat",
              "module": "jackson-dataformat-smile"
            },
            {
              "group": "com.fasterxml.jackson.dataformat",
              "module": "jackson-dataformat-cbor"
            },
            {
              "group": "com.fasterxml.jackson.dataformat",
              "module": "jackson-dataformat-yaml"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.6.5-b1.jar",
          "url": "core-ng-search-7.6.5-b1.jar",
          "size": 38505,
          "sha512": "c9ffb5ccc88766aa4bc39f579af1288d1668ff2c0ba222f7a4b0589e8d2ac1b6b3a6f82537679086c524f173413049782b64434f012271b410b9d04c3b5d470d",
          "sha256": "1f9cdac9b78ba75fc7071b8119f6fea0c72853fdb8f4e3a33824fa046086afda",
          "sha1": "79c18f2b5a323a745807c93c51b0469600519b91",
          "md5": "062820d6803742ede5dd114a1f58ed02"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-7.6.5-b1-sources.jar",
          "url": "core-ng-search-7.6.5-b1-sources.jar",
          "size": 17331,
          "sha512": "29ff64dc656fc40f904e379c34cb992780b9feffc886c66761598893954dd3706016ab9a12332c8674b954d62891ab725013a00a7db013fb693d523d8336984b",
          "sha256": "57e867280fa1a2039f267e9a5dd10e0e2c941fa0c7e4dbb8bb3880b7c3196232",
          "sha1": "dcd9d92b1facf3c421a9385dcc015bde5e7c89ce",
          "md5": "b2f7173c4e88fad8cca64a05b7d3a514"
        }
      ]
    }
  ]
}
