{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework.mysql",
    "module": "mysql-connector-j",
    "version": "8.4.0-r1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mysql-connector-j-8.4.0-r1.jar",
          "url": "mysql-connector-j-8.4.0-r1.jar",
          "size": 519055,
          "sha512": "d8e540f45517179edc4a484ce62c5368610512f148c4089c12e70c33a2bb3745614a81234a002a3ef0a95930a86f493ce47dbcdffd5979d2f05a91f6245e8408",
          "sha256": "2200732fe69b8473dda8ca3183d064e31dc29431b0b6cca8e2dd2d5da7a634b8",
          "sha1": "70dc0e0a71cb0780e098dbddfa9ec5f7483639b0",
          "md5": "84d3927491ab3255bf0a428565620e15"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mysql-connector-j-8.4.0-r1.jar",
          "url": "mysql-connector-j-8.4.0-r1.jar",
          "size": 519055,
          "sha512": "d8e540f45517179edc4a484ce62c5368610512f148c4089c12e70c33a2bb3745614a81234a002a3ef0a95930a86f493ce47dbcdffd5979d2f05a91f6245e8408",
          "sha256": "2200732fe69b8473dda8ca3183d064e31dc29431b0b6cca8e2dd2d5da7a634b8",
          "sha1": "70dc0e0a71cb0780e098dbddfa9ec5f7483639b0",
          "md5": "84d3927491ab3255bf0a428565620e15"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mysql-connector-j-8.4.0-r1-sources.jar",
          "url": "mysql-connector-j-8.4.0-r1-sources.jar",
          "size": 521202,
          "sha512": "7faf46047fa862b24da89234a4d0e978b555435d78b9d8ba57414640414b99683c7ce049ef70a3be6ec5e8d0e204cd5d5ed0000bd90aeeec604c4b58f4f92b81",
          "sha256": "f673c64c41b5c5b864ea4bd6b5276a9083f69c26d75d6926d1a0e4942eeb0737",
          "sha1": "5ab13a430f674288aaf40fdf4aa1bee44c1ed20d",
          "md5": "12bbe725b38d888d9f8a84e4f8130781"
        }
      ]
    }
  ]
}
