{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "7.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "tiw26whr7vh43djrdosu3oi4rq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-7.4.6.jar",
          "url": "core-ng-api-7.4.6.jar",
          "size": 10448,
          "sha512": "d772284b83be010f16960f6d4273f11ac3ff6330000aaa07ee9654d91c90ccf4e0cecda1f302422a11187cb8171736b4dc38a79130cd54bdfc6bf8a9b06da537",
          "sha256": "7bb7c244b6469a617d3563e7c76ac0261099aaa9355602e1c7000f8b266fe347",
          "sha1": "132c6d41a5ec0666e72cf2a3ab6200ce3ffd3e85",
          "md5": "48e3e3691f84e5635edc9777c1751591"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.4.6.jar",
          "url": "core-ng-api-7.4.6.jar",
          "size": 10448,
          "sha512": "d772284b83be010f16960f6d4273f11ac3ff6330000aaa07ee9654d91c90ccf4e0cecda1f302422a11187cb8171736b4dc38a79130cd54bdfc6bf8a9b06da537",
          "sha256": "7bb7c244b6469a617d3563e7c76ac0261099aaa9355602e1c7000f8b266fe347",
          "sha1": "132c6d41a5ec0666e72cf2a3ab6200ce3ffd3e85",
          "md5": "48e3e3691f84e5635edc9777c1751591"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.4.6-sources.jar",
          "url": "core-ng-api-7.4.6-sources.jar",
          "size": 8184,
          "sha512": "7df97882730deb25ba696518b90bf468378b8dd3cd967ed123a62abf37022b2d304ec477dcb819585323ccf049dfa9d1438d7f1ba7edb9665a6b89f1c7dd9bc7",
          "sha256": "11217f472910985d4b7431eb4d36df36270f5c8a35a1465158015baf794f9572",
          "sha1": "e3dae78947ec42d57121306b0019439932bbdaad",
          "md5": "43ceeb900a0248175cb0ba37f78ec9a1"
        }
      ]
    }
  ]
}
