{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "7.7.4-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.11.1"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.7.4-b1.jar",
          "url": "core-ng-test-7.7.4-b1.jar",
          "size": 41889,
          "sha512": "82c20b3025cba4e1e75af279237e9663a60deafe81e6655ec971142571793ecb40792b24d5ebeab8dceebc85813d2a6a79f6b1d68d075c8a7ec7e01b03df8335",
          "sha256": "6eee8bb8eda0c98283006aa6dfb74f1615ec56faf4f4bdc57b1aa70005154e43",
          "sha1": "9e182c226942ce8903f363af2f0a84025055e2a7",
          "md5": "e64d909ca23da83d901857d58aa2ff9a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.7.4-b1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.7.2"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.8.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.11.1"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.7.4-b1.jar",
          "url": "core-ng-test-7.7.4-b1.jar",
          "size": 41889,
          "sha512": "82c20b3025cba4e1e75af279237e9663a60deafe81e6655ec971142571793ecb40792b24d5ebeab8dceebc85813d2a6a79f6b1d68d075c8a7ec7e01b03df8335",
          "sha256": "6eee8bb8eda0c98283006aa6dfb74f1615ec56faf4f4bdc57b1aa70005154e43",
          "sha1": "9e182c226942ce8903f363af2f0a84025055e2a7",
          "md5": "e64d909ca23da83d901857d58aa2ff9a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-7.7.4-b1-sources.jar",
          "url": "core-ng-test-7.7.4-b1-sources.jar",
          "size": 20153,
          "sha512": "f42b7b1a6d8e56990846257ce9b464764222ae640b5dd2f56a8444f1d96884aab65eca628244de99e1b08ad27617d7b6639517cc2aeb754e5d127a2733726426",
          "sha256": "1aae1ed434ec3248c9c62289de968f9120fd83d3c5074b58bd5f4249368ce878",
          "sha1": "ea19d57027b74fc5a42b26d05e335145186169b5",
          "md5": "4963bb944fea339cd92da4d05a0a7044"
        }
      ]
    }
  ]
}
