{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "7.7.1-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.7.1-b0"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "7.13.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "elasticsearch",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch-x-content",
          "version": {
            "requires": "7.13.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "elasticsearch-x-content",
              "type": "jar",
              "extension": "jar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.7.1-b0.jar",
          "url": "core-ng-search-7.7.1-b0.jar",
          "size": 38915,
          "sha512": "6014b25c0a0d077cae39c98a47ac71f52b8a941f9411ca276907636994e775822d8265e20e6be0cda8565ae4e653e866422bd657387baf8bc7123926b160f958",
          "sha256": "8d86b34ea695ea0d1bf5014b9e0d0f0c4567fdcfd1011a9d1bac3f2608d1211a",
          "sha1": "ce58a3bd3a3acc2afaa8fa3486289961b3390cf8",
          "md5": "8b6af501fa06d7dce382cf60ce598057"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.elasticsearch.client",
          "module": "elasticsearch-rest-high-level-client",
          "version": {
            "requires": "7.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.7.1-b0"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "7.13.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "elasticsearch",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch-x-content",
          "version": {
            "requires": "7.13.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "elasticsearch-x-content",
              "type": "jar",
              "extension": "jar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.7.1-b0.jar",
          "url": "core-ng-search-7.7.1-b0.jar",
          "size": 38915,
          "sha512": "6014b25c0a0d077cae39c98a47ac71f52b8a941f9411ca276907636994e775822d8265e20e6be0cda8565ae4e653e866422bd657387baf8bc7123926b160f958",
          "sha256": "8d86b34ea695ea0d1bf5014b9e0d0f0c4567fdcfd1011a9d1bac3f2608d1211a",
          "sha1": "ce58a3bd3a3acc2afaa8fa3486289961b3390cf8",
          "md5": "8b6af501fa06d7dce382cf60ce598057"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-7.7.1-b0-sources.jar",
          "url": "core-ng-search-7.7.1-b0-sources.jar",
          "size": 17510,
          "sha512": "04ba31dc73616b4c4d953e64a1534237a5400e5089aa4da840c69ae7fc3c852dee165a4b39d8b083b281803f5ca40a617983f78f3f21c9ddbabb4909402ea6d6",
          "sha256": "8c3bff1d28a6d479f0fcbe76c107bd822428d95750a0f1158cd64ccbe79530e9",
          "sha1": "279e5bcadab402fba41a680ce246ca379cf1da76",
          "md5": "bf392563c262b944b6b758e3cb331e30"
        }
      ]
    }
  ]
}
