{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "7.6.8-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "fqfj5gjcprevjolwmzhcja5rx4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.6.8-b1.jar",
          "url": "core-ng-search-test-7.6.8-b1.jar",
          "size": 9068,
          "sha512": "afd78f015679c8bff0ce1753c7a533a5546f2b58064584da7916745e6a488e85d0166ba51cbc669655d7b49a6dfd148f0f465b1b2fd3a8fc17a172ff23345185",
          "sha256": "6798e5aede3c9175ac77e107e641393c9e6530de6d3d622ab04870bf924f0805",
          "sha1": "1b640e827ca8906c80c65a0eb4bac7839294ce1f",
          "md5": "55b69ac6d61ae51a57554c7ff99d64e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.6.8-b1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.6.8-b1"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4-client",
          "version": {
            "requires": "7.10.1"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "reindex-client",
          "version": {
            "requires": "7.10.1"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "7.10.1"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "7.10.1"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "7.10.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.6.8-b1.jar",
          "url": "core-ng-search-test-7.6.8-b1.jar",
          "size": 9068,
          "sha512": "afd78f015679c8bff0ce1753c7a533a5546f2b58064584da7916745e6a488e85d0166ba51cbc669655d7b49a6dfd148f0f465b1b2fd3a8fc17a172ff23345185",
          "sha256": "6798e5aede3c9175ac77e107e641393c9e6530de6d3d622ab04870bf924f0805",
          "sha1": "1b640e827ca8906c80c65a0eb4bac7839294ce1f",
          "md5": "55b69ac6d61ae51a57554c7ff99d64e7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.6.8-b1-sources.jar",
          "url": "core-ng-search-test-7.6.8-b1-sources.jar",
          "size": 5479,
          "sha512": "2bdb2811e172521a83b435cc395106ddd9dbea455f81c86fd166120ebf6c29b95a0875bde333c36236aa74a1e3df17209c9a65e348000cb980fb4b81b1c3741d",
          "sha256": "57c47d19d6e6afd01c1a1d2df4e9e32a3be1364066a376e0ee788de23788d4c8",
          "sha1": "54731e21a3cb0438b0ae884f1099c5092e373c03",
          "md5": "27e0be1812d98e53ecf0e4dc46547d0a"
        }
      ]
    }
  ]
}
