{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "7.7.1-b2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.7.1-b2.jar",
          "url": "core-ng-search-test-7.7.1-b2.jar",
          "size": 9068,
          "sha512": "3a9990023b78bde00faaffb51f0a4613b2184c6dd695d51d69326e173f78ab7ffe658e8eeba872f8617597466e7f396d5a071be522923b5f97b1027f47684712",
          "sha256": "dc56aa2a19640b1877bac2891d83f6b75b883a23daa3f0a3f0c5d01389e69cc4",
          "sha1": "d297c7a71e2dccd5e1941241c5c454824944bdb0",
          "md5": "b75699e9c203fb426d30720c2e358c1a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.7.1-b2"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.7.1-b2"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "7.13.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4-client",
          "version": {
            "requires": "7.13.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "reindex-client",
          "version": {
            "requires": "7.13.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "mapper-extras-client",
          "version": {
            "requires": "7.13.0"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "7.13.0"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "7.13.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.7.1-b2.jar",
          "url": "core-ng-search-test-7.7.1-b2.jar",
          "size": 9068,
          "sha512": "3a9990023b78bde00faaffb51f0a4613b2184c6dd695d51d69326e173f78ab7ffe658e8eeba872f8617597466e7f396d5a071be522923b5f97b1027f47684712",
          "sha256": "dc56aa2a19640b1877bac2891d83f6b75b883a23daa3f0a3f0c5d01389e69cc4",
          "sha1": "d297c7a71e2dccd5e1941241c5c454824944bdb0",
          "md5": "b75699e9c203fb426d30720c2e358c1a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.7.1-b2-sources.jar",
          "url": "core-ng-search-test-7.7.1-b2-sources.jar",
          "size": 5479,
          "sha512": "c885448035564fb20693f63e17d3f8940860a33d4a8b2aa4a087b8e0484b3a16213fcc3cdc1f63f076d7e86cb1afb6e857b12772202d969ef358c64e92ffb576",
          "sha256": "b3734d52ee9b2a88a99bbe8b9ffe1c47f691ed0bcd8c36f49a5c37c0a6e4cf50",
          "sha1": "4c6cb08d2e034d556675f2da1f1685403e28dc51",
          "md5": "763ccc0c524440bd4921c1ed6451ea18"
        }
      ]
    }
  ]
}
