{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "9.2.3-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.2.3-b0.jar",
          "url": "core-ng-mongo-test-9.2.3-b0.jar",
          "size": 2487,
          "sha512": "97a1fec25069137e30ac4cdac0c19ad2f8389ca81475b2789a2061e6d71456565d53ab7486cbf952eaca213274706fd130a2606e10305ed931a2a95482f81f37",
          "sha256": "e8f838c721b320b3ffb34c780d1ca1c3da9c953f7ed3ab1ddc621182f88b56ee",
          "sha1": "49ae46e88975ee7ca079698ddd8cf2a6c7b6f374",
          "md5": "0160c790ce6aee06d15001716d6ac299"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 24,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.2.3-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "9.2.3-b0"
          }
        },
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.46.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-9.2.3-b0.jar",
          "url": "core-ng-mongo-test-9.2.3-b0.jar",
          "size": 2487,
          "sha512": "97a1fec25069137e30ac4cdac0c19ad2f8389ca81475b2789a2061e6d71456565d53ab7486cbf952eaca213274706fd130a2606e10305ed931a2a95482f81f37",
          "sha256": "e8f838c721b320b3ffb34c780d1ca1c3da9c953f7ed3ab1ddc621182f88b56ee",
          "sha1": "49ae46e88975ee7ca079698ddd8cf2a6c7b6f374",
          "md5": "0160c790ce6aee06d15001716d6ac299"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.2.3-b0-sources.jar",
          "url": "core-ng-mongo-test-9.2.3-b0-sources.jar",
          "size": 1780,
          "sha512": "703ea21cb22bd31171ca47c0c691a1aca97ea0e1eda7662f9e5e7efb30cd3e0f48bc0e52aeb0bd1b09fb4c162c5d63f81ac59698166d2cd590f4ef3954aa91e3",
          "sha256": "8a175cf625a491043a058433ff3dff47e979d7c1247d21a7fee8111641977579",
          "sha1": "a01f538457e08ad86f7499aa40a821b360ac6cb1",
          "md5": "648a0cfbf38a93d09108b26a1dd2b449"
        }
      ]
    }
  ]
}
