{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "9.1.1-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.3"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.12.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.26.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.1.1-b1.jar",
          "url": "core-ng-test-9.1.1-b1.jar",
          "size": 45685,
          "sha512": "599d8cbe377e5a4568f6a4c7ce71afc4e7ca4aa1a494b82d0411ac1bb27ad205197e3077365bc3cd4786095123eb709f7c50f76c11f69591e723a710dd0c9ecc",
          "sha256": "0ac5e5a424deacbdb7e44898a6d34743faa49de89dca7ae1baef3b092c243ea0",
          "sha1": "16eedeb17108306ffd38fd9bf305acf04f8969be",
          "md5": "9d8b937e88464c9d219807a5f9765e44"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.1-b1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.10.3"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.3"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.12.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.26.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.1.1-b1.jar",
          "url": "core-ng-test-9.1.1-b1.jar",
          "size": 45685,
          "sha512": "599d8cbe377e5a4568f6a4c7ce71afc4e7ca4aa1a494b82d0411ac1bb27ad205197e3077365bc3cd4786095123eb709f7c50f76c11f69591e723a710dd0c9ecc",
          "sha256": "0ac5e5a424deacbdb7e44898a6d34743faa49de89dca7ae1baef3b092c243ea0",
          "sha1": "16eedeb17108306ffd38fd9bf305acf04f8969be",
          "md5": "9d8b937e88464c9d219807a5f9765e44"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-9.1.1-b1-sources.jar",
          "url": "core-ng-test-9.1.1-b1-sources.jar",
          "size": 22203,
          "sha512": "92ac0eddbce19d0201e4c82e29cd2ec0fafac8df9b5f452523556f72ae4e178c9383698326538bd2506f644f456464830c3d84e128342f9485009a68748a2680",
          "sha256": "ddc748c8fb742937db7debd78d877deb7322c1e6e78f8cd13c7c27f0ce7919a1",
          "sha1": "dc7012e58165c9da5d4cfe314f3322cd1a1466be",
          "md5": "c59d300f038a64d0d3bbcf740ce4c6f1"
        }
      ]
    }
  ]
}
