{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "7.6.8-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "fqfj5gjcprevjolwmzhcja5rx4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-7.6.8-b1.jar",
          "url": "core-ng-api-7.6.8-b1.jar",
          "size": 10959,
          "sha512": "844c66c8a5c7df6a473dfee95b98e6b36e1d576efb487068997e7bf7ee3de5388756f3cd3779fbd6ad8d0635a3987b3b53ca0a8f2cdaf152b64237f0f6df04bc",
          "sha256": "d9836f6602189db76d1bfa43d75d7831dd84b7eeef26faa5d8d73036ae19d991",
          "sha1": "96de85bf7f20f43862d59b01f58084e23db9b0f1",
          "md5": "5e885cdfea55ddf4d5ad49e11aaf3e05"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.6.8-b1.jar",
          "url": "core-ng-api-7.6.8-b1.jar",
          "size": 10959,
          "sha512": "844c66c8a5c7df6a473dfee95b98e6b36e1d576efb487068997e7bf7ee3de5388756f3cd3779fbd6ad8d0635a3987b3b53ca0a8f2cdaf152b64237f0f6df04bc",
          "sha256": "d9836f6602189db76d1bfa43d75d7831dd84b7eeef26faa5d8d73036ae19d991",
          "sha1": "96de85bf7f20f43862d59b01f58084e23db9b0f1",
          "md5": "5e885cdfea55ddf4d5ad49e11aaf3e05"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.6.8-b1-sources.jar",
          "url": "core-ng-api-7.6.8-b1-sources.jar",
          "size": 8644,
          "sha512": "050057330420d2b11a5f1963dfe1eaed90b066a090fd50fc411458374dfc2452764589ee0795b9b48a675b46eff6852e030a780add697942d4d71f920e933332",
          "sha256": "ab64bcf2e108d32442393366f2dd2f5bbd5ce514699e066dacebb17992f5e0a2",
          "sha1": "3dbf262aa350975c0119357a56cc9abf8c5133e3",
          "md5": "25111b15d9588713e86b514e9189f551"
        }
      ]
    }
  ]
}
