{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "7.6.16-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-7.6.16-b1.jar",
          "url": "core-ng-mongo-test-7.6.16-b1.jar",
          "size": 2384,
          "sha512": "6e3543d40e19d4030a3ac50f88511664dae5fe05b939ecfb0414e5fe977ee628434684b747daf98e15df688f39ed7d046c867b3294f4e13188452775b0c1f5ac",
          "sha256": "5a81b8a63108f04b11c0c09066388f8b050c280732031952f78d64e9ed92790d",
          "sha1": "211ecaab859a831f1a13477680f399d3fd0a9daa",
          "md5": "7d12135e01a24a3fa5dbbaedb07bd334"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.6.16-b1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "7.6.16-b1"
          }
        },
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.38.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-7.6.16-b1.jar",
          "url": "core-ng-mongo-test-7.6.16-b1.jar",
          "size": 2384,
          "sha512": "6e3543d40e19d4030a3ac50f88511664dae5fe05b939ecfb0414e5fe977ee628434684b747daf98e15df688f39ed7d046c867b3294f4e13188452775b0c1f5ac",
          "sha256": "5a81b8a63108f04b11c0c09066388f8b050c280732031952f78d64e9ed92790d",
          "sha1": "211ecaab859a831f1a13477680f399d3fd0a9daa",
          "md5": "7d12135e01a24a3fa5dbbaedb07bd334"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-7.6.16-b1-sources.jar",
          "url": "core-ng-mongo-test-7.6.16-b1-sources.jar",
          "size": 1722,
          "sha512": "bbae70c4199faa1d7ae452f56f522ba20f179df67fb91e1dc11fec18c0b1ca6060d5fd93eda44177c65d41ec89eaa958879bdfa43e51c669985b9f28d771a158",
          "sha256": "66153ec25f33e6d77b1be16a2e959d4bf9bfa03db8b18eb726d28668a7b76293",
          "sha1": "df6190c2e919ba5c33ed07da82a5f2d20730c98e",
          "md5": "d847c9803b6764f324b16963e7035bbf"
        }
      ]
    }
  ]
}
