{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "9.0.8-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.10.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.0.8-b0.jar",
          "url": "core-ng-test-9.0.8-b0.jar",
          "size": 45694,
          "sha512": "4d7c9f1bb67ea44392be7e65d5adb3cd07f7b60c0344ca621c5f8e03cb28f07f5c154c3d44e67b6a8e86ae42775c0b5491393e99f85f39a226fec888f3e0746b",
          "sha256": "7f79621f851c1df733899e187abe6d4bd51a0c30f56f0bddb2dd7cbcc5b43159",
          "sha1": "df99a09665aee6a42b105ec39d7bb2f44bc8d9e6",
          "md5": "e15ff2daea4e852ab783c6b55b1c527e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.8-b0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.10.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.0.8-b0.jar",
          "url": "core-ng-test-9.0.8-b0.jar",
          "size": 45694,
          "sha512": "4d7c9f1bb67ea44392be7e65d5adb3cd07f7b60c0344ca621c5f8e03cb28f07f5c154c3d44e67b6a8e86ae42775c0b5491393e99f85f39a226fec888f3e0746b",
          "sha256": "7f79621f851c1df733899e187abe6d4bd51a0c30f56f0bddb2dd7cbcc5b43159",
          "sha1": "df99a09665aee6a42b105ec39d7bb2f44bc8d9e6",
          "md5": "e15ff2daea4e852ab783c6b55b1c527e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-9.0.8-b0-sources.jar",
          "url": "core-ng-test-9.0.8-b0-sources.jar",
          "size": 22170,
          "sha512": "e9fccb5b979687cf2cd95bb7602f9a035a7ce10cffe530b07508f7e76129c0e4ab2ffaaef84c8b8f65e7f7a8a2f910ff400f0c40cf05410734cabdc077191bc2",
          "sha256": "07e6b2ea2b886628f6bee2ba5da95afca1354a0fdefdcf0264eaa81aa8f44c2f",
          "sha1": "784ac02a4d8eb208edc40daf3fc9f4ade180f389",
          "md5": "09c2f69f6f4ee8a20fcc1d5f156d5304"
        }
      ]
    }
  ]
}
