{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "7.6.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "5ouw753gz5cgbnubxggdyz4bvu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.6.12"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.6.12.jar",
          "url": "core-ng-7.6.12.jar",
          "size": 685355,
          "sha512": "9222aeeef80d2423bbda386b941fee19e05574e5e33b80577e39871180782ef5c1674caf276a6d55e8d4a831f6a140cd26ad855503888c4e7266257bbca8593b",
          "sha256": "a29942701e54dbc13656d0857d3d2ebf174151ab0df4f57f345346c25d24091d",
          "sha1": "e624acba9d410fd3da2db76408438381d778b98a",
          "md5": "0e96d489148b7c05e024a65e7d559280"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.27.0-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.2.4.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.7.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.8.2"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.6.12"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.6.12.jar",
          "url": "core-ng-7.6.12.jar",
          "size": 685355,
          "sha512": "9222aeeef80d2423bbda386b941fee19e05574e5e33b80577e39871180782ef5c1674caf276a6d55e8d4a831f6a140cd26ad855503888c4e7266257bbca8593b",
          "sha256": "a29942701e54dbc13656d0857d3d2ebf174151ab0df4f57f345346c25d24091d",
          "sha1": "e624acba9d410fd3da2db76408438381d778b98a",
          "md5": "0e96d489148b7c05e024a65e7d559280"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-7.6.12-sources.jar",
          "url": "core-ng-7.6.12-sources.jar",
          "size": 352587,
          "sha512": "aaab28aa9b8d2d2e94d2a188b30257a2d6a6ca16d837401e60921a2bbf2cd933c93079d36dd5b5a67e48b6a52ab22bb1385b97af10adae6793a1763dca574388",
          "sha256": "0748066978d190ffd1636e0f98acf2699dadea9dc5b8b4e4dd2c30601dabcc9f",
          "sha1": "e566c24d8032ed6f877447d747e445588b39855c",
          "md5": "062373dbdba3deca8314ac849db07a29"
        }
      ]
    }
  ]
}
