{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "7.6.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "y4jpvy47ejel5oivsnxw6bxvra"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.6.12"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.6.12.jar",
          "url": "core-ng-7.6.12.jar",
          "size": 685053,
          "sha512": "9c2721ce191591cae083967123dcfd8bfcca9a7826e584fbae9058491598c8d606480b1d1187197d5c4ce0869af9b7c086a43dcc58aa2cbfac4a7906a547b166",
          "sha256": "fedb7d5cc3f7985d19073b5fb757e54ffe5f81a083152815f1c8979c70301011",
          "sha1": "bb5eaea493a209cd617e4ffa4fb9d61493c0b1fb",
          "md5": "bd7416ec39c6e264116455c6d4267135"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.27.0-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.2.4.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.7.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.8.2"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.6.12"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.6.12.jar",
          "url": "core-ng-7.6.12.jar",
          "size": 685053,
          "sha512": "9c2721ce191591cae083967123dcfd8bfcca9a7826e584fbae9058491598c8d606480b1d1187197d5c4ce0869af9b7c086a43dcc58aa2cbfac4a7906a547b166",
          "sha256": "fedb7d5cc3f7985d19073b5fb757e54ffe5f81a083152815f1c8979c70301011",
          "sha1": "bb5eaea493a209cd617e4ffa4fb9d61493c0b1fb",
          "md5": "bd7416ec39c6e264116455c6d4267135"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-7.6.12-sources.jar",
          "url": "core-ng-7.6.12-sources.jar",
          "size": 352114,
          "sha512": "7385364b6dcdede53052ef18f1b2d7991f2b6bd3bcad5085eeb663c1d80dd3ec236d3a4c571f631a14674952f0def7c0b010e52cf18b0c6810aa0767f87fe4e6",
          "sha256": "079dd9e502b340ccd7718b93014dad195a5e1002ea379c7c6ad366454c7dc0a9",
          "sha1": "f47d528bd907127d1f342dc2efac254949f68824",
          "md5": "bc8634ca6f38e2be9b9c6ac01f1afdea"
        }
      ]
    }
  ]
}
