{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.0.8-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.0.8-b0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.12"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.0.8-b0.jar",
          "url": "core-ng-9.0.8-b0.jar",
          "size": 739232,
          "sha512": "2a7bb63cabeb4663dfe3836abf20d433ed8d70005d008fafe5bbca0beebe3d42ebaaf036a8f0af44493155ff9f73163736f43dc27b30f6f71c45090b4af1d362",
          "sha256": "a659e610376087c058b1debacb0a4f91d89cb7d69895943a9045c969bbc47b9b",
          "sha1": "5e4f8c5e16984e43961fc0e11c1370c922df7556",
          "md5": "f703a27520de4cd7db297551a08366d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.16.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.16.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.10.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "3.7.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.10.5"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.0.8-b0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.12"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.0.8-b0.jar",
          "url": "core-ng-9.0.8-b0.jar",
          "size": 739232,
          "sha512": "2a7bb63cabeb4663dfe3836abf20d433ed8d70005d008fafe5bbca0beebe3d42ebaaf036a8f0af44493155ff9f73163736f43dc27b30f6f71c45090b4af1d362",
          "sha256": "a659e610376087c058b1debacb0a4f91d89cb7d69895943a9045c969bbc47b9b",
          "sha1": "5e4f8c5e16984e43961fc0e11c1370c922df7556",
          "md5": "f703a27520de4cd7db297551a08366d1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.0.8-b0-sources.jar",
          "url": "core-ng-9.0.8-b0-sources.jar",
          "size": 380052,
          "sha512": "681d8eff849b79b939166e9ac765289ed3164fa48a8665db1b7f1962bd34ec788ed69a5b4c4a8b5e789a2caa93e3bb62e2d363c010cace08ac3515fd103148cd",
          "sha256": "f366297366c3bdc482457e0150a9bc2134f78d8269aaa47fa37cf3eec17c2a34",
          "sha1": "3b3e553eb60edf75918bd49ac3f6cc1b42501af7",
          "md5": "a0bcf64501acde0beac1aade07c98097"
        }
      ]
    }
  ]
}
