{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "9.5.1-b5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.5.1-b5.jar",
          "url": "core-ng-search-test-9.5.1-b5.jar",
          "size": 11066,
          "sha512": "518680507a4f7c3bebaa68a45ece989eb5de259420df5cbd719e89c3ce8029ca1da854114b1531332b6a25f0b1f0d3dffc15dbf442c5bc43aee8b4b23423006b",
          "sha256": "08b8b9ac4b7d1c622163e23ad699609ac9d6cd230309571ed5c620898cebd2c5",
          "sha1": "26ef8ef9f4896159f20f90de83d9c611084eb3cb",
          "md5": "a86d69270bf452191f83dc9b89f8cc5f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.5.1-b5"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "9.5.1-b5"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "9.3.2"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "reindex",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-9.5.1-b5.jar",
          "url": "core-ng-search-test-9.5.1-b5.jar",
          "size": 11066,
          "sha512": "518680507a4f7c3bebaa68a45ece989eb5de259420df5cbd719e89c3ce8029ca1da854114b1531332b6a25f0b1f0d3dffc15dbf442c5bc43aee8b4b23423006b",
          "sha256": "08b8b9ac4b7d1c622163e23ad699609ac9d6cd230309571ed5c620898cebd2c5",
          "sha1": "26ef8ef9f4896159f20f90de83d9c611084eb3cb",
          "md5": "a86d69270bf452191f83dc9b89f8cc5f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.5.1-b5-sources.jar",
          "url": "core-ng-search-test-9.5.1-b5-sources.jar",
          "size": 7106,
          "sha512": "ee4c065fcf44951d64a7b5b917070b9e78fd93ce4136dde97a07cf6a4bc92c895c26ae72e87e7063c6478a338a0d42234bcb6af937226c17979855ab50041f9d",
          "sha256": "b7e8f6e53ca1b19c2e896a5b551e13912e98edf4c54bfb49c4fce10e4890377d",
          "sha1": "ad00f7d5dca5c8a75be6d004f6dcfc8df4ca8426",
          "md5": "924b1d446529da13fc76930de8f28257"
        }
      ]
    }
  ]
}
