{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "9.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.3.1"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.3.1.jar",
          "url": "core-ng-mongo-9.3.1.jar",
          "size": 60076,
          "sha512": "69cf72cd1b2a37e69c8d721a0ce79e33ddfde2ad1b86e977934287c68fc8a2891b1c5fa141883d66bce6ca6e6f535915c9affb8d8b5224891189a5f86a4d7494",
          "sha256": "47e1b967db705abba5a6ba821fd034911d40b8af9b7e621981e10d744bb48833",
          "sha1": "68b350d4a8d78b95cc14c22f7570a4b472d43f2f",
          "md5": "cdbe7806bbddcc763683e0be4cc4088c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.3.1"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.3.1.jar",
          "url": "core-ng-mongo-9.3.1.jar",
          "size": 60076,
          "sha512": "69cf72cd1b2a37e69c8d721a0ce79e33ddfde2ad1b86e977934287c68fc8a2891b1c5fa141883d66bce6ca6e6f535915c9affb8d8b5224891189a5f86a4d7494",
          "sha256": "47e1b967db705abba5a6ba821fd034911d40b8af9b7e621981e10d744bb48833",
          "sha1": "68b350d4a8d78b95cc14c22f7570a4b472d43f2f",
          "md5": "cdbe7806bbddcc763683e0be4cc4088c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-9.3.1-sources.jar",
          "url": "core-ng-mongo-9.3.1-sources.jar",
          "size": 28814,
          "sha512": "b93e7118dee92dfd2b37926a12cb387dd3ee45e7844e8502a4cb6cbe350a70e7acf80e1142a5e46460412b0d9161bfcacdb5fc4d86ec1824ab15c7d0466896b0",
          "sha256": "d897955ded8ea5dc5391a06b2fa5e96a2cf7911acc61e353c56812bfbf17dcab",
          "sha1": "687edb2209b10eb39d34b6aa84874939081768b9",
          "md5": "4abdf476d612aa8dbf76ca2689c6778d"
        }
      ]
    }
  ]
}
