{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "7.7.4-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.7.4-b0.jar",
          "url": "core-ng-search-test-7.7.4-b0.jar",
          "size": 9068,
          "sha512": "dee722532a1d263746574ea649fb9e2dc16b74d761a5424a5d1ffd5b7d38aa0e59570147e4b39dddccd6c03cfd66d2568fa126056d9519946bdd0f5d76a835b3",
          "sha256": "093aea0cf37ad74be50e5c68e710cdc0a66bbcf2e859dd754a6c1896e9c3b663",
          "sha1": "25c801c7e7a1018d9a8a152f1fdbf947d8a31084",
          "md5": "d641bbe99e25c97ca5364bbf57391b86"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.7.4-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "7.7.4-b0"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "7.13.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4-client",
          "version": {
            "requires": "7.13.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "reindex-client",
          "version": {
            "requires": "7.13.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "mapper-extras-client",
          "version": {
            "requires": "7.13.0"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "7.13.0"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "7.13.0"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.11.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-7.7.4-b0.jar",
          "url": "core-ng-search-test-7.7.4-b0.jar",
          "size": 9068,
          "sha512": "dee722532a1d263746574ea649fb9e2dc16b74d761a5424a5d1ffd5b7d38aa0e59570147e4b39dddccd6c03cfd66d2568fa126056d9519946bdd0f5d76a835b3",
          "sha256": "093aea0cf37ad74be50e5c68e710cdc0a66bbcf2e859dd754a6c1896e9c3b663",
          "sha1": "25c801c7e7a1018d9a8a152f1fdbf947d8a31084",
          "md5": "d641bbe99e25c97ca5364bbf57391b86"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-7.7.4-b0-sources.jar",
          "url": "core-ng-search-test-7.7.4-b0-sources.jar",
          "size": 5479,
          "sha512": "3cf475cdafbcde353183f3cb09de200f9fb4b9c05f7d2d3bb9e4c788bd9675b26e03e8315b2ba2eee03ad9f9cfa4d8cc8af4660d284d46c558e5f4153cebc389",
          "sha256": "3c8dc229cae832dedbf2fd187b415271472b12bc3d7d9e5ebaaae8fec2fc4650",
          "sha1": "069d69b5bf83c76a24c179ddbd9d61f7fcf58800",
          "md5": "17d61809a0f6573e79646d13057c2209"
        }
      ]
    }
  ]
}
