{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "9.4.0-b3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.4.0-b3"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.18.1"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.4.0-b3.jar",
          "url": "core-ng-search-9.4.0-b3.jar",
          "size": 56012,
          "sha512": "d94d6b541423f412d033d0bbf29b39236f5f5374e32aff2f544d056b6c9fe6b0d73f9b9fd1ef391b7fe399fbc550667373459d7603c16a9bba06d8f77d62e2f3",
          "sha256": "efe487b735a47f0324cfdd2efa57daf795a4885f0d4eccfb88ef3aeab2b3e49c",
          "sha1": "bddd718e7bbed7b177c7acc910887af4aa1f1fea",
          "md5": "569170d14eee2def6fb9067328309f02"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.4.0-b3"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.18.1"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.4.0-b3.jar",
          "url": "core-ng-search-9.4.0-b3.jar",
          "size": 56012,
          "sha512": "d94d6b541423f412d033d0bbf29b39236f5f5374e32aff2f544d056b6c9fe6b0d73f9b9fd1ef391b7fe399fbc550667373459d7603c16a9bba06d8f77d62e2f3",
          "sha256": "efe487b735a47f0324cfdd2efa57daf795a4885f0d4eccfb88ef3aeab2b3e49c",
          "sha1": "bddd718e7bbed7b177c7acc910887af4aa1f1fea",
          "md5": "569170d14eee2def6fb9067328309f02"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-9.4.0-b3-sources.jar",
          "url": "core-ng-search-9.4.0-b3-sources.jar",
          "size": 23530,
          "sha512": "4dfefa0e8a1f90b1f019263a3095021149bc8921cd14dd70566b83f176526d9fbd5575b2f331389564bb445c8677459d015fd870829e66568e53eb5c087f2b6d",
          "sha256": "0e6c58abad9f39c182af6cdf802d68e60aa0bbe9a526eacf3c4660035b8feba4",
          "sha1": "de861bc21a8f0c3e97baad2d140f1076deb8c0ec",
          "md5": "375eecf8251084ea8429d76ab001ad7f"
        }
      ]
    }
  ]
}
