{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "9.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.5.0.jar",
          "url": "core-ng-mongo-test-9.5.0.jar",
          "size": 2939,
          "sha512": "40f3f0487b0bdfc8ee84f08fb8f0db553c008e1aaf01f925ab7429a18902b0954a786af76883b2a77298b576f49d52440d3e9e16a915482583fe1ab8d97eacee",
          "sha256": "41393980b28a1d4039850523003f556234f1f68fbc4b6b74e7ca4735470927cb",
          "sha1": "d59c8b61fd8acd86b076a3ac5aaddf5de573b5fc",
          "md5": "0f9d88e7eceeceec3332e19e7d8e234e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.5.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "9.5.0"
          }
        },
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.47.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-9.5.0.jar",
          "url": "core-ng-mongo-test-9.5.0.jar",
          "size": 2939,
          "sha512": "40f3f0487b0bdfc8ee84f08fb8f0db553c008e1aaf01f925ab7429a18902b0954a786af76883b2a77298b576f49d52440d3e9e16a915482583fe1ab8d97eacee",
          "sha256": "41393980b28a1d4039850523003f556234f1f68fbc4b6b74e7ca4735470927cb",
          "sha1": "d59c8b61fd8acd86b076a3ac5aaddf5de573b5fc",
          "md5": "0f9d88e7eceeceec3332e19e7d8e234e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-9.5.0-sources.jar",
          "url": "core-ng-mongo-test-9.5.0-sources.jar",
          "size": 2078,
          "sha512": "8b02cec169e9a99f9913399192c4347bbc338812c6d06651f2a6fb7e1a5bf1ef238564563ff2e6fa0b9912d537eae76ceaae76fe09f208988f56419dea149e93",
          "sha256": "fe8a945b94508d3669768611f96cbb5c7fd093841ba60f00ecbe45a9ac26fed9",
          "sha1": "b619774dcd3589d5c1b963f09b2ca0796eb8eb4d",
          "md5": "5f395cbe6b8164a993d246107fc1d9ce"
        }
      ]
    }
  ]
}
