{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "9.5.1-b2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.5.1-b2"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "9.3.2"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            },
            {
              "group": "io.opentelemetry.semconv",
              "module": "*"
            },
            {
              "group": "com.fasterxml.jackson.core",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.5.1-b2.jar",
          "url": "core-ng-search-9.5.1-b2.jar",
          "size": 58056,
          "sha512": "cdebb3dfe56d7baa033a27ddad018d3af9019f713eb92744b1604763c558ad142115af1df3b6702f0f3634a2f9e30016a0f2240b635cd56ab00f8f141238d663",
          "sha256": "0eba5052b6be583ae59f527281ca322982acf91e8645980a318177bdda1eb405",
          "sha1": "1a644e0986b517cc3c4175acc3756dab8a35ef77",
          "md5": "697ac63a664f68503e2ad3950bba4aea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-rest5-client",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "tools.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.5.1-b2"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "9.3.2"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            },
            {
              "group": "io.opentelemetry.semconv",
              "module": "*"
            },
            {
              "group": "com.fasterxml.jackson.core",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.5.1-b2.jar",
          "url": "core-ng-search-9.5.1-b2.jar",
          "size": 58056,
          "sha512": "cdebb3dfe56d7baa033a27ddad018d3af9019f713eb92744b1604763c558ad142115af1df3b6702f0f3634a2f9e30016a0f2240b635cd56ab00f8f141238d663",
          "sha256": "0eba5052b6be583ae59f527281ca322982acf91e8645980a318177bdda1eb405",
          "sha1": "1a644e0986b517cc3c4175acc3756dab8a35ef77",
          "md5": "697ac63a664f68503e2ad3950bba4aea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-9.5.1-b2-sources.jar",
          "url": "core-ng-search-9.5.1-b2-sources.jar",
          "size": 24211,
          "sha512": "1fc32eba4dbc33d8cb0257945b3d21ba6450f0543b6eb5713493b1228e1889d15e811b580b3090dcbf5d8105ed95238d94b322fdfeb0186bd7474f8e8a1dcae2",
          "sha256": "2ffd92a6e81eb99d583129b50b389f4b17baab3b57f27d68183bc9b720ab277b",
          "sha1": "58b9c9c29989b1530e60e1d8448b95b851e245fe",
          "md5": "00bcda2189150680615c8ed421e73df6"
        }
      ]
    }
  ]
}
