{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "7.6.16-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.6.16-b1.jar",
          "url": "core-ng-test-7.6.16-b1.jar",
          "size": 41890,
          "sha512": "cf5033532bb77f1558e60bd772630e675cefb0d1aa347e830c89bf8995354e664f84dae7a316c50ad82601af563105ff9c4de61c29d9eb127973cea8bd58361d",
          "sha256": "412c831b2e14665baf12f5a66d05bc30a7ca6adf81f5fccd422b363d9367584f",
          "sha1": "99c795b23957f40a56b3c7c2f950458138397800",
          "md5": "1fba7f7b120967b491e0ccd0ca1a90d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.16-b1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.8.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.6.16-b1.jar",
          "url": "core-ng-test-7.6.16-b1.jar",
          "size": 41890,
          "sha512": "cf5033532bb77f1558e60bd772630e675cefb0d1aa347e830c89bf8995354e664f84dae7a316c50ad82601af563105ff9c4de61c29d9eb127973cea8bd58361d",
          "sha256": "412c831b2e14665baf12f5a66d05bc30a7ca6adf81f5fccd422b363d9367584f",
          "sha1": "99c795b23957f40a56b3c7c2f950458138397800",
          "md5": "1fba7f7b120967b491e0ccd0ca1a90d4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-7.6.16-b1-sources.jar",
          "url": "core-ng-test-7.6.16-b1-sources.jar",
          "size": 20154,
          "sha512": "023ef600eb289fd7327c421f6a2b6ac9bc6b68116fd43b8dc5f5491de7e610472119e7a04650da8520576e6ddbf55b70763c47513e23c3792bcd743f5171290e",
          "sha256": "539d0096ba8c51dc46c1087190592c940e8adfbcdabea4b16109320c9b2c7796",
          "sha1": "4f041b7573e0e3abf7e7e297213d5cbfb2edf052",
          "md5": "f898253e336427aa46eff10e2e830ca1"
        }
      ]
    }
  ]
}
