{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "7.4.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "tdtmk7f34zfd5f3rflawv7b2ry"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.4.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.4.7.jar",
          "url": "core-ng-7.4.7.jar",
          "size": 619498,
          "sha512": "96cffe1dea3d2880a089deccbd68f106e1e351a76f136ae0b72a9a6be95eac9753b50c6bb3f67282ca1a4f07b4c19459bd33601cd12e45bc3cd490ce0f97d5f4",
          "sha256": "f31937f207e9fbb49698c9250ec3fbe5aa9000efb08977ca3a99ea3d4cfea283",
          "sha1": "817852443e976b4cee089f6d4d74fc6ab5467b13",
          "md5": "8392d1143c1cfcf085116cab826932a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.27.0-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.10.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.10.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.1.1.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.4.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.7.3"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.4.7"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.4.7.jar",
          "url": "core-ng-7.4.7.jar",
          "size": 619498,
          "sha512": "96cffe1dea3d2880a089deccbd68f106e1e351a76f136ae0b72a9a6be95eac9753b50c6bb3f67282ca1a4f07b4c19459bd33601cd12e45bc3cd490ce0f97d5f4",
          "sha256": "f31937f207e9fbb49698c9250ec3fbe5aa9000efb08977ca3a99ea3d4cfea283",
          "sha1": "817852443e976b4cee089f6d4d74fc6ab5467b13",
          "md5": "8392d1143c1cfcf085116cab826932a2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-7.4.7-sources.jar",
          "url": "core-ng-7.4.7-sources.jar",
          "size": 317507,
          "sha512": "1872dcee4a6e8d9c79ed3feda78b5e8493a6df0c5131d0b5dc4957daf6b6a98008e9de22782b693ffc9c269a7efa1d5d6b5dd9a8972864834312989d16025a45",
          "sha256": "3936e876375c9fa535b3a30755c03d5d52b8d558fc7f3a23be000d81cad37cac",
          "sha1": "becfc3a5f7beefe397fa83735d883a6fa452bf1d",
          "md5": "072c3705becdd2a8af4c9464ac4402a6"
        }
      ]
    }
  ]
}
