{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "9.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.20.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.4.0.jar",
          "url": "core-ng-test-9.4.0.jar",
          "size": 50952,
          "sha512": "5fae5183f41f7e8cd12e504fc2ffe513c64c68782b8fff9bcaf8ff83aaeff3f77206f6a0d5d9f8dd8d2626f629e36d5a4c9071be5780e3c77b396b2221bec0aa",
          "sha256": "3ae4aea2fbaff7f3bdb9a4ec62c9c7514a58fe251955eee3cf9c0bae1a90c874",
          "sha1": "6e8a7bb12835413ee5a37d37bcb252bba0f89524",
          "md5": "d00a8a07e6fde8ebdf5ac675fd3cb5fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.4.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.20.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.4.0.jar",
          "url": "core-ng-test-9.4.0.jar",
          "size": 50952,
          "sha512": "5fae5183f41f7e8cd12e504fc2ffe513c64c68782b8fff9bcaf8ff83aaeff3f77206f6a0d5d9f8dd8d2626f629e36d5a4c9071be5780e3c77b396b2221bec0aa",
          "sha256": "3ae4aea2fbaff7f3bdb9a4ec62c9c7514a58fe251955eee3cf9c0bae1a90c874",
          "sha1": "6e8a7bb12835413ee5a37d37bcb252bba0f89524",
          "md5": "d00a8a07e6fde8ebdf5ac675fd3cb5fe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-9.4.0-sources.jar",
          "url": "core-ng-test-9.4.0-sources.jar",
          "size": 25055,
          "sha512": "42d94c69a8020e590f87cb8e117a5bca9e8aa5d4d6bd24a8d920153c9c4336d0cb62b9066481e9ab415a048b4ee6b71f2f39ab08529d5995a60867661f2575a3",
          "sha256": "925c2055cc58bc04f75d210bc4a9a4980d484a7a3e12f7b7c878894644f84d8f",
          "sha1": "20ceadfd922b9cc7bc1572703a697aa2a5a4d5e1",
          "md5": "6e3551f6bfd60d6a77d60039f1cf8cb4"
        }
      ]
    }
  ]
}
