{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "7.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6",
      "buildId": "jdhsmwlbjvg6foywe56zxxdxk4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-7.5.6.jar",
          "url": "core-ng-api-7.5.6.jar",
          "size": 10422,
          "sha512": "25997591b2adb6fede8b287e26aeb55856744773e83945ef83770f553f25b6e15f9815baefcd497c3eaa1b24d1e26894f1045b1b895551be4da52125cd4ab71e",
          "sha256": "f4e44d90b5d6c43bb0d38c31c46b9e18c4a9b085f6ccd4fd01baceab2669d476",
          "sha1": "56f2b97249ad11b8a597499597c40183ddd53e31",
          "md5": "7f2a31791b5688c0386646194fa15223"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.5.6.jar",
          "url": "core-ng-api-7.5.6.jar",
          "size": 10422,
          "sha512": "25997591b2adb6fede8b287e26aeb55856744773e83945ef83770f553f25b6e15f9815baefcd497c3eaa1b24d1e26894f1045b1b895551be4da52125cd4ab71e",
          "sha256": "f4e44d90b5d6c43bb0d38c31c46b9e18c4a9b085f6ccd4fd01baceab2669d476",
          "sha1": "56f2b97249ad11b8a597499597c40183ddd53e31",
          "md5": "7f2a31791b5688c0386646194fa15223"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.5.6-sources.jar",
          "url": "core-ng-api-7.5.6-sources.jar",
          "size": 8154,
          "sha512": "a35077142ec1956e6c391bf6d0cfe68b883dc0a1c1109d6df2f2c7ff00f79468a7288ffd1d7db3c67bc30fdc2c332b8d4b930c5aac8cb902b6d68300d7154cdf",
          "sha256": "b7931871b225875a8d31fa03bd8785a84a7c17508451c9047d74021bad8b3419",
          "sha1": "c8f01c29b6b05036ca0688576436197632dbfc78",
          "md5": "4c9ffe9eafdda53dae301a61cddab3ea"
        }
      ]
    }
  ]
}
