{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "9.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.3"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.1.3.jar",
          "url": "core-ng-mongo-9.1.3.jar",
          "size": 57159,
          "sha512": "8675ee1592bbe9eddf6d6348ab2dfa6739bfbe6ca9e6e61e640917f27caa3780472624a91abb346514e2300b2c3140edced85d075de8010e32384b1bb153c17f",
          "sha256": "b82b3aca57a99af4968498b04e7a37173fdfc29081685aa9fcae2d00d0942347",
          "sha1": "4d8fb52468c3ade37a09bb46188567f4466ea0e6",
          "md5": "b1bb76d43e288c86afb2f7a0c774eb7f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.3"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.1.3.jar",
          "url": "core-ng-mongo-9.1.3.jar",
          "size": 57159,
          "sha512": "8675ee1592bbe9eddf6d6348ab2dfa6739bfbe6ca9e6e61e640917f27caa3780472624a91abb346514e2300b2c3140edced85d075de8010e32384b1bb153c17f",
          "sha256": "b82b3aca57a99af4968498b04e7a37173fdfc29081685aa9fcae2d00d0942347",
          "sha1": "4d8fb52468c3ade37a09bb46188567f4466ea0e6",
          "md5": "b1bb76d43e288c86afb2f7a0c774eb7f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-9.1.3-sources.jar",
          "url": "core-ng-mongo-9.1.3-sources.jar",
          "size": 27016,
          "sha512": "b7effc1ea80b1b92a6b08058e5ffd811bb0b7c730353deadc729caf1590caa3b57705badc9fbc33b1f993e44c14bc821b9f3946c509af3aa4d384b222826c2a6",
          "sha256": "c00bd91b52883ae7ee5a796a32f0e92a64aa15e6a9e12f5c44613d30f5d3a195",
          "sha1": "4da869bad213141c6bb96d797eed1181ee51fa90",
          "md5": "c8caac1fd218a1490cb5d0e757ce19c0"
        }
      ]
    }
  ]
}
