{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "7.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "hlsm32oozncy7bet3hvrcrnjte"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.4.4"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.6.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.4.4.jar",
          "url": "core-ng-test-7.4.4.jar",
          "size": 35966,
          "sha512": "c860343ee450bffb78b62e29da8eb6c93d56bdda8d12eab5264223204a58cf64280de4cf3f88e14ff039ea678efbe3f63efaa82b1cef8e36a887a55aa73f38a9",
          "sha256": "326daeb6e2260f226ab90a0c6fe992604bce5d05188c8be6df56aef3cfa1cd2e",
          "sha1": "a2f7241d2b9c6ad8117a6d986f631172a64c1333",
          "md5": "7cc6458787992781a7ead384eb959801"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.6.2"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.4.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.4.4"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.6.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-7.4.4.jar",
          "url": "core-ng-test-7.4.4.jar",
          "size": 35966,
          "sha512": "c860343ee450bffb78b62e29da8eb6c93d56bdda8d12eab5264223204a58cf64280de4cf3f88e14ff039ea678efbe3f63efaa82b1cef8e36a887a55aa73f38a9",
          "sha256": "326daeb6e2260f226ab90a0c6fe992604bce5d05188c8be6df56aef3cfa1cd2e",
          "sha1": "a2f7241d2b9c6ad8117a6d986f631172a64c1333",
          "md5": "7cc6458787992781a7ead384eb959801"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-7.4.4-sources.jar",
          "url": "core-ng-test-7.4.4-sources.jar",
          "size": 18212,
          "sha512": "36b6f5b1ddc1d51443b71e10b8cd92560b901357fbfeef41baa3af7d671e115b16cc67c0d8cee5f9bac84e46432c8b8e8c0898bcd1e56e770aa694b57b07d14c",
          "sha256": "00cbff29f9ef21c237f50e66d679c8da53179de9dd4295f6952a61a04746a1fe",
          "sha1": "d26d7505e8d5cfe940414acd270129d5d9422c49",
          "md5": "73906ea5ae495eef35ba64812bcb01a6"
        }
      ]
    }
  ]
}
