{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.1.1.jar",
          "url": "core-ng-9.1.1.jar",
          "size": 771274,
          "sha512": "c624cc0916935cc29a3525eb5b8157edc8ff8baccf6f27a96ab72521041c1a5593e57bf866a492845795c24b8ddcee72429b6b09b765ab61b44c10b564a943e8",
          "sha256": "532c21089f15d25796469aaff505d23122236723725e3f204ca0fe603d85e935",
          "sha1": "1e18cb0f534e89d019dc81c0ae6cc4db78467b37",
          "md5": "0caf463abb70f0107115c984639e68a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "okhttp",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.10.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "3.8.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.10.5"
          }
        },
        {
          "group": "com.github.luben",
          "module": "zstd-jni",
          "version": {
            "requires": "1.5.6-4"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.1.1.jar",
          "url": "core-ng-9.1.1.jar",
          "size": 771274,
          "sha512": "c624cc0916935cc29a3525eb5b8157edc8ff8baccf6f27a96ab72521041c1a5593e57bf866a492845795c24b8ddcee72429b6b09b765ab61b44c10b564a943e8",
          "sha256": "532c21089f15d25796469aaff505d23122236723725e3f204ca0fe603d85e935",
          "sha1": "1e18cb0f534e89d019dc81c0ae6cc4db78467b37",
          "md5": "0caf463abb70f0107115c984639e68a9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.1.1-sources.jar",
          "url": "core-ng-9.1.1-sources.jar",
          "size": 394276,
          "sha512": "be7aa9b81921d379aac0003adf5cb6770128de78b9156c1a1339f57d197229ca1b38c964ef93a41a7c8a2515001e5abccca113cfb98cd54be79461c8e28ee21c",
          "sha256": "12370c57d0cfaf3e29317c1cebb7a15d95967cd151eff544fca51cfdcbcee3c7",
          "sha1": "d8785d7f49483dffc1fee626e737eeecc3a913b7",
          "md5": "f53fdf44512c608ed5d1eba80289b1b1"
        }
      ]
    }
  ]
}
