{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.5.1-b2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.5.1-b2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.5.1-b2.jar",
          "url": "core-ng-9.5.1-b2.jar",
          "size": 789769,
          "sha512": "07789c0fc99896e344a3d12090d0ab4c3f234f7e2be55195049e59af1b5a16f978315bc300c359ba19e88695fadc7cfbbb8539fdf409246f63e278b428b31a3f",
          "sha256": "f7a15bd17887458f2aac33151c66a55e9974d836efca8e94e11bfdaf1cee9e0a",
          "sha1": "6c43055dd2cd4e30dc773c0030fec37c8a92dd34",
          "md5": "4b4b54ac64dbe59e3e02b1c9835eaed8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "tools.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "tools.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.24.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "4.2.0"
          },
          "excludes": [
            {
              "group": "org.xerial.snappy",
              "module": "*"
            },
            {
              "group": "at.yawk.lz4",
              "module": "*"
            }
          ]
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.5.1-b2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.5.1-b2.jar",
          "url": "core-ng-9.5.1-b2.jar",
          "size": 789769,
          "sha512": "07789c0fc99896e344a3d12090d0ab4c3f234f7e2be55195049e59af1b5a16f978315bc300c359ba19e88695fadc7cfbbb8539fdf409246f63e278b428b31a3f",
          "sha256": "f7a15bd17887458f2aac33151c66a55e9974d836efca8e94e11bfdaf1cee9e0a",
          "sha1": "6c43055dd2cd4e30dc773c0030fec37c8a92dd34",
          "md5": "4b4b54ac64dbe59e3e02b1c9835eaed8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.5.1-b2-sources.jar",
          "url": "core-ng-9.5.1-b2-sources.jar",
          "size": 405945,
          "sha512": "cc505c4b2fd319549ef62f5e8268083dda28b30829b9e84ff7e682a269dc1d9d6026dab9a6cc1de497bb9e9c0bad1f5b9faf48ebf7f78d429f0d90b2d0e2d5da",
          "sha256": "639cd2f9e0c9f1dd4a24bc735a282a3e79003e7ca3b99bbfc039f41163154d18",
          "sha1": "ac6caa3b5c3796c379836ab7871e8e4ee3fb21a7",
          "md5": "83020b52c86f2c434ae8518d07f1c63a"
        }
      ]
    }
  ]
}
