{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "9.3.0-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-api-9.3.0-b0.jar",
          "url": "core-ng-api-9.3.0-b0.jar",
          "size": 11010,
          "sha512": "1df31a5fea66caf1d29c560910e9ac270149b3bc1788f347453282df8f4c82d5df0b908280b88f266c57cfa2c906a23488ef39127935b64a1d1e78d27b4b9097",
          "sha256": "575cd407b12943830d3303a1b1c9608a3a0be14de3f8d31f4fe8c3789ff19e8d",
          "sha1": "5da5642df97cfeb1d54fe1767d070d1d59d6c8ee",
          "md5": "81e284f78f96b745041658348c7610df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-api-9.3.0-b0.jar",
          "url": "core-ng-api-9.3.0-b0.jar",
          "size": 11010,
          "sha512": "1df31a5fea66caf1d29c560910e9ac270149b3bc1788f347453282df8f4c82d5df0b908280b88f266c57cfa2c906a23488ef39127935b64a1d1e78d27b4b9097",
          "sha256": "575cd407b12943830d3303a1b1c9608a3a0be14de3f8d31f4fe8c3789ff19e8d",
          "sha1": "5da5642df97cfeb1d54fe1767d070d1d59d6c8ee",
          "md5": "81e284f78f96b745041658348c7610df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.3.0-b0-sources.jar",
          "url": "core-ng-api-9.3.0-b0-sources.jar",
          "size": 8662,
          "sha512": "8fe2e819a9c46233d28c6584dcb628273ef8b0aae497b860df95c930124040b9fb3b37a50359eb2408e521cc3965b7737418055e2661ac8519b624bf5565ba04",
          "sha256": "fee206c2047d02c1744d3fc6f6f0a072ded7dfac2534bf8c7c3565f9c9830f21",
          "sha1": "369dcc950fe1fc322220a607c046c49f75e53aad",
          "md5": "c0bf7248eb0f04cc9fa33ad83bb60e81"
        }
      ]
    }
  ]
}
