{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.4.0-b2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.4.0-b2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.4.0-b2.jar",
          "url": "core-ng-9.4.0-b2.jar",
          "size": 788928,
          "sha512": "9dc8b7d2c517a3eb8a8a4787ed50e1c2a8cc55b8ed930fdc5ec0ab373b8a803f883f38b17cd49722806003a48f281154c2ca7b1884ba18cbf8b0287e57fddd3e",
          "sha256": "ddae76bdff5491b33a01b2cbc15c2a2b44f54d3baa0a872569e8cd52a277ffd8",
          "sha1": "deb3f63404e7dabadfd9e5a0a5e13cd1e0ba11e5",
          "md5": "c45e3f9bcac960133391be0656cb703e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.22.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "4.1.1"
          },
          "excludes": [
            {
              "group": "org.xerial.snappy",
              "module": "*"
            },
            {
              "group": "org.lz4",
              "module": "*"
            }
          ]
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.4.0-b2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.4.0-b2.jar",
          "url": "core-ng-9.4.0-b2.jar",
          "size": 788928,
          "sha512": "9dc8b7d2c517a3eb8a8a4787ed50e1c2a8cc55b8ed930fdc5ec0ab373b8a803f883f38b17cd49722806003a48f281154c2ca7b1884ba18cbf8b0287e57fddd3e",
          "sha256": "ddae76bdff5491b33a01b2cbc15c2a2b44f54d3baa0a872569e8cd52a277ffd8",
          "sha1": "deb3f63404e7dabadfd9e5a0a5e13cd1e0ba11e5",
          "md5": "c45e3f9bcac960133391be0656cb703e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.4.0-b2-sources.jar",
          "url": "core-ng-9.4.0-b2-sources.jar",
          "size": 405394,
          "sha512": "68aaa6d2f914cd5504f8657cebdbbd5a981ec4512b55513dac8461a56655bad68ca049e6aac1efea5131cfe34077631acd76286e0207c2ffbd0cc0a0babb9605",
          "sha256": "7c619aec704d6185868b73f61e0dc044d49485b38358c32418da589d17eeba0f",
          "sha1": "e2589c5e88604279767223ed57cbf91555331408",
          "md5": "d438ca0b50c77da54ceec91ebce90045"
        }
      ]
    }
  ]
}
