{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework.mysql",
    "module": "mysql-connector-j",
    "version": "8.4.0-r6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mysql-connector-j-8.4.0-r6.jar",
          "url": "mysql-connector-j-8.4.0-r6.jar",
          "size": 517177,
          "sha512": "55cd9d932d2e05c7d3ea52b5d1491beb57c8bf8d40281d55af5d5154ac85a3e18e4b201fc8be38eeafe0895ab13dd9ab6b89d478be86baf7deadbad3745cf654",
          "sha256": "ca22eb1e616ef8156798d518cb2510a01d1911741d80fae2ed4910e64c25b369",
          "sha1": "87dad03ce1785bdee0d9bc002d81b204d983b576",
          "md5": "52a71ac870cf6a2a84093612ef87d39d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mysql-connector-j-8.4.0-r6.jar",
          "url": "mysql-connector-j-8.4.0-r6.jar",
          "size": 517177,
          "sha512": "55cd9d932d2e05c7d3ea52b5d1491beb57c8bf8d40281d55af5d5154ac85a3e18e4b201fc8be38eeafe0895ab13dd9ab6b89d478be86baf7deadbad3745cf654",
          "sha256": "ca22eb1e616ef8156798d518cb2510a01d1911741d80fae2ed4910e64c25b369",
          "sha1": "87dad03ce1785bdee0d9bc002d81b204d983b576",
          "md5": "52a71ac870cf6a2a84093612ef87d39d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mysql-connector-j-8.4.0-r6-sources.jar",
          "url": "mysql-connector-j-8.4.0-r6-sources.jar",
          "size": 520205,
          "sha512": "daf83b062935e99387e3169155d42261ffacbedf6c9a8e82dd177c6d549c4634c4496f0a884886afb0b1e98240109811916d4bde310eae472307a5647eb7b23a",
          "sha256": "acc004948664a8064cd34497b0d44167874d3aa94da2a78f87f0393fbcb16f03",
          "sha1": "34992da84a34de422f656c8fa40318981a0a1814",
          "md5": "cf26c1da8ebc0eb5fddd4ca8cffd0e9e"
        }
      ]
    }
  ]
}
