{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.1.7-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.7-b0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.1.7-b0.jar",
          "url": "core-ng-9.1.7-b0.jar",
          "size": 775440,
          "sha512": "5899eabb057147695dedaa4ce507592c7717f44c3086df4866b39194fba3e1d3cd59b9eb62588aa1d6b739e160ea923151a6266e636c0bb1e0fc484c8c9f9abd",
          "sha256": "52cd8249227c193212210bc3a5baf6ee26e9712834876476b72904382e224d2d",
          "sha1": "6892c521fb21173406e8959214c37ec17e786e37",
          "md5": "cf2490de35763e3c00e61b67d29f083d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "okhttp",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.7-b0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.1.7-b0.jar",
          "url": "core-ng-9.1.7-b0.jar",
          "size": 775440,
          "sha512": "5899eabb057147695dedaa4ce507592c7717f44c3086df4866b39194fba3e1d3cd59b9eb62588aa1d6b739e160ea923151a6266e636c0bb1e0fc484c8c9f9abd",
          "sha256": "52cd8249227c193212210bc3a5baf6ee26e9712834876476b72904382e224d2d",
          "sha1": "6892c521fb21173406e8959214c37ec17e786e37",
          "md5": "cf2490de35763e3c00e61b67d29f083d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.1.7-b0-sources.jar",
          "url": "core-ng-9.1.7-b0-sources.jar",
          "size": 396241,
          "sha512": "a766778b09376a7686fa19df6b40f7a512533800b9bacb3053e90b2a3cddeb6a0adcb7ed3d0ad32a02a90bd10c0c61180bb01263020977740f6d546193cab104",
          "sha256": "9d2ff392dd0245c9634b44e8c152d339c2450755885ca5bfd68c9564e44dc2af",
          "sha1": "3a79ef7df990b7fe53467e50473e39bea1d0728a",
          "md5": "37e6a6aff33482b9ab383b486a8430eb"
        }
      ]
    }
  ]
}
