{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "7.6.5-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "ccyvjnb7orff5dpf6eczxv6e7a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-7.6.5-b1.jar",
          "url": "core-ng-api-7.6.5-b1.jar",
          "size": 10433,
          "sha512": "d3525641b51793224a84bfaf0c025c2f7d0d3ab49d92ac488008854bedd03ab851e9501b61d0510e96d527830a7ed55aa1ef15adc9719962b461090785201cfe",
          "sha256": "dcdf938d8b4fd79f9e67a437bd2d530fd288fa8c9106b4b5ec1c6ca1b1a307a5",
          "sha1": "190b7b5399278eae484c3582ba99bf4563a38a19",
          "md5": "779777115de184dd8717f3e7e43ced1a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.6.5-b1.jar",
          "url": "core-ng-api-7.6.5-b1.jar",
          "size": 10433,
          "sha512": "d3525641b51793224a84bfaf0c025c2f7d0d3ab49d92ac488008854bedd03ab851e9501b61d0510e96d527830a7ed55aa1ef15adc9719962b461090785201cfe",
          "sha256": "dcdf938d8b4fd79f9e67a437bd2d530fd288fa8c9106b4b5ec1c6ca1b1a307a5",
          "sha1": "190b7b5399278eae484c3582ba99bf4563a38a19",
          "md5": "779777115de184dd8717f3e7e43ced1a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.6.5-b1-sources.jar",
          "url": "core-ng-api-7.6.5-b1-sources.jar",
          "size": 8156,
          "sha512": "4ce6d96d02d82da02dec42b3ee752d80b3705b07da35145cb5228dbb50f80e3d1e2d704538a65f2255dfe3b42b5ef682e5d783ff068d41d84c57d0bdf6b1e980",
          "sha256": "3185be29b86556630e67725affb85ff76d52511f88a29898db2a2f41e04d175e",
          "sha1": "5391ab6f283e685b300a1ad9cf397a7f37173cc6",
          "md5": "8d9da01a3ec649e244f8b8a504b4ebb0"
        }
      ]
    }
  ]
}
