{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "7.6.5-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "xfkirao6brgntg7bbsmeiie7me"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-7.6.5-b1.jar",
          "url": "core-ng-api-7.6.5-b1.jar",
          "size": 10433,
          "sha512": "c9b987ca315b325e1188ad351e4485e8a5da1a881bce45480d61b0643ff35d6e11d34801e5504ef2f122d445309079ffc64df65e8f2609fb09b57bb3de6fcbbc",
          "sha256": "3b4715d0d2b9114f0cfa7600cb9e765f1b71f8fc82ef935e4c4c3e814541c985",
          "sha1": "d6373c2d7b1c72af93b9dfb3666e7af1fabaee6e",
          "md5": "91fe10f1ff95d9b095b2a64ed3b8d46a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.6.5-b1.jar",
          "url": "core-ng-api-7.6.5-b1.jar",
          "size": 10433,
          "sha512": "c9b987ca315b325e1188ad351e4485e8a5da1a881bce45480d61b0643ff35d6e11d34801e5504ef2f122d445309079ffc64df65e8f2609fb09b57bb3de6fcbbc",
          "sha256": "3b4715d0d2b9114f0cfa7600cb9e765f1b71f8fc82ef935e4c4c3e814541c985",
          "sha1": "d6373c2d7b1c72af93b9dfb3666e7af1fabaee6e",
          "md5": "91fe10f1ff95d9b095b2a64ed3b8d46a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.6.5-b1-sources.jar",
          "url": "core-ng-api-7.6.5-b1-sources.jar",
          "size": 8156,
          "sha512": "fe7c334dcf7d766103d08093e1a495152b0d17df669870cab6060cb9d49ba034b1cf0ec75ebdacfb0a02bb256f4b4612308eecc761908872b8e316fdc9643f25",
          "sha256": "cf2066da396521c84320f19e87d88f09e0e4d7faba3ed5a9d0567c66af704c5a",
          "sha1": "7938e2b1060969c0d98031f929d1a67afa0fd2ef",
          "md5": "a840ff3c3aab7322f6536a5e1884a3a4"
        }
      ]
    }
  ]
}
