{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "7.6.4-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "d4bpwwgkvbhk5k3pu7mvcd3od4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-7.6.4-b0.jar",
          "url": "core-ng-api-7.6.4-b0.jar",
          "size": 10433,
          "sha512": "8f06bb678c6d8689c95cb814c9deb7284fb55e52922ed9175454f03a247a7d43f9395d0c1d7eea9c425a9001f3e558a92a786b4f6e148282b211811f42adf78d",
          "sha256": "be589c03504f8b46176e241049743f0587eb4782e42ea4bfaa1afcf76881fcf7",
          "sha1": "5ee3efeae3dc3ce58e5f0232ba1396f4f2b0ce20",
          "md5": "d6a3954940fe8dfe92230f0e7c0eadf0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.6.4-b0.jar",
          "url": "core-ng-api-7.6.4-b0.jar",
          "size": 10433,
          "sha512": "8f06bb678c6d8689c95cb814c9deb7284fb55e52922ed9175454f03a247a7d43f9395d0c1d7eea9c425a9001f3e558a92a786b4f6e148282b211811f42adf78d",
          "sha256": "be589c03504f8b46176e241049743f0587eb4782e42ea4bfaa1afcf76881fcf7",
          "sha1": "5ee3efeae3dc3ce58e5f0232ba1396f4f2b0ce20",
          "md5": "d6a3954940fe8dfe92230f0e7c0eadf0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-7.6.4-b0-sources.jar",
          "url": "core-ng-api-7.6.4-b0-sources.jar",
          "size": 8156,
          "sha512": "f461e0aa2d3ba8b09f83d28ed99e3ee911ec488d0bb11db8f9ef09abe634ceae84e4e5a7c6760dd8c45f00345a6d838322e5e0ad8ce0e25be2b0d9c537927528",
          "sha256": "abe7ed6e283eb87b1df8ff8a05a96055408cd5e8eed6893b1001dfb9f5d64a3b",
          "sha1": "a49a6cb06cf45322c0ece3f1a95d07394d13173f",
          "md5": "2455ff4e34829f566db0d923a795de2c"
        }
      ]
    }
  ]
}
