{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "9.5.1-b5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.5.1-b5"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.5.1-b5.jar",
          "url": "core-ng-mongo-9.5.1-b5.jar",
          "size": 60079,
          "sha512": "54aba825565aef9d3610f6f10a2e73ef5eaedaafa81c4ced370a71e41c29751e3b9ed059dcea30b6dd1b559d21b5dacfab8e5706fcb0b65fea55b9a1539fa46b",
          "sha256": "58931c75db65afe7353e14523e5763b6a4306ff3d50504b088b5858591d8f96e",
          "sha1": "d21f01c4b540139078b5698933386a4867d215dc",
          "md5": "eedeba69945220d96428ce20c57e65d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.5.1-b5"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.5.1-b5.jar",
          "url": "core-ng-mongo-9.5.1-b5.jar",
          "size": 60079,
          "sha512": "54aba825565aef9d3610f6f10a2e73ef5eaedaafa81c4ced370a71e41c29751e3b9ed059dcea30b6dd1b559d21b5dacfab8e5706fcb0b65fea55b9a1539fa46b",
          "sha256": "58931c75db65afe7353e14523e5763b6a4306ff3d50504b088b5858591d8f96e",
          "sha1": "d21f01c4b540139078b5698933386a4867d215dc",
          "md5": "eedeba69945220d96428ce20c57e65d7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-9.5.1-b5-sources.jar",
          "url": "core-ng-mongo-9.5.1-b5-sources.jar",
          "size": 28818,
          "sha512": "88ce7945fd5ca3104c72159f484236fa84ae17977aebcad46e10b7d1393de1fb4628d530913ad8d7e83995f5170344d04e4f69a693712c0d660b77a8b20c2025",
          "sha256": "94cfe390a190e160293249ec506e8b17b31b343fb013193abe04fd9bbd6acd70",
          "sha1": "e659c5c3efd8229916aaf76dfaac31f70a23a00d",
          "md5": "64745300ae66c08dde6aac5f924226b8"
        }
      ]
    }
  ]
}
