{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "7.4.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "kbxxkdn4jfcxdkqpqnxwgkaiym"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.4.13"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.4.13.jar",
          "url": "core-ng-7.4.13.jar",
          "size": 639355,
          "sha512": "d2e4b0123b79a9c376ae1fe4b69b9fc964456318879dc3502c0d16013bc945dd0191e5d30e229d0d85e6d891f92c8edae3cb74eb7793937b1005320fc5973d7b",
          "sha256": "1fdc9ffb49568f9a60bfa0fce2d53719f7fd538367e15ea33540d663a833b9d8",
          "sha1": "7b915da1d423748a13e78a4506e069bfdad0ddc3",
          "md5": "ed42bb1aff3064a35c64485e6aa51605"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.27.0-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.10.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.10.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.1.3.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.4.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.7.5"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.4.13"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.4.13.jar",
          "url": "core-ng-7.4.13.jar",
          "size": 639355,
          "sha512": "d2e4b0123b79a9c376ae1fe4b69b9fc964456318879dc3502c0d16013bc945dd0191e5d30e229d0d85e6d891f92c8edae3cb74eb7793937b1005320fc5973d7b",
          "sha256": "1fdc9ffb49568f9a60bfa0fce2d53719f7fd538367e15ea33540d663a833b9d8",
          "sha1": "7b915da1d423748a13e78a4506e069bfdad0ddc3",
          "md5": "ed42bb1aff3064a35c64485e6aa51605"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-7.4.13-sources.jar",
          "url": "core-ng-7.4.13-sources.jar",
          "size": 327557,
          "sha512": "e2ee96db85eb5f16ffd3e8202b97f9a01003a8156be6c4981db2505f2a1fefbcee239b95f34785e2eece5df53455206f87afa99f5b4d0fdf0ff0ec8e7cf0329d",
          "sha256": "7d20aeba32028f4744b94b176419b5fef8b6f3b54d3db43ae3d07f5b5a2318a1",
          "sha1": "1b964e2e82b08926fdfbaf3f9739d6f0cb8b8af9",
          "md5": "a3e225e99c30b957b300b643d0f24828"
        }
      ]
    }
  ]
}
