{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "9.1.7-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.7-b1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.1.7-b1.jar",
          "url": "core-ng-9.1.7-b1.jar",
          "size": 776687,
          "sha512": "ef9fffaaae587809d215140ca109855193b61bfca0ba36affe6a2440f3235b8b2981eae5320a4075fc09ad50fced48f93cc68ff5c418481590e2b3740545016a",
          "sha256": "61fb94462cb7197563ac4c3239ba2d85ac7d33fa43ec02326638a24f145bf1fd",
          "sha1": "366484b21db96c2ec2b01f3227ed9bd0585a63f9",
          "md5": "1704e3ad95bf919e15938aa990c1f3cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "okhttp",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.18.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "9.1.7-b1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-9.1.7-b1.jar",
          "url": "core-ng-9.1.7-b1.jar",
          "size": 776687,
          "sha512": "ef9fffaaae587809d215140ca109855193b61bfca0ba36affe6a2440f3235b8b2981eae5320a4075fc09ad50fced48f93cc68ff5c418481590e2b3740545016a",
          "sha256": "61fb94462cb7197563ac4c3239ba2d85ac7d33fa43ec02326638a24f145bf1fd",
          "sha1": "366484b21db96c2ec2b01f3227ed9bd0585a63f9",
          "md5": "1704e3ad95bf919e15938aa990c1f3cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-9.1.7-b1-sources.jar",
          "url": "core-ng-9.1.7-b1-sources.jar",
          "size": 396672,
          "sha512": "a5ed0f86366426adb2f166e12e142b193f7ab16463dd12c11b4c306556e27ed946bc8268550bcaf58a77b8f8853eeb1dafe3905908cb5ca15bd802d4e5167c68",
          "sha256": "9d99ce659c3a3bf797b1b1b53125f402bfcfa4041b68ec05ce854e31fbccbc2f",
          "sha1": "f32a0eecd8c95b6ff14571a3ce1c54b486b08062",
          "md5": "d4d651699b3da9beb442481e020678ff"
        }
      ]
    }
  ]
}
