{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "9.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.5.2"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.5.2.jar",
          "url": "core-ng-mongo-9.5.2.jar",
          "size": 60076,
          "sha512": "916f97e513beb701eea34c83c77759afeef83bda6ed969f43391407df255ac19badb2731db20b3d3963b00c85a2094590904e23c3f72abc44a870a9efd33fad1",
          "sha256": "140255022db2f4f83c38fb6d7880b7798df15b5c663c29bc4906c907b6532574",
          "sha1": "2540a5ebead69a86a90b09df1db333e54cb4c68b",
          "md5": "33b4fa21801ceeb2a7e0c1f55a5faf1c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.5.2"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "5.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.5.2.jar",
          "url": "core-ng-mongo-9.5.2.jar",
          "size": 60076,
          "sha512": "916f97e513beb701eea34c83c77759afeef83bda6ed969f43391407df255ac19badb2731db20b3d3963b00c85a2094590904e23c3f72abc44a870a9efd33fad1",
          "sha256": "140255022db2f4f83c38fb6d7880b7798df15b5c663c29bc4906c907b6532574",
          "sha1": "2540a5ebead69a86a90b09df1db333e54cb4c68b",
          "md5": "33b4fa21801ceeb2a7e0c1f55a5faf1c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-9.5.2-sources.jar",
          "url": "core-ng-mongo-9.5.2-sources.jar",
          "size": 28815,
          "sha512": "9ed818a22751dc41c68eb47ec7728937dcf47ab1fa24f712401d30183ef1ebd173c073e2f1b4985213b4cb1a3041fcd8d662250cb350bbd3d92659dc0880f259",
          "sha256": "a5bdba9c6d4b9621243e8099206a79fb5ab9226139ec1f5f1fbcb3c67d77095a",
          "sha1": "3c6d5fc33c91976160164f4fe64b73074fd7aaae",
          "md5": "cd6a79c357d502b8bf3a88f9a2cfa145"
        }
      ]
    }
  ]
}
