{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo-test",
    "version": "7.4.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4.1",
      "buildId": "tu5zh2lsu5chpeteqmpc5tiek4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.4.8"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "7.4.8"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-7.4.8.jar",
          "url": "core-ng-mongo-test-7.4.8.jar",
          "size": 2412,
          "sha512": "c2e073a386c7bbbcdc9d5aa35dc9560152acc2dfe1140581dcb7688f78ab4c398f04dc577678d900f181688faaf7fdb80bc97ea701985c838ff215abaa792df4",
          "sha256": "4cb34adc7761f5404333e079385aecb2a9f896c8aaf81f8991bbdfcc02091859",
          "sha1": "00d7bdc40611908036ed844cecb9dd15cec20dd6",
          "md5": "749c28304ed358fb17e32567bb80ae4f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.bwaldvogel",
          "module": "mongo-java-server",
          "version": {
            "requires": "1.28.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "7.4.8"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-mongo",
          "version": {
            "requires": "7.4.8"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-test-7.4.8.jar",
          "url": "core-ng-mongo-test-7.4.8.jar",
          "size": 2412,
          "sha512": "c2e073a386c7bbbcdc9d5aa35dc9560152acc2dfe1140581dcb7688f78ab4c398f04dc577678d900f181688faaf7fdb80bc97ea701985c838ff215abaa792df4",
          "sha256": "4cb34adc7761f5404333e079385aecb2a9f896c8aaf81f8991bbdfcc02091859",
          "sha1": "00d7bdc40611908036ed844cecb9dd15cec20dd6",
          "md5": "749c28304ed358fb17e32567bb80ae4f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-test-7.4.8-sources.jar",
          "url": "core-ng-mongo-test-7.4.8-sources.jar",
          "size": 1750,
          "sha512": "f1a8b68f031ce2f29a154b4e0ed6ce17efa6de7488663f8121954c1ec1b60a71cbef4568af09d541e0190d160f3b8d0638573328e2dea92352c47341f3fc48d4",
          "sha256": "07b3663a088ab33f0a1f2dce09baf0bd682d461cdcba5d1f5c88c164c61b1660",
          "sha1": "f568e27ea4be575be1ed29960c4ea209e3109530",
          "md5": "c79b78b1dfbb3f118578c94a7705e398"
        }
      ]
    }
  ]
}
