{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "9.5.1-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.5.1-b0"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "9.3.2"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            },
            {
              "group": "io.opentelemetry.semconv",
              "module": "*"
            },
            {
              "group": "com.fasterxml.jackson.core",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.5.1-b0.jar",
          "url": "core-ng-search-9.5.1-b0.jar",
          "size": 57899,
          "sha512": "6f4e7bc4f5cb8ec889a079539abb40696251042756f89da5fe8d4753d222058c417276af4d89222642fe339c11ef3d5249538c1c953b1599e1e0da1381d160e6",
          "sha256": "4eb875bfc7d21f31633fbe22d122bd30474a05273614a3a81f920a1798d7369a",
          "sha1": "f11e0d6db8ca5084515dd14fd4ba7284a70c00c6",
          "md5": "58052154de81a650cde05e82bfca46ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-rest5-client",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "tools.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.5.1-b0"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "9.3.2"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            },
            {
              "group": "io.opentelemetry.semconv",
              "module": "*"
            },
            {
              "group": "com.fasterxml.jackson.core",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.5.1-b0.jar",
          "url": "core-ng-search-9.5.1-b0.jar",
          "size": 57899,
          "sha512": "6f4e7bc4f5cb8ec889a079539abb40696251042756f89da5fe8d4753d222058c417276af4d89222642fe339c11ef3d5249538c1c953b1599e1e0da1381d160e6",
          "sha256": "4eb875bfc7d21f31633fbe22d122bd30474a05273614a3a81f920a1798d7369a",
          "sha1": "f11e0d6db8ca5084515dd14fd4ba7284a70c00c6",
          "md5": "58052154de81a650cde05e82bfca46ec"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-9.5.1-b0-sources.jar",
          "url": "core-ng-search-9.5.1-b0-sources.jar",
          "size": 24155,
          "sha512": "6f87837abe55649c3038e11a218197e05206765c3adc049307bc05b2d0efa5b3d53ec9df5fea883a6d99f6d7e7ba951f26b6bdd8a282ff1183ade8bd09ba51e6",
          "sha256": "2efb88b4a33b0ba9d8947a701d8ea32e991796280f21ca96d8c5f365bbaf0161",
          "sha1": "9a8ea4600f6f599fd5401d0fc5a783d562f0b6ec",
          "md5": "579e161c4c5f282373d6c86cd6d40652"
        }
      ]
    }
  ]
}
