{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "9.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.4.0.jar",
          "url": "core-ng-search-test-9.4.0.jar",
          "size": 10070,
          "sha512": "dc118e847331c8449dd3d0c1759476e62e7e54adbb9d7f58d785e3709c61417d2cbfb3156f24ed30626f83a63709f1a754234fe950ee4e0cb6e2c18023354caf",
          "sha256": "0b6324e58615666a4ef5647fd2935951149a00a1fa0db319e0be3ba9472daf76",
          "sha1": "e73a685b996a74730b85e412fdc9afeee745426c",
          "md5": "f59e874dce083164e116e9194eb0c53a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.4.0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "9.4.0"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "8.18.1"
          },
          "excludes": [
            {
              "group": "io.opentelemetry",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "core.framework.elasticsearch.module",
          "module": "reindex",
          "version": {
            "requires": "8.18.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-9.4.0.jar",
          "url": "core-ng-search-test-9.4.0.jar",
          "size": 10070,
          "sha512": "dc118e847331c8449dd3d0c1759476e62e7e54adbb9d7f58d785e3709c61417d2cbfb3156f24ed30626f83a63709f1a754234fe950ee4e0cb6e2c18023354caf",
          "sha256": "0b6324e58615666a4ef5647fd2935951149a00a1fa0db319e0be3ba9472daf76",
          "sha1": "e73a685b996a74730b85e412fdc9afeee745426c",
          "md5": "f59e874dce083164e116e9194eb0c53a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.4.0-sources.jar",
          "url": "core-ng-search-test-9.4.0-sources.jar",
          "size": 6285,
          "sha512": "fa9d87581a55caeab4036ad4d0c0d0bc93f7984165aa2590453f0bbbc42bb4d9dea81d5ae1e9608d9230476b6389b15abff9b52d2657e63de0159c98a02569a0",
          "sha256": "2c67b940491718b33506a3fe73742cf616498e44dbae953c57a3080a709f10d3",
          "sha1": "57726eb6c85dc767fe1f702d0002f0a6995ca2fc",
          "md5": "6617bf32285ef21a7f37ad398797aa74"
        }
      ]
    }
  ]
}
