{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "7.7.4-b1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.7.4-b1"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "7.13.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "elasticsearch",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch-x-content",
          "version": {
            "requires": "7.13.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "elasticsearch-x-content",
              "type": "jar",
              "extension": "jar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.7.4-b1.jar",
          "url": "core-ng-search-7.7.4-b1.jar",
          "size": 38915,
          "sha512": "903e08865b0323dc437875498bffd2bccf027ccfc869babec3f5ae1f4ae650c306134d03a729d5b7266222e05dc7dc6ecdd174e59b18c4e945d91f3a0d3f92d8",
          "sha256": "3141d31ab70f4103a1c4fe5b5b3e2030e7a899fed10031c432f612f34672ceed",
          "sha1": "456f4ccad42fc55cc63d3713ecef27e3a4aff437",
          "md5": "e5ac595b8b0f9071ce3127c8cecf5cf6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.elasticsearch.client",
          "module": "elasticsearch-rest-high-level-client",
          "version": {
            "requires": "7.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.3"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.7.4-b1"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "7.13.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "elasticsearch",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch-x-content",
          "version": {
            "requires": "7.13.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "elasticsearch-x-content",
              "type": "jar",
              "extension": "jar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.7.4-b1.jar",
          "url": "core-ng-search-7.7.4-b1.jar",
          "size": 38915,
          "sha512": "903e08865b0323dc437875498bffd2bccf027ccfc869babec3f5ae1f4ae650c306134d03a729d5b7266222e05dc7dc6ecdd174e59b18c4e945d91f3a0d3f92d8",
          "sha256": "3141d31ab70f4103a1c4fe5b5b3e2030e7a899fed10031c432f612f34672ceed",
          "sha1": "456f4ccad42fc55cc63d3713ecef27e3a4aff437",
          "md5": "e5ac595b8b0f9071ce3127c8cecf5cf6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-7.7.4-b1-sources.jar",
          "url": "core-ng-search-7.7.4-b1-sources.jar",
          "size": 17510,
          "sha512": "6cab1518c878de969f354e65aae6910cb18a956a4b6b176abd5745d3045ea224953bec57f535df1d0ba4c509d056fa5761c889dab3139195c5e64ab445fd9ee3",
          "sha256": "cc21f08b08630474f72c4fde09b0f76dbf2da0d356bfa5eaf0f386433e4fe4e4",
          "sha1": "e285a3573b7b7adefb921fade417365d0475c74f",
          "md5": "bdd42efd8cf8f3b50134c93344854589"
        }
      ]
    }
  ]
}
