{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "9.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.3"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.1.3.jar",
          "url": "core-ng-search-9.1.3.jar",
          "size": 54147,
          "sha512": "b1413a147194621a78967040b6cc5e2fbeedd1e70f2cd212b053d4e75cf84a559d121d5b6501168adde1d6e4a1e667f682fdaebf2ea947687a826cf4af62e0c8",
          "sha256": "541e1d8f935cd61f64ad9d6ae231313d204254f1246da07c592fdf107484ab04",
          "sha1": "6f1242088ad967d0003b4725c0c920da3f716287",
          "md5": "0cc3700548ec7ee1460857177eb5301d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.1.3"
          }
        },
        {
          "group": "co.elastic.clients",
          "module": "elasticsearch-java",
          "version": {
            "requires": "8.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-9.1.3.jar",
          "url": "core-ng-search-9.1.3.jar",
          "size": 54147,
          "sha512": "b1413a147194621a78967040b6cc5e2fbeedd1e70f2cd212b053d4e75cf84a559d121d5b6501168adde1d6e4a1e667f682fdaebf2ea947687a826cf4af62e0c8",
          "sha256": "541e1d8f935cd61f64ad9d6ae231313d204254f1246da07c592fdf107484ab04",
          "sha1": "6f1242088ad967d0003b4725c0c920da3f716287",
          "md5": "0cc3700548ec7ee1460857177eb5301d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-9.1.3-sources.jar",
          "url": "core-ng-search-9.1.3-sources.jar",
          "size": 22301,
          "sha512": "ab3997f620c97d61778b8d80ddf2281273183ddf52c06431d2039eb32f85752f29c1c8ffa441ebf0ddc1d8171ed1089a866a8425315d1997fc227edf5bb9c04e",
          "sha256": "8c84ada6b08cc3ff63f27eb77386a87d6b23ebf64364e7afde6377f7fe50f5ae",
          "sha1": "2424bd33145ae83e4753f5f69be7c4b3c20db288",
          "md5": "562c1da4d7824b4b0b7461c2cbad348b"
        }
      ]
    }
  ]
}
