{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "7.6.4-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "d4bpwwgkvbhk5k3pu7mvcd3od4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.4-b0"
          }
        },
        {
          "group": "org.elasticsearch.client",
          "module": "elasticsearch-rest-high-level-client",
          "version": {
            "requires": "7.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.6.4-b0.jar",
          "url": "core-ng-search-7.6.4-b0.jar",
          "size": 38505,
          "sha512": "0aaef611f4429b4cc55e8bcab2686038137fbb0a47190782e7715d025889bc58065a12edcd3e9cf52025963a574c173e7f13a2dba66f669e7b84d6bfbfaca8bb",
          "sha256": "4914ec6efe9765ff3a710529031055c01789ab27da1f9c3d5a95ae2e23ea0b51",
          "sha1": "3f04f45d5fdadfec5949b46bfbc8d402eae36bcb",
          "md5": "afc8af094c96fb7f968608d17b9fb4ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.6.4-b0"
          }
        },
        {
          "group": "org.elasticsearch.client",
          "module": "elasticsearch-rest-high-level-client",
          "version": {
            "requires": "7.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.6.4-b0.jar",
          "url": "core-ng-search-7.6.4-b0.jar",
          "size": 38505,
          "sha512": "0aaef611f4429b4cc55e8bcab2686038137fbb0a47190782e7715d025889bc58065a12edcd3e9cf52025963a574c173e7f13a2dba66f669e7b84d6bfbfaca8bb",
          "sha256": "4914ec6efe9765ff3a710529031055c01789ab27da1f9c3d5a95ae2e23ea0b51",
          "sha1": "3f04f45d5fdadfec5949b46bfbc8d402eae36bcb",
          "md5": "afc8af094c96fb7f968608d17b9fb4ec"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-7.6.4-b0-sources.jar",
          "url": "core-ng-search-7.6.4-b0-sources.jar",
          "size": 17331,
          "sha512": "6291b1dd243f0a93f134b2fee4f405d9f84982a78ca7bf3f80deb9eab3ad1377225c19a1af2a3d7969d7b6958ea492ba319120fd5fd4359fb0570a3a4319a8cf",
          "sha256": "b5ccabd479c6c4423c6978448ca60f6a3cd07295ecfcf782f851b6df31e49f34",
          "sha1": "a6e69e08eb5420daab5e5a77fa6dff61507ae7ca",
          "md5": "6d5061a8ac09b2a9842aeabe4e3a445d"
        }
      ]
    }
  ]
}
