{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "7.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "r2yzj2bdcnc77m277me4ku3vya"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.4.3"
          }
        },
        {
          "group": "org.elasticsearch.client",
          "module": "elasticsearch-rest-high-level-client",
          "version": {
            "requires": "7.6.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.4.3.jar",
          "url": "core-ng-search-7.4.3.jar",
          "size": 37118,
          "sha512": "8ab17b7eec1742cb180ec78ad9b8a0489ab4d78ba0d6168a1fb12b1d48ee730472c7c9b141afd06aabffd4325d8fb08ac38407ba0a8cafa38273a471b0f199d3",
          "sha256": "f4f5ee2d15dc2f0add4a19b0f604c7899ccf5a232b27a1a7d90b4bb8d4ff17e1",
          "sha1": "05c75d0882d50e5ab1b185748b4ef82be9edb57e",
          "md5": "9130482d535f775e15a79ea9926603ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.4.3"
          }
        },
        {
          "group": "org.elasticsearch.client",
          "module": "elasticsearch-rest-high-level-client",
          "version": {
            "requires": "7.6.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-smile",
          "version": {
            "requires": "2.10.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.10.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-cbor",
          "version": {
            "requires": "2.10.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.25"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.4.3.jar",
          "url": "core-ng-search-7.4.3.jar",
          "size": 37118,
          "sha512": "8ab17b7eec1742cb180ec78ad9b8a0489ab4d78ba0d6168a1fb12b1d48ee730472c7c9b141afd06aabffd4325d8fb08ac38407ba0a8cafa38273a471b0f199d3",
          "sha256": "f4f5ee2d15dc2f0add4a19b0f604c7899ccf5a232b27a1a7d90b4bb8d4ff17e1",
          "sha1": "05c75d0882d50e5ab1b185748b4ef82be9edb57e",
          "md5": "9130482d535f775e15a79ea9926603ea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-7.4.3-sources.jar",
          "url": "core-ng-search-7.4.3-sources.jar",
          "size": 16403,
          "sha512": "634174576559d30f29ca6615ca12b75303fc101dda5e3876167ef19337693fbc31daa5d86c690b0bde18e6b7dd3b57497407d82fe98b2470633f5ad0364f5fce",
          "sha256": "e2e057838475a6d2ad3226cc5ae55dbc46c8dc735cfc62db23aaa017a091ef91",
          "sha1": "8fb8466047d5985aa35167e762f12ae2d9d922f1",
          "md5": "28743de62c15d18a39d41cf92da94e05"
        }
      ]
    }
  ]
}
