{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "7.6.2-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "5jfivrnadrg73pcyjgmirgtp24"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.6.2-b0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.6.2-b0.jar",
          "url": "core-ng-7.6.2-b0.jar",
          "size": 670001,
          "sha512": "3084f0327ae07c4c7f9ed70ffe8c57adb1f9af1343e62589e80fec83da1b9a354260c0bc3de382044c1ac53ad8dcaf66d2414b3efe6d49b4e1cb2549b586a3eb",
          "sha256": "0c0d34545fc1e248331259f3031da1a1199e169b07f9b16d2f736d3df9ea44c7",
          "sha1": "5994d5d0271efbeaaca2d62f686777b4bc8db4ed",
          "md5": "e6f6b57cb9882702624dcb58c68b2b0a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.27.0-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.10.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.10.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.2.2.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.4.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.7.6"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.6.2-b0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.6.2-b0.jar",
          "url": "core-ng-7.6.2-b0.jar",
          "size": 670001,
          "sha512": "3084f0327ae07c4c7f9ed70ffe8c57adb1f9af1343e62589e80fec83da1b9a354260c0bc3de382044c1ac53ad8dcaf66d2414b3efe6d49b4e1cb2549b586a3eb",
          "sha256": "0c0d34545fc1e248331259f3031da1a1199e169b07f9b16d2f736d3df9ea44c7",
          "sha1": "5994d5d0271efbeaaca2d62f686777b4bc8db4ed",
          "md5": "e6f6b57cb9882702624dcb58c68b2b0a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-7.6.2-b0-sources.jar",
          "url": "core-ng-7.6.2-b0-sources.jar",
          "size": 341885,
          "sha512": "4c9c714bf29174abdfd15a0f77243615fff35dbd9405af8274ae621326e2b3f545253809dbc397fa35a31775ea165ddcbde6fa6a1b8e864b331c00bc806bd4fe",
          "sha256": "66c6e9c7269bab128b8ca85c9be4478d1363c29ec3015ab4b495545922eb3742",
          "sha1": "3801f7d19934c6e851d8e0f15b2cf890c3ca04cd",
          "md5": "b6dbdfcf72572db4cc72013d09369390"
        }
      ]
    }
  ]
}
