{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng",
    "version": "7.6.2-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "xd54h2egmrab5k7pkkb7oigyyq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.6.2-b0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.6.2-b0.jar",
          "url": "core-ng-7.6.2-b0.jar",
          "size": 670001,
          "sha512": "b829b771557d28c0ec8801c8928453a106a8ae64a97e53cbb8babc73fa4721462ead4d0d52ced26ff8a72e5e9d1383fd6969875634732d575270e88a0f3713b2",
          "sha256": "3f297994c72b4aeb27358880b068133ad81a81ec30b99912a1ae35d6585d3c80",
          "sha1": "23d769ee9aed576250303ab9ada776032bb0e329",
          "md5": "923e5cbcd0bbdcc4ec24a5ceeaa076c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.27.0-GA"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.10.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.10.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.2.2.Final"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "2.4.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "kafka-clients",
              "type": "jar",
              "extension": "jar"
            }
          }
        },
        {
          "group": "org.xerial.snappy",
          "module": "snappy-java",
          "version": {
            "requires": "1.1.7.6"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-api",
          "version": {
            "requires": "7.6.2-b0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.8.0-beta4"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-7.6.2-b0.jar",
          "url": "core-ng-7.6.2-b0.jar",
          "size": 670001,
          "sha512": "b829b771557d28c0ec8801c8928453a106a8ae64a97e53cbb8babc73fa4721462ead4d0d52ced26ff8a72e5e9d1383fd6969875634732d575270e88a0f3713b2",
          "sha256": "3f297994c72b4aeb27358880b068133ad81a81ec30b99912a1ae35d6585d3c80",
          "sha1": "23d769ee9aed576250303ab9ada776032bb0e329",
          "md5": "923e5cbcd0bbdcc4ec24a5ceeaa076c7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-7.6.2-b0-sources.jar",
          "url": "core-ng-7.6.2-b0-sources.jar",
          "size": 341885,
          "sha512": "ec514a19c0c5d7d9b33c28a4242804fb69dff9193a6fde117a3e06a442339a3c28aa30d861c5aebbda7d6262b93a11d62d57cb6d3aeebc87c134549d72407d19",
          "sha256": "61f2d453b229c4c7d18cb8d5bffeafa0bdaf2bf5cd74c0ef5eb62395b4a75b25",
          "sha1": "1d93b968ecdf0869267b11e4ad368096474179ca",
          "md5": "84ec32adf42e1e41e7c1cf7aa1db2fa4"
        }
      ]
    }
  ]
}
