{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-test",
    "version": "9.3.0-b2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.13.4"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.20.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.3.0-b2.jar",
          "url": "core-ng-test-9.3.0-b2.jar",
          "size": 50849,
          "sha512": "c25d9584c30b9799892e821611f9b1e2eadee83cef60da7ec101c02951f28cd5356a534a883a295274ae78fecadae9366d08728c7c22be838125338e52619c52",
          "sha256": "1d8308b0a8b2ddbde7ab838546fc26b6e35ebaa26d797c8c41aa6e7e34ab0ade",
          "sha1": "20c1b89edcfd997fde87d4bcadca9b3a041fa76e",
          "md5": "1fe11dff90939821d870caaee9845e8d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.3.0-b2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.13.4"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.13.4"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.20.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.6"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-test-9.3.0-b2.jar",
          "url": "core-ng-test-9.3.0-b2.jar",
          "size": 50849,
          "sha512": "c25d9584c30b9799892e821611f9b1e2eadee83cef60da7ec101c02951f28cd5356a534a883a295274ae78fecadae9366d08728c7c22be838125338e52619c52",
          "sha256": "1d8308b0a8b2ddbde7ab838546fc26b6e35ebaa26d797c8c41aa6e7e34ab0ade",
          "sha1": "20c1b89edcfd997fde87d4bcadca9b3a041fa76e",
          "md5": "1fe11dff90939821d870caaee9845e8d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-test-9.3.0-b2-sources.jar",
          "url": "core-ng-test-9.3.0-b2-sources.jar",
          "size": 24947,
          "sha512": "691881fccf5f5aafea16d2052bf496cb688b903f9e675f0c95bb4a415cb5a78ea53c86d3cffd3d2481e418f7389c721bbeefab463b2fb2aaf46340eb8d65c354",
          "sha256": "ce57fd071e610748bb10fe6eda718579a5edd3d526f38740966eaa0872d2ab6a",
          "sha1": "1556c75e637f9325ab2f887bd7b755b31d280c73",
          "md5": "0cb05eb4574c0674fa34e027ebe527e0"
        }
      ]
    }
  ]
}
