{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search",
    "version": "7.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "gbi5hrwjajbnjmwcbxgbmwel6e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.3.5"
          }
        },
        {
          "group": "org.elasticsearch.client",
          "module": "elasticsearch-rest-high-level-client",
          "version": {
            "requires": "7.5.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.3.5.jar",
          "url": "core-ng-search-7.3.5.jar",
          "size": 36871,
          "sha512": "8383ff4068bde46b236de987cc3c10f0eff2fa40a9a62b0a6898d1d86dbb42aa1a0b9f91a52baa1e5f8e994b702834e4d71a26443ffcfe0ac74a21a54f86f514",
          "sha256": "bbae82bad0864a034e7066cf287862653029a71bb9e7f2a35bacef4f71f27e40",
          "sha1": "9d2c049f2a3e26f03c07f369c27d1f00d890eb85",
          "md5": "c5d59aabc4a03eee607758549e1b1e2e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "7.3.5"
          }
        },
        {
          "group": "org.elasticsearch.client",
          "module": "elasticsearch-rest-high-level-client",
          "version": {
            "requires": "7.5.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-smile",
          "version": {
            "requires": "2.10.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.10.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-cbor",
          "version": {
            "requires": "2.10.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.25"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-7.3.5.jar",
          "url": "core-ng-search-7.3.5.jar",
          "size": 36871,
          "sha512": "8383ff4068bde46b236de987cc3c10f0eff2fa40a9a62b0a6898d1d86dbb42aa1a0b9f91a52baa1e5f8e994b702834e4d71a26443ffcfe0ac74a21a54f86f514",
          "sha256": "bbae82bad0864a034e7066cf287862653029a71bb9e7f2a35bacef4f71f27e40",
          "sha1": "9d2c049f2a3e26f03c07f369c27d1f00d890eb85",
          "md5": "c5d59aabc4a03eee607758549e1b1e2e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-7.3.5-sources.jar",
          "url": "core-ng-search-7.3.5-sources.jar",
          "size": 16232,
          "sha512": "9dbbbd39fd74ba333c4f76f5ca06cc157165322f5b96e66d31a9a0372739366714f93fa5af4b1031af0d1b35537cc61bf25e97b63fe00c3b733186c12d0877e9",
          "sha256": "fd82b5b51bbe254b8396df44d5456bc750678153866694db5b9c8f50078cfc31",
          "sha1": "f4108ce736e4b14b633a9663cc2cc5da2f0a51f1",
          "md5": "fd4d0e8e24d895f702e44558606de922"
        }
      ]
    }
  ]
}
