{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-api",
    "version": "9.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-api-9.0.1.jar",
          "url": "core-ng-api-9.0.1.jar",
          "size": 10983,
          "sha512": "c4449083a21a75225ff66f02727f16ae79d7d77052a5926693b4622fe150fe92d75254f0050c2e1d5b4feecf690b848bd106b7ae5ad13e9f2d76c62eb96a29e5",
          "sha256": "df4609018762a7ec9cfe51696b6cf539368763f22f1a1160dd28cfabcecf336a",
          "sha1": "72e44c57167880dc2b8103310d10fd3d85a00411",
          "md5": "a27a50e9f261ad4b442b27e8615b8a06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.0.1.jar",
          "url": "core-ng-api-9.0.1.jar",
          "size": 10983,
          "sha512": "c4449083a21a75225ff66f02727f16ae79d7d77052a5926693b4622fe150fe92d75254f0050c2e1d5b4feecf690b848bd106b7ae5ad13e9f2d76c62eb96a29e5",
          "sha256": "df4609018762a7ec9cfe51696b6cf539368763f22f1a1160dd28cfabcecf336a",
          "sha1": "72e44c57167880dc2b8103310d10fd3d85a00411",
          "md5": "a27a50e9f261ad4b442b27e8615b8a06"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-api-9.0.1-sources.jar",
          "url": "core-ng-api-9.0.1-sources.jar",
          "size": 8641,
          "sha512": "c1fa779f4a15a746716ff62da184513fee96406c4abf98992ebc5644882fe2c3f179e407d49c5658fedbdae5daff32cbf3463b89275a7af99838112a7e79a53b",
          "sha256": "e7920408b7e2a4550971e3005b857c06ef34ebd2fd056a3a9a6d0ce81c22fa3d",
          "sha1": "50cca4683bc1040850a1020a45cb5dbf8435517f",
          "md5": "9a93a5b7c50359b2866afe2a5281077e"
        }
      ]
    }
  ]
}
