{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-mongo",
    "version": "9.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.4"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.0.4.jar",
          "url": "core-ng-mongo-9.0.4.jar",
          "size": 57155,
          "sha512": "daa6b5c08edadadb61bdba3eccb49933088c47a81602d358be1d9f12146fe311b8ca02330619172351d960f4f7e0d0f44f65acaac707cfb35aaa9bd164ab9429",
          "sha256": "36a1595170bbf8292ed7eb534a87ec1a18a4bd0b03a1ee422246c3299caec6c4",
          "sha1": "fa53c453f5573721bbd8d3a954e654ea4edecc05",
          "md5": "292f6cbeb61eba15125c6c70a7237912"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng",
          "version": {
            "requires": "9.0.4"
          }
        },
        {
          "group": "org.mongodb",
          "module": "mongodb-driver-sync",
          "version": {
            "requires": "4.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-mongo-9.0.4.jar",
          "url": "core-ng-mongo-9.0.4.jar",
          "size": 57155,
          "sha512": "daa6b5c08edadadb61bdba3eccb49933088c47a81602d358be1d9f12146fe311b8ca02330619172351d960f4f7e0d0f44f65acaac707cfb35aaa9bd164ab9429",
          "sha256": "36a1595170bbf8292ed7eb534a87ec1a18a4bd0b03a1ee422246c3299caec6c4",
          "sha1": "fa53c453f5573721bbd8d3a954e654ea4edecc05",
          "md5": "292f6cbeb61eba15125c6c70a7237912"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-mongo-9.0.4-sources.jar",
          "url": "core-ng-mongo-9.0.4-sources.jar",
          "size": 27011,
          "sha512": "8a250af117f110d0fda13ca8c4f999c9f8bd6bd63713326fc5ba78664e8b1058b7210e8bf47f6bd3ce34d963b6aa012f22fef5f37571eed5cf3bd878dc202f68",
          "sha256": "ba76a125ae7f75ce181dffe1411e76946f7550bb11b88a7ec0fd9ae3ee5212e8",
          "sha1": "d64ea50e8e7e19797a5a6042e71080c0c1466b30",
          "md5": "a2aa8dee5f01f88ec6110a63d84901c4"
        }
      ]
    }
  ]
}
