{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework",
    "module": "core-ng-search-test",
    "version": "9.1.1-b0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.1.1-b0.jar",
          "url": "core-ng-search-test-9.1.1-b0.jar",
          "size": 13230,
          "sha512": "c262c06fed63cc88bd0ee65b26e73ad06362f140cf62d66758861912a5761d12727b0b309ffcec3619f75892012cdf2f0ea66e00fc9f9ffb813eb62fcf4096ee",
          "sha256": "bccf6fd13d7f71d731ae03a7c0d174511d1431295602a0a9520e1803fbec5e30",
          "sha1": "523d6b0ca160128c0b5748736d96b8a3b90c8603",
          "md5": "4a9d4795d6f89746d039de67fac75d85"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "core.framework",
          "module": "core-ng-test",
          "version": {
            "requires": "9.1.1-b0"
          }
        },
        {
          "group": "core.framework",
          "module": "core-ng-search",
          "version": {
            "requires": "9.1.1-b0"
          }
        },
        {
          "group": "org.elasticsearch",
          "module": "elasticsearch",
          "version": {
            "requires": "8.14.0"
          }
        },
        {
          "group": "org.elasticsearch.plugin",
          "module": "transport-netty4",
          "version": {
            "requires": "8.14.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "mapper-extras",
          "version": {
            "requires": "8.14.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "lang-painless",
          "version": {
            "requires": "8.14.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "analysis-common",
          "version": {
            "requires": "8.14.0"
          }
        },
        {
          "group": "org.codelibs.elasticsearch.module",
          "module": "reindex",
          "version": {
            "requires": "8.14.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "reindex",
              "type": "jar",
              "extension": "jar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "core-ng-search-test-9.1.1-b0.jar",
          "url": "core-ng-search-test-9.1.1-b0.jar",
          "size": 13230,
          "sha512": "c262c06fed63cc88bd0ee65b26e73ad06362f140cf62d66758861912a5761d12727b0b309ffcec3619f75892012cdf2f0ea66e00fc9f9ffb813eb62fcf4096ee",
          "sha256": "bccf6fd13d7f71d731ae03a7c0d174511d1431295602a0a9520e1803fbec5e30",
          "sha1": "523d6b0ca160128c0b5748736d96b8a3b90c8603",
          "md5": "4a9d4795d6f89746d039de67fac75d85"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ng-search-test-9.1.1-b0-sources.jar",
          "url": "core-ng-search-test-9.1.1-b0-sources.jar",
          "size": 7236,
          "sha512": "1865ad9251f023d1b6b80bfdd1372609cc9dc7427436e9b933c7e713a8277bdbd9042b9fa8b67b46d5e2e65506917af73175695bf6dc064c841286f5833a37dd",
          "sha256": "65edede4d0d2461c6b113b66cdab33642166535274c91888816617f817130524",
          "sha1": "fec99fd352db0e874f1956ec89849410905ad4d7",
          "md5": "3fa4aa4bdf259e4e6cbb9e63f5566f13"
        }
      ]
    }
  ]
}
