{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework.mysql",
    "module": "mysql-connector-j",
    "version": "8.2.0-r3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mysql-connector-j-8.2.0-r3.jar",
          "url": "mysql-connector-j-8.2.0-r3.jar",
          "size": 574291,
          "sha512": "88673dce6b9d3f767cb7e0851e080720525ad266a2001bb30254154af01eee90442d5fd935368e0a2eacccbc860f356d1fc03487ce8b5881ef4a3fa9cad71d89",
          "sha256": "1e2cf38915f98bad11d83e9dd1a67e4de0ae06b1c99a0a16f68a757fdb900a01",
          "sha1": "e25b548498ad0efa2302cc776c2ed462cb606a88",
          "md5": "a8d5cb6edf1d9dce9579df6cd9bcd208"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mysql-connector-j-8.2.0-r3.jar",
          "url": "mysql-connector-j-8.2.0-r3.jar",
          "size": 574291,
          "sha512": "88673dce6b9d3f767cb7e0851e080720525ad266a2001bb30254154af01eee90442d5fd935368e0a2eacccbc860f356d1fc03487ce8b5881ef4a3fa9cad71d89",
          "sha256": "1e2cf38915f98bad11d83e9dd1a67e4de0ae06b1c99a0a16f68a757fdb900a01",
          "sha1": "e25b548498ad0efa2302cc776c2ed462cb606a88",
          "md5": "a8d5cb6edf1d9dce9579df6cd9bcd208"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mysql-connector-j-8.2.0-r3-sources.jar",
          "url": "mysql-connector-j-8.2.0-r3-sources.jar",
          "size": 568387,
          "sha512": "13b19ca6b8de799f2b1c18d6e5a0f914f965880ac75113cf7bd5856048f4c5d842d12315411888b4d4b623ff74ef2972c1d756a1b258a0dbdab2e67a0d4524fd",
          "sha256": "d5fd24932ccd6db8aac2d1cc907524eca71a77f4e61c107a24237a9390cbcb4b",
          "sha1": "ed3b915286c63bd15752453b911c85b413a612a5",
          "md5": "65576e0df954ca47a19aa3f7ae385427"
        }
      ]
    }
  ]
}
