{
  "formatVersion": "1.1",
  "component": {
    "group": "core.framework.mysql",
    "module": "mysql-connector-j",
    "version": "8.3.0-r1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mysql-connector-j-8.3.0-r1.jar",
          "url": "mysql-connector-j-8.3.0-r1.jar",
          "size": 532187,
          "sha512": "aeeeedfe4b37321f070f3920c4419086dd8f884125a18a604d2baccb7b26e1c5579a22d55681ff9c13aebecbbd3bc882c3cba77c65754bcc56e77fc4d553b83e",
          "sha256": "5c68f01ad4840ed1bbcf7096b0c5bc1e774ee374e976b642a0420907c455ffcb",
          "sha1": "879d05fc2bce581fc520316d71268ffb2023dc01",
          "md5": "b66e544212eb1d74530da8282478a316"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mysql-connector-j-8.3.0-r1.jar",
          "url": "mysql-connector-j-8.3.0-r1.jar",
          "size": 532187,
          "sha512": "aeeeedfe4b37321f070f3920c4419086dd8f884125a18a604d2baccb7b26e1c5579a22d55681ff9c13aebecbbd3bc882c3cba77c65754bcc56e77fc4d553b83e",
          "sha256": "5c68f01ad4840ed1bbcf7096b0c5bc1e774ee374e976b642a0420907c455ffcb",
          "sha1": "879d05fc2bce581fc520316d71268ffb2023dc01",
          "md5": "b66e544212eb1d74530da8282478a316"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mysql-connector-j-8.3.0-r1-sources.jar",
          "url": "mysql-connector-j-8.3.0-r1-sources.jar",
          "size": 536978,
          "sha512": "c8e7f6a6596ef0066cbe1bafeddfe832ba859d20e52af74bd5b3a7ef5dc2508eb78bed7d76ace9031951efb5c7c282b486443ee0ea64f972c10fe858b20e5061",
          "sha256": "c7c4a831b5cbb28349e19987d585de8695f27a9535356ddb5cbfa729b56518b0",
          "sha1": "61adb178e94bae19d53044b57c54a4d9f8b057a5",
          "md5": "15c1b27cc4efbb004c2896619ca0ad3a"
        }
      ]
    }
  ]
}
